### ISSUE TITLE
SNMP/ICMP Support?

### ISSUE THREAD

**Issue by haomingz** [influxdata/telegraf#40] opened 2015-07-03 08:14 UTC
Are you planning on supporting remote services, like SNMP or ICMP ?

**Comment by sparrc** [comment] 2015-08-05 22:06
@haomingz at the moment there is not, telegraf is more meant for aggregating local data, but we could consider that for a future enhancement.

Could you provide more details on what you'd be looking for?

**Comment by pasancario** [comment] 2015-08-25 15:58
I've some script working written in Python to retrieve information from network devices (mainly Traffic IN/OUT in interfaces). 

It will be really usefull, if we can use Telegraf also as a daemon to work as a collector from remote devices publishing stats in SNMP. 

Could it be possible create a Plugin, extending some SNMP library, and using Telegraph to multiple thread connection to each devices.?

**Comment by sparrc** [comment] 2015-09-11 00:16
I don't see why not @pasancario, there is also the `exec` plugin, which needs to be documented better but basically allows for any JSON-emitting script to be collected by telegraf

**Comment by paulstuart** [comment] 2015-09-25 02:57
I wrote a standalone snmp stats collector for influxdb 8.x, and am now updating it to work with 9.x (hopefully will be done next week).

https://github.com/paulstuart/influxsnmp

**Comment by JulienChampseix** [comment] 2015-10-29 08:34
@paulstuart working like a charm ! @sparrc Hope to see this into telegraf as a plugin soon and that will be perfect and great improvement for telegraf tool ;)

**Comment by TheFlyingCorpse** [comment] 2016-01-14 17:24
+1 on SNMP, would simplify greatly collecting from network / appliance devices. 

Maybe some way to allow adding in new hosts to query via an API of sorts so it doesnt need to be one gigantic config file? 1000+ network devices with adds/removes every day.

**Comment by paulstuart** [comment] 2016-01-14 21:31
@TheFlyingCorpse -- seems reasonable to me. The issue is how to do so cleanly - the hosts would have varying mibs to monitor, n'est pas? How do you envision this API looking?

p.s. I wrote this code for a project that has been sidelined, so I'm not even using these days myself :-(. I still want to make it useful for others so I'll do whatever I can as time allows.

**Comment by TheFlyingCorpse** [comment] 2016-01-15 18:30
On the API, I'm not really sure. I'm used to Nagios/icinga with reload signal to make it reload its configuration, which is not really an API. It could easily be this in some form as long as it doesn't go and polll everything in the first 2 seconds then waits for say 298 seconds and does it again to everything, spread it out a bit.

What I'm struggling with in regards to SNMP is what is useful to gather and in what way it should be stored to fit with other similar data, what devices supply what information (EMC, pfSense, HP, BlackBox, Cisco++ and misc other appliances that support "SNMP"). There is even some vendors (Citrix that I know of) that have superspecial random OIDs generated on object creation in their appliances that can only be found in their GUI, SNMP walking from root does not show these.

**Comment by sparrc** [comment] 2016-01-15 18:52
If any of you have comments on an SNMP plugin, please make them at https://github.com/influxdata/telegraf/pull/495, we should be able to get that merged soon and I want to make sure that it fits everyone's needs

**Closed** 2016-01-25 19:36 UTC
Labels: help wanted
