### ISSUE TITLE
config-directory not working in Windows 10

### ISSUE THREAD

**Issue by lchan007** [influxdata/telegraf#10356] opened 2021-12-29 18:53 UTC
### Relevent telegraf.conf

`--config-directory` is not working as expected on Microsoft Windows 10 Pro. Multiple `--config` is working

telegraf.exe --config "c:\Program Files\Telegraf\conf\inputs.conf" --config "c:\Program Files\Telegraf\conf\outputs.conf" --once [WORK]
telegraf.exe --config-directory "c:\Program Files\Telegraf\conf" --test [NOT WORK]
telegraf.exe --config-directory "c:/etc/telegraf/conf" --test [NOT WORK]
telegraf.exe --config-directory "c:\etc\telegraf\conf" --test [NOT WORK]

### Logs from Telegraf

telegraf.exe --config-directory "c:\Program Files\Telegraf\conf" --test [NOT WORK]
```
>telegraf.exe --config "c:\Program Files\Telegraf\conf\inputs.conf" --config "c:\Program Files\Telegraf\conf\outputs.conf" --once
2021-12-29T18:46:40Z I! Starting Telegraf 1.21.1
2021-12-29T18:46:40Z I! Loaded inputs: cpu disk diskio kernel mem processes swap system
2021-12-29T18:46:40Z I! Loaded aggregators:
2021-12-29T18:46:40Z I! Loaded processors:
2021-12-29T18:46:40Z I! Loaded outputs: influxdb_v2
2021-12-29T18:46:40Z I! Tags enabled: host=ws3
2021-12-29T18:46:40Z W! [inputs.processes] Current platform is not supported
2021-12-29T18:46:40Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-12-29T18:46:41Z I! [agent] Stopping running outputs

>telegraf.exe --config-directory "c:\Program Files\Telegraf\conf" --test
2021-12-29T18:45:56Z I! Starting Telegraf 1.21.1
2021-12-29T18:45:56Z E! [telegraf] Error running agent: No config file specified, and could not find one in $TELEGRAF_CONFIG_PATH, /.telegraf/telegraf.conf, or C:\Program Files\Telegraf\telegraf.conf
```

### System info

telegraf 1.21.1

### Steps to reproduce

1. mkdir "c:\Program Files\Telegraf\conf"
2. copy "c:\Program Files\Telegraf\telegraf.conf" "c:\Program Files\Telegraf\conf\new.conf" 
3. telegraf.exe --config-directory "c:\Program Files\Telegraf\conf" --test
...

### Expected behavior

Should read the config dir.

### Actual behavior

config not found?

**Comment by powersj** [comment] 2022-01-04 20:34
It appears that this is in part due to https://github.com/influxdata/telegraf/issues/5571 in that the config handling in Telegraf is not exactly fully operational with config vs config-directory.

**Comment by powersj** [comment] 2022-08-16 20:23
Hi,

We are working on revamping the CLI (#11316) and how it handles configs internally. I am going to close this issue as a duplicate of #5571. 

Thanks

**Closed by powersj** 2022-08-16 20:23 UTC
Labels: bug, platform/windows
