### ISSUE TITLE
Issue with v1.19.0 - Telegraf failing to start 

### ISSUE THREAD

**Issue by veenaypatil** [influxdata/telegraf#9467] opened 2021-07-05 07:46 UTC
### Relevant telegraf.conf:

```
[[inputs.statsd]]
  service_address = ":8125"
  protocol = "udp"
  percentiles = [ 90 ]
  delete_gauges = true
  delete_timings = true
  delete_counters = true
  parse_data_dog_tags = true
  max_tcp_connections = 250
  delete_sets = true
  allowed_pending_messages = 10000
  percentile_limit = 1000
  metric_separator = "."
```

### System info:

Telegraf Version : 1.19.0
Operating System: Linux

### Steps to reproduce:

1. Starting Telegraf results in 
```
telegraf.service: Unit entered failed state.
telegraf.service: Failed with result 'exit-code'.
telegraf.service: Service hold-off time over, scheduling restart.
Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
telegraf.service: Start request repeated too quickly.
Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.
```
2. Run `telegraf -test`
```
telegraf --test
2021-07-05T07:13:43Z I! Starting Telegraf 1.19.0
2021-07-05T07:13:43Z I! Using config file: /etc/telegraf/telegraf.conf
2021-07-05T07:13:43Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: error parsing statsd, line 129: (statsd.Statsd.Percentiles) cannot unmarshal TOML integer into float64
```

### Expected behavior:

Expected Telegraf to be in running state as there was no change in the configs

### Actual behavior:

It failed with the errors discussed above

### Additional info:

Workaround we found is to Change the config `percentiles = [ 90 ]` to `percentiles = [ 90.0 ]` and restart Telegraf, it starts successfully

**Comment by srebhan** [comment] 2021-07-05 14:45
Duplicate of #9441.

**Closed** 2021-07-05 14:46 UTC
Labels: area/statsd, bug
