### ISSUE TITLE
Binary download doesnt work and instructions are wrong

### ISSUE THREAD

**Issue by jchauncey** [influxdata/telegraf#587] opened 2016-01-26 17:09 UTC
The instructions for downloading the binary are wrong on this page - `https://influxdata.com/downloads//#telegraf`

```
wget http://get.influxdb.org/telegraf/telegraf-0.10.0_linux_amd64.tar.gz
tar xvfz telegraf_linux_amd64_0.10.0_linux_amd64.tar.gz
```

The file in the tar command doesn't match the one you download.

But besides that the command gives the following error - 

```
bash-4.3# tar xvfz telegraf-0.10.0_linux_amd64.tar.gz
tar: invalid magic
tar: short read
```

**Comment by sparrc** [comment] 2016-01-26 17:13
dupe of https://github.com/influxdata/telegraf/issues/562, this will be fixed in 0.10.1

**Closed by sparrc** 2016-01-26 17:13 UTC
