### ISSUE TITLE
Telegraf logs error about unable to create InfluxDB database

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#2739] opened 2017-04-28 20:52 UTC
### Relevant telegraf.conf:
```
[[outputs.influxdb]]
  urls = ["http://influxdb.example.com:8086"]
  username = "telegraf"
  password = "secret"
  database = "telegraf"
  retention_policy = ""
```

### System info:

Telegraf 1.3.0-rc1 + #2553

### Steps to reproduce:

1. Have an InfluxDB database where telegraf user is not an admin
2. Start telegraf

### Expected behavior:
No errors

### Actual behavior:
```
telegraf[19617]: 2017-04-28T20:43:28Z E! Database creation failed: Response Error: Status Code [403], expected [200], [error authorizing query: telegraf not authorized to execute statement 'CREATE DATABASE telegraf', requires admin privilege]
```

### Additional info:
Telegraf appears to function fine. Data is getting into InfluxDB, it just logs this error on start. Previous versions of telegraf did not do this.

**Comment by danielnelson** [comment] 2017-04-28 20:57
Maybe duplicate of #2496

**Comment by phemmer** [comment] 2017-04-28 20:59
It might be, though the description there indicates that writes don't even work. But it could be misreported.

**Comment by danielnelson** [comment] 2017-04-28 21:04
No it says writes are working:

> I haven't found that further writes are broken if the database already exists despite the CREATE failure, but it does create a log entry each time Telegraf starts.

I think we should just silence this error for 1.3, assuming there is an error on write.

**Comment by phemmer** [comment] 2017-04-28 21:06
That comment wasn't from the author of the issue.

> I think we should just silence this error for 1.3, assuming there is an error on write.

Sounds reasonable.

**Comment by danielnelson** [comment] 2017-04-28 21:07
Ahh, right.

The option suggested over there could be nice as it's own thing, so I'll keep both of these open.

**Closed** 2017-04-28 22:58 UTC
Labels: in progress
