### ISSUE TITLE
Feature Request: Aggregator is dropping metrics which are out of period. Whether drop or not should be configurable

### ISSUE THREAD

**Issue by zhang8473** [influxdata/telegraf#2238] opened 2017-01-07 00:21 UTC
### System info:

Telegraf 1.1.0

## Feature Request

I wrote a telegraf aggregator to clean my Kafka data. However, some of the metrics are dropped mysteriously. After digging into the code, I found out that
https://github.com/influxdata/telegraf/blob/master/internal/models/running_aggregator.go#L152-L157

This part of codes filters them out. However, I need all data, including those out of period. Whether or drop the metrics out of period should be configurable.

### Proposal:
Whether or drop the metrics out of period for aggregators should be configurable.

### Current behavior:
drop.

### Desired behavior:
I can config drop/not drop in telegraf.conf.

### Use case: [Why is this important (helps with prioritizing requests)]
Use telegraf inside data pipeline. (not a sensor)

Some data always come later than the others. Thus the timestamp of that particular kind of data is always before the periodStart. That kind of data is always dropped, which is not supposed to be.

**Comment by sparrc** [comment] 2017-01-09 10:33
dupe of #1992

**Closed by sparrc** 2017-01-09 10:33 UTC

**Comment by xibz** [comment] 2018-04-27 23:02
@sparrc - Taking a look at #1992 and it doesn't seem to relate to this issue. I've taken a look at the `RunningAggregator` and see that you can't configure it to be enabled or disabled. I think that's the issue that @zhang8473 was trying to highlight.

Can we reopen this as this is a different feature request?
