### ISSUE TITLE
pleaase fix problem with gopsutil bug

### ISSUE THREAD

**Issue by yosefy** [influxdata/telegraf#1578] opened 2016-08-03 18:57 UTC
it shows wrong metrics now.
https://github.com/shirou/gopsutil/commit/28640e5d732ed31d65cd10927c2fa7f46feb6019

also there is typo in code:
in 
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/spec_processor.go:

	if err == nil {
		fields[prefix+"read_count"] = io.ReadCount
		fields[prefix+"write_count"] = **io.WriteCount**
		fields[prefix+"read_bytes"] = io.ReadBytes
		fields[prefix+"write_bytes"] = **io.WriteCount**

problem looks like that:
procstat,host=pa-live-publish21,pidfile=/var/run/WowzaStreamingEngineManager.pid,process_name=java cpu_time_guest=0,cpu_time_guest_nice=0,cpu_time_idle=0,cpu_time_iowait=0,cpu_time_irq=0,cpu_time_nice=0,cpu_time_soft_irq=0,cpu_time_steal=0,cpu_time_stolen=0,cpu_time_system=3148.26,cpu_time_user=6144.58,involuntary_context_switches=3i,memory_rss=94728192i,memory_swap=0i,memory_vms=5102858240i,num_fds=57i,num_threads=30i,pid=25450i,read_bytes=0i,read_count=14372i,voluntary_context_switches=6i,write_bytes=**105i**,write_count=**105i** 1470250276000000000

https://github.com/shirou/gopsutil/commit/28640e5d732ed31d65cd10927c2fa7f46feb6019

thanks

**Comment by yosefy** [comment] 2016-08-03 20:04
also it wont output io metrics for process when running as telegraf (not root ) user
thanks

**Comment by sparrc** [comment] 2016-08-05 08:40
dupe of #1584

**Closed by sparrc** 2016-08-05 08:40 UTC
