### ISSUE TITLE
'all' input plugin is loaded by default - crashing telegraf (in gopsutil/cpu.parseStatLine)

### ISSUE THREAD

**Issue by ayashjorden** [influxdata/telegraf#2399] opened 2017-02-13 08:41 UTC
## Bug report
The 'all' input plugin is loaded by default, even when no related metrics are configured to be collected.
Causing `panic`:
```
2017-02-13 08:10:55,105 INFO spawned: 'telegraf' with pid 72
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xf2b720, 0xc4200120b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/shirou/gopsutil/cpu.parseStatLine(0x1076108, 0x0, 0x1, 0xc420242f50, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/cpu/cpu_linux.go:201 +0x895
github.com/shirou/gopsutil/cpu.Times(0x19a2700, 0xc420049ea8, 0x19c6638, 0x18ed640, 0x19c6638, 0xc420207340)
        /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/cpu/cpu_linux.go:53 +0x287
github.com/shirou/gopsutil/cpu.init.1()
        /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/cpu/cpu.go:57 +0x83
github.com/shirou/gopsutil/cpu.init()
        /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/cpu/cpu_linux.go:273 +0x5b
github.com/shirou/gopsutil/process.init()
        /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/process/process_posix.go:123 +0x58
github.com/influxdata/telegraf/plugins/inputs/procstat.init()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/procstat/spec_processor.go:111 +0x4c
github.com/influxdata/telegraf/plugins/inputs/all.init()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/all/all.go:84 +0x140
main.init()
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:345 +0x8a
2017-02-13 08:10:55,152 INFO exited: telegraf (exit status 2; not expected)
```
### Relevant telegraf.conf:
```
# Configuration for telegraf agent
[agent]
  interval = "5m"
  round_interval = true
  metric_buffer_limit = 10000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  hostname = ""

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.nsq]]
  server = "127.0.0.1:PORT_NUM"
  topic = "telegraf"
  data_format = "influx"

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Telegraf plugin for gathering metrics from N Mesos masters
[[inputs.mesos]]
  # Timeout, in ms.
  timeout = 100
  # A list of Mesos masters, default value is localhost:PORT_NUM.
  masters = ["master.mesos:PORT_NUM"]
  # Metrics groups to be collected, by default, all enabled.
  #master_collections = ["resources","master","system","slaves","frameworks","messages","evqueue","registrar"]

[[inputs.elasticsearch]]
  ## specify a list of one or more Elasticsearch servers
  servers = ["http://slave.mesos:PORT_NUM"]
  ## set local to false when you want to read the indices stats from all nodes
  ## within the cluster
  local = false
  ## set cluster_health to true when you want to also obtain cluster level stats
  cluster_health = true
````
### System info:
Telegraf 1.2.1
Go Version 1.7
Docker 1.12
DC/OS 1.8.7
Marathon 1.3.6

### Steps to reproduce:

1. Run a container with Telegraf 1.2.1 *without mounting /proc:/rootfs/proc*, --net=brigde

### Expected behavior:
Telegraf shouldn't panic if it can't collect metrics, maybe log some error.

### Actual behavior:
Telegraf panics in shirou/gopsutil/cpu.parseStatLine

**Comment by sparrc** [comment] 2017-02-13 09:51
this is a dupe of #2356, it will be fixed in 1.3

**Closed by sparrc** 2017-02-13 09:51 UTC
