### ISSUE TITLE
AWS CloudWatch input storing partial rows, missing some fields and tags

### ISSUE THREAD

**Issue by jcmcken** [influxdata/telegraf#4480] opened 2018-07-27 00:08 UTC
### Relevant telegraf.conf:

```toml
[agent]
collection_jitter = "120s"
debug = true
flush_interval = "10s"
flush_jitter = "0s"
hostname = ""
interval = "10s"
logfile = ""
metric_batch_size = 1000
metric_buffer_limit = 10000
omit_hostname = false
precision = ""
quiet = false
round_interval = true

[inputs]

[[inputs.cloudwatch]]
delay = "5m"
interval = "5m"
namespace = "AWS/RDS"
period = "5m"
ratelimit = 100
region = "us-east-1"

[inputs.cloudwatch.tags]
source = "telegraf"

[[outputs.influxdb]]
database = "telegraf"
password = "..."
retention_policy = ""
tagexclude = ["source"]
timeout = "5s"
urls = ["..."]
username = "telegraf"
write_consistency = "any"

[outputs.influxdb.tagpass]
source = ["telegraf"]
```

### System info:

Telegraf v1.7.1
CentOS 7.5

### Steps to reproduce:

1. Create many AWS resources using many services.
2. Ingest metrics for these services.

### Expected behavior:

All stored metric rows should have the full complement of tags and field values.

In the case of rate-limiting behavior, something should be logged.

If rate-limiting or retrieval period is reached, Telegraf should not store partial lines.

### Actual behavior:

Some rows are missing tags and fields. E.g. RDS metrics missing the ``db_instance_identifier``. It's unclear from the logs what the issue could be. It doesn't seem that Telegraf logs many details about what goes wrong when it does, even in ``debug``.

**Comment by jcmcken** [comment] 2018-07-27 00:37
I also opened a support case with AWS to see if this behavior could be caused by CloudWatch. Will post if I find anything definitive

**Comment by danielnelson** [comment] 2018-07-27 00:41
The rate limit should only slow the gathering down, but the data collection shouldn't be cut short.  You would see warnings `took longer to collect than collection interval` if an interval must be skipped.  Even with this warning the input continues to work uninterrupted so it would only result is the next interval being skipped completely.

For debugging can you try setting `delay = "10m"` and see if it makes any difference.

Finally, can you try these [troubleshooting commands](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cloudwatch#troubleshooting), this is a good way to determine if it is an AWS issue.

**Comment by jcmcken** [comment] 2018-07-27 00:50
Running the Telegraf test command, I can definitely verify that there are tags missing. E.g. for RDS, some lines have ``engine_name`` missing, others have ``db_instance_identifier``, others have a combination of tags missing. There doesn't seem to be any rhyme or reason to which rows are missing which tags. Will try with awscli and see what I get

**Comment by jcmcken** [comment] 2018-07-27 14:00
It's not terribly useful running awscli. I get results, but it's not clear to me how these are transformed into the final data structure that Telegraf sees.

I'm just guessing here, but the metrics seem to be gathered in a columnar format, i.e. one slice of each dimension across multiple AWS resources. If the data from each slice needs to be married together into row format, and a particular API call is rate-limited by AWS or cancelled (so that column slice is missing from the final result), then that would explain why values are missing.

**Comment by jcmcken** [comment] 2018-07-27 14:20
FYI, I was getting errors indicating the interval expired, but I increased the interval until the errors went away, and am still seeing the missing values.

**Comment by danielnelson** [comment] 2018-07-27 19:21
Can you attach the output of these two commands, and assuming one of the metrics from the telegraf output is missing a dimension, point out which metric it is:
```
aws cloudwatch list-metrics --namespace AWS/RDS --region us-east-1
telegraf --input-filter cloudwatch --test
```

**Comment by jcmcken** [comment] 2018-07-27 22:16
It's a lot of data, so I'm not sure how to get it to you in a good format and sanitized. Here's a small subset of data:

```console
# telegraf --config /etc/telegraf/telegraf.conf --input-filter cloudwatch --test|grep -i rds|grep -v db_instance_identifier
> cloudwatch_aws_rds,db_cluster_identifier=<sanitizied>,host=<sanitizied>,ipaddress=<sanitizied>,project=<sanitizied>,region=us-east-1,role=influxdb.cloudwatch,source=telegraf,subnet_id=<sanitizied>,unit=count/_second,vpc_id=<sanitizied> deadlocks_average=0,deadlocks_maximum=0,deadlocks_minimum=0,deadlocks_sample_count=10,deadlocks_sum=0 1532727960000000000
> cloudwatch_aws_rds,engine_name=mysql,host=<sanitizied>,ipaddress=<sanitizied>,project=<sanitized>,region=us-east-1,role=influxdb.cloudwatch,source=telegraf,subnet_id=<sanitized>,unit=seconds,vpc_id=vpc-<sanitized> write_latency_average=0.0008835913585904058,write_latency_maximum=0.0067346938775510205,write_latency_minimum=0,write_latency_sample_count=320,write_latency_sum=0.2827492347489299 1532727960000000000
> cloudwatch_aws_rds,database_class=db.r4.large,host=<sanitized>,ipaddress=<sanitized>,project=<sanitized>,region=us-east-1,role=influxdb.cloudwatch,source=telegraf,subnet_id=<sanitized>,unit=count/_second,vpc_id=vpc-<sanitized> delete_throughput_average=0,delete_throughput_maximum=0,delete_throughput_minimum=0,delete_throughput_sample_count=10,delete_throughput_sum=0 1532727960000000000
> cloudwatch_aws_rds,engine_name=mysql,host=<sanitized>,ipaddress=<sanitized>,project=<sanitized>,region=us-east-1,role=influxdb.cloudwatch,source=telegraf,subnet_id=<sanitized>,unit=bytes,vpc_id=vpc-<sanitized> free_storage_space_average=190109425472,free_storage_space_maximum=1053182566400,free_storage_space_minimum=9952968704,free_storage_space_sample_count=320,free_storage_space_sum=60835016151040 1532727960000000000
```

You can see that e.g. the first line and the second have different complements of tags and fields, even though they're coming from the same namespace. I'm not sure if each line of this output is supposed to correspond to a "row" in Influx, but that's what I was assuming.

I also have an Influx query showing missing tags:

```
> select db_instance_identifier, cpu_utilization_average from cloudwatch_aws_rds where engine_name = '' order by time desc limit 5;
name: cloudwatch_aws_rds
time                 db_instance_identifier cpu_utilization_average
----                 ---------------------- -----------------------
2018-07-27T13:40:00Z                        3.9440497050267416
2018-07-27T13:40:00Z                        3.622881355934177
2018-07-27T13:40:00Z <sanitized>          0.1520830439010688
2018-07-27T13:40:00Z <sanitized>             0.9333842734103314
2018-07-27T13:40:00Z <sanitized>          0.15625000000000006
```

You can see that some lines don't have ``engine_name`` set, and others don't have ``db_instance_identifier`` set.

The ``aws`` command returns data like this:

```json
{
    "Metrics": [
        {
            "Namespace": "AWS/RDS",
            "Dimensions": [
                {
                    "Name": "DatabaseClass",
                    "Value": "db.r4.large"
                }
            ],
            "MetricName": "Deadlocks"
        },
        {
            "Namespace": "AWS/RDS",
            "Dimensions": [
                {
                    "Name": "EngineName",
                    "Value": "aurora-mysql"
                }
            ],
            "MetricName": "Deadlocks"
        },
        {
            "Namespace": "AWS/RDS",
            "Dimensions": [
                {
                    "Name": "DBClusterIdentifier",
                    "Value": "<sanitized>"
                }
            ],
            "MetricName": "Deadlocks"
        },
       ...etc...
```

**Comment by danielnelson** [comment] 2018-07-28 00:35
I think it must be caused by only getting one page of Metrics, the docs for the call we use says:

> Up to 500 results are returned for any one call. To retrieve additional results, use the returned token with subsequent calls. 

How many items are in the "Metrics" array?
```
aws cloudwatch list-metrics --namespace AWS/RDS --region us-east-1 | grep '"MetricName"' | wc -l
```

**Comment by danielnelson** [comment] 2018-07-28 00:57
Although it does appear that we are paginating to list all metrics, so maybe that isn't the problem.

Let's focus on just one of the Metric names the `CPUUtilization` metric, can you do:
```
aws cloudwatch list-metrics --namespace AWS/RDS --region us-east-1 --metric-name CPUUtilization
telegraf --input-filter cloudwatch --test | grep cpu_utilization
```

You can attach files in a comment here on github, there are instructions at the bottom of the text box when editing your comment.

**Comment by danielnelson** [comment] 2018-07-30 19:07
Yeah, I believe I was mistaken about it being a pagination issue.  Can you still attach the output of the commands my last comment though?

**Comment by jcmcken** [comment] 2018-07-30 21:16
I can provide the data, but I need to sanitize certain tags, which will take some time if you need the full results

**Comment by jcmcken** [comment] 2018-07-31 13:49
AWSCLI:

[awscli-metrics.log](https://github.com/influxdata/telegraf/files/2245473/awscli-metrics.log)

Telegraf:

[telegraf-metrics.log](https://github.com/influxdata/telegraf/files/2245524/telegraf-metrics.log)

**Comment by jcmcken** [comment] 2018-07-31 14:31
Here's the response from my AWS support ticket:

> Hello,
> 
> Thanks for your patience. I spend some time looking at the Telegraf code and also tried recreating the API calls the tool was using. Addressing your last set for queries first, the limit of 400 transactions per second is for an account on a region basis. A user can initiate 400 CloudWatch GetMetricStatistics calls per second for each of the regions. Having said that, I do no suspect that this is an API throttling case mainly because of the fact that Telegraf is limiting this at 300 TPS. Also if the calls are throttled, requests won’t be serviced and there won’t be truncated responses.
> 
> Now, coming to the observations that you made. First of all, I would like to thank you for all the information that you provided. Debugging third party tools is outside the scope of AWS Support but I’ll share my analysis on a best effort basis.  I see from the Telegraf code that they are mainly using ListMetrics and GetMetricStatistics API calls. For AWS/RDS namespace the supported metrics are documented in the below reference:
> 
> Amazon RDS Metrics
> https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/rds-metricscollected.html#rds-metrics
> 
> I assume that you were fetching the CPUUtilization metrics for your RDS resources. The above Amazon RDS data can be filtered along any of the following dimensions listed below. 
> 1. DBInstanceIdentifier
> 2. DBClusterIdentifier
> 3. DBClusterIdentifier, Role
> 4. DatabaseClass
> 5. EngineName
> 
> You also have the option of providing no dimension filters to show the data across all databases. I'm not an expert on Telegraf but I believe that what you are observing is the result of a similar call. This correlates with the CloudWatch metric data too. Following is the data for a query without using any dimension filters
> 
> CPUUtilization:
> sanitized URL
> 
> Similarly if I add Dimensions - DBInstanceIdentifier=sanitized you will get the following
> 
> CPUUtilization (Dimensions - DBInstanceIdentifier=sanitized)
> sanitized URL
> 
> Hence I believe that what you observed is not a missing data case. There was no dimension filter provided in the query – a valid case. To confirm I tried out the ListMetrics CLI call for one of my RDS resource. Following is the output:
> 
> [ec2-user@ip-172-31-16-62 ~]$ aws cloudwatch list-metrics --namespace AWS/RDS --region eu-west-1  --metric-name CPUUtilization {
>     "Metrics": [
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [
>                 {
>                     "Name": "Role",
>                     "Value": "READER"
>                 },
>                 {
>                     "Name": "DBClusterIdentifier",
>                     "Value": "dbinstance-cluster"
>                 }
>             ],
>             "MetricName": "CPUUtilization"
>         },
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [
>                 {
>                     "Name": "DBInstanceIdentifier",
>                     "Value": "dbinstance-eu-west-1a"
>                 }
>             ],
>             "MetricName": "CPUUtilization"
>         },
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [],
>             "MetricName": "CPUUtilization"
>         },
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [
>                 {
>                     "Name": "DBInstanceIdentifier",
>                     "Value": "dbinstance"
>                 }
>             ],
>             "MetricName": "CPUUtilization"
>         },
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [
>                 {
>                     "Name": "DBClusterIdentifier",
>                     "Value": "dbinstance-cluster"
>                 }
>             ],
>             "MetricName": "CPUUtilization"
>         },
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [
>                 {
>                     "Name": "Role",
>                     "Value": "WRITER"
>                 },
>                 {
>                     "Name": "DBClusterIdentifier",
>                     "Value": "dbinstance-cluster"
>                 }
>             ],
>             "MetricName": "CPUUtilization"
>         },
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [
>                 {
>                     "Name": "DatabaseClass",
>                     "Value": "db.r4.large"
>                 }
>             ],
>             "MetricName": "CPUUtilization"
>         },
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [
>                 {
>                     "Name": "EngineName",
>                     "Value": "aurora"
>                 }
>             ],
>             "MetricName": "CPUUtilization"
>         }
>     ]
> }
> 
> As you can see, one of the dimension objects returned is of the following format:
>         {
>             "Namespace": "AWS/RDS",
>             "Dimensions": [],
>             "MetricName": "CPUUtilization"
>         },
> 
> I assume Telegraf initiates a GetMetricStatistics API call for each of these objects and the values populated in the influxDB. Hence this seems to be an expected result from the API call output perspective. Please do correct me if I made any wrong assumptions here. Let me know your thoughts on this.
> 
> I hope the information above will prove to be useful. However if you have any additional questions please do not hesitate to let me know. As always, I'll be happy to help! 
>

**Comment by danielnelson** [comment] 2018-07-31 23:26
Ideally Telegraf would receive metrics with all dimensions like this:
```
{
  "Metrics" : [
    {
      "Namespace": "AWS/RDS",
      "Dimensions": [
        {
          "Name": "DBInstanceIdentifier",
          "Value": "<sanitized>"
        },
        {
          "Name": "DatabaseClass",
          "Value": "db.r3.4xlarge"
        }
      ],
      "MetricName": "CPUUtilization"
    },
  ]
}
```

Then Telegraf could tag each metric with the full set of dimensions:
```
cloudwatch_aws_rds,database_class=XXX,db_instance_identifier=XXX cpu_utilization=42
```


But in actuality the metrics are separated out:
```
{
  "Metrics" : [
    {
      "Namespace": "AWS/RDS",
      "Dimensions": [
        {
          "Name": "DBInstanceIdentifier",
          "Value": "<sanitized>"
        }
      ],
      "MetricName": "CPUUtilization"
    },
    {
      "Namespace": "AWS/RDS",
      "Dimensions": [
        {
          "Name": "DatabaseClass",
          "Value": "db.r3.4xlarge"
        }
      ],
      "MetricName": "CPUUtilization"
    },
  ]
}
```

Giving us two series:
```
cloudwatch_aws_rds,database_class=XXX cpu_utilization=42
cloudwatch_aws_rds,db_instance_identifier=XXX cpu_utilization=42
```

We can't combine these because we aren't sure they are related.  And in fact the one tagged with `database_class` is probably an aggregate of several servers.

I assume this was done in Cloudwatch to allow lookup on any dimension, since you need to specify all dimensions to do a lookup.

Usually we wouldn't want to store metrics with completely different tagsets under the same measurement because you often want to exclude the unset tag.  You can avoid getting the metric without a tag though by using a where clause to match only tags with a value:
```
select * from cloudwatch_aws_rds where db_instance_identifier =~ /./ group by db_instance_identifier
```

Another way would be to split each dimension out to a different measurement name:
```
rds_database_class=XXX cpu_utilization=42
rds_db_instance_identifier=XXX cpu_utilization=42
```

You would need one plugin per dimension to do this:
```toml
[[inputs.cloudwatch]]
  name_override = "rds_instance"
  delay = "5m"
  interval = "5m"
  namespace = "AWS/RDS"
  period = "5m"
  ratelimit = 100
  region = "us-east-1"

  [inputs.cloudwatch.tags]
    source = "telegraf"

  [[inputs.cloudwatch.metrics]]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "DBInstanceIdentifier"
      value = "*"

[[inputs.cloudwatch]]
  name_override = "rds_database_class"
  delay = "5m"
  interval = "5m"
  namespace = "AWS/RDS"
  period = "5m"
  ratelimit = 100
  region = "us-east-1"

  [inputs.cloudwatch.tags]
    source = "telegraf"

  [[inputs.cloudwatch.metrics]]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "DatabaseClass"
      value = "*"
```

Then you could query using only the measurement name:
```
select * from rds_instance group by db_instance_identifier
```

I don't think there is anything we should change in the way Telegraf is working, so I'm going to close the issue, let me know if you have more questions though.

**Closed by danielnelson** 2018-07-31 23:26 UTC
Labels: area/aws, bug

**Comment by jcmcken** [comment] 2018-08-01 13:27
Thanks for investigating this, it makes sense. It's a little unfortunate, but I can work around it.

Do you think there's room to add any of this detail to the input plugin documentation?
