### ISSUE TITLE
Add ability to specify raw post body in httpjson

### ISSUE THREAD

**Issue by darsh221** [influxdata/telegraf#1180] opened 2016-05-10 19:21 UTC
Hi ,

I'm trying to use the telegraf httpjson plugin POST method to pull some stats from the REST endpoint.

Rest end point take multiple metrics as inputs and retrieves the json with its values.

for ex:  {"metrics":["jvm.cl.loaded", "jvm.memory.pools.Metaspace.committed"]}

Is passing a json object to post method is supported ? I tried below config but its giving  parsing error. 

[inputs.httpjson.parameters]

  metrics = [

    "jvm.cl.loaded", 

    "jvm.memory.pools.Metaspace.committed"

  ]

Darsh

**Comment by sparrc** [comment] 2016-05-10 19:24
just do 

metrics = "["jvm.cl.loaded", "jvm.memory.pools.Metaspace.committed"]"

**Comment by alimousazy** [comment] 2016-05-10 20:11
Hi,

I think what @darsh221 meant, he want to push the JSON in the body as it is (raw) @sparrc ,  without get it formatted  as key value pair 

I just check the code 
`data := url.Values{}
	switch {
	case h.Method == "GET":
		params := requestURL.Query()
		for k, v := range h.Parameters {
			params.Add(k, v)
		}
		requestURL.RawQuery = params.Encode()

	case h.Method == "POST":
		requestURL.RawQuery = ""
		for k, v := range h.Parameters {
			data.Add(k, v)
		}
	}

	// Create + send request
	req, err := http.NewRequest(h.Method, requestURL.String(),
		strings.NewReader(data.Encode()))`

and it seem that is not possible, can we add a feature for raw post body data.

**Comment by sparrc** [comment] 2016-05-10 20:15
sure, I'll change the issue

**Comment by sparrc** [comment] 2016-05-10 20:16
closing because it's a dupe of #768

**Closed by sparrc** 2016-05-10 20:16 UTC
