### ISSUE TITLE
Raspberry Pi  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by superbool** [influxdata/telegraf#1704] opened 2016-09-03 12:06 UTC
Hello ：
 I'm using Raspberry PI 2B+,and the OS is `Raspbian`, the `Telegraf` is `Standalone Binaries (ARM)`
but when I run `telegraf`,I get the error:

```
2016/09/03 19:51:38 Using config file: /etc/telegraf/telegraf.conf
2016/09/03 19:51:38 Starting Telegraf (version 0.13.2)
2016/09/03 19:51:38 Loaded outputs: influxdb
2016/09/03 19:51:38 Loaded inputs: swap system cpu disk diskio kernel mem processes
2016/09/03 19:51:38 Tags enabled: host=raspberrypi
2016/09/03 19:51:38 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"raspberrypi", Flush Interval:10s 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x21f0ac]

goroutine 36 [running]:
panic(0x9cd960, 0x1120a038)
        /usr/local/go/src/runtime/panic.go:481 +0x330
github.com/influxdata/telegraf/plugins/inputs/system.(*systemPS).DiskUsage(0x10b6778, 0x0, 0x0, 0x0, 0x112bbcc0, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/ps.go:87 +0x4a4
github.com/influxdata/telegraf/plugins/inputs/system.(*DiskStats).Gather(0x1126a480, 0x76efb508, 0x11300d80, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/disk.go:44 +0xb8
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0x112c20c0, 0x112e28a0, 0x11300d80)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:174 +0x8c
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:175 +0xb8
```

What can I do ?

**Comment by sparrc** [comment] 2016-09-05 16:51
looks like it's the `disk` plugin that is panicking. It's not possible for me to reproduce this so if anyone can submit a PR it would be hugely appreciated.

**Comment by slezko** [comment] 2016-12-04 19:30
Hello! Same situation on Ubuntu 14.04. Telegraf worked for a few months but yesterday it failed with panic:

```
2016/12/03 10:31:40 Output [influxdb] buffer fullness: 104 / 10000 metrics. Total gathered metrics: 11283511. Total dropped metrics: 0.
2016/12/03 10:31:40 Output [influxdb] wrote batch of 104 metrics in 46.669798ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x63fd09]

goroutine 4516357 [running]:
panic(0x107ebc0, 0xc820010080)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/system.(*systemPS).DiskUsage(0x1c78550, 0x0, 0x0, 0x0, 0xc8201f7760, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/ps.go:87 +0x829
github.com/influxdata/telegraf/plugins/inputs/system.(*DiskStats).Gather(0xc8201f82a0, 0x7fc52a815dc8, 0xc82251f3b0, 0x0, 0x0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/system/disk.go:44 +0xd9
github.com/influxdata/telegraf/agent.gatherWithTimeout.func1(0xc8213beae0, 0xc8201c48a0, 0xc82251f3b0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:174 +0x73
created by github.com/influxdata/telegraf/agent.gatherWithTimeout
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:175 +0xe0
```

**Comment by lfarkas** [comment] 2017-01-29 20:19
does it means currently there is not any working telegraf for raspberry? anyway for me the above problem seems to be a little bit different, but can be the cause of the same problem...:-(
anyway we just start to investigate whether to write our own collector or enhance telegraf for our needs. as this bug is already half year long it seems nobody really cares about telegraf on arm...does it true?

**Comment by sparrc** [comment] 2017-01-30 17:50
Please submit a PR for telegraf if you have the resources, I do not have a raspberry Pi to test and can't fix this myself.

from what I can tell it is only panicking on raspberry, and not on other ARM systems.

**Comment by lfarkas** [comment] 2017-01-30 19:42
the packaging problem is only the minor problem, the real problem is the segfault. anyway I don't know the way the arm tar.gz created so I can't fix it:-(

**Comment by sparrc** [comment] 2017-01-30 19:47
What packaging problem? what does that have to do with this?

**Comment by lfarkas** [comment] 2017-01-30 19:52
see #2337

**Comment by sparrc** [comment] 2017-01-30 20:04
it gets created in scripts/build.py

**Comment by lfarkas** [comment] 2017-01-31 09:36
just change this line:
tar_command = "cd {} && tar -cvzf {}.tar.gz ./*".format(package_build_root, name)
to this:
tar_command = "cd {} && tar -cvzf {}.tar.gz --owner=root ./*".format(package_build_root, name)
regards.

**Comment by lfarkas** [comment] 2017-02-04 11:44
is there any debug version or anything else we can help with this issue?

**Comment by sparrc** [comment] 2017-02-04 13:35
nope, sorry, right now I'm hoping someone will take this on and submit a PR

**Comment by lfarkas** [comment] 2017-02-05 09:24
ok i found another bug since form the arm tar.gz the /etc/telegraf/telegraf.d missing it's also missing on my machine too. and since the service file start the service as 
`/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d`
that cause the crash. anyway i'm still belive then telegraf should have to be more fault tolerant and handle the missing directory. so it's still a bug. or at  least should have to report the cause of the crash!

after that i comment out all inputs section from the config file which also cause another segfault without any usable error message.

these should have to be fixed or at least reported.

**Comment by nwneisen** [comment] 2019-11-15 15:58
Is anyone still having an issue with this?  I'm running telegraf a RPi3 with raspbian lite and I'm not seeing any issues.  I'm using telegraf 1.12.5 using swap, system, cpu, disk, diskio, kernel, mem, and processes input plugins and outputting to influxDB_v2 on my local machine.

**Comment by danielnelson** [comment] 2019-11-15 18:56
I'll bet many of the arm specific bugs in Go have been worked out over the years.  Let's close this one and if anyone still has related problems please open a new issue.

**Closed by danielnelson** 2019-11-15 18:56 UTC
Labels: bug, help wanted, panic
