### ISSUE TITLE
Prometheus metrics titles are capitalized 

### ISSUE THREAD

**Issue by dewnull** [influxdata/telegraf#9568] opened 2021-07-31 20:04 UTC
### Relevant telegraf.conf:

```toml
[[outputs.prometheus_client]]
  collectors_exclude = [
    "gocollector",
    "process"
  ]
  expiration_interval = "60s"
  listen = ":9273"
  metric_version = 2
  path = "/metrics"
  string_as_label = false
```

### System info:

 using helm chart to deploy Telegraf  https://github.com/influxdata/helm-charts/tree/master/charts/telegraf
### Docker
1.19-alpine and 1.19.2-alpine

### Steps to reproduce:

1.  deploy telegraf 

### Expected behavior:

influxdb_query_executor_queries_active
### Actual behavior:
influxdb_query**E**xecutor_queriesActive

### Additional info:
The prometheus_client metrics are have mixed 🐪camel case and 🐍snake case.

**Comment by reimda** [comment] 2022-04-19 20:33
I think this is working as designed. The output plugin uses the prometheus serializer. The serializer docs talk a little about how the names are translated: https://github.com/influxdata/telegraf/tree/master/plugins/serializers/prometheus#metrics

To get rid of you camel case, you may need to look into whatever input produced the metrics in the first place. If there's no option to change the names in the input, you could use the processor change the names to what you want.

Since I think this can be fixed with configuration and doesn't require a code change, I'm going to close the issue

**Closed by reimda** 2022-04-19 20:33 UTC
Labels: bug, area/prometheus
