### ISSUE TITLE
Proper Configuration for inputs.aliyuncms

### ISSUE THREAD

**Issue by vipinvkmenon** [influxdata/telegraf#9135] opened 2021-04-15 13:24 UTC
I am trying the aliyuncms plugin for getting metrics from Ali Cloud.

### Relevant telegraf.conf:
I tried to assess the aliyuncms plugin 
Following configurations used
```
[agent]
  [[inputs.aliyuncms]]
    discovery_regions = ["eu-central-1"]
    alicloud_access_key = "asdadasdadasd"
    alicloud_secret_key = "jabsdjasjdanjkdnjasd"
    [[inputs.aliyuncms.metrics]]
      names = ["InstanceActiveConnection", "InstanceNewConnection"]

  [[outputs.file]]
    files = ["stdout"]
```

### Expected behavior:

Metrics from Ali

### Actual behavior:

Error:

```
/telegraf-1.19.0/usr/bin# ./telegraf --config telegraf.conf
2021-04-15T13:21:31Z I! Starting Telegraf
2021-04-15T13:21:31Z E! [telegraf] Error running agent: Error loading config file telegraf.conf: plugin inputs.aliyuncms: line 2: configuration specified the fields ["alicloud_secret_key" "alicloud_access_key"], but they weren't used
la-la-laa-vm:~/telegraf-1.19.0/usr/bin#
```
### Additional info:
Release: telegraf-nightly (April 15-2021)https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_linux_amd64.tar.gz

What is the right configuration?

**Comment by vipinvkmenon** [comment] 2021-04-15 13:26
@srebhan @helenosheaa . can you guys kindly help :)
Thanks

**Comment by Jagularr** [comment] 2021-04-15 20:54
Some of your config options are not named correctly, see https://github.com/influxdata/telegraf/blob/master/plugins/inputs/aliyuncms/README.md for the names. `access_key_id` and `access_key_secret` likely are the replacements for the names that you're using.

**Comment by vipinvkmenon** [comment] 2021-04-16 03:53
Thanks for the quick response. Closing this :)

**Comment by vipinvkmenon** [comment] 2021-04-18 04:11
furthering to this question I tried the following configurations:

```
[agent]
  [[inputs.aliyuncms]]
   discovery_regions = ["eu-central-1"]
   project = "acs_slb_dashboard"
   access_key_id  = "xxx"
   access_key_secret = "xxx"
   [[inputs.aliyuncms.metrics]]
     names = ["InstanceActiveConnection", "InstanceNewConnection"]

  [[outputs.file]]
    files = ["stdout"]
```
I get the following error:
```
2021-04-16T04:58:14Z I! Starting Telegraf
2021-04-16T04:58:14Z I! Loaded inputs: aliyuncms
2021-04-16T04:58:14Z I! Loaded aggregators:
2021-04-16T04:58:14Z I! Loaded processors:
2021-04-16T04:58:14Z I! Loaded outputs: file socket_writer
2021-04-16T04:58:14Z I! Tags enabled: host=xxx
2021-04-16T04:58:14Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"xxx", Flush Interval:10s
2021-04-16T04:58:15Z I! [inputs.aliyuncms] 62 object(s) discovered...
2021-04-16T04:58:20Z E! [inputs.aliyuncms] Error in plugin: failed to query metricName list: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"Cms","RegionId":"","LocationProduct":"cms","LocationEndpointType":"openAPI"}), please check your accessKey with secret, and read the user guide

caused by:
SDK.ServerError
ErrorCode: InternalError
Recommend: https://error-center.aliyun.com/status/search?Keyword=InternalError&source=PopGw
RequestId: ACA875AB-4571-4B71-1BA0-D512AB21B700
Message: The request processing has failed due to some unknown error, exception or failure.
2021-04-16T04:58:20Z E! [inputs.aliyuncms] Error in plugin: failed to query metricName list: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"Cms","RegionId":"","LocationProduct":"cms","LocationEndpointType":"openAPI"}), please check your accessKey with secret, and read the user guide
```
It says 62 objects discovered but the errors out.
I tried running it on the command line as well:
```
aliyun cms DescribeMetricList --Namespace acs_slb_dashboard --MetricName InstanceActiveConnection
ERROR: net/http: request canceled (Client.Timeout exceeded while reading body)
```
So I thought it was API  issue....

I then tried it for a different namespace. (This time I verified on the command line first):
```
aliyun cms DescribeMetricList --Namespace acs_ecs_dashboard --MetricName cpu_idle

{
        "Code": "200",
        "Datapoints": "[]",
        "Period": "15",
        "RequestId": "A1BB0021-8A7C-45AC-B914-46B320E721F1",
        "Success": true
}
```
However the similar config on telegraf:
```
[agent]
  [[inputs.aliyuncms]]
   discovery_regions = ["eu-central-1"]
   project = "acs_ecs_dashboard"
   access_key_id  = "xxx"
   access_key_secret = "xxx"
   [[inputs.aliyuncms.metrics]]
     names = ["cpu_idle"]

  [[outputs.file]]
    files = ["stdout"]
```
But Gives the same error:
```
2021-04-16T05:03:56Z I! Starting Telegraf
2021-04-16T05:03:56Z I! Loaded inputs: aliyuncms
2021-04-16T05:03:56Z I! Loaded aggregators:
2021-04-16T05:03:56Z I! Loaded processors:
2021-04-16T05:03:56Z I! Loaded outputs: file socket_writer
2021-04-16T05:03:56Z I! Tags enabled: host=xxx
2021-04-16T05:03:56Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"xxx", Flush Interval:10s
2021-04-16T05:04:00Z I! [inputs.aliyuncms] 489 object(s) discovered...
2021-04-16T05:04:10Z E! [inputs.aliyuncms] Error in plugin: failed to query metricName list: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"Cms","RegionId":"","LocationProduct":"cms","LocationEndpointType":"openAPI"}), please check your accessKey with secret, and read the user guide

caused by:
SDK.ServerError
ErrorCode: InternalError
Recommend: https://error-center.aliyun.com/status/search?Keyword=InternalError&source=PopGw
RequestId: 162F23AC-9D8C-3489-B7A8-1D2966D2331A
Message: The request processing has failed due to some unknown error, exception or failure.
```
Similarly, it says 489 objects discovered but the errors out.
What am I missing here?

**Comment by srebhan** [comment] 2021-04-19 11:29
@vipinvkmenon I'm not exactly sure how I can help here... :-P A short google search revealed [this documentation of the error codes](https://partners-intl.aliyun.com/help/doc-detail/66505.htm). It says:

> SDK.CanNotResolveEndpoint | Can not resolve endpoint, please check the user guide | The SDK cannot automatically obtain the endpoint of the called product in the specified region. | Checks whether the provided region ID and endpoint are correct. Run the following codes to set the endpoint:DefaultProfile.addEndpoint("cn-hangzhou", "cn-hangzhou", "Ecs", "ecs.aliyuncs.com");

So it seems like the automatic resolving of the endpoint does not work for you. I have no idea why it worked for the author of the plugin. @i-prudnikov any idea?
An alternative seems to be to add an endpoint explicitly (as shown in the SDK documentation above) or to specify a region-ID... Both is beyond my scope as I have no way to test this...

**Comment by i-prudnikov** [comment] 2021-04-19 16:05
Hello @vipinvkmenon , @srebhan, well I can confirm that I had similar issue. To me it looks like the Alicloud API changes. The root cause is that API is not accepting anymore request across all regions, so we need to specify exactly the region which we are requesting. The fix is clear.

**Comment by srebhan** [comment] 2021-04-20 07:00
@i-prudnikov looking forward to your PR! Please feel free to mention me so I can take a look.

**Comment by i-prudnikov** [comment] 2021-04-20 12:58
@srebhan, could you please have a look on #9156

**Comment by vipinvkmenon** [comment] 2021-04-21 05:40
Hope it gets merged soon :)

**Comment by i-prudnikov** [comment] 2021-04-21 07:09
@vipinvkmenon , meanwhile, you can try it. From the PR page you can find precompiled binaries with the fix.

**Comment by vipinvkmenon** [comment] 2021-04-21 17:09
Built @i-prudnikov 's branch and ran with the following config:

```
[agent]
  [[inputs.aliyuncms]]
   regions = ["eu-central-1"]
   project = "acs_ecs_dashboard"
   access_key_id  = "xxx"
   access_key_secret = "xxx"
   period = "60m"
   [[inputs.aliyuncms.metrics]]
     names = ["cpu_total"]
   allow_dps_without_discovery = false

  [[outputs.file]]
    files = ["stdout"]
```
started telegraf in debug
```
./telegraf --config confx --debug
```
Output:
```
i311636@C02XC0ZPJGH5 telegraf % ./telegraf --config config.toml --debug
2021-04-21T17:02:56Z I! Starting Telegraf
2021-04-21T17:02:56Z I! Loaded inputs: aliyuncms
2021-04-21T17:02:56Z I! Loaded aggregators:
2021-04-21T17:02:56Z I! Loaded processors:
2021-04-21T17:02:56Z I! Loaded outputs: file
2021-04-21T17:02:56Z I! Tags enabled: host=xxx
2021-04-21T17:02:56Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"xxx", Flush Interval:10s
2021-04-21T17:02:56Z D! [agent] Initializing plugins
2021-04-21T17:02:56Z W! [inputs.aliyuncms] 'discovery_regions' is deprecated and ignored in favour of 'regions'.
2021-04-21T17:03:05Z I! [inputs.aliyuncms] 495 object(s) discovered...
2021-04-21T17:03:05Z D! [agent] Connecting outputs
2021-04-21T17:03:05Z D! [agent] Attempting connection to [outputs.file]
2021-04-21T17:03:05Z D! [agent] Successfully connected to outputs.file
2021-04-21T17:03:05Z D! [agent] Starting service inputs
2021-04-21T17:03:12Z D! [inputs.aliyuncms] No metrics returned from CMS, response msg:
2021-04-21T17:03:15Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2021-04-21T17:03:23Z D! [inputs.aliyuncms] No metrics returned from CMS, response msg:
2021-04-21T17:03:25Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
^C^C2021-04-21T17:03:31Z D! [inputs.aliyuncms] No metrics returned from CMS, response msg:
2021-04-21T17:03:31Z D! [agent] Stopping service inputs
2021-04-21T17:03:34Z D! [agent] Input channel closed
2021-04-21T17:03:34Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-04-21T17:03:34Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2021-04-21T17:03:34Z I! [agent] Stopping running outputs
2021-04-21T17:03:34Z D! [agent] Stopped Successfully
```

From this initial run, looks similar to the one from the ali command line.
```
aliyun cms DescribeMetricList --Namespace acs_ecs_dashboard --MetricName cpu_idle

{
        "Code": "200",
        "Datapoints": "[]",
        "Period": "15",
        "RequestId": "A1BB0021-8A7C-45AC-B914-46B320E721F1",
        "Success": true
}
```

I'll probably need to find out a namespace or check if some permissions are missing for these metrics to not come... but seems like the plugin is giving outputs similar to the command-line. Anybody with access to these namespaces with permissions is also welcome :)

**Comment by i-prudnikov** [comment] 2021-04-21 19:13
@vipinvkmenon, what you are showing here is very typical case. Please note that alicloud cms metrics are stored in aggregated form. Different projects (namespaces) has different aggregations. Also metrics come with delay.  In order to be able to query metrics you need to adjust `period`,`delay`,`interval`.
Here the config that works well for  exactly the same namespace, with useful comments, explaining the settings:
```toml
[agent]
  interval = "1m"
  round_interval = false
  quiet = false
  hostname = "xxx"
  omit_hostname = false

[[inputs.aliyuncms]]
 regions = ["cn-hongkong"]
 project = "acs_ecs_dashboard"

 access_key_id = "xxx"
 access_key_secret = "xxx"

  # The minimum period for AliyunCMS metrics is 1 minute (60s). However not all
  # metrics are made available to the 1 minute period. Some are collected at
  # 3 minute, 5 minute, or larger intervals.
  # See: https://help.aliyun.com/document_detail/51936.html?spm=a2c4g.11186623.2.18.2bc1750eeOw1Pv
  # Note that if a period is configured that is smaller than the minimum for a
  # particular metric, that metric will not be returned by the Aliyun OpenAPI
  # and will not be collected by Telegraf.
  #
  period = "1m"

  ## Collection Delay (required - must account for metrics availability via AliyunCMS API)
  delay = "1m"
  
  ## Recommended: use metric 'interval' that is a multiple of 'period' to avoid
  ## gaps or overlap in pulled data
  interval = "1m"

[[inputs.aliyuncms.metrics]]
   names = ["cpu_idle"]

[[outputs.file]]
  files = ["stdout"]
```

**Comment by vipinvkmenon** [comment] 2021-04-22 03:00
Tried another test configuration, however, mentioned that in your [PR](https://github.com/influxdata/telegraf/pull/9156).....Works as expected. :)

**Closed** 2021-04-29 16:06 UTC
Labels: area/aliyuncms, cloud, support
