### ISSUE TITLE
Incorrect package power consumption from intel_powerstat

### ISSUE THREAD

**Issue by PW999** [influxdata/telegraf#14109] opened 2023-10-15 16:45 UTC
### Relevant telegraf.conf

```toml
[[inputs.intel_powerstat]]
  interval = "10s"
  ## The user can choose which package metrics are monitored by the plugin with
  ## the package_metrics setting:
  ## - The default, will collect "current_power_consumption",
  ##   "current_dram_power_consumption" and "thermal_design_power"
  ## - Leaving this setting empty means no package metrics will be collected
  ## - Finally, a user can specify individual metrics to capture from the
  ##   supported options list
  ## Supported options:
  ##   "current_power_consumption", "current_dram_power_consumption",
  ##   "thermal_design_power", "max_turbo_frequency", "uncore_frequency",
  ##   "cpu_base_frequency"
  package_metrics = ["current_power_consumption", "current_dram_power_consumption"]

  ## The user can choose which per-CPU metrics are monitored by the plugin in
  ## cpu_metrics array.
  ## Empty or missing array means no per-CPU specific metrics will be collected
  ## by the plugin.
  ## Supported options:
  ##   "cpu_frequency", "cpu_c0_state_residency", "cpu_c1_state_residency",
  ##   "cpu_c6_state_residency", "cpu_busy_cycles", "cpu_temperature",
  ##   "cpu_busy_frequency"
  ## ATTENTION: cpu_busy_cycles is DEPRECATED - use cpu_c0_state_residency
  cpu_metrics = ["cpu_frequency", "cpu_c0_state_residency", "cpu_c1_state_residency","cpu_c6_state_residency", "cpu_busy_cycles", "cpu_busy_frequency"]
```

### Logs from Telegraf

```text
Oct 15 18:20:02 pve systemd[1]: Started Telegraf.
░░ Subject: A start job for unit telegraf.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit telegraf.service has finished successfully.
░░ 
░░ The job identifier is 3649.
Oct 15 18:20:02 pve telegraf[1560016]: 2023-10-15T16:20:02Z D! [agent] Connecting outputs
Oct 15 18:20:02 pve telegraf[1560016]: 2023-10-15T16:20:02Z D! [agent] Attempting connection to [outputs.influxdb_v2]
Oct 15 18:20:02 pve telegraf[1560016]: 2023-10-15T16:20:02Z D! [agent] Successfully connected to outputs.influxdb_v2
Oct 15 18:20:02 pve telegraf[1560016]: 2023-10-15T16:20:02Z D! [agent] Starting service inputs
Oct 15 18:20:10 pve telegraf[1560016]: 2023-10-15T16:20:10Z D! [inputs.intel_powerstat] RAPL folders weren't found using pattern: /sys/devices/virtual/powercap/intel-rapl/intel-rapl:1/intel-rapl:[0-9]*[0-9]*
Oct 15 18:20:14 pve telegraf[1560016]: 2023-10-15T16:20:14Z D! [outputs.influxdb_v2] Wrote batch of 20 metrics in 42.129233ms
Oct 15 18:20:14 pve telegraf[1560016]: 2023-10-15T16:20:14Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Oct 15 18:20:20 pve telegraf[1560016]: 2023-10-15T16:20:20Z D! [inputs.intel_powerstat] RAPL folders weren't found using pattern: /sys/devices/virtual/powercap/intel-rapl/intel-rapl:1/intel-rapl:[0-9]*[0-9]*
Oct 15 18:20:25 pve telegraf[1560016]: 2023-10-15T16:20:25Z D! [outputs.influxdb_v2] Wrote batch of 52 metrics in 7.184226ms
Oct 15 18:20:25 pve telegraf[1560016]: 2023-10-15T16:20:25Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.28.1 (git: HEAD@3ea9ffbe), Debian GNU/Linux 11 (bullseye), Proxmox

### Steps to reproduce

I loaded the kernel modules as per the documentation
```
modprobe rapl
modprobe msr
modprobe intel_rapl_common
modprobe intel_rapl_msr
```

The `intel-uncore-frequency` doesn't exist on my distro, but I'm not interested in that frequency anyway.

I have the following modules loaded (as per `lsmod | egrep '.*intel.*|msr|rapl'`).
```
intel_rapl_msr         20480  0
intel_rapl_common      32768  1 intel_rapl_msr
msr                    16384  0
rapl                   20480  0
intel_tcc_cooling      16384  0
intel_powerclamp       24576  0
kvm_intel             360448  5
kvm                  1024000  1 kvm_intel
btintel                40960  1 btusb
ghash_clmulni_intel    16384  0
bluetooth             696320  4 btrtl,btintel,btbcm,btusb
snd_hda_intel          53248  0
snd_intel_dspcfg       28672  1 snd_hda_intel
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
aesni_intel           376832  2
snd_hda_codec         159744  4 snd_hda_codec_generic,snd_hda_codec_conexant,snd_hda_codec_hdmi,snd_hda_intel
crypto_simd            16384  1 aesni_intel
snd_hda_core          110592  5 snd_hda_codec_generic,snd_hda_codec_conexant,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
snd_pcm               143360  4 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_core
snd                   106496  8 snd_hda_codec_generic,snd_hda_codec_conexant,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_timer,snd_pcm
intel_cstate           20480  0
```

The CPU power consumption is measured using `powerstat` and compared to the result output to Influx
```
root@pve:/etc/modules-load.d# powerstat -R
Running for 60.0 seconds (60 samples at 1.0 second intervals).
Power measurements will start in 0 seconds time.

  Time    User  Nice   Sys  Idle    IO  Run Ctxt/s  IRQ/s Fork Exec Exit  Watts
18:35:06   5.3   0.0   2.0  92.4   0.3    3   3906   1859    7    7   10   1.58 
18:35:07   5.3   0.0   1.5  92.9   0.3    5   4171   1997    7    7    7   1.23 
18:35:08   7.8   0.0   4.3  87.8   0.0    2   5010   1982   45   44   45   2.39 
18:35:09   6.0   0.0   2.8  90.7   0.5    4   4288   2044   15   14   17   1.84 
18:35:10   6.5   0.0   2.5  91.0   0.0    4   4257   1967   10   10   10   1.21 
18:35:11  12.6   0.0   2.1  84.9   0.5    1   5602   2600    9    7    9   3.03 
18:35:12  13.3   0.0   6.3  80.2   0.3    1   7874   2722   46   26   45   4.90 
^C-------- ----- ----- ----- ----- ----- ---- ------ ------ ---- ---- ---- ------ 
 Average   8.1   0.0   3.1  88.6   0.3  2.9 5015.4 2167.3 19.9 16.4 20.4   2.31 
 GeoMean   7.6   0.0   2.7  88.4   0.0  2.4 4878.0 2145.6 14.5 12.8 15.5   2.05 
  StdDev   3.1   0.0   1.5   4.3   0.2  1.5 1285.3  318.2 16.4 12.9 15.8   1.22 
-------- ----- ----- ----- ----- ----- ---- ------ ------ ---- ---- ---- ------ 
 Minimum   5.3   0.0   1.5  80.2   0.0  1.0 3906.0 1859.0  7.0  7.0  7.0   1.21 
 Maximum  13.3   0.0   6.3  92.9   0.5  5.0 7874.0 2722.0 46.0 44.0 45.0   4.90 
-------- ----- ----- ----- ----- ----- ---- ------ ------ ---- ---- ---- ------ 
Summary:
CPU:   2.31 Watts on average with standard deviation 1.22  
Note: power read from RAPL domains: uncore, package-0, core, dram, psys.
These readings do not cover all the hardware in this device.

```

### Expected behavior

The reported power consumption by the `intel_powerstat` module are kind of close to the ones report by `powerstat`. When both cores are idle I would expect their power consumption to be similar.

### Actual behavior

There's a big difference in power consumption between both (physical) cores and the total power consumption is much higher than reported by `powerstat`:

![image](https://github.com/influxdata/telegraf/assets/8831154/b11c940a-b1e4-4c97-a3be-57f3b586e2af)
In the above screen shot you can also see that the DRAM power consumption is exactly the same as Core 1's power consumption (which is also pretty weird).

As you can see in the below graph, all cores are under low load, so there's no obvious reason why core 1 would report +10Watts compared to Core 0
![image](https://github.com/influxdata/telegraf/assets/8831154/0f080760-85e9-409b-9b72-02b13ff43963)

The discrepancy is also very obvious in my Grafana dashboard
![image](https://github.com/influxdata/telegraf/assets/8831154/74cd1998-06ed-4c87-908f-2b3e2aecf82a)

### Additional info

Running on an Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz.

**Comment by p-zak** [comment] 2023-10-16 12:30
@PW999 Thanks for the issue. 

Can you provide output of following command?
```
find /sys/devices/virtual/powercap/intel-rapl/ -type f -print -exec cat {} \;
```

It will print path to every file inside `intel-rapl` subsystem together with every value. This will help me investigate this problem.

**Comment by p-zak** [comment] 2023-10-16 20:56
@PW999 Thanks, I understand where the problem is. 

Right now we are rebuilding this plugin and in next version this problem should be fixed. I will let you know.

**Closed** 2023-12-07 16:56 UTC
Labels: bug, plugin/input
