### ISSUE TITLE
inputs.mysql : value too large in SHOW STATUS make strconv.ParseUint return a negative int

### ISSUE THREAD

**Issue by Daryes** [influxdata/telegraf#10407] opened 2022-01-09 13:54 UTC
### Relevent telegraf.conf

```toml
# Read metrics from one or many mysql servers
[[inputs.mysql]]
  ## specify servers via a url matching:
  # servers = ["tcp(127.0.0.1:3306)/"]
  servers = ["<**user**>:<**pass**>@tcp(127.0.0.1:3306)/"]

  ## Selects the metric output format.
  metric_version = 2

  ## the limits for metrics form perf_events_statements
  perf_events_statements_digest_text_limit  = 120
  perf_events_statements_limit              = 250
  perf_events_statements_time_limit         = 86400
  #
  ## if the list is empty, then metrics are gathered from all databasee tables
  table_schema_databases                    = []
  #
  ## gather metrics from INFORMATION_SCHEMA.TABLES for databases provided above list
  gather_table_schema                       = false
  #
  ## gather thread state counts from INFORMATION_SCHEMA.PROCESSLIST
  gather_process_list                       = true
  #
  ## gather thread state counts from INFORMATION_SCHEMA.USER_STATISTICS
  gather_user_statistics                    = false
  #
  ## gather auto_increment columns and max values from information schema
  gather_info_schema_auto_inc               = true
  #
  ## gather metrics from INFORMATION_SCHEMA.INNODB_METRICS
  gather_innodb_metrics                     = true
  #
  ## gather metrics from SHOW SLAVE STATUS command output
  gather_slave_status                       = true
  #
  ## gather metrics from SHOW BINARY LOGS command output
  gather_binary_logs                        = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.TABLE_IO_WAITS_SUMMARY_BY_TABLE
  gather_table_io_waits                     = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.TABLE_LOCK_WAITS
  gather_table_lock_waits                   = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.TABLE_IO_WAITS_SUMMARY_BY_INDEX_USAGE
  gather_index_io_waits                     = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.EVENT_WAITS
  gather_event_waits                        = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.FILE_SUMMARY_BY_EVENT_NAME
  gather_file_events_stats                  = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.EVENTS_STATEMENTS_SUMMARY_BY_DIGEST
  gather_perf_events_statements             = false
  #
  ## Some queries we may want to run less often (such as SHOW GLOBAL VARIABLES)
  interval_slow                   = "30m"

  ## Optional TLS Config (will be used if tls=custom parameter specified in server uri)
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false


# fix some mysql metrics data type
[[processors.converter]]
  [processors.converter.fields]
    string = [ "old_alter_table" ]
```

### Logs from Telegraf
```
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-31": strconv.ParseUint: parsing "-31": invalid syntax
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-31": strconv.ParseUint: parsing "-31": invalid syntax
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-27": strconv.ParseUint: parsing "-27": invalid syntax
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-102": strconv.ParseUint: parsing "-102": invalid syntax
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-26": strconv.ParseUint: parsing "-26": invalid syntax
```

### System info

Telegraf 1.21.2 - Ubuntu 18.04 - no Docker - MariaDB 10.4.22

### Steps to reproduce

1. Upgrade from telegraf 1.19.2 to 1.21.2
1. start telegraf 1.21.2 normally with the mysql input
2. check the logs

Btw, telegraf 1.19.2 doesn't raise this error.

### Expected behavior

no error

### Actual behavior

- Generate an error (in the log) due to a value too long in `SHOW STATUS`
- Generate also an error with `telegraf --test`  (rc=1) but the cause is only visible in the logs (could be as expected)

### Additional info

The cause is due to a too long value in MariaDB STATUS, and telegraf expecting an integer (or long) while it's much greater.

```
MariaDB [(none)]> SHOW STATUS like "%buffer_pool_pages_misc%";
+-------------------------------+----------------------+
| Variable_name                 | Value                |
+-------------------------------+----------------------+
| Innodb_buffer_pool_pages_misc | 18446744073709551418 |
+-------------------------------+----------------------+
```

Dunno why it is at this value as it is on an light instance sized for low memory usage , but it seems to be valid, given "innodb_buffer_pool_chunk_size" which has a similar limit.
https://mariadb.com/kb/en/innodb-system-variables/#innodb_buffer_pool_chunk_size

**Comment by powersj** [comment] 2022-01-10 15:13
That value is in fact larger than a signed int64:

```
max signed int64:   9223372036854775807
your value:        18446744073709551418
max unsigned in64: 18446744073709551615
```

Offhand, my hunch is the value is being read into a signed in64, overflowing, and then when telegraf tries to run ParseUint it throws the error because the overflow resulted in a negative number.

This will take a bit more digging to see how the value is handled as it looks like the ParseUint function is called right away. Hmm

**Comment by Daryes** [comment] 2022-01-10 20:59
For the curious, the reason the buffer_pool_pages_misc value is so high is due to the bug [59550](https://bugs.mysql.com/bug.php?id=59550) on MySQL and MariaDB, happening when compressed page is active.  
Given how old it is, it's fine to assume it's now a permanent "feature".

**Comment by powersj** [comment] 2022-01-12 20:27
Are you using compressed tables? 

It looks like this is due to a [MySQL bug](https://bugs.mysql.com/bug.php?id=59550) ([dup here](https://bugs.mysql.com/bug.php?id=72423)). The value is rolling over and becoming negative in MySQL. Then when Telegraf reads the negative value, `ParseUint` is expecting an unsigned int. The value is negative, the function throws the error that you are seeing.

The variables calling `parseUint` are expecting unsigned integers, so I do not want to try to start parsing the negative value. However, if the `parseUint` function errors, we could return 0, but I feel like that would potentially mask other errors.

As a result, I am inclined to close this as a bug in MySQL due to their overflow issue. Thoughts?

**Comment by Daryes** [comment] 2022-01-15 11:39
I've answered this in the post right before yours. Maybe I wasn't enough explicit, but yes, I do use compressed page.  

But I don't agree with handling this as a bug from MySQL and nothing to do with telegraf, while technically it's true : 
* said bug is opened since 2011
* it exists on both MySQL and MariaDB (which I use, version 10.4.22)
* no move has been done since to fix it on both of them

So it can be viewed as a permanent feature, that might be never be changed.

And also, more importantly, as I've pointed, the other statistic `innodb_buffer_pool_chunk_size` had a max value of 18446744073709551615 (>= MariaDB 10.8).
If you do a search on this value on the [MariaDB documentation site](https://mariadb.com/kb/en/innodb-system-variables/) , you'll see there are some other variables allowing a such high number as an allowed maximum value.

So when using the telegraf argument `--test`, any of those variables will raise an error if at an abnormal, but legit value. 
Problem is, this will be blocking when using the test mode to validate new settings in a configuration management job, like an ansible playbook for example.

I can't say much about how to handle this properly. That's true it's not common, and not all installations will exhibit such values.
Having a hardcoded list of those variable names to handle those requiring a uL64, while better, wouldn't be best as it would require updates. 
Maybe as a band-aid, to try a strlen() on it, and change the uInt/uLong/... conversion depending of the length.
Also, I didn't check the code differences, but as said, telegraf v1.19 don't raise an error on this.

Btw, thanks for asking about my opinion on this, much appreciated.

**Comment by powersj** [comment] 2022-01-15 15:33
> And also, more importantly, as I've pointed, the other statistic `innodb_buffer_pool_chunk_size` had a max value of 18446744073709551615 (>= MariaDB 10.8). If you do a search on this value on the [MariaDB documentation site](https://mariadb.com/kb/en/innodb-system-variables/) , you'll see there are some other variables allowing a such high number as a valid maximum value.

The fact that it is a large number is *not* the problem. Telegraf reads the value directly into an unsigned int. That has the max value equal to the max value of the field: or `(2^64)-1`

```
Maria max value: 18446744073709551615
Go max uint64:   18446744073709551615
```

> So when using the telegraf argument `--test`, any of those variables will raise an error if at an abnormal, but legit value. Problem is, this will be blocking when using the test mode to validate new settings in a configuration management job, like an ansible playbook for example.

If by abnormal you mean negative, yes. I would agree a negative value is not a legit value to these settings, as per the documentation you linked the range is between 0 and a large number. Hence those bug reports to MySQL.

> I can't say much about how to handle this properly. That's true it's not common, and not all installations will exhibit such values. Having a hardcoded list of those variable names to handle those requiring a uL64, while better, wouldn't be best as it would require updates. Maybe as a band-aid, to try a strlen() on it, and change the uInt/uLong/... conversion depending of the length. Also, I didn't check the code differences, but as said, telegraf v1.19 don't raise an error on this.

Again, the problem is not that the value is too big. It is an invalid, negative value.

**Comment by Daryes** [comment] 2022-01-15 19:59
Seems there's a misunderstanding here.
Just to be sure we're on the same page : 

* this is the value from my mariadb server  :
```
MariaDB [(none)]> SHOW STATUS like "%buffer_pool_pages_misc%";
+-------------------------------+----------------------+
| Variable_name                 | Value                |
+-------------------------------+----------------------+
| Innodb_buffer_pool_pages_misc | 18446744073709551418 |
+-------------------------------+----------------------+
```
* this is the value returned by telegraf, which raise an error because it is negative.
```
Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-31"
```

The negative value IS generated by telegraf, it does not come from MariaDB.
First question being : why does Telegraf convert the original value after reading it to a negative integer ?

**Comment by Daryes** [comment] 2022-01-16 09:08
Spend a lot of time, between Mariadb, and Telegraf source code. Finally found the real cause.
I was mistaken, the negative value do come from MariaDB, due to what look like an overflow bug.
But there is also a regression in Telegraf 1.21, as Telegraf 1.19 was handling the negative value correctly.

Explanation : 
**first, the telegraf 1.19 output from a test command**
```
$ sudo telegraf --test --config /etc/telegraf/telegraf.d/mysql.conf | grep -i buffer_pool_pages_misc
2022-01-16T00:41:18Z I! Starting Telegraf 1.19.2
> mysql,host=prometheus,server=127.0.0.1:3306 innodb_buffer_pool_pages_flushed=2223910i,innodb_buffer_pool_pages_free=1024i,innodb_buffer_pool_pages_misc=18446744073709552000,innodb_buffer_pool_pages_total=2006i,innodb_buffer_pool_read_ahead=1517i,innodb_buffer_pool_read_ahead_evicted=0i,innodb_buffer_pool_read_ahead_rnd=0i,innodb_buffer_pool_read_requests=188497242i,innodb_buffer_pool_reads=371308i,innodb_buffer_pool_wait_free=17i,innodb_buffer_pool_write_requests=13700731i,innodb_data_fsyncs=1457800i,innodb_data_pending_fsyncs=0i,innodb_data_pending_reads=0i,innodb_data_pending_writes=0i,innodb_data_read=5345069568i,innodb_data_reads=375684i,innodb_data_writes=3561133i,innodb_data_written=75521169408i,innodb_dblwr_pages_written=2222878i 1642293679000000000
> mysql_innodb,host=prometheus,server=127.0.0.1:3306 buffer_pool_bytes_data=15835136i,buffer_pool_bytes_dirty=0i,buffer_pool_pages_data=1114i,buffer_pool_pages_dirty=0i,buffer_pool_pages_misc=-132i,buffer_pool_pages_total=2006i,buffer_pool_read_ahead=1517i,buffer_pool_read_ahead_evicted=0i,buffer_pool_read_requests=188503737i,buffer_pool_reads=371308i,buffer_pool_size=33554432i,buffer_pool_wait_free=17i,buffer_pool_write_requests=13700739i,lock_deadlocks=0i,lock_row_lock_current_waits=0i,lock_row_lock_time=2528i,lock_row_lock_time_avg=66i,lock_row_lock_time_max=1527i,lock_row_lock_waits=38i,lock_timeouts=0i 1642293679000000000
```
Notice in the first bloc, the group data is `mysql`, with `innodb_buffer_pool_pages_misc=18446744073709552000`  handled correctly.
In the second bloc, the group data is `mysql_innodb`, with `buffer_pool_pages_misc=-132i`. 
It is generated due to the `gather_innodb_metrics = true` parameter.
And indeed, there's a negative value in the query `select * from INFORMATION_SCHEMA.INNODB_METRICS where NAME like "%misc%";`

**Then, telegraf 1.21 with the same config file**
```
$ sudo ./telegraf --test --config /etc/telegraf/telegraf.d/mysql.conf | grep -i buffer_pool_pages_misc
2022-01-16T00:48:16Z I! Starting Telegraf 1.21.2
2022-01-16T00:48:16Z I! Loaded inputs: mysql
2022-01-16T00:48:16Z I! Loaded aggregators:
2022-01-16T00:48:16Z I! Loaded processors: converter
2022-01-16T00:48:16Z W! Outputs are not used in testing mode!
2022-01-16T00:48:16Z I! Tags enabled: host=prometheus
> mysql,host=prometheus,server=127.0.0.1:3306 innodb_buffer_pool_pages_flushed=2224558i,innodb_buffer_pool_pages_free=1024i,innodb_buffer_pool_pages_misc=9223372036854775807i,innodb_buffer_pool_pages_total=2006i,innodb_buffer_pool_read_ahead=1517i,innodb_buffer_pool_read_ahead_evicted=0i,innodb_buffer_pool_read_ahead_rnd=0i,innodb_buffer_pool_read_requests=188551942i,innodb_buffer_pool_reads=371385i,innodb_buffer_pool_wait_free=17i,innodb_buffer_pool_write_requests=13701674i,innodb_data_fsyncs=1458246i,innodb_data_pending_fsyncs=0i,innodb_data_pending_reads=0i,innodb_data_pending_writes=0i,innodb_data_read=5346429440i,innodb_data_reads=375767i,innodb_data_writes=3562175i,innodb_data_written=75542650880i,innodb_dblwr_pages_written=2223526i 1642294096000000000
2022-01-16T00:48:16Z E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-83": strconv.ParseUint: parsing "-83": invalid syntax
2022-01-16T00:48:16Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```
First bloc `mysql` is as expected.
The second bloc related to the `mysql_innodb` group data choke on the negative value. 
This value is returned by MariaDB.

Disabling  `gather_innodb_metrics` do the trick, especially as Telegraf documentation has `gather_innodb_metrics` set to `false` as a default value. 
But for anybody using it, as compressed pages can be activated per tables, telegraf 1.19 is the last one handling the MariaDB bug correctly. Which is poised to appear for other statistics allowing a 64b long.
That's still a regression case, but a rare one. So, I dunno.

**Comment by powersj** [comment] 2022-01-18 16:37
> Spend a lot of time, between Mariadb, and Telegraf source code. Finally found the real cause.
> I was mistaken, the negative value do come from MariaDB, due to what look like an overflow bug.

Excellent, happy we are on the same page.

> Notice in the first bloc, the group data is mysql, with innodb_buffer_pool_pages_misc=18446744073709552000 handled correctly.
> In the second bloc, the group data is mysql_innodb, with buffer_pool_pages_misc=-132i.
> It is generated due to the gather_innodb_metrics = true parameter.

You will note that in your first output, the large value is getting stored as a string as the value does not have an `i` after it. The negative value has the `i`. If both values are found, this will actually cause an error trying to write to InfluxDB as the data type is changing.

The change to using an unsigned int was due to https://github.com/influxdata/telegraf/commit/4194e54ceb36ec3d8eeede523f1de68b73521357. This was to fix two issues: 

1) Deal with values that are too large for a signed int
2) Ensure the datatype so it does not change between an int and string

You also discovered ` gather_innodb_metrics` which I think is the right solution here.

I'm going to go ahead and close this, but thanks for diving in.

**Closed by powersj** 2022-01-18 16:37 UTC
Labels: bug, area/mysql
