### ISSUE TITLE
input plugin rabbitmq json: cannot unmarshal

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/telegraf#9475] opened 2021-07-07 15:39 UTC
Hi,

with telegraf v1.19.0, we are getting this error:

2021-07-07T15:19:42Z E! [inputs.rabbitmq] Error in plugin: json: cannot unmarshal object into Go value of type []rabbitmq.FederationLink
2021-07-07T15:19:42Z E! [inputs.rabbitmq] Error in plugin: json: cannot unmarshal number 0.051 into Go struct field Node.io_read_avg_time of type int64

works fine with 1.18.3

**Comment by helenosheaa** [comment] 2021-07-07 15:46
Hi, thanks for opening the issue. I'm closing it as it's a duplicate of [#9383 ](https://github.com/influxdata/telegraf/issues/9383) which has been resolved.

 If you try the latest [nightly build](https://github.com/influxdata/telegraf#nightly-builds) it should be resolved and the fix should be included in the next bugfix release of Telegraf. 

If you encounter problems with it please reopen the issue!

**Closed by helenosheaa** 2021-07-07 15:46 UTC
Labels: area/rabbitmq, bug
