### ISSUE TITLE
% CPU utilization.

### ISSUE THREAD

**Issue by Eulerizeit** [influxdata/telegraf#962] opened 2016-04-04 19:45 UTC
Just curious what CPU utilization I am supposed to expect from the Telegraf process.  I spun up Telegraf and am writing to a file on the same server. Using the Telegraf process plugin I pulled the stats for Telegraf and discovered it was using 30% of one CPU.  This seemed way too high.  I ran pidstat and it confirmed those numbers.  

Is that expected or should I try and find a root cause?

**Comment by sparrc** [comment] 2016-04-04 20:06
that certainly seems too high, could you provide your OS, system information, and config file?

**Comment by Eulerizeit** [comment] 2016-04-04 20:16
sure 
os - cat /etc/*-release
Servers are d2.2xlarge
`# Telegraf Configuration

# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.

# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.

# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.

# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "1s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will cache metric_buffer_limit metrics for each output, and will
  ## flush this buffer on a successful write.
  metric_buffer_limit = 1000
  ## Flush the buffer whenever full, regardless of flush_interval.
  flush_buffer_when_full = true

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. You shouldn't set this below
  ## interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "1s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## Run telegraf in debug mode
  debug = false
  ## Run telegraf in quiet mode
  quiet = true 
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""


#
# OUTPUTS:
#


# Send telegraf metrics to file(s)
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["/tmp/metrics.out"]

  ## Data format to output. This can be "influx" or "graphite"
  ## Each data format has it's own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "graphite"

#[outputs.kafka]
    # URLs of kafka brokers
#    brokers = ["etl1:9092"] # EDIT THIS LINE
    # Kafka topic for producer messages
#    topic = "telegraf"

#
# INPUTS:
#

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## Comment this line if you want the raw CPU time metrics
  fielddrop = ["time_*"]

# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default, telegraf gather stats for all mountpoints.
  ## Setting mountpoints will restrict the stats to the specified mountpoints.
  # mount_points = ["/"]

  ## Ignore some mountpoints by filesystem type. For example (dev)tmpfs (usually
  ## present on /run, /var/run, /dev/shm or /dev).
  ignore_fs = ["tmpfs", "devtmpfs"]

# Read metrics about disk IO by device
[[inputs.diskio]]
  ## By default, telegraf will gather stats for all devices including
  ## disk partitions.
  ## Setting devices will restrict the stats to the specified devices.
  # devices = ["sda", "sdb"]
  ## Uncomment the following line if you do not need disk serial numbers.
  # skip_serial_number = true


# Read metrics about memory usage
[[inputs.mem]]
  # no configuration


# Read metrics about network interface usage
[[inputs.net]]
  ## By default, telegraf gathers stats from any up interface (excluding loopback)
  ## Setting interfaces will tell it to gather these explicit interfaces,
  ## regardless of status.
  ##
  # interfaces = ["eth0"]


# Read TCP metrics such as established, time wait and sockets counts.
[[inputs.netstat]]
  # no configuration

# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration

# Monitor process cpu and memory usage
[[inputs.procstat]]
  ## Must specify one of: pid_file, exe, or pattern
  ## PID file to monitor process
  # pid_file = "/var/run/nginx.pid"
  ## executable name (ie, pgrep <exe>)
  # exe = "nginx"
  ## pattern as argument for pgrep (ie, pgrep -f <pattern>)
  pattern = "telegraf"
  ## user as argument for pgrep (ie, pgrep -u <user>)
  # user = "nginx"

  ## Field name prefix
  prefix = ""



# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration

# Read metrics about system load & uptime
[[inputs.system]]
  # no configuration


#
# SERVICE INPUTS:
#



`

**Comment by Eulerizeit** [comment] 2016-04-04 20:20
OS - CentOS release 6.7 (Final)

Servers are AWS d2.2xlarge

[global_tags]

[agent]
  interval = "1s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  debug = false
  quiet = true 
  hostname = ""

[[outputs.file]]
  files = ["/tmp/metrics.out"]
  data_format = "graphite"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fielddrop = ["time_*"]


[[inputs.disk]]

  ignore_fs = ["tmpfs", "devtmpfs"]


[[inputs.diskio]]

[[inputs.mem]]

[[inputs.net]]

[[inputs.netstat]]

[[inputs.processes]]

[[inputs.procstat]]

  pattern = "telegraf"

  prefix = ""

[[inputs.swap]]

[[inputs.system]]

**Comment by Eulerizeit** [comment] 2016-04-04 20:21
the procpid results are:
`   Time       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
 1459801214     27151    2.20   60.40    0.00   62.60     0   3448.20      0.00  749592  19968   0.03  telegraf

   Time       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
 1459801219     27151    2.00   56.29    0.00   58.28     0   3406.59      0.00  749592  19968   0.03  telegraf

    Time       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
 1459801224     27151    2.40   55.31    0.00   57.72     0   3372.34      0.00  749592  19968   0.03  telegraf

   Time       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
 1459801229     27151    2.00   59.08    0.00   61.08     0   3416.37      0.00  749592  19968   0.03  telegraf

    Time       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
 1459801234     27151    2.20   55.80    0.00   58.00     0   3420.40      0.00  749592  19968   0.03  telegraf

     Time       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
 1459801239     27151    2.40   65.40    0.00   67.80     0   3539.40      0.00  749592  19968   0.03  telegraf`

**Comment by Eulerizeit** [comment] 2016-04-04 20:22
The procpid results are
`     Time       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
 1459801324     27151    1.80   53.40    0.00   55.20     0   3339.60      0.00  749592  19968   0.03  telegraf`

**Comment by sparrc** [comment] 2016-04-04 20:32
In this case I'm not as surprised, running with a 1s flush and collection interval is rather intense. I'm curious how much CPU usage is getting contributed by the procstat plugin in particular, could you run with procstat disabled and see if that changes your usage noticably?

**Comment by Eulerizeit** [comment] 2016-04-04 20:35
What I'm trying to do is compare to some other products fairly. In a couple min I'd be happy to do what ever you like config wise.

**Comment by Eulerizeit** [comment] 2016-04-04 20:52
No real change disabling the procstat plugin.  I lowered the collection rate to once every 5 sec and that lowered CPU to ~10% of one CPU.  I increased the flush rate and nothing seemed to change. 

Thanks for the reply.

**Comment by sparrc** [comment] 2016-04-04 20:53
k, thanks for the info, that still seems high to me so I'll try to see if I can reproduce

**Comment by Eulerizeit** [comment] 2016-04-04 20:57
I'd be happy to help anyway I can.

**Comment by sparrc** [comment] 2016-04-06 23:37
@Eulerizeit I'm closing as a dupe of #743.

I still haven't been able to reproduce though, do you consistently see this behavior during multiple timeframes, and on different machines? And for a sustained period? (please comment on #743 with any further details)

**Closed** 2016-04-06 23:37 UTC
