### ISSUE TITLE
Multithreading stateless processors for better performance

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13698] opened 2023-07-31 11:58 UTC
### Use Case

So I was debugging the ominous
`[inputs.sysstat] Collection took longer than expected; not complete after interval of 10s`
message. Which always coincides with high load, the telegraf running at 100% cpu on one cpu...

So now I managed to reproduce it with a minimal config:
https://gist.github.com/knollet/5d77f0816df8f10bcbb09c1301a97cf3

With this config (no output needed, the starlark does busywaiting, but could probably use a "sleep()" function if there were one), I can reliably get the "...not complete after..." after around 30 seconds.

Then I created a config to measure how long a metric takes to get through the processor-pipeline
https://gist.github.com/knollet/2ac7364c1b1f924e139e06440b89bc61
this one 
- creates a mock-metric every second with a random "wait_time" between 1 and 5 seconds (obviously too many)
- takes the time when the processor-pipeline is entered
- a starlark processor waits for the "wait_time" (simulating slow processing)
- takes the time again after the pipeline

the time the metrics spend in the pipeline goes continuously up. at some point the pipeline can't accumulate any more metrics and the "...took too long..." error will be triggered.

My suggestion is to enable multithreading for simple, stateless processors (such as rename, regex and such) by just spawning multiple of them connecting them to the go-channels. I think `nproc` would be a reasonable count (more wouldn't help anything). I believe 
https://github.com/influxdata/telegraf/blob/master/agent/agent.go#L641
would be the place to implement this.
![grafik](https://github.com/influxdata/telegraf/assets/131003185/90cb01a5-3038-4256-84a9-55217879b642)

### Expected behavior

- Better usage of system resources.
- perhaps a better warning message pointing to a full pipeline.
- pointers on how to resolve the problem

### Actual behavior

- One slow processor on one core creates a bottleneck even if this is unneccessary b/c most processors are stateless and could be run in parallel
- warning message which doesn't point to the real problem
- problem not visible in the monitoring of telegraf's output buffers, b/c it's not the metrics buffer being full. So: problem not visible, solution unclear.

**Comment by knollet** [comment] 2023-07-31 12:02
I can't get telegraf to build myself, yet, and I am a beginner at go, so I can't create a PR right now.

**Comment by knollet** [comment] 2023-07-31 12:08
Sidefact about debugging: Why is `inputs.sysstat` mostly affected? Because it creates a lot of metrics at once which all have to be delivered to the pipeline in under one second. If inputs are already waiting to deliver into the first processor, then this will probably take too long and trigger the warning.
Note: It is NOT the input that is slow. It's the processors.

**Comment by Hipska** [comment] 2023-07-31 12:30
The code you highlighted is already being run parallel. This is because of the `go func` on line 647: https://github.com/influxdata/telegraf/blob/0496741f4ad040f6bab24e75583513f53a51fa25/agent/agent.go#L647

All code inside this function is executed parallel, the problem you are seeing is that it waits until all processors are finished (`wg.Wait()`).

**Comment by knollet** [comment] 2023-07-31 12:34
Parallel to the other processor-units, yes, but every processor unit is only run once and can only process one metric at a time. My suggestion is to run one processor-unit multiple times.

**Comment by Hipska** [comment] 2023-07-31 12:41
Oh I see what you mean now..

Basically you want this section to be executed parallel as well:
https://github.com/influxdata/telegraf/blob/0496741f4ad040f6bab24e75583513f53a51fa25/agent/agent.go#L651-L656

**Comment by knollet** [comment] 2023-07-31 12:42
This is my suggestion
```
// ┌───────┐
// │ Input │───┐
// └───────┘   │                      v----------- parallel -------v
// ┌───────┐   │      ______     ┌───────────┐      ______     ┌───────────┐     ______
// │ Input │───┼──▶ ()_____) ─▶ │ Processor │──▶ ()_____) ─▶ │ Processor │──▶ ()_____) ...
// └───────┘   │                 └───────────┘                 └───────────┘
// ┌───────┐   │
// │ Input │───┘
// └───────┘

```

**Comment by knollet** [comment] 2023-07-31 12:43
This is my suggestion:
![grafik](https://github.com/influxdata/telegraf/assets/131003185/8e5dcdc7-7528-427a-b84e-5435a86e527e)

**Comment by knollet** [comment] 2023-07-31 12:53
https://github.com/influxdata/telegraf/issues/11707
This one seems to be similar.
Execd wouldn't be my first choice for parallelizing, but that's what they wanted. As the subprocess with execd is started in the `.Start()`-method, it wouldn't work this way.

**Comment by Hipska** [comment] 2023-07-31 13:05
This is already the case for some individual plugins like for example ifname: https://github.com/influxdata/telegraf/blob/0496741f4ad040f6bab24e75583513f53a51fa25/plugins/processors/ifname/ifname.go#L170-L173

So it is something to be implemented on a per-plugin basis..

**Comment by knollet** [comment] 2023-07-31 13:14
We have a processor-pipeline with `json_v2` on input and only `converter`, `regex` and `rename` as processors and it clogs the telegraf. At the same time, cpu-load doesn't go above 100%, so it's a single-thread bottleneck.

**Comment by knollet** [comment] 2023-07-31 14:29
That would be an alternative, of course. I think it'd be more complicated, but would probably still solve our problem, too

**Comment by Hipska** [comment] 2023-07-31 14:41
Do you agree to close this request in favour of the other? Please add your use case and reproducible config as a comment in that one.

**Comment by knollet** [comment] 2023-07-31 15:30
Yes, that's ok.

**Closed** 2023-07-31 15:50 UTC
Labels: feature request
