### ISSUE TITLE
Running with --test does not generate output in specified data format

### ISSUE THREAD

**Issue by ryanmorris708** [influxdata/telegraf#9005] opened 2021-03-17 20:21 UTC
### Intro

Hello,

I am attempting to use the HTTP output plugin from Telegraf v1.17.3 but found that it will not use the specified data format and will instead use influx. For my use case, the output data format must be JSON.

I found [this closed issue](https://github.com/influxdata/telegraf/issues/4224) which appears to be similar, but I am using a much later version of Telegraf.

### Relevant telegraf.conf:
```
# A plugin that can transmit metrics over HTTP
[[outputs.http]]
  ## URL is the address to send metrics to
  url = "http://127.0.0.1:5000/haproxy"

  ## Timeout for HTTP message
  timeout = "10s"

  ## HTTP method, one of: "POST" or "PUT"
  method = "POST"

  ## Data format to output.
  ## Each data format has it's own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "json"

  ## Additional HTTP headers
  [outputs.http.headers]
    # Should be set manually to "application/json" for json data_format
    Content-Type = "application/json; charset=utf-8"
```

### System info:

Telegraf v1.17.3

Operating System: Oracle Linux Server 8.3
CPE OS Name: cpe:/o:oracle:linux:8:3:server
Kernel: Linux 4.18.0-147.el8.x86_64
Architecture: x86-64

### Steps to reproduce:

1. Install Telegraf as a non-root user from this tarball: https://dl.influxdata.com/telegraf/releases/telegraf-1.17.3_linux_amd64.tar.gz
2. Generate a config file with any input and the HTTP output: usr/bin/telegraf --input-filter [plugin] --output-filter http config > telegraf.conf
3. Set the output data_format to "json" (or anything other than "influx")
4. Run Telegraf: usr/bin/telegraf --config telegraf.conf [--test]

### Expected behavior:

Telegraf should output data in the "json" format (or any other format specified).

### Actual behavior:

Telegraf outputs data only in the "influx" format. This is observed on the command line when using --test, and at the HTTP endpoint when not using --test.

### Additional info:

I have previously used the Kafka output plugin and encountered no issues there with choosing a non-influx data_format.

I tried moving the data_format selection to the top of the outputs.http section, but the output was still in influx format after this change.

**Comment by sspaink** [comment] 2021-03-18 16:06
Thank you for making this issue! It looks like this is a problem with the HTTP output plugin, looking at the code it is only setting the default (which is `"text/plain; charset=utf-8"`) and not checking if the config has been set. I will look into resolving this.

**Comment by ryanmorris708** [comment] 2021-03-18 16:40
Thank you @sspaink, I appreciate it!

**Comment by sspaink** [comment] 2021-03-18 17:21
@ryanmorris708 looks like I spoke too soon, walking through the code again it looks like everything is being set correctly (data_format and Content-Type). I will try to reproduce this issue locally, in the meantime I recommend perhaps trying the latest version of Telegraf? v1.18.0 was just released.

**Comment by ryanmorris708** [comment] 2021-03-18 17:31
Sure, I will try the new version. The Content-Type is being checked at the endpoint and that is being set correctly by Telegraf. It is just the data_format config that seems to be the problem.

**Comment by ryanmorris708** [comment] 2021-03-18 20:13
Hi @sspaink, I am seeing the same issue with v1.18.0 where the Content-Type is correctly set, but the data sent out by Telegraf is always in the influx format. Interestingly, Telegraf throws an error when I give it an unrecognized data format:

```
2021-03-18T20:06:33Z I! Starting Telegraf 1.18.0
2021-03-18T20:06:33Z E! [telegraf] Error running agent: Error loading config file telegraf.conf: error parsing http array, Invalid data format: askdflksdl
```

The parsing and validation of the output data_format is happening, but it's not being applied.

**Comment by ryanmorris708** [comment] 2021-03-19 21:39
I had a hunch that seems to be true: running Telegraf with the --test flag will always show influx-formatted data in the stdout response. This had me stuck for a bit since it doesn't reflect the format of the data that would be sent to the HTTP endpoint during an actual run. Checking at the endpoint for an actual run, I can see that some change I made corrected the data format.

In summary: there does not seem to be an issue with the HTTP output plugin and I think my early problem was likely due to user error. However, there seems to be a different bug preventing the test runs from showing output data in the specified format.

**Comment by Jagularr** [comment] 2021-04-02 19:02
Hi, from what I can tell, `--test` mode was meant moreso to check the values of the metrics being gathered rather than their potential output format, as `--test` mode doesn't actually run or know about any of the output plugins, which might explain what led to your question with the http config settings.

**Comment by sjwang90** [comment] 2021-04-12 17:52
Please see @Jagularr's comment.

**Closed by sjwang90** 2021-04-12 17:52 UTC
Labels: bug
