### ISSUE TITLE
Tune different timeouts for outputs.http

### ISSUE THREAD

**Issue by jryberg** [influxdata/telegraf#12997] opened 2023-03-31 09:16 UTC
### Use Case

I have issues with default timeout values in output.http resulting in aborted transmissions of data like this:
`2023-03-31T09:00:09Z E! [agent] Error writing to outputs.http: Post "https://<redacted>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

This is due to high latency via satellite link

It would be nice to be able to tune different timeout defaults. ResponseHeaderTimeout for example is set to 3 seconds and that is little to low. I would like to be able to tune that to 10 for example. 

Please see code snippet bellow
 
```
	HTTPClient := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
			Dial: (&net.Dialer{
				Timeout:   time.Duration(dialTimeout) * time.Second,
				KeepAlive: time.Duration(dialKeepAlive) * time.Second,
			}).Dial,
			ForceAttemptHTTP2:     true,
			MaxIdleConns:          maxIdleConns,
			IdleConnTimeout:       time.Duration(idleConnTimeout) * time.Second,
			TLSHandshakeTimeout:   time.Duration(TLSHandshakeTimeout) * time.Second,
			ExpectContinueTimeout: time.Duration(expectContinueTimeout) * time.Second,
			ResponseHeaderTimeout: time.Duration(responseHeaderTimeout) * time.Second,
		},
		Timeout: time.Duration(httpTimeout) * time.Second,
	}
```

### Expected behavior

```
[[outputs.http]]
  dial_timeout = 30
  dial_keep_alive = 30
  max_idle_conns = 100
  idle_conn_timeout = 90
  tls_handshake_timeout = 10
  expect_contineue_timeout = 1
  response_header_timeout = 3
  http_timeout = 30
```

### Actual behavior

A lot of failed transmissions of metrics

**Comment by jryberg** [comment] 2023-03-31 10:58
I did an attempt to send a PR but I don't have a proper dev environment for this. 

Default value needs to be 3 for ResponseHeaderTimeout but I did not find where defaults should be defined.

**Comment by powersj** [comment] 2023-03-31 12:57
Hi,

> context deadline exceeded (Client.Timeout exceeded while awaiting headers)

This error can mean a lot of things, see [HashiCorp's article on it](https://support.hashicorp.com/hc/en-us/articles/4404634420755-Why-am-I-seeing-context-deadline-exceeded-errors). As you mentioned you are using a high latency connection, which may need more time.

We already provide access to the `http.Client.Timeout` timeout via the `timeout` config option, which covers the entire HTTP request, from dial, handshake, request, headers, and response. Increasing this should be the  same as tuning all those smaller timeouts.

When telegraf encounters these types of timeouts, it should save the metrics to the buffer to ensure metrics are not dropped. Then on the next flush interval re-try sending those metrics. Only if the buffer is full or telegraf stopped would a user lose metrics.

Have you used that timeout value and seen better reliability?

**Comment by jryberg** [comment] 2023-03-31 13:22
> Hi,
> 
> > context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 
> This error can mean a lot of things, see [HashiCorp's article on it](https://support.hashicorp.com/hc/en-us/articles/4404634420755-Why-am-I-seeing-context-deadline-exceeded-errors). As you mentioned you are using a high latency connection, which may need more time.
> 
> We already provide access to the `http.Client.Timeout` timeout via the `timeout` config option, which covers the entire HTTP request, from dial, handshake, request, headers, and response. Increasing this should be the same as tuning all those smaller timeouts.
> 
> When telegraf encounters these types of timeouts, it should save the metrics to the buffer to ensure metrics are not dropped. Then on the next flush interval re-try sending those metrics. Only if the buffer is full or telegraf stopped would a user lose metrics.
> 
> Have you used that timeout value and seen better reliability?

Hi,

I disagree that tuning http.Client.Timeout will affect ResponseHeaderTimeout in the transport because we already tried that path for our own components that was affected by high latency. 

Only when we started to raise ResponseHeaderTimeout our issues was resolved. 

The only component we have issues with now in this specific location is our metrics and I checked the code and discovered this difference.

**Comment by powersj** [comment] 2023-03-31 13:53
> I will however conduct some more testing.

Please do, because I am not inclined to start providing users with a method that is not proven to help and instead cause more confusion as to why there are multiple timeouts.

> The only component we have issues with now in this specific location is our metrics and I checked the code and discovered this difference.
> May you please tell me where default values should be stored like my own addition to the timeout in the transport?

Not sure I am following the above statements: You said you check "the code" is that telegraf(?) and found a difference, but you are asking where in telegraf to set a value?

Defaults are literally set where you were editing the code, you use the users value, and then check if it is set to 0, which is the default value for a config.Duration that is nil. If it is 0, then set a default value.
https://github.com/influxdata/telegraf/blob/master/plugins/common/http/config.go#L51-L54

**Comment by jryberg** [comment] 2023-03-31 16:00
I just started some tests and I will have some results in 24 hours

**Comment by jryberg** [comment] 2023-04-01 17:12
@powersj The timeout is an umbrella that limits the entire transaction in total but if each step has a smaller timeout they will still be the most significant timeout

Please see provided image when one device or ours started to have issues with high latency, probably because of bad weather and the satellite communication was hit with longer latency  
![Skärmbild 2023-04-01 185507](https://user-images.githubusercontent.com/837415/229304950-4730318f-3b47-441b-b058-9ca7281e210c.png)

My patch was applied to the Telegraf container at 16:34  with no single issues after that timestamp. I checked metrics just before posting and there are still no single timeout (17:04)

This is the config I'm using, the diff before and after 16:34 is also that I added response_header_timeout to the config

Note that response_header_timeout default values in your setup are using default value of 3 seconds and I'm now changed it to 20s

```
[[outputs.http]]
  ## URL is the address to send metrics to
  url = "{{ env['TELEGRAF_REMOTE_WRITE_URL'] }}"
  insecure_skip_verify = false
  timeout = "40s"
  response_header_timeout = "20s"
  ## Data format to output.
  data_format = "prometheusremotewrite"
  use_system_proxy = true
```

**Comment by jryberg** [comment] 2023-04-01 17:44
@powersj The timeout is an umbrella that limits the entire transaction in total but if each step has a smaller timeout they will still be the most significant timeout

Please see provided image when one device or ours started to have issues with high latency, probably because of bad weather and the satellite communication was hit with longer latency  
![Skärmbild 2023-04-01 185507](https://user-images.githubusercontent.com/837415/229306398-8ebde815-7a45-4a32-bb80-78d6f94c8814.png)

My patch was applied to the Telegraf container at 16:34  with no single issues after that timestamp. I checked metrics just before posting and there are still no single timeout (17:04)

This is the config I'm using, the diff before and after 16:34 is also that I added response_header_timeout to the config

Note that response_header_timeout default values in your setup are using default value of 3 seconds and I'm now changed it to 20s

```
[[outputs.http]]
  ## URL is the address to send metrics to
  url = "{{ env['TELEGRAF_REMOTE_WRITE_URL'] }}"
  insecure_skip_verify = false
  timeout = "40s"
  response_header_timeout = "20s"
  ## Data format to output.
  data_format = "prometheusremotewrite"
  use_system_proxy = true
```

**Comment by powersj** [comment] 2023-04-03 13:58
> Note that response_header_timeout default values in your setup are using default value of 3 seconds and I'm now changed it to 20s

We are not setting the response header timeout in the current code base. While I agree that the timeout is an umbrella, given we are not setting the response header timeout it is not clear why you would be hitting it unless the timeout is not large enough either.

These are my open questions:

1) I'd like to scenario about when you hit this to ensure that you are not seeing temporary success because you restarted your connection with a new telegraf
2) We should continue to not set the response header timeout as doing so may start introducing regressions that were previously not seen
3) If you set your timeout to even larger values, like 60s or 120s, does this continue to reproduce as well.

> My patch was applied to the Telegraf container at 16:34 with no single issues after that timestamp. I checked metrics just before posting and there are still no single timeout (17:04)

You have given me a 1 hour snapshot. How long did it take to get into this state? Is it always immediate or random due to conditions?

Have you run with this PR for many hours and seen the same?

**Comment by jryberg** [comment] 2023-04-03 14:22
I think you are right. The biggest improvement was in fact when we tuned the umbrella timeout = "40s"

Now when I have metrics from multiple days it's clear that my patch did nothing

I did however learn something about Telegraf internals :)  Sorry about this noise

**Comment by powersj** [comment] 2023-04-03 15:02
> I did however learn something about Telegraf internals :) Sorry about this noise

nice and no worries - you had me questioning my own understanding too :)

Can you give a longer timeout a try and confirm that it does resolve the issue?

**Comment by jryberg** [comment] 2023-04-04 15:04
Yes, the increase overall timeout did resolve the issue.

I had issues to understand how unset timeout could trigger "Client.Timeout exceeded while awaiting headers" and not the overall timeout in the error message. 

It suppose it's on that "step" in the code when the overall timeout hits the request?
![Timeouts-001](https://user-images.githubusercontent.com/837415/229835054-0e64344a-282a-47d2-a20d-d0ed572de7ae.png)

**Comment by powersj** [comment] 2023-04-05 12:42
> Yes, the increase overall timeout did resolve the issue.

Thanks for confirming again

> It suppose it's on that "step" in the code when the overall timeout hits the request?

Agreed, you can look at the [http code](https://cs.opensource.google/go/go/+/master:src/net/http/client.go;l=718-730) to see that that error is triggered during the primary request. Meaning if the timeout is triggered during that entire process, tls handshake, waiting for headers, etc. it will print that error.

That is also why I started with that comment that the waiting on headers message can mean a lot of different things. It is a very poorly worded error that leads to a lot of confusion.

Thanks again! I am going to close this now.

**Closed by powersj** 2023-04-05 12:42 UTC
Labels: feature request
