### ISSUE TITLE
jti_openconfig_telemetry reconnection logic possibly broken.

### ISSUE THREAD

**Issue by ttosbt** [influxdata/telegraf#6693] opened 2019-11-20 22:05 UTC
### Relevant telegraf.conf:

Default telegraf.conf.

### System info:

Telegraf: 1.12.2 (8b4c9a0e)
OS: CentOS 7.6.1810 (Core)
Kernel: 3.10.0-957
JunOS: 19.3R1.8 (QFX)

### Steps to reproduce:

Upon start of the telegraf service a connection is made to the gRPC endpoint served up by the service on the Juniper switch.  If at any point the service on the switches end dies/restarts, the input processor on telegraf quickly fills its logs with 'Failed to read from rpc error: code = Unauthenticated...' errors.

### Expected behavior:

Connections to be reinitialized according to the retry back-off limit.

### Actual behavior:

Reconnection does not happen and it doesn't honor the retry back-off limit.

### Additional info:

I am by no means even a beginner in the Go language so I'd have just fixed it and put in a PR if I could.

However, the issue seems to be present in https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry.go on lines 291-345.  Within the second unbounded for loop on line 313 when service disconnection happens on the server end that loop should break out, (which presumably it does) and the first unbounded loop on line 291 will start over and try a TelemetrySubscribe...which seemingly returns no error because again the second unbounded loop tries a Recv gets and error and reports the error on line 318 gets sent and the process starts all over again.

My guess is that the TelemetrySubscribe function still thinks it's got a subscription and just returns happily without actually checking the status of the connection thus skipping the execution path for subscription errors.

Thanks for any help!!!  :^)

**Comment by giuseur** [comment] 2020-04-02 14:18
Hi, we are experiencing this problem during a switch over between the routing engines of a Juniper device (MX960, Junos 17.4) using both certificate and authentication; we tried to recompile telegraf by modifying the plugin code (a great way to learn the basics of Golang!) and after some attempts we managed to solve this problem, at least in a prototypical way.

In short, what we do (for each server, when gotten "Unauthenticated" error on the stream) is stop all the server related subscription goroutines (using a channel), then closing that server connection, and after some configurable time (10 seconds works well) recreating the connection, the subscription goroutines ecc.

This works well if we declare in the configuration server section the hostname of a single routing engine (device declared in the /etc/hosts with the same ip address but with two entries for the different hostnames), and using a certificate created with a wildcard on the domain (and as an added benefit that a group of servers in the same domain may be served by a single plugin instance).

Sure, because of our basic knowledge about the underlying layers of the plugin and Golang, a best approach will exist, however we want to share with the telegraf team the modifyed plugin code, if this may be of help.

Best greetings.

Giuseppe

**Comment by powersj** [comment] 2022-08-11 22:10
Hi, sorry no one has ever gotten back to you about this issue.

Are you still able to reproduce this with the latest telegraf version? If so, it might be something we want to revisit, but I also wondering if there have been improvements since you filed this issue.

Thanks!

**Closed** 2022-08-26 18:10 UTC
Labels: bug, waiting for response, area/juniper
