### ISSUE TITLE
Feature request - gathering metrics on demand.

### ISSUE THREAD

**Issue by woockashek** [influxdata/telegraf#3887] opened 2018-03-14 12:05 UTC
## Feature Request
I would like to have an option to trigger gathering metrics once on demand.

### Proposal:
The easiest solution I see is to add a new option e.g. `--once` which will work as a combination of standard and `--test` mode. It will trigger gathering each metric once and send them to given outputs.

This could be either implemented as a rest endpoint or signal handling. (With the option to start telegraf paused, waiting for the requests). Still I believe that first option would be more convenient.

### Current behavior:
`--test` option only prints out metrics

### Desired behavior:
`telegraf --config config.xml --once`
Gathers all metrics defined in `config.xml` once and sends them to defined outputs.

### Use case:
There are situations where gathering some metrics can interfere with the other tools running on the machine. We need do gather some data on demand, only before and after some events.

**Comment by danielnelson** [comment] 2018-03-14 18:25
I believe this is a duplicate of #2546

**Closed by danielnelson** 2018-03-14 18:25 UTC
