### ISSUE TITLE
Jolokia input should normalize key name

### ISSUE THREAD

**Issue by maxenced** [influxdata/telegraf#1934] opened 2016-10-24 14:29 UTC
## Bug report

Jolokia input supports fetching of various metrics without any cleaning.  As a consequence, some values returned by Jolokia can contains spaces, which aren't replaced, which make data unavailable in influxdb, for ex with MemoryPool Mbean : 

``` json
# curl  -sd "{\"type\":\"read\",\"mbean\":\"java.lang:type=MemoryPool,name=*\",\"attribute\":\"Usage\"}" http://localhost:8161/api/jolokia/ | python -m json.tool
{
    "request": {
        "attribute": "Usage",
        "mbean": "java.lang:name=*,type=MemoryPool",
        "type": "read"
    },
    "status": 200,
    "timestamp": 1477317211,
    "value": {
        "java.lang:name=Code Cache,type=MemoryPool": {
            "Usage": {
                "committed": 33030144,
                "init": 2555904,
                "max": 251658240,
                "used": 32632128
            }
        },
        "java.lang:name=Compressed Class Space,type=MemoryPool": {
            "Usage": {
                "committed": 4980736,
                "init": 0,
                "max": 1073741824,
                "used": 4785824
            }
        },
```

names contains spaces, which makes them unavailable to query in influxdb.
### Relevant telegraf.conf:

```
[[inputs.jolokia]]
  context = "/api/jolokia/"
  ## List of servers exposing jolokia read service
  [[inputs.jolokia.servers]]
    name = "activemq"
    host = "localhost"
    port = "8161"

  ## Memory
  [[inputs.jolokia.metrics]]
    name      = "memorypool_usage"
    mbean     = "java.lang:type=MemoryPool,name=*"
    attribute = "Usage"
```
### System info:

```
# lsb_release  -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie

# dpkg -l|grep telegraf
ii  telegraf                       1.0.1-1                    amd64        Plugin-driven server agent for reporting metrics into InfluxDB.

# ./activemq --version
INFO: Loading '/etc/default/activemq'
INFO: Using java '/usr/bin/java'
Java Runtime: Oracle Corporation 1.8.0_66 /usr/lib/jvm/jdk-8-oracle-x64/jre
  Heap sizes: current=131072k  free=130088k  max=6291456k
    JVM args: -Xms128M -Xmx6G -Xloggc:/home/log/activemq/gc.log -XX:+PrintGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseG1GC -Djava.util.logging.config.file=logging.properties -Djava.security.auth.login.config=/opt/apache-activemq-5.14.1//conf/login.config -Dactivemq.classpath=/opt/apache-activemq-5.14.1//conf:/opt/apache-activemq-5.14.1//../lib/: -Dactivemq.home=/opt/apache-activemq-5.14.1/ -Dactivemq.base=/opt/apache-activemq-5.14.1/ -Dactivemq.conf=/opt/apache-activemq-5.14.1//conf -Dactivemq.data=/opt/apache-activemq-5.14.1//data
Extensions classpath:
  [/opt/apache-activemq-5.14.1/lib,/opt/apache-activemq-5.14.1/lib/camel,/opt/apache-activemq-5.14.1/lib/optional,/opt/apache-activemq-5.14.1/lib/web,/opt/apache-activemq-5.14.1/lib/extra]
ACTIVEMQ_HOME: /opt/apache-activemq-5.14.1
ACTIVEMQ_BASE: /opt/apache-activemq-5.14.1
ACTIVEMQ_CONF: /opt/apache-activemq-5.14.1/conf
ACTIVEMQ_DATA: /opt/apache-activemq-5.14.1/data

ActiveMQ 5.14.1
For help or more information please see: http://activemq.apache.org

```
### Steps to reproduce:

Run Telegraf with jolokia plugin, and configure a metric which has space in its name.
### Expected behavior:

plugin should normalize name by removing spaces (at least as an opt-in feature)
### Actual behavior:

plugin does not sanitize the input, which makes data unable to query in infludb.

**Comment by phemmer** [comment] 2016-10-24 21:52
InfluxDB is capable of handling tags with spaces just fine:

```
> insert test,foo=bar\ baz value=1i
> select * from test where foo='bar baz'
name: test
----------
time                    foo     value
1477345753039455944     bar baz 1
```

**Comment by maxenced** [comment] 2016-10-28 09:36
Ok, so straced telegraf to try to understand what's going on.

The answer I get from jolokia is : 

```java
[pid 29240] <... read resumed> "HTTP/1.1 200 OK\r\nDate: Fri, 28 Oct 2016 09:03:00 GMT\r\nX-FRAME-OPTIONS: SAMEORIGIN\r\nContent-Type: text/plain; charset=UTF-8\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nExpires: Fri, 28 Oct 2016 08:03:00 GMT\r\nContent-Length: 767\r\nServer: Jetty(9.2.13.v20150730)\r\n\r\n{\"timestamp\":1477645380,\"status\":200,\"request\":{\"mbean\":\"java.lang:name=*,type=MemoryPool\",\"attribute\":\"Usage\",\"type\":\"read\"},\"value\":{\"java.lang:name=PS Eden Space,type=MemoryPool\":{\"Usage\":{\"max\":329252864,\"committed\":318242816,\"init\":17301504,\"used\":287773320}},\"java.lang:name=PS Survivor Space,type=MemoryPool\":{\"Usage\":{\"max\":14680064,\"committed\":14680064,\"init\":2621440,\"used\":3430416}},\"java.lang:name=Code Cache,type=MemoryPool\":{\"Usage\":{\"max\":50331648,\"committed\":7995392,\"init\":2555904,\"used\":7799552}},\"java.lang:name=PS Perm Gen,type=MemoryPool\":{\"Usage\":{\"max\":174063616,\"committed\":77594624,\"init\":22020096,\"used\":36632784}},\"java.lang:name=PS Old Gen,type=MemoryPool\":{\"Usage\":{\"max\":715653120,\"committed\":95420416,\"init\":45088768,\"used\":78359392}}}}", 4096) = 1030
```

What is sent to influx is : 

```
"POST /write?consistency=&db=typhon_telegraf_foo&precision=s&rp= HTTP/1.1\r\nHost: 10.24.1.11:8086\r\nUser-Agent: typhon_telegraf_foo\r\nContent-Length: 9015\r\nAuthorization: Basic dHlwaG9uX21lbHR5OmV1NE9vaGVlcXUzdg==\r\nContent-Type: \r\nAccept-Encoding: gzip\r\n\r\njolokia,client=foo,dc=th3,host=extra.foo,jolokia_host=localhost,jolokia_name=activemq,jolokia_port=8161,projet=foo,type=extra memorypool_usage_java.lang:name\\=Code\\ Cache\\,type\\=MemoryPool=\"map[Usage:map[max:5.0331648e+07 committed:7.995392e+06 init:2.555904e+06 used:7.799552e+06]]\",memorypool_usage_java.lang:name\\=PS\\ Eden\\ Space\\,type\\=MemoryPool=\"map[Usage:map[max:3.29252864e+08 committed:3.18242816e+08 init:1.7301504e+07 used:2.8777332e+08]]\",memorypool_usage_java.lang:name\\=PS\\ Old\\ Gen\\,type\\=MemoryPool=\"map[Usage:map[init:4.5088768e+07 used:7.8359392e+07 max:7.1565312e+08 committed:9.5420416e+07]]\",memorypool_usage_java.lang:name\\=PS\\ Perm\\ Gen\\,type\\=MemoryPool=\"map[Usage:map[max:1.74063616e+08 committed:7.7594624e+07 init:2.2020096e+07 used:3.6632784e+07]]\",memorypool_usage_java.lang:name\\=PS\\ Survivor\\ Space\\,type\\=MemoryPool=\"map[Usage:map[max:1.4680064e+07 committed:1.4680064e+07 init:2.62144e+06 used:3.430416e+06]]\"
```

The answer is : 

```
[pid 29240] <... read resumed> "HTTP/1.1 204 No Content\r\nContent-Type: application/json\r\nRequest-Id: 56a47360-9ced-11e6-ab00-000000000000\r\nX-Influxdb-Version: 1.0.0-c1.0.0\r\nDate: Fri, 28 Oct 2016 09:03:05 GMT\r\n\r\n", 4096) = 180
```

But in influx : 

```
> SHOW SERIES WHERE jolokia_name='activemq'
key
jolokia,client=foo,dc=th3,host=extra.foo,jolokia_host=localhost,jolokia_name=activemq,jolokia_port=8161,projet=foo,type=extra

> SELECT * FROM jolokia WHERE host='extra.foo' LIMIT 1
name: jolokia
-------------
time                    broker_current_connections_count        broker_memory_percent   broker_store_percent    broker_total_connections_count  broker_total_consumer_count     broker_total_incoming   broker_total_message_count      broker_total_outgoing   bytes_in        bytes_out        class_count_LoadedClassCount    class_count_TotalLoadedClassCount       class_count_UnloadedClassCount  client  controller_active_count dc      gc_collection_count_java.lang:name=G1 Old Generation,type=GarbageCollector_CollectionCount      gc_collection_count_java.lang:name=G1 Young Generation,type=GarbageCollector_CollectionCount     gc_collection_time_java.lang:name=G1 Old Generation,type=GarbageCollector_CollectionTime        gc_collection_time_java.lang:name=G1 Young Generation,type=GarbageCollector_CollectionTime      heap_memory_usage_committed      heap_memory_usage_init  heap_memory_usage_max   heap_memory_usage_used  host            idle_handler    incoming_msg    jolokia_host    jolokia_name    jolokia_port    leader_count    leader_election max_replication_lag     memorypool_usage_java.lang:name=Code Cache,type=MemoryPool                                       memorypool_usage_java.lang:name=Code Cache,type=MemoryPool_Usage        memorypool_usage_java.lang:name=Compressed Class Space,type=MemoryPool_Usage    memorypool_usage_java.lang:name=G1 Eden Space,type=MemoryPool_Usage      memorypool_usage_java.lang:name=G1 Old Gen,type=MemoryPool_Usage        memorypool_usage_java.lang:name=G1 Survivor Space,type=MemoryPool_Usage memorypool_usage_java.lang:name=Metaspace,type=MemoryPool_Usage memorypool_usage_java.lang:name=PS Eden Space,type=MemoryPool                                            memorypool_usage_java.lang:name=PS Old Gen,type=MemoryPool                                      memorypool_usage_java.lang:name=PS Perm Gen,type=MemoryPool                                             memorypool_usage_java.lang:name=PS Survivor Space,type=MemoryPool                                offline_partitions_count        partition_count projet  rps_fetch_consumer      rps_fetch_follower      rps_producer    server_count    thread_count_DaemonThreadCount  thread_count_PeakThreadCount     thread_count_ThreadCount        thread_count_TotalStartedThreadCount    time_fetch_consumer     time_fetch_follower     time_producer   type    unclean_leader_election under_replicated_partitions
1477644270000000000                                                                                                                                                                                                                                                             foo                            th3                                                                                                                                                                                                                                             extra.foo                                      localhost       activemq        8161                                                                    map[Usage:map[max:5.0331648e+07 committed:7.929856e+06 init:2.555904e+06 used:7.744064e+06]]                            map[Usage:map[max:3.29252864e+08 committed:3.18242816e+08 init:1.7301504e+07 used:2.0274516e+08]]        map[Usage:map[max:7.1565312e+08 committed:9.5420416e+07 init:4.5088768e+07 used:7.8359392e+07]] map[Usage:map[max:1.74063616e+08 committed:7.7594624e+07 init:2.2020096e+07 used:3.6601184e+07]] map[Usage:map[max:1.4680064e+07 committed:1.4680064e+07 init:2.62144e+06 used:3.430416e+06]]                                                    foo                                                                                                   extra
```

But from grafana, the request is : 

```
/api/datasources/proxy/7/query?db=typhon_telegraf_foo&q=SELECT%20mean(%22memorypool_usage_java.lang%3Aname%3DCode%20Cache%2Ctype%3DMemoryPool%22)%20FROM%20%22jolokia%22%20WHERE%20%22host%22%20%3D%20%27extra.foo%27%20AND%20time%20%3E%20now()%20-%2030m%20GROUP%20BY%20time(1m)%20fill(null)&epoch=ms
```
ie : 

```
SELECT mean("memorypool_usage_java.lang:name=Code Cache,type=MemoryPool") FROM "jolokia" WHERE "host" = 'extra.foo'
```
which returns : 

```
error:"unsupported mean iterator type: *influxql.stringInterruptIterator"
```

Might be more a grafana issue than a telegraf one ...

**Comment by sparrc** [comment] 2016-11-02 11:35
what version of grafana are you using? I think it should be supported in the latest version

**Comment by maxenced** [comment] 2016-11-02 12:08
Grafana v3.1.1 (commit: a4d2708)

**Comment by sparrc** [comment] 2017-02-03 10:56
closing this because I don't think it's a reproducible issue, Grafana & InfluxDB should both support metrics with spaces.

**Closed by sparrc** 2017-02-03 10:56 UTC
