### ISSUE TITLE
Raspberry Pi3 telegraf segfault

### ISSUE THREAD

**Issue by lfarkas** [influxdata/telegraf#2337] opened 2017-01-29 19:43 UTC
Hi,
I'm just installed telegraf to a raspberry pi3 with default config file and start to run (at the same time I also run influxdb and kapacitor too which working without problem, at least started). Right after it's start I've got this error in the log and exit:
```
Jan 29 19:35:09 raspberry-729b4b5 systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0xc5c24]
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: goroutine 1 [running]:
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: panic(0xad8dd0, 0x11422008)
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: /usr/local/go/src/runtime/panic.go:500 +0x33c
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: github.com/influxdata/telegraf/internal/config.(*Config).LoadDirectory.func1(0x7ef6ac63, 0x18, 0x0, 0x0, 0x105b420, 0x1183c080, 0x0, 0x0)
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/config/config.go:509 +0x30
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: path/filepath.Walk(0x7ef6ac63, 0x18, 0x11726188, 0x0, 0x0)
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: /usr/local/go/src/path/filepath/path.go:396 +0x8c
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: github.com/influxdata/telegraf/internal/config.(*Config).LoadDirectory(0x1140d4f0, 0x7ef6ac63, 0x18, 0x0, 0x0)
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/config/config.go:522 +0x6c
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: main.reloadLoop(0x1156ed40, 0x0, 0x0)
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:211 +0x11b4
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: main.main()
Jan 29 19:35:09 raspberry-729b4b5 telegraf[235]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x74
Jan 29 19:35:09 raspberry-729b4b5 systemd[1]: telegraf.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 29 19:35:09 raspberry-729b4b5 systemd[1]: Unit telegraf.service entered failed state.
Jan 29 19:35:09 raspberry-729b4b5 systemd[1]: telegraf.service holdoff time over, scheduling restart.
```
it's a known bug or I did something wrong?
I donwloaded the the tarball from this https://www.influxdata.com/downloads/

**Comment by sparrc** [comment] 2017-01-29 20:11
are you using the ARM binaries?

**Comment by lfarkas** [comment] 2017-01-29 20:12
After a further investigation I found another problem, but it's still not solve the above. Both for influxdb's and kapacitor's the files inside the tar.gz file owned by root, but in case of telegraf the files owned by ubuntu/ubuntu. It'd be useful to upload new tar.gz where the files owned by root/root.

**Comment by sparrc** [comment] 2017-01-29 20:13
actually I think this is a dupe of #1704

**Comment by lfarkas** [comment] 2017-01-29 20:13
I used this file:  https://dl.influxdata.com/telegraf/releases/telegraf-1.2.0_linux_armhf.tar.gz

**Closed by sparrc** 2017-01-29 20:13 UTC
