### ISSUE TITLE
Latest telegraf aarch64 RPM not installable on Amazon Linux 2

### ISSUE THREAD

**Issue by jpalomaki** [influxdata/telegraf#9861] opened 2021-10-05 09:16 UTC
## Summary

Cannot install latest telegraf version (`1.20.0` at the time of writing) via yum repo on Amazon Linux 2 (arm64)

NOTE: List of RPM packages on <https://repos.influxdata.com/rhel/7/arm64/stable/> includes the `1.20.0` package.

### YUM repository config /etc/yum.repos.d/telegraf.repo

```
[influxdb]
name=InfluxDB
baseurl=https://repos.influxdata.com/rhel/7/arm64/stable
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-telegraf
```

### System info:

Amazon Linux 2, arm64 (aarch64), AWS EC2 `c6gn.*` series instance type

### Docker

Not applicable

### Steps to reproduce:

1. Run Amazon Linux 2 on arm64
2. Configure yum repository as above
3. Run `yum check-update`
4. Run `yum --showduplicates list telegraf`

### Expected behavior:

Latest installable version is `1.20.0`

### Actual behavior:

Latest installable version is `1.19.1`

### Additional info:

What's the difference between these repos (beyond the former having only a few packages)?

- https://repos.influxdata.com/rhel/7/aarch64/stable/
- https://repos.influxdata.com/rhel/7/arm64/stable/

**Comment by powersj** [comment] 2021-10-05 14:05
"arm64" and "aarch64" refer to the same thing. Go and Debian-based distros use "arm64" to specify support for 64-bit arm, while RHEL/CentOS-based distros use the 'aarch64' value. Historically, our publication scripts appear to be using the Go-lang arch value of 'arch64' versus the RHEL/CentOS 'aarch64' value for the package architecture. It is more accurate to publish the RPMs with the aarch64 value and it is something we are looking into.

As far as 1.20.0 not showing up, I have confirmed that as well:

```
[ec2-user@ip-172-31-40-20 ~]$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
[ec2-user@ip-172-31-40-20 ~]$ arch
aarch64
[ec2-user@ip-172-31-40-20 ~]$ yum check-update
<snip>
[ec2-user@ip-172-31-40-20 ~]$ yum --showduplicates list telegraf
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Available Packages
telegraf.aarch64                                           1.15.1-1                                            influxdb
telegraf.aarch64                                           1.15.2-1                                            influxdb
telegraf.aarch64                                           1.15.3-1                                            influxdb
telegraf.aarch64                                           1.15.4-1                                            influxdb
telegraf.aarch64                                           1.16.0-1                                            influxdb
telegraf.aarch64                                           1.16.1-1                                            influxdb
telegraf.aarch64                                           1.16.2-1                                            influxdb
telegraf.aarch64                                           1.16.3-1                                            influxdb
telegraf.aarch64                                           1.17.0-1                                            influxdb
telegraf.aarch64                                           1.17.1-1                                            influxdb
telegraf.aarch64                                           1.17.2-1                                            influxdb
telegraf.aarch64                                           1.17.3-1                                            influxdb
telegraf.aarch64                                           1.18.0-1                                            influxdb
telegraf.aarch64                                           1.18.1-1                                            influxdb
telegraf.aarch64                                           1.18.2-1                                            influxdb
telegraf.aarch64                                           1.18.3-1                                            influxdb
telegraf.aarch64                                           1.19.0-1                                            influxdb
telegraf.aarch64                                           1.19.1-1                                            influxdb
[ec2-user@ip-172-31-40-20 ~]$ 
```

I was able to download the RPM and install it just fine:

```
[ec2-user@ip-172-31-40-20 ~]$ sudo rpm -ihv telegraf-1.20.0-1.aarch64.rpm 
warning: telegraf-1.20.0-1.aarch64.rpm: Header V4 RSA/SHA256 Signature, key ID 2582e0c5: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:telegraf-1.20.0-1                ################################# [100%]
Created symlink from /etc/systemd/system/multi-user.target.wants/telegraf.service to /usr/lib/systemd/system/telegraf.service.
[ec2-user@ip-172-31-40-20 ~]$ rpm -qa | grep telegraf
telegraf-1.20.0-1.aarch64
[ec2-user@ip-172-31-40-20 ~]$ telegraf version
Telegraf 1.20.0 (git: HEAD f489cff3)
```

@codyshepherd any thoughts on why this might be?

**Comment by jpalomaki** [comment] 2021-10-05 14:15
@powersj Thanks for the quick response.

I don't have much experience with yum repos, but should the timestamps in this file be more recent: https://repos.influxdata.com/rhel/7/arm64/stable/repodata/repomd.xml?

Currently it shows `<timestamp>1626296927</timestamp>` which'd be `Wed Jul 14 2021 21:08:47 GMT+0000`?

**Comment by powersj** [comment] 2021-10-05 14:21
Ah yes! that would explain why `1.19.2`, `1.19.3`, and `1.20.0` are not showing up. Let me get with the team to see how we update that file.

**Comment by codyshepherd** [comment] 2021-10-05 15:09
This is very likely due to [changes made to the package repo to support correct aarch64 packaging for rpms](https://github.com/influxdata/repos/pull/66). I've proposed [a fix](https://github.com/influxdata/repos/pull/89) to bring Telegraf in line with this reorganization.

**Comment by jpalomaki** [comment] 2021-10-06 05:45
@codyshepherd All right, let me know when the fix is rolled out (Iooks like the links point to a private repo so I can't track it myself).

**Comment by powersj** [comment] 2021-10-19 15:35
@jpalomaki Thanks for letting us know. I manually kicked off the update process last week. We just landed some automation to ensure that the older arm64 folder and the proper aarch64 folders get updated in the future. I'm going to go ahead and close this, but do feel free to reach out if you see any issues in the future!

Thanks again!

**Closed by powersj** 2021-10-19 15:35 UTC
Labels: bug, area/aws
