### ISSUE TITLE
[Feature Request] K/V telegraf configuration

### ISSUE THREAD

**Issue by blaggacao** [influxdata/telegraf#1558] opened 2016-07-29 00:14 UTC
As we build telegraf poles on every host in our cluster, I wonder if we can run host specific configuration easily from a metadata service (key value storage). Yes there are tools for doing that, like https://github.com/kelseyhightower/confd, but I think modern telegraf poles are remotely/centrally maintained by default in these days :smile:

**Comment by sparrc** [comment] 2016-07-29 09:05
+1, but this is a dupe of https://github.com/influxdata/telegraf/issues/272, which I've renamed to be a bit more relevant

**Closed by sparrc** 2016-07-29 09:05 UTC
