### ISSUE TITLE
arm package: nil pointer deref on startup due to absent /etc/telegraf/telegraf.d

### ISSUE THREAD

**Issue by aelse** [influxdata/telegraf#2770] opened 2017-05-06 03:50 UTC
Discovered this running up telegraf on a raspberry pi. This problem is mentioned tangentially in #1704 but I didn't find an open issue for it.

The arm bundle does not include /etc/telegraf/telegraf.d but the bundled init script uses this path for the config dir arg and the process terminates during startup (see detail in syslog extract below).

Telegraf should be tolerant of a missing config directory, or gracefully handle termination if it's intended that it should stop when the config directory does not exist. If config dir is mandatory then it should be present in the arm bundle.

`May  6 03:41:57 astro systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
May  6 03:41:58 astro telegraf[1726]: panic: runtime error: invalid memory address or nil pointer dereference
May  6 03:41:58 astro telegraf[1726]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0xc6044]
May  6 03:41:58 astro telegraf[1726]: goroutine 1 [running]:
May  6 03:41:58 astro telegraf[1726]: panic(0xad9df0, 0x1141c008)
May  6 03:41:58 astro telegraf[1726]: /usr/local/go/src/runtime/panic.go:500 +0x33c
May  6 03:41:58 astro telegraf[1726]: github.com/influxdata/telegraf/internal/config.(*Config).LoadDirectory.func1(0xbe9f4f3a, 0x18, 0x0, 0x0, 0x105c420, 0x114cc6e0, 0x0, 0x0)
May  6 03:41:58 astro telegraf[1726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/config/config.go:509 +0x30
May  6 03:41:58 astro telegraf[1726]: path/filepath.Walk(0xbe9f4f3a, 0x18, 0x1141c938, 0x0, 0x0)
May  6 03:41:58 astro telegraf[1726]: /usr/local/go/src/path/filepath/path.go:396 +0x8c
May  6 03:41:58 astro telegraf[1726]: github.com/influxdata/telegraf/internal/config.(*Config).LoadDirectory(0x11777720, 0xbe9f4f3a, 0x18, 0x0, 0x0)
May  6 03:41:58 astro telegraf[1726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/config/config.go:522 +0x6c
May  6 03:41:58 astro telegraf[1726]: main.reloadLoop(0x117c8f40, 0x0, 0x0)
May  6 03:41:58 astro telegraf[1726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:211 +0x11b4
May  6 03:41:58 astro telegraf[1726]: main.main()
May  6 03:41:58 astro telegraf[1726]: /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:342 +0x74
May  6 03:41:58 astro systemd[1]: telegraf.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May  6 03:41:58 astro systemd[1]: Unit telegraf.service entered failed state.
`

**Comment by danielnelson** [comment] 2017-05-08 17:13
What version of Telegraf is this happening with?

**Comment by aelse** [comment] 2017-05-10 12:07
@danielnelson Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)

**Comment by danielnelson** [comment] 2017-05-11 20:33
It looks like this has been fixed in master, and will be in the 1.3 release. https://github.com/influxdata/telegraf/commit/9e810ac46369e723f14fb3c51cbada859b4d0f8c

You can try the release candidate now: #2733

**Comment by danielnelson** [comment] 2017-05-11 20:33
Duplicate of #2466

**Closed by danielnelson** 2017-05-11 20:33 UTC
Labels: need more info
