### ISSUE TITLE
Telegraf not starting using systemd, not reading variables defined on /etc/default/telegraf

### ISSUE THREAD

**Issue by barry361** [influxdata/telegraf#13386] opened 2023-06-05 03:28 UTC
### Relevant telegraf.conf

```toml
urls = ["http://127.0.0.1:8086"]
token = "$mytoken"
organization = "myorganization"
bucket = "telegraf"
```

### Logs from Telegraf

```text
I dont have any logs on /var/log/telegraf folder. I got the logs below on /var/log/syslog

---
conf: line 1: configuration specified the fields ["urls" "organization" "token" "bucket"], but they weren't used
Jun  5 01:49:26 u_server2 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jun  5 01:49:26 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun  5 01:49:26 u_server2 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Jun  5 01:49:26 u_server2 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 4.
Jun  5 01:49:27 u_server2 telegraf[2757]: 2023-06-05T01:49:27Z I! Loading config: /etc/telegraf/telegraf.conf
Jun  5 01:49:27 u_server2 telegraf[2757]: 2023-06-05T01:49:27Z E! error loading config file /etc/telegraf/telegraf.conf: line 1: configuration specified the fields ["urls" "token" "bucket" "organization"], but they weren't used
Jun  5 01:49:27 u_server2 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jun  5 01:49:27 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun  5 01:49:27 u_server2 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Jun  5 01:49:27 u_server2 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Jun  5 01:49:27 u_server2 systemd[1]: telegraf.service: Start request repeated too quickly.
Jun  5 01:49:27 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun  5 01:49:39 u_server2 telegraf[2788]: 2023-06-05T01:49:39Z I! Loading config: /etc/telegraf/telegraf.conf
Jun  5 01:49:39 u_server2 telegraf[2788]: 2023-06-05T01:49:39Z E! error loading config file /etc/telegraf/telegraf.conf: line 1: configuration specified the fields ["urls" "token" "organization" "bucket"], but they weren't used
Jun  5 01:49:39 u_server2 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jun  5 01:49:39 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun  5 01:49:39 u_server2 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Jun  5 01:49:39 u_server2 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 1.
Jun  5 01:49:40 u_server2 telegraf[2811]: 2023-06-05T01:49:40Z I! Loading config: /etc/telegraf/telegraf.conf
Jun  5 01:49:40 u_server2 telegraf[2811]: 2023-06-05T01:49:40Z E! error loading config file /etc/telegraf/telegraf.conf: line 1: configuration specified the fields ["token" "urls" "bucket" "organization"], but they weren't used
Jun  5 01:49:40 u_server2 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jun  5 01:49:40 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun  5 01:49:40 u_server2 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Jun  5 01:49:40 u_server2 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 2.
Jun  5 01:49:40 u_server2 telegraf[2837]: 2023-06-05T01:49:40Z I! Loading config: /etc/telegraf/telegraf.conf
Jun  5 01:49:40 u_server2 telegraf[2837]: 2023-06-05T01:49:40Z E! error loading config file /etc/telegraf/telegraf.conf: line 1: configuration specified the fields ["bucket" "organization" "urls" "token"], but they weren't used
Jun  5 01:49:40 u_server2 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jun  5 01:49:40 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun  5 01:49:40 u_server2 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Jun  5 01:49:40 u_server2 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 3.
Jun  5 01:49:41 u_server2 telegraf[2862]: 2023-06-05T01:49:41Z I! Loading config: /etc/telegraf/telegraf.conf
Jun  5 01:49:41 u_server2 telegraf[2862]: 2023-06-05T01:49:41Z E! error loading config file /etc/telegraf/telegraf.conf: line 1: configuration specified the fields ["organization" "bucket" "urls" "token"], but they weren't used
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 4.
Jun  5 01:49:41 u_server2 telegraf[2888]: 2023-06-05T01:49:41Z I! Loading config: /etc/telegraf/telegraf.conf
Jun  5 01:49:41 u_server2 telegraf[2888]: 2023-06-05T01:49:41Z E! error loading config file /etc/telegraf/telegraf.conf: line 1: configuration specified the fields ["bucket" "organization" "token" "urls"], but they weren't used
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Start request repeated too quickly.
Jun  5 01:49:41 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
```

### System info

Telegraf 1.26.3, Debian 11, Ubuntu 18.4 lts

### Steps to reproduce

I tried the configs on both Debian 11 and Ubuntu 18.4 lts and the same problem occur, using basic configs

### Expected behavior

The expected bahavior is to have telegraf starting automatically from systemd. 

### Actual behavior

Telegraf only starts manually. Starting using systemd provides the below error.

test@u_server2:~$ sudo systemctl status telegraf.service  
telegraf.service - Telegraf
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2023-06-05 01:49:41 UTC; 1h 22min ago
     Docs: https://github.com/influxdata/telegraf
  Process: 2888 ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/tel
 Main PID: 2888 (code=exited, status=1/FAILURE)

Jun 05 01:49:41 u_server2 systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Jun 05 01:49:41 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun 05 01:49:41 u_server2 systemd[1]: Failed to start Telegraf.
Jun 05 01:49:41 u_server2 systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Jun 05 01:49:41 u_server2 systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Jun 05 01:49:41 u_server2 systemd[1]: Stopped Telegraf.
Jun 05 01:49:41 u_server2 systemd[1]: telegraf.service: Start request repeated too quickly.
Jun 05 01:49:41 u_server2 systemd[1]: telegraf.service: Failed with result 'exit-code'.
Jun 05 01:49:41 u_server2 systemd[1]: Failed to start Telegraf.

### Additional info

**Configs on /etc/default/telegraf:**
$INFLUX_TOKEN=token

This problem was not solved according to the issue #11868, #8395.
It seems that Systemd doesn't read variables on the file /etc/default/telegraf.
I tried some of the workaround by removing the "hyphen" and doesn't worked for me. I'm using this on a lab for
tests. I'm facing this issues on Debian 11, and Ubuntu Server 18.4 lts.
Does anybody know how to fix this issue?

**Comment by neelayu** [comment] 2023-06-05 10:24
Just to clarify if its not a typo, but 
```
$INFLUX_TOKEN=token
```
prefixed with `$` is not the correct syntax for the env file. It should just be the env name

**Comment by powersj** [comment] 2023-06-05 13:10
Can you please provide your full config, not just the section under influxdb.

**Comment by powersj** [comment] 2023-06-05 13:25
As @neelayu mentioned, I do think your issue is that you have prefaced your environment variables with a `$`, when you should not.

I used the nightly deb on Ubuntu 22.04:

```s
root@j1:~# cat /etc/default/telegraf 
INFLUX_URL=http://192.168.1.160:8086
INFLUX_TOKEN=my-token
INFLUX_ORG=my-org
INFLUX_BUCKET=my-bucket
root@j1:~# cat /etc/default/telegraf 
[[inputs.mem]]
[[outputs.influxdb_v2]]
   urls=["$INFLUX_URL"]
   token = "$INFLUX_TOKEN"
   organization = "$INFLUX_ORG"
   bucket = "$INFLUX_BUCKET"
root@j1:~# systemctl start telegraf
root@j1:~# systemctl status telegraf
● telegraf.service - Telegraf
     Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-06-05 13:20:06 UTC; 3s ago
       Docs: https://github.com/influxdata/telegraf
   Main PID: 1238 (telegraf)
      Tasks: 25 (limit: 77034)
     Memory: 31.2M
        CPU: 51ms
     CGroup: /system.slice/telegraf.service
             └─1238 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/teleg>

Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Starting Telegraf 1.27.0-eea3bf3c
Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Available plugins: 236 inputs, 9 aggregators, 28 pro>
Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded inputs: mem
Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded aggregators:
Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded processors:
Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded secretstores:
Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded outputs: influxdb_v2
Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Tags enabled: host=j1
Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:>
Jun 05 13:20:06 j1 systemd[1]: Started Telegraf.
```

> It seems that Systemd doesn't read variables on the file /etc/default/telegraf.

You can verify that it does via the [`telegraf.service` file](https://github.com/influxdata/telegraf/blob/master/scripts/telegraf.service#L9).

> This problem was not solved according to the issue https://github.com/influxdata/telegraf/issues/11868, https://github.com/influxdata/telegraf/issues/8395.

The above shows otherwise.

**Comment by barry361** [comment] 2023-06-05 23:11
> ```
> 
> ```
> 
> 
>     
>   
> 
> prefixed with `$` is not the correct syntax for the env file. It should just be the env name

I removed the typo. That's not the problem. I was playing with it and forget the $ sign there. So, that was as mistake why telegraf doesn't logged this error? I think it is not reading this file at all.

**Comment by powersj** [comment] 2023-06-05 23:23
> So, that was as mistake why telegraf doesn't logged this error? I think it is not reading this file at all.

Telegraf does not read the file. The systemd service loads that file into the environment when the service is running. Telegraf will read from the environment.

Unless you have additional logs or steps to reproduce I am going to close this as you have not shown a reproducible error.

**Comment by barry361** [comment] 2023-06-05 23:35
follow the full telegraf.conf config

[telegraf.zip](https://github.com/influxdata/telegraf/files/11658567/telegraf.zip)

**Comment by barry361** [comment] 2023-06-05 23:37
> > So, that was as mistake why telegraf doesn't logged this error? I think it is not reading this file at all.
> 
> Telegraf does not read the file. The systemd service loads that file into the environment when the service is running. Telegraf will read from the environment.
> 
> Unless you have additional logs or steps to reproduce I am going to close this as you have not shown a reproducible error.

what are the basic configs that telegraf needs to start? I mean just start the service.

**Comment by barry361** [comment] 2023-06-05 23:41
> As @neelayu mentioned, I do think your issue is that you have prefaced your environment variables with a `$`, when you should not.
> 
> I used the nightly deb on Ubuntu 22.04:
> 
> ```m68k
> root@j1:~# cat /etc/default/telegraf 
> INFLUX_URL=http://192.168.1.160:8086
> INFLUX_TOKEN=my-token
> INFLUX_ORG=my-org
> INFLUX_BUCKET=my-bucket
> root@j1:~# cat /etc/default/telegraf 
> [[inputs.mem]]
> [[outputs.influxdb_v2]]
>    urls=["$INFLUX_URL"]
>    token = "$INFLUX_TOKEN"
>    organization = "$INFLUX_ORG"
>    bucket = "$INFLUX_BUCKET"
> root@j1:~# systemctl start telegraf
> root@j1:~# systemctl status telegraf
> ● telegraf.service - Telegraf
>      Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
>      Active: active (running) since Mon 2023-06-05 13:20:06 UTC; 3s ago
>        Docs: https://github.com/influxdata/telegraf
>    Main PID: 1238 (telegraf)
>       Tasks: 25 (limit: 77034)
>      Memory: 31.2M
>         CPU: 51ms
>      CGroup: /system.slice/telegraf.service
>              └─1238 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/teleg>
> 
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Starting Telegraf 1.27.0-eea3bf3c
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Available plugins: 236 inputs, 9 aggregators, 28 pro>
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded inputs: mem
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded aggregators:
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded processors:
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded secretstores:
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Loaded outputs: influxdb_v2
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! Tags enabled: host=j1
> Jun 05 13:20:06 j1 telegraf[1238]: 2023-06-05T13:20:06Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:>
> Jun 05 13:20:06 j1 systemd[1]: Started Telegraf.
> ```
> 
> > It seems that Systemd doesn't read variables on the file /etc/default/telegraf.
> 
> You can verify that it does via the [`telegraf.service` file](https://github.com/influxdata/telegraf/blob/master/scripts/telegraf.service#L9).
> 
> > This problem was not solved according to the issue #11868, #8395.
> 
> The above shows otherwise.

The isssue on #11868, #8395, was closed automatically without a solution.
From where did you get telegraf?  I download the version 1.26.3 from this link, https://www.influxdata.com/time-series-platform/telegraf/.

**Comment by barry361** [comment] 2023-06-05 23:45
The document on the link https://docs.influxdata.com/telegraf/v1.21/administration/configuration/, states that the variable should be encased using ${ }, i tried this way and nothing changed.

**Comment by barry361** [comment] 2023-06-05 23:54
I got the error below using -_-debug._ **What are the basic configs for this thing start?** The file telegraf.conf only have output for influxdb_v2, right now.

root@u_server2:/home/test# **/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d/ --debug**
2023-06-05T23:50:14Z I! Loading config: /etc/telegraf/telegraf.conf
2023-06-05T23:50:14Z E! error loading config file /etc/telegraf/telegraf.conf: line 1: configuration specified the fields ["urls" "token" "organization" "bucket"], but they weren't used

**Comment by powersj** [comment] 2023-06-06 00:08
The reason I asked for your full config is that error message about line 1 specifying fields but not getting used means your config is invalid. Looking at your config you have the influxdb_v2 table header commented out:

```
# [[outputs.influxdb_v2]]   <--- this is commented out
#   ## The URLs of the InfluxDB cluster nodes.
#   ##
#   ## Multiple URLs can be specified for a single cluster, only ONE of the
#   ## urls will be written to each interval.
#   ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]

urls = ["http://127.0.0.1:8086"]
#
#   ## Token for authentication.
token = "$INFLUX_TOKEN"
#
#   ## Organization is the name of the organization you wish to write to.
organization = "$MYORG"
#
#   ## Destination bucket to write into.
bucket = "telegraf"
```

Which means that all those settings where trying to be applied to the `[agent]` section. You have not declared a `influxdb_v2` plugin, so telegraf does not know what to do with those options.

Please uncomment that line above and try again.

**Comment by barry361** [comment] 2023-06-06 02:27
That was the problem, after remove the comment it started just fine.
Before i see your comment , i installed other versions, and the version 1.24.4 worked ok, without any change on the file telegraf.conf. Any version above 1.24.4 didn't work! So, i copy the telegraf.conf to the 1.26.3, and worked fine! I looked both files and didn't find any difference. I will upload the file from version 1.24.4, maybe you can point where is the problem.  

Thanks for the help

**Comment by barry361** [comment] 2023-06-06 02:30
Follow the file from version 1.24.4. 
[telegraf-1.24.4.conf.zip](https://github.com/influxdata/telegraf/files/11659348/telegraf-1.24.4.conf.zip)

**Comment by powersj** [comment] 2023-06-06 13:35
If you look at your config from 1.24.4 it uses the `outputs.influxdb` output.

I believe in 1.25 we changed the default config to no longer include the `[[outputs.influxdb]]` by default. This was done after lots of feedback that because that was there telegraf would start automatically but fail to send any metrics. The telegraf service would report as running making it seem that everything was working fine.

**Closed by powersj** 2023-06-06 13:35 UTC
Labels: bug
