### ISSUE TITLE
Telegraf Ignores The Failed Input Requirement

### ISSUE THREAD

**Issue by observeralone** [influxdata/telegraf#11289] opened 2022-06-13 12:11 UTC
# Background
When telegraf starts, the Inputs will be initialized. If the initialization fails, telegraf will exit the program directly. This leads to the process of automatic monitoring. If there is an error in one input, all input additions on the machine will fail.

## Our process is as follows:
`New Server —> create telegraf conf to telegraf.d —> restart telegraf`
example：
`new monogodb —> create mongodb.conf to telegraf.d — restart telegraf`
`new docker container —> create mongodb.conf to telegraf.d — restart telegraf`

In this process, the monitoring of the same machine uses the same telegraf systemd.

When there is an input init exception (for example: the mongodb process is gone, the mongodb input init fails), telegraf will fail to start.

## Why don't we start multiple telegraf processes to monitor their own programs?
Because we may install multiple programs on one machine, this involves the problem of excessive resource consumption. 

After all, monitoring is very sensitive to resource usage, and we hope that a machine only needs to start a telegraf.

# Demand
We would like to be able to add a configuration that sets whether it ignores input that fails init. 

If it is true, when the telegraf is loading, if the input initialization is abnormal, the exception log will be logged directly, ignore it and continue to execute other inputs.

Hope to hear from you, thanks

**Comment by srebhan** [comment] 2022-06-13 12:20
Duplicate of #10694. Please continue the discussion there.

**Closed by srebhan** 2022-06-13 12:20 UTC
Labels: area/mongodb, support
