### ISSUE TITLE
processors.rename: fields are stored as string instead of float

### ISSUE THREAD

**Issue by iserranoe** [influxdata/telegraf#10142] opened 2021-11-22 12:00 UTC
I'm using the `inputs.http` plugin to store data from an API into `Influxdb2.0`. The fields are strings, therefore I have to convert them to float with `processors.converter`. Moreover, I want to rename these fields using `processors.rename`. However, once I rename the fields they are no longer floats, but string. I try to rename them first and the convert them, with the same results. 

This is the configuration file, option 1:
```
[[processors.converter]]
  [processors.converter.fields]
    float = ["c_0_value","f_0_value","t_0_value","p_0_value"]

[[processors.rename]]
  [[processors.rename.replace]]
    field = "c_0_value"
    dest = "Conductivity"

  [[processors.rename.replace]]
    field = "f_0_value"
    dest = "Frequency"
  
  [[processors.rename.replace]]
    field = "p_0_value"
    dest = "pH"
  
  [[processors.rename.replace]]
    field = "t_0_value"
    dest = "Temperature"
```

And configuration file, option 2:

```
[[processors.rename]]
  [[processors.rename.replace]]
    field = "c_0_value"
    dest = "Conductivity"

  [[processors.rename.replace]]
    field = "f_0_value"
    dest = "Frequency"
  
  [[processors.rename.replace]]
    field = "p_0_value"
    dest = "pH"
  
  [[processors.rename.replace]]
    field = "t_0_value"
    dest = "Temperature"

[[processors.converter]]
  [processors.converter.fields]
    float = ["Conductivity","Frequency","pH","Temperature"]
```

**Comment by powersj** [comment] 2021-11-22 17:52
Can you please provide the output before and after applying the processors, please?

**Comment by iserranoe** [comment] 2021-11-23 08:17
I don't know if this is what you mean with the output, the output configuration is: 
```
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "org"
  bucket = "bucket"
  metric_buffer_limit = 30000
```
I didn't change the configuration after applying the processors.

**Comment by Hipska** [comment] 2021-11-24 22:55
The metric output when you run telegraf with `—test`

**Comment by iserranoe** [comment] 2021-11-26 09:58
Ok, this is what I get:

Option 1: `Device1 Conductivity="131.78",Frequency="131027.0",Temperature="14.94",pH="10.84" 1637920557000000000`
Option 2: `Device1 Conductivity="131.78",Frequency="131027.0",Temperature="14.94",pH="10.84" 1637920557000000000`

**Comment by iserranoe** [comment] 2021-11-26 10:26
Playing with different combinations of configuration, I finally found the working one, a mixed of option 1 and 2 together...:
```
[[processors.converter]]
  [processors.converter.fields]
    float = ["c_0_value","f_0_value","t_0_value","p_0_value"]

[[processors.rename]]
  [[processors.rename.replace]]
    field = "c_0_value"
    dest = "Conductivity"

  [[processors.rename.replace]]
    field = "f_0_value"
    dest = "Frequency"
  
  [[processors.rename.replace]]
    field = "p_0_value"
    dest = "pH"
  
  [[processors.rename.replace]]
    field = "t_0_value"
    dest = "Temperature"

[[processors.converter]]
  [processors.converter.fields]
    float = ["Conductivity","Frequency","pH","Temperature"]
```

**Comment by Hipska** [comment] 2021-11-29 11:28
Yeah, the problem is the ordering of the processors. As stated in the docs, that order is not fixed unless you specify it with the `order` option.

**Comment by powersj** [comment] 2021-12-21 22:08
I'm going to go ahead and close this one. I think we are in agreement that the regex expects strings and operates on strings. Changing that is not something we would want to do.

**Closed by powersj** 2021-12-21 22:08 UTC
Labels: feature request
