### ISSUE TITLE
http_listener_test hangs indefinitely ~50% of invocations 

### ISSUE THREAD

**Issue by rickard-von-essen** [influxdata/telegraf#3158] opened 2017-08-23 07:08 UTC
master (8c68bd9ddbc2a7495796f44048b013c5098065f8)
Darwin Kernel Version 17.0.0: Thu Jul 20 17:24:26 PDT 2017; root:xnu-4556.0.0.1.2~1/RELEASE_X86_64 x86_64
go version go1.8.3 darwin/amd64

### Steps to reproduce:

```shell
$ go test -v ./plugins/inputs/http_listener
=== RUN   TestWriteHTTP
2017/08/23 09:07:03 I! Started HTTP listener service on :0
2017/08/23 09:07:03 E! http_listener received a single line longer than the maximum of 65536 bytes
2017/08/23 09:07:03 I! Stopped HTTP listener service on  :0
--- PASS: TestWriteHTTP (0.00s)
=== RUN   TestWriteHTTPNoNewline
2017/08/23 09:07:03 I! Started HTTP listener service on :0
2017/08/23 09:07:03 I! Stopped HTTP listener service on  :0
--- PASS: TestWriteHTTPNoNewline (0.00s)
=== RUN   TestWriteHTTPMaxLineSizeIncrease
2017/08/23 09:07:03 I! Started HTTP listener service on :0
2017/08/23 09:07:03 I! Stopped HTTP listener service on  :0
--- PASS: TestWriteHTTPMaxLineSizeIncrease (0.00s)
=== RUN   TestWriteHTTPVerySmallMaxBody
2017/08/23 09:07:03 I! Started HTTP listener service on :0
2017/08/23 09:07:03 I! Stopped HTTP listener service on  :0
--- PASS: TestWriteHTTPVerySmallMaxBody (0.00s)
=== RUN   TestWriteHTTPVerySmallMaxLineSize
2017/08/23 09:07:03 I! Started HTTP listener service on :0
2017/08/23 09:07:03 I! Stopped HTTP listener service on  :0
--- PASS: TestWriteHTTPVerySmallMaxLineSize (0.00s)
=== RUN   TestWriteHTTPLargeLinesSkipped
2017/08/23 09:07:03 I! Started HTTP listener service on :0
2017/08/23 09:07:03 E! http_listener received a single line longer than the maximum of 100 bytes
2017/08/23 09:07:03 I! Stopped HTTP listener service on  :0
--- PASS: TestWriteHTTPLargeLinesSkipped (0.00s)
=== RUN   TestWriteHTTPGzippedData
2017/08/23 09:07:03 I! Started HTTP listener service on :0
2017/08/23 09:07:03 I! Stopped HTTP listener service on  :0
--- PASS: TestWriteHTTPGzippedData (0.00s)
=== RUN   TestWriteHTTPHighTraffic
2017/08/23 09:07:03 I! Started HTTP listener service on :0
^C⏎ 
```

**Comment by rickard-von-essen** [comment] 2017-08-23 07:09
Might be related to #2923 and or #2280.

**Comment by danielnelson** [comment] 2017-08-23 19:09
Can't reproduce on Linux

**Comment by rickard-von-essen** [comment] 2017-08-23 19:10
I'll have some time to look into it tomorrow.

**Comment by rickard-von-essen** [comment] 2017-08-24 13:58
Can't reproduce this on FreeBSD either. Seems to be macOS specific.

**Comment by rickard-von-essen** [comment] 2017-08-24 14:10
The problematic test is `TestWriteHTTPHighTraffic` and running with `-cpu 1` seems to avoid it.

**Comment by rickard-von-essen** [comment] 2017-08-24 14:41
Removing this [`acc.Wait(25000)`](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http_listener/http_listener_test.go#L253)  reveals a bit more info.

**Comment by rickard-von-essen** [comment] 2017-08-24 19:51
Without  `acc.Wait(25000)` I get this when it fails on macOS High Sierra (10.13).

```
 $ go test -v -timeout 5s -run TestWriteHTTPHighTraffic ./plugins/inputs/http_listener/ 
=== RUN   TestWriteHTTPHighTraffic
2017/08/24 17:19:19 I! Started HTTP listener service on :0
2017/08/24 17:19:19 I! Stopped HTTP listener service on  :0
--- FAIL: TestWriteHTTPHighTraffic (0.30s)
        Error Trace:    http_listener_test.go:244
                        asm_amd64.s:2337
        Error:          Received unexpected error:
                        Post http://localhost:58440/write?db=mydb: read tcp [::1]:59202->[::1]:58440: read: connection reset by peer
        Error Trace:    http_listener_test.go:244
                        asm_amd64.s:2337
        Error:          Received unexpected error:
                        Post http://localhost:58440/write?db=mydb: read tcp [::1]:59204->[::1]:58440: read: connection reset by peer
        Error Trace:    http_listener_test.go:244
                        asm_amd64.s:2337
        Error:          Received unexpected error:
                        Post http://localhost:58440/write?db=mydb: read tcp [::1]:59422->[::1]:58440: read: connection reset by peer
        Error Trace:    http_listener_test.go:254
        Error:          Not equal:
                        expected: 25000
                        received: 20445
FAIL
exit status 1
FAIL    github.com/influxdata/telegraf/plugins/inputs/http_listener     0.315s
```

It might be a Go bug.

**Comment by goller** [comment] 2017-08-24 20:02
I get this panic when I tried:

```
ChristohersMBP2:telegraf goller$ go test -v -timeout 5s -run TestWriteHTTPHighTraffic ./plugins/inputs/http_listener/
=== RUN   TestWriteHTTPHighTraffic
2017/08/24 15:01:36 I! Started HTTP listener service on :0
panic: test timed out after 5s

goroutine 19960 [running]:
testing.startAlarm.func1()
	/usr/local/Cellar/go/1.8.3/libexec/src/testing/testing.go:1023 +0xf9
created by time.goFunc
	/usr/local/Cellar/go/1.8.3/libexec/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420076ea0, 0x1342c71, 0x18, 0x1371128, 0x105ac01)
	/usr/local/Cellar/go/1.8.3/libexec/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc420076ea0)
	/usr/local/Cellar/go/1.8.3/libexec/src/testing/testing.go:882 +0x67
testing.tRunner(0xc420076ea0, 0xc42010fde0)
	/usr/local/Cellar/go/1.8.3/libexec/src/testing/testing.go:657 +0x96
testing.runTests(0xc4200f10a0, 0x14d5620, 0xd, 0xd, 0xc42010fed0)
	/usr/local/Cellar/go/1.8.3/libexec/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc4203b1f20, 0xc42010ff20)
	/usr/local/Cellar/go/1.8.3/libexec/src/testing/testing.go:822 +0xfc
main.main()
	github.com/influxdata/telegraf/plugins/inputs/http_listener/_test/_testmain.go:66 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [semacquire]:
sync.runtime_notifyListWait(0xc421f6c090, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc421f6c080)
	/usr/local/Cellar/go/1.8.3/libexec/src/sync/cond.go:57 +0x89
github.com/influxdata/telegraf/testutil.(*Accumulator).Wait(0xc42001cfc0, 0x61a8)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/testutil/accumulator.go:222 +0x69
github.com/influxdata/telegraf/plugins/inputs/http_listener.TestWriteHTTPHighTraffic(0xc420076f70)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener/http_listener_test.go:253 +0x1f0
testing.tRunner(0xc420076f70, 0x1371128)
	/usr/local/Cellar/go/1.8.3/libexec/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/Cellar/go/1.8.3/libexec/src/testing/testing.go:697 +0x2ca

goroutine 7 [IO wait]:
net.runtime_pollWait(0x2005018, 0x72, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200bb418, 0x72, 0x0, 0xc422505a20)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200bb418, 0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4200bb3b0, 0x0, 0x14a77a0, 0xc422505a20)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000e0d8, 0xc42003ede0, 0x1242ffe, 0x1056530)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000e0d8, 0x13714d8, 0xc4223e6780, 0x14abea0, 0xc4201280c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0xc420122000, 0x14ab660, 0xc42000e0d8, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2643 +0x228
github.com/influxdata/telegraf/plugins/inputs/http_listener.(*HTTPListener).httpListen(0xc4200997c0, 0x1371ba0, 0xc420099800)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener/http_listener.go:170 +0x10b
github.com/influxdata/telegraf/plugins/inputs/http_listener.(*HTTPListener).Start.func1(0xc4200997c0)
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener/http_listener.go:133 +0x57
created by github.com/influxdata/telegraf/plugins/inputs/http_listener.(*HTTPListener).Start
	/Users/goller/src/go/src/github.com/influxdata/telegraf/plugins/inputs/http_listener/http_listener.go:134 +0x7ce

goroutine 20089 [IO wait]:
net.runtime_pollWait(0x20218c0, 0x72, 0xf)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42248cfb8, 0x72, 0x14a8c20, 0x14a54f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42248cfb8, 0xc42255f000, 0x1000)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42248cf50, 0xc42255f000, 0x1000, 0x1000, 0x0, 0x14a8c20, 0x14a54f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000f7c0, 0xc42255f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc42253ea00, 0xc42255f000, 0x1000, 0x1000, 0x0, 0xc421903d48, 0x11413f8)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc42251b440)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc42251b440, 0x4, 0x1db2c3a8, 0x14d8ae0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:129 +0x67
net/http.(*conn).serve(0xc4223e63c0, 0x14abde0, 0xc42253e9c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1850 +0x7f1
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce

goroutine 20108 [IO wait]:
net.runtime_pollWait(0x39b0d50, 0x72, 0xb)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42248d418, 0x72, 0x14a8c20, 0x14a54f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42248d418, 0xc4224d9000, 0x1000)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42248d3b0, 0xc4224d9000, 0x1000, 0x1000, 0x0, 0x14a8c20, 0x14a54f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42019d0d0, 0xc4224d9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc422584120, 0xc4224d9000, 0x1000, 0x1000, 0x4, 0xc422483ac0, 0xf)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc422540e40)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc422540e40, 0x1, 0x0, 0x1, 0x0, 0xc421d204e0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc422584120)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1117 +0xa35

goroutine 20109 [select]:
net/http.(*persistConn).writeLoop(0xc422584120)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1118 +0xa5a

goroutine 20120 [IO wait]:
net.runtime_pollWait(0x2595e50, 0x72, 0x17)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc422466928, 0x72, 0x14a8c20, 0x14a54f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc422466928, 0xc42255a000, 0x1000)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4224668c0, 0xc42255a000, 0x1000, 0x1000, 0x0, 0x14a8c20, 0x14a54f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4201f5210, 0xc42255a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc4224adb00, 0xc42255a000, 0x1000, 0x1000, 0x4, 0xc422477910, 0xf)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc4225329c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc4225329c0, 0x1, 0x0, 0x1, 0x0, 0xc4220c14a0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc4224adb00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1117 +0xa35

goroutine 20121 [select]:
net/http.(*persistConn).writeLoop(0xc4224adb00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1118 +0xa5a

goroutine 20151 [IO wait]:
net.runtime_pollWait(0x2021200, 0x72, 0xd)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42248d4f8, 0x72, 0x14a8c20, 0x14a54f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42248d4f8, 0xc422569000, 0x1000)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42248d490, 0xc422569000, 0x1000, 0x1000, 0x0, 0x14a8c20, 0x14a54f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000f820, 0xc422569000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc42253f240, 0xc422569000, 0x1000, 0x1000, 0x0, 0xc421904d48, 0x11413f8)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc42251b500)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc42251b500, 0x4, 0x1dabd42e, 0x14d8ae0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:129 +0x67
net/http.(*conn).serve(0xc4223e6780, 0x14abde0, 0xc42253f200)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1850 +0x7f1
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce
exit status 2
FAIL	github.com/influxdata/telegraf/plugins/inputs/http_listener```

**Comment by danielnelson** [comment] 2017-08-24 20:09
It looks like a lot of connections would be made by this test, maybe we are just hitting the open file limit?

**Comment by danielnelson** [comment] 2017-08-24 20:10
Is there a way on Mac to let it hang, then check the number of tcp connections open?

**Comment by danielnelson** [comment] 2017-08-25 20:06
Can you test with this change:
```diff
diff --git a/plugins/inputs/http_listener/http_listener_test.go b/plugins/inputs/http_listener/http_listener_test.go
index 654f2f83..5e439bf8 100644
--- a/plugins/inputs/http_listener/http_listener_test.go
+++ b/plugins/inputs/http_listener/http_listener_test.go
@@ -242,6 +242,7 @@ func TestWriteHTTPHighTraffic(t *testing.T) {
                        for i := 0; i < 500; i++ {
                                resp, err := http.Post(createURL(listener, "/write", "db=mydb"), "", bytes.NewBuffer([]byte(testMsgs)))
                                require.NoError(t, err)
+                               resp.Body.Close()
                                require.EqualValues(t, 204, resp.StatusCode)
                        }
                }(&wg)
```

**Comment by rickard-von-essen** [comment] 2017-08-25 20:10
I'm off for the weekend. I'll give it a try on Monday.

**Comment by danielnelson** [comment] 2017-08-25 21:00
I went ahead and committed this to master, probably a good thing regardless if it works.  8ecc5863

**Comment by rickard-von-essen** [comment] 2017-08-28 19:34
Unfortunately 8ecc586 didn't fix it.

**Comment by danielnelson** [comment] 2017-08-28 19:51
Thanks for the update, too bad

**Comment by ssoroka** [comment] 2020-02-19 15:48
Looks like this isn't relevant anymore, since there's now plugins/inputs/http_listener_v2 and it doesn't exhibit this behavior.
Closing

**Closed by ssoroka** 2020-02-19 15:48 UTC
Labels: bug, platform/darwin
