### ISSUE TITLE
Graphite output keeps sending metrics to the old server when the ip address in DNS name changes

### ISSUE THREAD

**Issue by dibilder** [influxdata/telegraf#13487] opened 2023-06-23 14:34 UTC
### Relevant telegraf.conf

```toml
[[inputs.statsd]]
  protocol = "udp"
  service_address = "127.0.0.1:30001"
  metric_separator = "."
  max_ttl = "1h" 
[[outputs.graphite]]
  servers = ["graphite.test:30000"]
  template = "host.measurement.field"
  graphite_tag_support = false
```

### Logs from Telegraf

```text
[agent] Error writing to outputs.graphite: could not write to any Graphite server in cluster
```

### System info

Ubuntu 22.04, telegraf 1.27.1

### Steps to reproduce

(1) In the example config, telegraf sends output to a graphite server graphite.test:30000. Create 2 hosts for fake graphite servers. Create DNS record for "graphite.test" with IP of one of these hosts. Or use /etc/hosts on the host with telegraf agent, with the hosts file the problem is reproduced too.
Add the same line with your ip to the /etc/hosts
192.168.0.11 graphite.test
(2) Start telegraf using the attached config
(3) In another shell of the host with telegraf agent, start sending input to the configured statsd UDP input at port 30001, for example using
while true; do echo "test:50|g" | nc -u -w1 127.0.0.1 30001; done
(4) Start a TCP server listening on 30000 port on both of 2 fake graphite servers:
nc -l -k 30000
(5) You will see received metrics on the host, which IP you set for 'graphite.test' record.
(6) Now set the IP of the second graphite host for 'graphite.test' record in DNS or in /etc/hosts file. You will still receive metrics on the first graphite host.

### Expected behavior

Telegraf agent start sending metrics to the new IP

### Actual behavior

Telegraf agent keeps sending metrics to the old IP

### Additional info

But telegraf will start sending metrics to the new ip if you restart telegraf service.

Video of problem reproducing: https://youtu.be/gCKBzOb5GAc

**Comment by powersj** [comment] 2023-06-23 16:09
Why do you think the client would respond to the DNS change? It has an established connection with a server that is both valid and alive.

The dialer user is the one from the Go library. You can view [the code yourself here](https://github.com/golang/go/blob/master/src/net/dial.go#L478-L481). This is during the initial call to `Dial`, where the address is resolved.

Unless there is an interruption in the connection the address would not be re-resolved or reconnected. This is not a bug nor a feature we would implement, so I am closing this as won't fix.

**Closed by powersj** 2023-06-23 16:09 UTC
Labels: bug
