### ISSUE TITLE
Consider current log file size for rotating

### ISSUE THREAD

**Issue by gerasym** [influxdata/telegraf#6845] opened 2020-01-02 14:06 UTC
## Feature Request

Consider current log file size for rotating

### Proposal:
It would be better to set https://github.com/influxdata/telegraf/blob/master/internal/rotate/file_writer.go#L109 to current file size
### Current behavior:
Logfile is rotated only when bytesWritten reaches logfile_rotation_max_size, which means if telegraf was restarted/crashed logfile will not be rotated.
### Desired behavior:
Rotate logfile when it's size exceeds logfile_rotation_max_size

**Comment by danielnelson** [comment] 2020-01-02 19:59
This is a duplicate of #6776.

**Closed by danielnelson** 2020-01-02 19:59 UTC
