### ISSUE TITLE
Telegraf unresponsive, cannot capture stack trace

### ISSUE THREAD

**Issue by soumya92** [influxdata/telegraf#5839] opened 2019-05-11 18:38 UTC
### Relevant telegraf.conf:
```toml
[global_tags]
  # some tags
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["**influx-url**"]
  username = "telegraf"
  password = "**password**"
# and nothing but [[input]] blocks.
```

### System info:

Telegraf 1.10.2 (git: HEAD 3303f5c3)
Linux host 4.19.32-1-ARCH #1 SMP PREEMPT Thu Apr 4 00:12:02 UTC 2019 armv7l GNU/Linux

### Steps to reproduce:

1. No concrete steps. Just wait a few days.

### Expected behavior:

Telegraf keeps publishing metrics continuously.

### Actual behavior:

Telegraf stops publishing metrics. Logs initially start with `input "..." did not complete within its interval`, but eventually even those stop. Does not respond to SIGTERM, and does not print a stack trace with SIGQUIT.

### Additional info:

Some logs for the unresponsive case and the normal case are here: https://gist.github.com/soumya92/8038a56f47f61b86aa2e1ab92972018d

**Comment by soumya92** [comment] 2019-05-11 18:56
A few things to note in the logs:

When telegraf is unresponsive, SIGQUIT exits with code 11 rather than code 2, and it also does not print stack traces.

The logs in the unresponsive case are not missing, there is just no output from telegraf for ~12 hours before I sent SIGQUIT and caused it to restart. It spends almost 45 minutes logging the "did not complete" message every 10s, before even that stops. No data from any input is received after the "did not complete" logs start, even from inputs not named in the log.

No other problems are apparent on the target machine. ssh, web servers, etc. continue to function as normal.

**Comment by danielnelson** [comment] 2019-05-15 00:01
Very odd, a Go program should always be responsive to this signal unless something very bad has happened.  Couple questions:

I notice that you have a `PREEMPT` kernel and this is an armv7 system,  is this the standard kernel for this system?

Since this is an arm system, is this using one of the official packages and which one?

Does it always complain about inputs.processes before it hangs or is it a random plugin?

**Comment by soumya92** [comment] 2019-05-15 00:26
> I notice that you have a PREEMPT kernel and this is an armv7 system, is this the standard kernel for this system?
Yes, this is the standard kernel. The hardware is a Raspberry Pi 3 Model B.

> Since this is an arm system, is this using one of the official packages and which one?
Yep, the generic arm linux tar gz (installed via the aur script https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=telegraf-bin)

> Does it always complain about inputs.processes before it hangs or is it a random plugin?
It's fairly random, sometimes it even loops through two or three. I will look at more logs to see if processes is always in there and update this comment.

**Comment by danielnelson** [comment] 2019-05-15 02:50
Has this been observed on multiple systems?

@mark-rushakoff Have you ever seen anything like this before?  Hung process exits with a segfault when sent SIGQUIT?
```
May 09 16:22:50 host telegraf[14135]: 2019-05-09T23:22:50Z W! [agent] input "inputs.processes" did not complete within its interval
-- This is where I called `kill -SIGQUIT (pgrep telegraf)`
May 10 23:16:15 host systemd[1]: telegraf.service: Main process exited, code=dumped, status=11/SEGV
May 10 23:16:15 host systemd[1]: telegraf.service: Failed with result 'core-dump'.
```

**Comment by soumya92** [comment] 2019-05-15 03:15
Depending on your definition of system :)

I have observed this on at least four hosts, but they're all very similar hardware (1 x RPi 2B, 2 x RPi 3B, 1 x RPi 3B+) and almost identical software (I usually update them all together).

There is also an RPi 3B that has never exhibited this problem, though, and all of them have been running similar workloads for similar durations.

**Comment by mark-rushakoff** [comment] 2019-05-15 15:43
This doesn't ring a bell to me. I don't see any open Go issues that look relevant, after trying a couple different searches.

SIGQUIT is handled in the Go runtime. The lack of output and lack of responsiveness to SIGQUIT sounds like perhaps you've uncovered a bug in the runtime?

First, I would recommend trying to run with the race detector, which is supported on linux/arm64 as of go 1.12. I assume you'll have to build telegraf yourself in that case.

If you [file a Go issue](https://github.com/golang/go/issues/new), fill out the issue template as usual, include information about the process seemingly hanging, and exiting with code 11. They'll probably ask if you've run with the race detector and if you're using CGo anywhere. I'm not up to speed with telegraf today -- if you can rule out any plugins that might use CGo, that should help isolate the problem. From what I can see, they aren't generally interested in core dumps, so it's possible they may want you to run a custom build or run with some other GODEBUG environment variables to get more info.

If there's anything you can do to make it reproduce the hang quicker, that would probably go a long way too. Maybe more frequent output flushes or collections?

**Comment by soumya92** [comment] 2019-05-15 16:24
Thanks for looking into this!

It seems that race detection on linux/armv7 is not supported (and it's a lot of effort to change the kernel arch for these machines to aarch64). Not to mention compiling telegraf on a Raspberry Pi is something I'd rather avoid :)

Given the circumstances surrounding this issue, I feel it's probably more expedient to just integrate with the systemd watchdog and let it restart the service automatically whenever it's in this state (my original feature request #5825) and close this as infeasible, but I'll let you decide what to do here.

In the meanwhile, I'll paper over this by having kapacitor fire an alert that restarts telegraf when received, which should mostly solve my issue (albeit with some gaps of ~10 minutes since I don't want the alert to fire spuriously).

**Comment by danielnelson** [comment] 2019-05-15 21:15
CGO shouldn't be enabled, since we cross compiled from an amd64 system.  However, if we want to enable the race detector for an arm64 build, which is supported with Go 1.12 and I think this system might be able to run, then we do need CGO_ENABLED.
```
$ GOARCH=arm64 go build -race -ldflags " -X main.commit=3548ce47 -X main.branch=release-1.10 -X main.version=1.10.4" ./cmd/telegraf
go build: -race requires cgo; enable cgo by setting CGO_ENABLED=1
```

Unfortunately, I still don't have my qemu working with arm, so this would be a problem for me to build as well and this will have to go on the back burner.

Let's close this issue until we can collect more information.

**Closed by danielnelson** 2019-05-15 21:15 UTC
