### ISSUE TITLE
httpjson throwing parse errors on valid json

### ISSUE THREAD

**Issue by kplimack** [influxdata/telegraf#3599] opened 2017-12-17 18:31 UTC
valid json is being returned to the plugin, but it throws weird parser errors.  i've tried adding the debug flag, but it is not helpful and does not provide any additional output.  i have no idea what is going wrong.  in addition to fixing the bug, the error message needs to be improved.

## log
```bash
2017-12-17T18:27:30Z E! Error in plugin [inputs.httpjson]: unable to parse out as JSON, invalid character '<' looking for beginning of value
```

## config
```
[[inputs.httpjson]]
  name = "coinmarketcap_bitcoin"
  servers = [
   "https://api.coinmarketcap.com/v1/ticker/bitcoin/?convert=BTC"
  ]
  response_timeout = "5s"
  method = "GET"
```

## test
```bash
curl "https://api.coinmarketcap.com/v1/ticker/bitcoin/"   | jq .
[
    {
        "id": "bitcoin",
        "name": "Bitcoin",
        "symbol": "BTC",
        "rank": "1",
        "price_usd": "19300.1",
        "price_btc": "1.0",
        "24h_volume_usd": "13749100000.0",
        "market_cap_usd": "323230586361",
        "available_supply": "16747612.0",
        "total_supply": "16747612.0",
        "max_supply": "21000000.0",
        "percent_change_1h": "-0.28",
        "percent_change_24h": "1.83",
        "percent_change_7d": "26.08",
        "last_updated": "1513535054"
    }
]
```

**Comment by danielnelson** [comment] 2018-01-03 19:57
I am unable to reproduce this error message, is it still happening for you?

Unfortunately, the JSON input format as-is cannot handle this message because all fields are strings, there must be at least one numeric value to use as a field.  I am hoping we can improve the flexibility of the JSON parser, you may want to watch https://github.com/influxdata/telegraf/issues/1363.

**Comment by danielnelson** [comment] 2018-01-13 00:45
Closing, let me know if you see this error again.

**Closed by danielnelson** 2018-01-13 00:45 UTC
Labels: need more info
