### ISSUE TITLE
Unable to get metrics for SQL Server

### ISSUE THREAD

**Issue by ronansalmon** [influxdata/telegraf#5429] opened 2019-02-14 08:44 UTC
### Relevant telegraf.conf:
```
[[inputs.sqlserver]]
  interval = "30s"
  servers = [
	"Server=host\\SQL2008;User Id=sa;Password=xxxx;app name=telegraf;log=1;",
	"Server=host\\SQL2005;User Id=sa;Password=xxxx;app name=telegraf;log=1;",
  ]
```

We don't normally use the 'sa' account, this is just for debugging !

### System info:
Telegraf v1.9.4
SQL Server 2005 and 2008
Windows Server 2008 R2 64 bits

### Steps to reproduce:
```
sqlcmd -S host\SQL2008 -U sa -P "xxxx" -Q "select 1"
=> Ok
sqlcmd -S host\SQL2005 -U sa -P "xxxx" -Q "select 1"
=> Ok
sqlcmd -S "host\SQL2008,1433" -U sa -P "xxxx" -Q "select 1"
=> Ok
.\telegraf.exe --config .\telegraf.conf --config-directory .\telegraf.d --test
```

### Expected behavior:
telegraf should be able to talk to SQL Server

### Actual behavior:
```
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2008' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2008' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2008' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2005' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2005' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2005' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2005' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2008' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2008' returned from host 'host'
2019-02-14T08:29:34Z E! [inputs.sqlserver]: Error in plugin: No instance matching 'SQL2005' returned from host 'host'
```

### Additional info:
```
powershell
PS >  function Get-SQLInstancesPort {
    param ([string]$Server)
    [system.reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Smo")|Out-Null
    [system.reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlWmiManagement")|Out-Null
    $mc = new-object Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer $Server
    $Instances = $mc.ServerInstances
    foreach ($Instance in $Instances) {
        $port = @{Name = "Port"; Expression = {$_.ServerProtocols['Tcp'].IPAddresses['IPAll'].IPAddressProperties['TcpPort'].Value}}
        $Parent = @{Name = "Parent"; Expression = {$_.Parent.Name}}
        $Instance|Select $Parent, Name, $Port
    }
}

PS > Get-SqlInstancesPort host
Parent                                                      Name                                                        Port
------                                                      ----                                                        ----
host                                                    SQL2005
host                                                    SQL2008
```

**Comment by danielnelson** [comment] 2019-02-14 23:22
I'm not sure, the only related issue I could find this was caused by the host having the wrong case, it would seem both the host and instance are case senstive.  Any chance this is what is happening?

https://github.com/denisenkom/go-mssqldb/issues/15

**Comment by ronansalmon** [comment] 2019-02-18 07:51
I tried both, lower and upper case.

Not related I think. I used whatever is returned from function Get-SqlInstancesPort. I assume that Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer returns values case sensitive.
Having said that, Get-SqlInstancesPort return hostname+instance, but port is empty. Could this be the issue ?

Anyway of getting more debugging out of telegraf ?

**Comment by danielnelson** [comment] 2019-02-20 00:29
I don't see a way to get at the instances more closely, it is within in the go-mssqldb library.  If you setup Go so that you can compile Telegraf I could show you where to add more logging.

**Comment by ronansalmon** [comment] 2019-02-21 07:46
Ok, I can do that.
If you already have some stuff to add more logging, I'm all hears!

**Comment by danielnelson** [comment] 2019-02-21 19:25
Once you have Telegraf compiling try this change to `vendor/github.com/denisenkom/go-mssqldb`:
```diff
diff --git a/tds.go b/tds.go
index a45711d..f9c2b31 100644
--- a/tds.go
+++ b/tds.go
@@ -1189,6 +1189,11 @@ func connect(ctx context.Context, log optionalLogger, p connectParams) (res *tds
                        f := "Unable to get instances from Sql Server Browser on host %v: %v"
                        return nil, fmt.Errorf(f, p.host, err.Error())
                }
+               for name, info := range instances {
+                       for proto := range info {
+                               fmt.Printf("Found instance on host %s: %s %s\n", p.host, name, proto)
+                       }
+               }
                strport, ok := instances[p.instance]["tcp"]
                if !ok {
                        f := "No instance matching '%v' returned from host '%v'"
```

After you make this change, build with `make telegraf` because just running `make` will undo any changes to the vendor directory.

**Comment by ronansalmon** [comment] 2019-02-22 07:48
The following appears several times : 
```
Found instance on host hostname_lowercase: SQL2005 ServerName
Found instance on host hostname_lowercase: SQL2005 InstanceName
Found instance on host hostname_lowercase: SQL2005 IsClustered
Found instance on host hostname_lowercase: SQL2005 Version
Found instance on host hostname_lowercase: SQL2008 ServerName
Found instance on host hostname_lowercase: SQL2008 InstanceName
Found instance on host hostname_lowercase: SQL2008 IsClustered
Found instance on host hostname_lowercase: SQL2008 Version
```

**Comment by ronansalmon** [comment] 2019-02-22 09:44
I was able to get metrics with the following dirty patch. I assume that all instance are available on port 1433/tcp. 

```
if p.instance != "" {
  p.instance = strings.ToUpper(p.instance)
  instances, err := getInstances(dialCtx, p.host)
  if err != nil {
    f := "Unable to get instances from Sql Server Browser on host %v: %v"
    return nil, fmt.Errorf(f, p.host, err.Error())
  }
  for name, info := range instances {
    for proto := range info {
      fmt.Printf("Found instance on host %s: %s %s\n", p.host, name, proto)
    }
  }

  _, ok := instances[p.instance]["ServerName"]
  if !ok {
    f := "No instance matching '%v' returned from host '%v'"
    return nil, fmt.Errorf(f, p.instance, p.host)
  }
  p.port = 1433
}
```
Even if  SQL Server is not listing tcp ports, since we did specify host/port/instance..., it should not try to detect anything.

**Comment by Trovalo** [comment] 2020-01-07 15:08
Port 1433 is the static port used by the SQL Server default instance, it can be changed using SQL Server Configuration Manager.
You are using two named instances "2005" and "2008", which by default use a dynamic port (if you are getting the correct data then those two instances have been configured to use static port 1433).
To reach a named instance without specifying the port "SQL Server browser" (Service) must be in execution on the machine. (by default it's disabled).

In the telegraf conf the port can be specified (if you specify the port you should not need to specify the instance name).
```
[[inputs.sqlserver]]
  interval = "30s"
  servers = [
	"Server=host;port=<portnum>;User Id=sa;Password=xxxx;app name=telegraf;log=1;",
	"Server=host;port=<portnum>;User Id=sa;Password=xxxx;app name=telegraf;log=1;",
  ]
```

you can also check [this article](https://www.mssqltips.com/sqlservertip/2013/find-sql-server-instances-across-your-network-using-windows-powershell/) to discover all the SQL Instances visible on the network (if SQL Server Browser is enabled on the server).

Summarizing, I suggest you check on which port the instances are running by using the ["SQL Server Configuration Manager"](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-configuration-manager?view=sql-server-ver15), also check if SQL Server Browser is in execution on your Hosts.

Let me know if this helps.

**Comment by evolart** [comment] 2021-01-25 20:05
> Port 1433 is the static port used by the SQL Server default instance, it can be changed using SQL Server Configuration Manager.
> You are using two named instances "2005" and "2008", which by default use a dynamic port (if you are getting the correct data then those two instances have been configured to use static port 1433).
> To reach a named instance without specifying the port "SQL Server browser" (Service) must be in execution on the machine. (by default it's disabled).
> 
> In the telegraf conf the port can be specified (if you specify the port you should not need to specify the instance name).
> 
> ```
> [[inputs.sqlserver]]
>   interval = "30s"
>   servers = [
> 	"Server=host;port=<portnum>;User Id=sa;Password=xxxx;app name=telegraf;log=1;",
> 	"Server=host;port=<portnum>;User Id=sa;Password=xxxx;app name=telegraf;log=1;",
>   ]
> ```
> 
> you can also check [this article](https://www.mssqltips.com/sqlservertip/2013/find-sql-server-instances-across-your-network-using-windows-powershell/) to discover all the SQL Instances visible on the network (if SQL Server Browser is enabled on the server).
> 
> Summarizing, I suggest you check on which port the instances are running by using the ["SQL Server Configuration Manager"](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-configuration-manager?view=sql-server-ver15), also check if SQL Server Browser is in execution on your Hosts.
> 
> Let me know if this helps.

@Trovalo,

Are you saying it is possible for the Telegraf SQL Server plugin to be configured to work with Dynamic SQL ports? We have our environment setup to use dynamic ports and I cannot seem to get a working configuration without setting a static port in SQL Server Configuration Manager and then configuring Telegraf to use that port when connecting to the SQL instances. We do have SQL Server Browser enabled and switching permanently to static ports for SQL in our production environment is apparently out of the question according to our SQL admin.

**Comment by Trovalo** [comment] 2021-01-29 20:54
I don't know what's the root cause of your issue, you can have a look at [MS Docs](https://docs.microsoft.com/en-us/troubleshoot/sql/connect/resolving-connectivity-errors) but I guess you already did that.
Have you tried to connect to SQL Server with different client tools (like [sqlcmd](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)) from the same Telegraf location? 
I personally doubt the problem is strictly related to telegraf.

on oldest editions like 2005 and 2008 (pre sp3) you also need to provide an additional connection parameter in the connection string `{...};encrypt=disable` but (if I remember correctly) this kind of problem usually returns a different error

**Comment by evolart** [comment] 2021-01-29 21:36
> I don't know what's the root cause of your issue, you can have a look at [MS Docs](https://docs.microsoft.com/en-us/troubleshoot/sql/connect/resolving-connectivity-errors) but I guess you already did that.
> Have you tried to connect to SQL Server with different client tools (like [sqlcmd](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)) from the same Telegraf location?
> I personally doubt the problem is strictly related to telegraf.
> 
> on oldest editions like 2005 and 2008 (pre sp3) you also need to provide an additional connection parameter in the connection string `{...};encrypt=disable` but (if I remember correctly) this kind of problem usually returns a different error

It works if reconfigure SQL to have a static port vs using Dynamic ports. If I leave SQL with a dynamic port like all of our production SQL instances are set it will not connect. If I do not specify a port it seems telegraf defaults to port 1433? Is there a switch or method of configuration I am not seeing that allows it to work with dynamic ports where you only specify the hostname/IP?

**Comment by Trovalo** [comment] 2021-01-29 22:44
The point of dinamic ports is that it gets discover automatically through the SQL Server agent. if this does not happen then there is something wrong but I doubt that's strictly related to telegraf and I can't provide further help with it.

Have a look at the links I've provided in the previous answer to troubleshoot the issue, if the same problem happens even with different tools (sqlcmd,SSMS,powershell) then it's not something related to Telegraf.
If in the end everything works except telegraf then open an issue here https://github.com/denisenkom/go-mssqldb , that's the lrepo of the library used by the Telegraf plugin.

**Comment by evolart** [comment] 2021-01-30 00:22
@Trovalo 

Apologies, it sounds like we have a disconnect here. We have numerous production databases along with staging databases that I am currently trying to get telegraf functional on. We have zero problems using Dynamic ports with SQL Server Browser running on our SQL instances. We are able to use all of our internal applications and SSMS without issue. However, when I look at the configuration of telegraf it seems to require a port number for monitoring SQL servers. If I do not set a port number I can see telegraf tries to connect but on the default SQL port 1433 instead of negotiating a proper dynamically assigned port via SQL Server Browser. Is there some kind of specific configuration I need to do when setting up SQL monitoring in telegraf to allow for it to connect to dynamically assigned ports on a SQL server?

**Comment by srebhan** [comment] 2023-08-02 09:22
@evolart does that problem still exist with the latest Telegraf version? @Trovalo any further ideas on what to do?

**Closed** 2023-08-16 18:09 UTC
Labels: bug, platform/windows, area/sqlserver, waiting for response
