### ISSUE TITLE
Support for golang 1.22

### ISSUE THREAD

**Issue by matejsp** [influxdata/telegraf#15987] opened 2024-10-07 08:01 UTC
### Use Case

Based on golang support, Golang 1.22 and 1.23 are supported. We have lots of microservices with its own upgrade cycle.
Telegraf as a library requires latest Golang instead of supporting currently officially supported golang versions.

### Expected behavior

Support for golang 1.22.

### Actual behavior

It forces you to upgrade to 1.23.

**Comment by srebhan** [comment] 2024-10-07 15:12
@matejsp I'm not exactly sure where the issue is. The official Telegraf binaries are built with the latest go-version usually, you don't need to install any go version on your machine. If you are talking about building Telegraf on your own with older versions of Go, you can modify the `go.mod` file and give it a try.

**Note**: You will be on your own, as we cannot support two versions of Go simultaneously because all testing etc is done using the newer version.

**Comment by srebhan** [comment] 2024-10-08 11:30
@matejsp can we close this issue?

**Comment by matejsp** [comment] 2024-10-08 12:16
The issue can be closed.

I cannot find UDP client in golang client libraries. Perhaps something that could be extended.
But the line protocol is supported inside. Perhaps we can have our own UDP client and combine.

**Closed** 2024-10-08 12:17 UTC
Labels: feature request

**Comment by srebhan** [comment] 2024-10-08 12:19
Sorry my bad, the client-libs indeed do not offer UDP...
