### ISSUE TITLE
Support for OPC-UA input and output plug-ins

### ISSUE THREAD

**Issue by edbernier** [influxdata/telegraf#3041] opened 2017-07-21 21:02 UTC
## Feature Request

The OPC-UA protocol is heavily used in the energy and utilities industries and was originally developed for SCADA systems.  As companies try to update their metrics collection platforms to next generation time series databases like InfluxDB they'd like to tap into this established infrastructure based on OPC-UA.

There is an OPC-UA logger that was developed to insert data into InfluxDB but nothing for writing back out to OPC-UA:
https://github.com/coussej/node-opcua-logger

There are a number of open source projects that one might be able to tap into while developing such a plug in which are listed here:
https://github.com/open62541/open62541/wiki/List-of-Open-Source-OPC-UA-Implementations

Companies interested in these plug ins:
  * Schlumberger
  * NOV
  * Emerson

**Comment by dprice809** [comment] 2018-01-10 03:14
OPC-UA is the new standard, correct? There is also the older standard which was simply known as OPC. 

A very common issue is that each OPC server is implemented a little different from each other.

**Comment by woodsb02** [comment] 2018-01-10 05:14
Yes, OPC-UA is the "new" standard (formally IEC 62541 published between 2010 and 2012), and replaces the classical OPC which utilised Windows DCOM. OPC-UA allows non-Windows devices to communicate, which was not the case with the classical OPC.

Good descriptions here:
https://en.wikipedia.org/wiki/OPC_Unified_Architecture
https://opcfoundation.org/about/opc-technologies/opc-ua/

Free OPC test/simulations tools are available from Matrikon, including clients and servers:
http://www.matrikonopc.com/products/opc-desktop-tools/index.aspx

**Comment by dprice809** [comment] 2018-01-13 19:27
I would like to start an initiative for this. I will be starting with the node library as a base and attempting to translate it into Go. If anyone would like to help I will be storing my code here, 

https://github.com/dprice809/opcua_listener

**Comment by woodsb02** [comment] 2018-01-14 00:09
Thanks for your efforts.

Can I ask what you mean by the term “listener”? This sounds like telegraf would perform the role of server, and wait for a client to push data to telegraf.

Generally industrial control systems would provide an OPC Server, so extracting data from them would be done by an OPC client sending queries for data for certain “tags”. A data historian collector like telegraf would normally perform the client role of regularly sending these queries to the server.

**Comment by dprice809** [comment] 2018-01-14 00:30
This is something that does need to be worked out. I am naming this a "listener" in order to follow the telegraf terminology. I am expecting the package to contain a OPC client, but from my understanding all telegraf interfaces are named "listeners". So this could just be some confusion caused by the mix of terminology.

In our case this will be an input listener. The listener needs to follow the telegraf standards for inputing data, but the data will be extracted in a way that follows OPC client standards. 

I'd just like to say that I do have some familiarity with OPC. Hopefully we can work together to work out these details.

**Comment by thecoldwine** [comment] 2018-01-26 08:59
To be honest, E&P companies are still using OPC DA/HDA protocol primarily, not the UA version, therefore it would be better to develop "legacy" windows only clients for telegraph to feed the database with data. I could start to develop this client but not sure if it would be useful for Linux oriented customers since it cannot be implemented without old DCOM+ bindings.

**Comment by RavilN** [comment] 2018-03-09 06:37
While majority might be still using classic OPC, the new OPC UA standard is gaining traction more and more. Taking into account that development of the plugin will take some time, over that period the ratio will change more towards OPC UA. For that reason perhaps plugin should be for OPC UA. Classic OPC data sources can be accessed using existing in the market protocol converters, like OPC UA Proxy from Matrikon.

**Comment by RavilN** [comment] 2018-03-09 06:43
Another alternative perhaps could be to build generic OPC UA adapter for SQL database, particularly PostgreSQL, for which there is already plugin. 
There are some optimized to store time series data versions of databases do exist, like TimescaleDb, which is accessible as regular PostgreSQL database.

**Comment by woodsb02** [comment] 2018-03-09 11:07
Another aspect is that OPC classic is based on Microsoft’s DCOM, so I believe telegraf could only realistically support it on Windows.

OPC UA on the other hand does not rely on DCOM and works on any operating system.

Yet another reason to focus on OPC UA.

**Comment by woodsb02** [comment] 2018-03-09 11:11
I believe that supporting OPC UA natively (not via a database middleman) should be a major priority for telegraf. This would effectively extend telegraf and influxdb from a purely IT monitoring historian, to a viable control system historian (OT).

Control system historians is a BIG industry, and the competitors are largely older technology. There could be big demand for this.

**Comment by BrentHumphreys** [comment] 2018-03-09 11:47
I would agree with the OPC-UA objective.  There are lots of cases where having a low friction way to get industrial/manufacturing data into a time series database, would be valuable.  One of the challenges would be coming up with a good way to map the data to the influx schema.

**Comment by RavilN** [comment] 2018-03-09 15:05
Yes, it can be kind of enterprise historian. 
I say "kind of", because cannot see how OPC UA model information can be utilized in full on the Influx architecture.
For example, OPC UA variables have not only value and timestamp, they have engineering units, range, description, display name (which BTW can be localized) - those characteristics are required on the visualization side. There is also deadband support to eliminate noise before collecting data into historian.
In the Influx architecture I see that the Chronograf module gets all data from InfluxDB, so if the DB does not have all that OPC UA model metadata mapped into it, then all that valuable info is lost and the system as a whole requires duplication of configuration: for example, instead of using engineering units available via OPC UA server, the user will have to type/select it on the Chronograf dashboard configuration.
One more aspect is that OPC UA Servers can generate alarms and events. they need to be historized too, and displayed on the dashboard too, and operator needs a way to react to them. I don't see how OPC UA alarms and events can be utilized in InfluxDB architecture.

Concluding, the questions are: can OPC UA model and alarms/event be utilized in Influx ecosystem?

If Chronograf could access them over generic API via some OPC UA plugin which connects directly to OPC UA servers to get model and events, and historian data via InfluxDB, perhaps that would be doable.
Or map them into InfluxDB, not sure if that is doable, I just started looking at InfluxDB and don't know its internals.

**Comment by BrentHumphreys** [comment] 2018-03-09 15:15
The approach I have used is to use the tag set and field set to define these additional attributes.  Keep in mind that most of the process historians (Pi, WW Historian) that I have dealt with don't consume all of this data from OPC-UA Either.  That is why I made my comment about developing a good strategy in the telegraf connection on how the OPC-UA data would be mapped into influx's tagset and fieldset schema.

**Comment by RavilN** [comment] 2018-03-09 16:32
I guess those historians are legacy and do not use all information provided by OPC UA Servers in full.
Ideally, it would be nice for example to have feature to browse OPC UA Server address space and select OPC UA variable from there right on dashboard configuration GUI, and that selection would populate settings in the dashboard like display range, or units, automatically. 
I wonder, can address space somehow mapped into InfluxDB together with all OPC UA node attributes/properties?

**Comment by dprice809** [comment] 2018-03-09 17:04
We should keep this effort limited to identifying if data can be properly storred in InfluxDB. While many other products provide things like displays and alarming those pieces are typically provided as additional products and not features of the historian itself (ex. PI Notifications and Processbook.)

As for the additional fields and data. Could we get away with serializing this data in something like a JSON format? And I’m sure there is a clever solution for deadband and compression

**Comment by BrentHumphreys** [comment] 2018-03-09 17:26
I wasn't aware that there was a UI for telegraf.
serializing the contextual data could be done, but it would not be optimal if you needed to use that data for retrieval.

**Comment by dprice809** [comment] 2018-03-09 17:57
I was thinking a lot of the metadata like engineering units, description, devMin, devMax are defined at the “tag” level. So it does not need to be attached to each time series event. This would also reduce indexing overheard.

**Comment by woodsb02** [comment] 2018-03-10 01:55
Yes, but it is also possible for the tag configuration to change over time.
E.g. a tag recording a pressure could use units "psi(g)" for the first 1 month, and then its configuration could later change to use units "kPa(g)". There needs to be a method in influxdb to record which units stored values use.

**Comment by woodsb02** [comment] 2018-03-10 01:56
The alarms and events portion of OPC UA is a separate component. This functionality does not need to be implemented in the first instance - it could be added later (or not at all).
I agree that it is a useful component, but it is not mandatory.

**Comment by RavilN** [comment] 2018-03-24 20:33
In the TICK stack architecture (https://www.influxdata.com/time-series-platform/) Telegraf and Chronograf both interact with InfluxDB (the first collects data from various sources and writes it to the DB, and second reads data and visualizes it). For me it is hard to imagine how OPC UA model information can be propagated  and used by visualization component. I don't see that Chronograf allows using of some custom data source, which can provide both data and model.

If you look at Grafana, it provides API to add custom data sources. I guess you could add data source for OPC UA, which can provide all you need for visualization - real time data, historical data, alarms and event, and most importantly, information model. Note that the model could be used to create and configure dashboards, users do not need to enter settings like localized display name, description, display ranges, units, etc.
That data source can get data either from ordinary OPC UA Servers directly, or it might be some historian with OPC UA Server interface, using in the backend some TSDB like InfluxDB or anything else.

I could lead such a project if there are interested parties.

**Comment by gisfinder** [comment] 2018-07-24 02:01
For OPC protocol, we are now using. The real-time data are sent to SCADA and to historian system. We use logger from OPC to sqlserver. Using open architecture solution it makes sense to integrate all required data to the monitor system. 
So in traditional control system , data adapter from OPC to influxDB or prometheus system is useful.

**Comment by russorat** [comment] 2018-07-24 19:22
@woodsb02 @RavilN @gisfinder @dprice809 @BrentHumphreys thank you all for the great discussion here. I'm the product manager for both Telegraf and Chronograf and I agree with many of the points here.

To summarize what I'm hearing:
 - A Telegraf plugin in the new OPC UA format would be valuable
 - Telegraf can be run on Windows machines so legacy OPC protocol support might be possible, but it is probably better to focus on UA now, with legacy support added later
 - The data model of InfluxDB, with tags and fields, can support storing the field value and all the metadata such as unit, range, etc
 - Chronograf is not a viable alternative to existing solutions unless it could leverage this metadata in it's UI in some way to facilitate creating dashboards or exploring data
 - The https://github.com/coussej/node-opcua-logger project has been running for a number of years successfully writing OPC-UA data into InfluxDB.

We have created custom experiences in Chronograf based on specific plugins in Telegraf. See the syslog plugin as an example (the log viewer in Chronograf 1.6).

I have limited knowledge of OPC UA, but on the surface it sounds like the https://github.com/coussej/node-opcua-logger might be a good model to mimic.

Once the data is being written to InfluxDB, we can work on building custom experiences in Chronograf for something like this.

**Comment by Metalfusion** [comment] 2018-09-25 11:14
Another use case for OPC UA is to provide a standardized API for historical (time series) data access. The standard defines historical data queries including aggregation. The DB would need to implement OPC UA server that exposes stored data using the OPC UA data model and supports historical data queries. OPC UA even has "methods" for RPC that can be used to expose custom API within the same secure communication model.
Primary way to get live data from OPC UA servers is to use a subscription that notifies on value changes, so polling is not needed.

**Comment by RavilN** [comment] 2018-11-03 03:38
I have built prototype application which can log data from OPC UA servers to PostgreSQL. Introduction video with context diagram is available here: [https://youtu.be/Gb56k0j-0Tc]
As a next step target database can be configurable - for example InfluxDB can be added as time-series database. 
The same application can be used also to browse OPC UA Servers' address space, from the front-end side (which is single page web application). Front-end communicates with the back-end over REST API. It is possible to extend REST API to provide also historical data and as well as real time data, so data source plugin written in JavaScript and running on browser can access time-series data via REST API from the back-end, which in turn gets some data from TSDB (history) and OPC UA Servers (real time).
If I had free time I could work on it further, but right now busy on other, paid projects.

**Comment by fernwerker** [comment] 2018-11-26 16:42
I was just recommended this opcua implementation in Go. Might be easier or helpful for an input. https://github.com/wmnsk/gopcua

**Comment by russorat** [comment] 2018-11-28 01:06
has anyone in this thread taken a look at https://github.com/influxdata/telegraf/pull/4623 ? What do you think?

**Comment by woodsb02** [comment] 2018-11-28 10:21
It is a great idea to support both Modbus TCP and OPC UA - this will ensure Telegraf supports data collection from a large percentage of the devices in the industrial control system / operational technology landscape.

**Comment by glinton** [comment] 2018-11-28 17:45
Is there an emulator or something that we could test against. It seems a major blocker on this is the need for specialized hardware. Would something like https://www.matrikonopc.com/downloads/1361/index.aspx (Matrikon FLEX OPC UA SDK) be an effective simulation server to get started here?

**Comment by RavilN** [comment] 2018-11-28 18:23
In my opinion, support for OPC UA is higher priority than Modbus. Because it is possible to access Modbus via OPC UA Server for Modbus. There are commercial products available in the market, for example https://www.prosysopc.com/products/opc-ua-modbus-server/
For quick tests its free trial version should be sufficient.
If you need Modbus device, there are Modbus simulators, you can find if Google in the Internet, there should be free versions.
For usage in real production environment, there is also gateway product which allows to access Modbus data over OPC UA: https://www.prosoft-technology.com/Products/Gateways/PLX3x/PLX32/EtherNet-IP-to-Modbus-TCP-IP-to-OPC-UA-Server-Gateway

Long story short, if there is support for OPC UA, then you can access practically any widely used device/protocol. If there is no direct OPC UA access, then most likely there is classic OPC DA server for it, which you can connect to via OPC UA Wrapper (which converts classic OPC into OPC UA).

If you need OPC UA Server bundled with hardware device, then one of options is Raspberry Pi, for which there are free opensource OPC UA Servers available (you might need to build from source code though).

Also, there are many OPC UA servers running 24/7/365 and available over the Internet. For example, there is one hosted by my company at URL opc.tcp://opcuaserver.com:48010
If you need a client, you can also try online OPC UA client at https://uaclient.com/ (another test product from my company).

**Comment by blackw1ng** [comment] 2019-03-14 19:06
Any news on these OPC-UA plugins?
In the industry space, this open collection of sensor data from legacy process control systems (e.g. Emerson DeltaV, Siemens PCS,...) 
This would eliminate painful solutions on Windows machines...

**Comment by alexmc1510** [comment] 2019-03-29 00:50
It is expected to be developed OPC UA as collector? In the industry we speak OPC language in timeseries data coming from machines.

Thanks!!

**Comment by RavilN** [comment] 2019-03-29 01:01
Is it possible to feed data from PostgreSQL?
If so, probably you could use data logger from my company to log data from OPC UA Servers to PostgreSQL first, and then read from PostgreSQL to telegraf (currently prototype is available at https://github.com/onewayautomation/OPC-UA-Data-Logger)

**Comment by Tonny72** [comment] 2019-04-04 17:46
@glinton You can use KepserverEX as OPCUA simulation server from Kepware.

**Comment by murmlgrmpf** [comment] 2019-05-03 13:20
There is a [new extension](https://opcfoundation.org/news/press-releases/opc-foundation-announces-opc-ua-pubsub-release-important-extension-opc-ua-communication-platform/) of opcua publishedm, called opc-ua pubsub. It is implementing a publisher subscriber logic and seems to be a quite universal solution.

**Comment by HogeBlekker** [comment] 2019-06-14 10:52
In this issues' opening post:

> nothing for writing back out to OPC-UA

We developed https://github.com/factrylabs/influx-opcua-server to do just that.

**Comment by tecmatia-dp** [comment] 2019-06-28 16:21
I invite you to try Notify, a software application specifically designed to collect data from SCADA systems (including OPC UA) and in addition to notifying alarms, allows registration in InfluxDB.
http://tecmatia.com/index.php/en/products/notify

**Comment by MaartenKleijwegt** [comment] 2019-07-17 20:10
Any news on this? Our company has got plenty of machines out in the field with OPC-UA and we're looking into building a test dashboard. [This](https://github.com/coussej/node-opcua-logger is what I'm currently using, but if telegraf could handle it that would be much better IMHO

**Comment by RavilN** [comment] 2019-08-06 21:08
Hi Maarten,
Would be storing of OPC UA data into InfluxDB sufficient for you to start?
If so, probably I could add support for InfluxDB target into _ogamma_ Visual Logger for OPC (https://cloud.docker.com/u/ogamma/repository/docker/ogamma/logger - this is development version, beta version will be released soon).
Time-frame can be 3-4 weeks.
If you are interested, please let me know, we can discuss mapping details.
Regards, Ravil

**Comment by yonas124** [comment] 2019-08-31 04:53
Any update on influxdb to opcua server? 
My setup is that I have an opc-ua scada and I'd like to browse my influxdb db/measurement as opc items. The db is populated by mqtt subscriber.

**Comment by monokot** [comment] 2019-08-31 10:12
If someone is interested then we offer a cross-platform OPC UA server with the ability to store data in InfluxDB (preview) ([https://monokot.io/download](https://monokot.io/download))

**Comment by monokot** [comment] 2019-10-05 10:56
If someone is interested then we offer a cross-platform OPC UA server with the ability to present InfluxDB fields as OPC UA items and store data in InfluxDB (https://monokot.io)

**Comment by RavilN** [comment] 2019-11-03 21:58
Hello,

Visual Logger with support of InfluxDB has been released! Both version 1.7 and 2.0 are supported. 
How to deploy community edition is described here: https://onewayautomation.com/visual-logger-docs/html/deploy.html

There is Docker image available, as well as installation packages for Windows, Ubuntu and Debian.

Major difference from other OPC UA to InfluxDB data moving solutions: high throughput and performance, and web based configuration GUI. In test setup throughput rate was around 100,000 values/second.

Best Regards, Ravil

**Comment by alexmc1510** [comment] 2019-11-28 09:17
I am very interested on it. Thanks to _ogamma_ and @RavilN we are able to store data in PostgreSQL and influxDB and I would like to give public thanks to RavilN for his effort. From my point of view, the last and best functionality would be to convert OPC UA to Kafka or include OPC UA as telegraf input.

**Comment by RavilN** [comment] 2019-11-28 17:41
Hi alexmc1510,
You are welcome, I am glad that it is useful.
Please feel free to create issue at GitHub page if you need new features or encounter bugs, or need different mapping from OPC UA to TSDB.
Also, would be interesting to know details of your project, if you could send me some info to ravil @ onewayautomation.com, would be really appreciated.
Adding support for Kafka is on our radar, can be accelerated if you create issue at GitHub.
Thank you, Ravil

**Comment by PWSys** [comment] 2020-02-15 16:50
Is there a reason this was removed from the 1.14.0 milestone?  Has it been pushed to a later release?

**Comment by danielnelson** [comment] 2020-02-18 19:11
We have pushed this back to a yet to be determined future release.

**Comment by PWSys** [comment] 2020-02-19 05:13
Thanks for the update.  Can you share if this is a reflection of a reduced priority from the Telegraf team or lack of understanding of the protocol or implementation?

**Comment by sjwang90** [comment] 2020-02-19 22:41
@PWSys With Telegraf 1.14 targeted for release next month, we removed the OPC-UA plugin as a priority as we are focusing on a few other IoT input/output plugins that are currently actively being worked on.  We understand the importance of OPC-UA and have designated some resources to begin developing an OPC-UA plugin for a future release.

**Comment by PWSys** [comment] 2020-02-21 05:57
Thanks for the update @sjwang90.  An OPC-UA plug-in is a requirement for my organization and customers to move over to a fully integrated TICK stack for Industrial Control System applications.

**Comment by alexmc1510** [comment] 2020-03-10 23:08
Hello, I have the same opinion as @PWSys , OPC UA is a requirement for my organization. By the moment I am using a workaround but it would be good to have it into TICK stack system.

**Comment by ThiruKumar** [comment] 2020-03-11 11:31
Hello, I have the same opinion as @PWSys , @alexmc1510  OPC UA is a requirement for my organization too. By the moment I am using a workaround but it would be good to have it into TICK stack system.

**Comment by xkilian** [comment] 2020-06-03 13:07
Grafana has an OPC-UA datasource plugin, it is currently being updated to work with Grafana 7. It is not currently published to the Grafana plugin directory, so it is hard to find. See [https://github.com/srclosson/grafana-opcua-datasource](https://github.com/srclosson/grafana-opcua-datasource)

**Comment by RavilN** [comment] 2020-06-04 23:49
Hi,
Update on the ogamma Visual Logger for OPC: version 1.0.1 is available now, which stores OPC data in InfluxDB 1.7 and 2.0, PostgreSQL, TimescaleDB, Apache Kafka, and in a few days MS SQL and MySQL will be supported too. Once stored, this data can be accessed from Grafana directly, or via Visual Logger (using SimpleJson plugin). You can also access data from Grafana without storing it in the database. 
Also, with additional OPC UA Wrapper, data from classic OPC DA servers can be stored too. 
And with additional OPC UA Server for Modbus, you can collect data from any legacy device supporting Modbus.
Community Edition (up to 64 tags) is free to use.
https://onewayautomation.com/visual-logger
Online User Manual will guide you through all steps on how to deploy, configure, etc. 
The configuration is over web GUI, runs in Docker, Windows, Linux.
Thank you, Ravil

**Comment by danielnelson** [comment] 2020-06-05 18:28
Please don't advertise other solutions on this issue tracker, it's off topic.  Let's keep any discussion focused on Telegraf support for OPC-UA.

**Comment by RavilN** [comment] 2020-06-05 18:48
Sorry, I have deleted it now.

**Comment by mrhb** [comment] 2020-06-14 05:58
> @woodsb02 @RavilN @gisfinder @dprice809 @BrentHumphreys thank you all for the great discussion here. I'm the product manager for both Telegraf and Chronograf and I agree with many of the points here.
> 
> To summarize what I'm hearing:
> 
> * A Telegraf plugin in the new OPC UA format would be valuable
> * Telegraf can be run on Windows machines so legacy OPC protocol support might be possible, but it is probably better to focus on UA now, with legacy support added later
> * The data model of InfluxDB, with tags and fields, can support storing the field value and all the metadata such as unit, range, etc
> * Chronograf is not a viable alternative to existing solutions unless it could leverage this metadata in it's UI in some way to facilitate creating dashboards or exploring data
> * The https://github.com/coussej/node-opcua-logger project has been running for a number of years successfully writing OPC-UA data into InfluxDB.
> 
> We have created custom experiences in Chronograf based on specific plugins in Telegraf. See the syslog plugin as an example (the log viewer in Chronograf 1.6).
> 
> I have limited knowledge of OPC UA, but on the surface it sounds like the https://github.com/coussej/node-opcua-logger might be a good model to mimic.
> 
> Once the data is being written to InfluxDB, we can work on building custom experiences in Chronograf for something like this.

as a control Engineer, I should say OPC-UA is designed to control the industrial process. but we need industrial data in a higher level of management in a management dashboard. who look at dashboard needs to see overall process performance, not details.
nowadays I'm looking for such plugIns to integrate field data into InfluxDB. please continue development... I'm waiting for it

**Comment by gavioto** [comment] 2020-09-08 13:35
https://github.com/influxdata/telegraf/pull/7213

**Comment by sjwang90** [comment] 2020-09-08 17:12
OPC UA input plugin was merged last week and will be included in the 1.16 release. 

There's a PR #7195 for the OPC UA output plugin if anyone would like to review. I'll close this for now. I've opened another issue #8083 around an events base input plugin for OPC UA (new plugin polls OPC UA metrics)

**Closed by sjwang90** 2020-09-08 17:12 UTC
Labels: feature request, vert/iot
