### ISSUE TITLE
[Feature Request] Add "AND" Conditional Operator to Telegraf Filter

### ISSUE THREAD

**Issue by danyli78** [influxdata/telegraf#2605] opened 2017-03-30 22:39 UTC
I think it would be useful to add the "AND" operator for multiple tag key filter using tagpass or taggdrop.

example

  [outputs.influxdb.tagpass]
    bu = ["company1"] AND env=["prod"]

**Comment by danielnelson** [comment] 2017-03-30 23:57
This is a duplicate of #937.

**Closed by danielnelson** 2017-03-30 23:57 UTC
