### ISSUE TITLE
telegraf dropped/purged/truncated its output buffer on SIGHUP

### ISSUE THREAD

**Issue by jasonkeller** [influxdata/telegraf#2679] opened 2017-04-17 12:58 UTC
### System info:
telegraf 1.2, RHEL7

### Steps to reproduce:
1. Have inputs (like SNMP) running
2. pkill -1 telegraf or pkill -SIGHUP telegraf

### Expected behavior:
Soft configuration reload

### Actual behavior:
Truncated output buffer and soft configuration reload, causing huge derivative dips in Grafana.

### Additional info:
https://community.influxdata.com/t/refreshing-telegraf-shows-dips-on-graphs-in-grafana/525/4
Opening this bug per daniel

First mentioned at the bottom of this bug by another user...
https://github.com/influxdata/telegraf/issues/69

And I think JZ even asked this on the forums but got no response...
https://community.influxdata.com/t/reload-config-telegraf-config-file-without-restarting-process/62

**Comment by jasonkeller** [comment] 2017-05-18 18:40
Any motion on this?

**Comment by danielnelson** [comment] 2017-07-06 01:49
This is somewhat tricky.

Each output currently has its own metric buffer and may not be able to flush at this time.  The metric buffers for the output may have more differences among them than just a position, due to filtering options transforming the points.

It may be easiest to stop the world and allow the outputs a time period to flush everything, and then perform the reload.  If the output could not complete in this time the buffered points would be lost for it.

Another way we could potentially handle this is by moving to a shared output buffer and performing filtering on flush.  This would use less memory when there are multiple outputs, but filtering would need to be done each time in case of failure, or only failures could be buffered per output.

I think I'll do the stop the world reload first, and perhaps do the shared output buffer at some later date.

**Comment by jasonkeller** [comment] 2017-10-20 14:41
@danielnelson are there any updates to this?  I keep running into this and getting weird dip/spikes on my graphs in grafana on derivative functions due to the missing datapoints.

If we don't have a good way to update the telegraf instance with new endpoints to poll without losing data, that really nerfs when we can realistically begin polling new devices.

**Comment by jasonkeller** [comment] 2017-10-20 16:14
@danielnelson I'll back up a second and get this out there so people realize the other implications of restarting/refreshing the telegraf process.

So part of the issue is dropping data (which if you flush more frequently than poll, you can get around it with careful timing), but another issue that may inevitably bite you is interval skew.  If you don't restart at the relative point in the interval that you did previously, telegraf will begin polling at a different point in your interval at the same cadence, leading to a frame-shift of points that will cause a spike/dip on your graph.

**Comment by danielnelson** [comment] 2017-10-21 01:02
I'm hoping to fix this as part of the configuration overhaul to support kv config stores. https://github.com/influxdata/telegraf/issues/272

I've heard about reload causing issues with plugin specific collection interval https://github.com/influxdata/telegraf/issues/2839, is it happening also with the global interval?  Also what round interval is set to.

**Comment by jasonkeller** [comment] 2017-10-23 14:40
Round interval is set to true, with default interval in our agent section set to 60s.  All our probe intervals are set to 300s though.  Does round_interval only interact with the global interval in the agent section?

**Comment by danielnelson** [comment] 2017-10-23 20:56
I haven't investigated the issue closely yet, but it is supposed to work in either case.

**Comment by rdxmb** [comment] 2018-01-02 16:10
similar problem here: https://community.influxdata.com/t/telegraf-should-reconnect-after-influxdb-timeouts/3550 . I guess this is the same issue.

**Comment by danielnelson** [comment] 2018-01-02 18:40
@rdxmb That doesn't look like a similar problem to the one reported on this issue.

**Comment by voiprodrigo** [comment] 2018-12-08 03:18
Could this be an incentive to add support to persist buffers on disk? :)

**Comment by rdxmb** [comment] 2018-12-10 10:44
I think I confused this issue with another. I am sorry.

**Comment by srebhan** [comment] 2023-07-26 18:46
@jasonkeller is this still an issue with the latest version of Telegraf? If so, is there any simple way to reproduce the issue?

**Closed** 2023-08-10 18:09 UTC
Labels: bug, area/configuration, waiting for response
