### ISSUE TITLE
[Feature Request] MQTT input topic templating

### ISSUE THREAD

**Issue by devkid** [influxdata/telegraf#2322] opened 2017-01-25 21:55 UTC
### Proposal:
Support templating of MQTT topics like it is currently supported for the [graphite input data format](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#graphite).

### Current behavior:
The MQTT topic is published via a single tag "topic" to telegraf.

### Desired behavior:
The topic should be divisible into multiple fields and tags. E.g. [homegear](https://doc.homegear.eu/data/homegear/communication_protocols.html) publishes messages with topics like:
```
homegear/HOMEGEAR_ID/plain/PEERID/CHANNEL/VARIABLE_NAME
```

For example:
```
homegear/1234-5678-90ab/plain/1/4/ACTUAL_TEMPERATUR
```

This could be mapped via a template:
```
measurement/*/*/peerid/*/field = 20
```

to:
```
homegear,peerid=1 ACTUAL_TEMPERATUR=20
```

### Use case:
This would enable better filtering depending by single tags of the topic in InfluxDB.

**Comment by sparrc** [comment] 2017-01-25 21:56
dupe of #648

**Comment by devkid** [comment] 2017-01-25 21:57
Whoops, didn't see you also proposed templating for inputs.

**Closed by sparrc** 2017-01-25 21:56 UTC
