### ISSUE TITLE
Feature Request: add exclude_interfaces_regex for inputs.netif

### ISSUE THREAD

**Issue by SEJeff** [influxdata/telegraf#3356] opened 2017-10-18 14:26 UTC
### Proposal:
A configuration option such as `exclude_interfaces_regex` would allow users to automatically exclude a set of interfaces.

### Current behavior:
1. Run telegraf with `inputs.netif` on a node that runs in a kubernetes cluster with lots and lots of docker containers
2. Watch telegraf start collecting metrics from all of the virtual interfaces and sending metrics we'd rather not collect (as the data isn't useful for veth*, kube-*, or docker0 interfaces).
3. Update the `telegraf.conf` to exclude said interfaces via config management.
4. Be sad when a new container starts with a new veth interface and you keep getting metrics.

### Desired behavior:
A way to exclude a regex of interfaces that will be automatically brought up and down constantly due to lots of containers starting/stopping on the host with stats that don't matter for monitoring.

### Use case:
It helps keep the metrics going to influx useful and actionable. It reduces noise.

**Comment by danielnelson** [comment] 2017-10-18 21:03
I believe this is duplicate of #1073, we will probably want to use globs for greater consistency with the rest of the telegraf plugins.

**Closed by danielnelson** 2017-10-18 21:03 UTC
