### ISSUE TITLE
inputs.ntpq creates rather a lot of series'

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/telegraf#6507] opened 2019-10-10 06:59 UTC
### Relevant telegraf.conf:
```toml
[[inputs.ntpq]]
   ## If false, set the -n ntpq flag. Can reduce metric gather time.
   dns_lookup = true
```

### System info:
telegraf-1.12.1_1
Name           : telegraf
Version        : 1.12.1_1
Installed on   : Tue Oct  8 13:49:47 2019 JST
Origin         : net-mgmt/telegraf
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : net-mgmt
Licenses       : MIT
Maintainer     : girgen@FreeBSD.org

### Steps to reproduce:

1. ... enable inputs.ntpq
2. ... leaves to simmer for a long time.

### Expected behavior:
maybe 1 series for each remote, at this precise time I have 15, 8 of which are local.

### Actual behavior:

140 of these: (and this is just for *one* host. 

ntpq,host=bunny.bunny,refid=6,remote=number6.bunny,state_prefix=#,stratum=b,type=7
ntpq,host=bunny.bunny,refid=6,remote=number6.bunny,state_prefix=#,stratum=b,type=8
ntpq,host=bunny.bunny,refid=6,remote=number6.bunny,state_prefix=#,stratum=b,type=9
ntpq,host=bunny.bunny,refid=6,remote=number6.bunny,state_prefix=-,stratum=b,type=1
ntpq,host=bunny.bunny,refid=6,remote=number6.bunny,state_prefix=-,stratum=b,type=10
ntpq,host=bunny.bunny,refid=6,remote=number6.bunny,state_prefix=-,stratum=b,type=106
ntpq,host=bunny.bunny,refid=6,remote=number6.bunny,state_prefix=-,stratum=b,type=11

### Additional info:

This plugin appears to be in contravention of:

https://docs.influxdata.com/influxdb/v1.7/concepts/schema_and_data_layout/

This may or may not be correct, but "type=" is not especially relevant when you have 1~120 of them. Per remote=

**Comment by glinton** [comment] 2019-10-10 17:36
If you find that you don't wish to include a tag, use a [metric modifier](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#modifiers) in this case `tagexclude` to drop the tag from that metric.

I'm not familiar enough with the output of ntpq to know what's valuable information, but you can even exclude the `state_prefix` if you wish. 

Regarding your data set pasted in the actual behavior section, is that all from one collection interval, or is that multiple collections (different timestamps)?

Also, what is the ntpq version you are running as well as the output of `ntpq -p -n`

The data layout and schema doc you linked is not necessarily in contradiction to what this plugin is doing, assuming the `type` output of ntpq is limited, there won't be too enough cardinality introduced to be a problem. If it is not limited, that is something we should address.

**Comment by bunnyevans** [comment] 2019-10-19 04:46
tagexclude? I shall have to look for that.
I expect you mean:  tagexclude=["state_prefix","type"]
And that it's not retroactive, meaning some black magic must be performed.

for that example above, there were about 140 of those type= just for that particular remote.


This is one server that has been running for a while. Since at least March Last year.
As a result all these werid little series' have shown up. It might well be all due for an export everything and start from scratch.

It is now 4.2.8p13 

     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 ntp.nict.jp     .POOL.          16 p    -   16    0    0.000    0.000   0.000
 127.127.1.0     .LOCL.          10 l  59d   64    0    0.000    0.000   0.000
 224.0.1.1       .MCST.          16 M    -   64    0    0.000    0.000   0.000
+210.171.228.6   210.171.228.23   2 u  146 1024  377    5.530    0.288   0.532
-202.234.233.106 210.173.160.57   3 u  129 1024  377    6.180    2.322   0.963
-202.234.233.109 210.173.160.57   3 u   63 1024  377    8.783    3.406   2.562
-18.182.176.94   169.254.169.123  4 u  165 1024  377    8.933    1.818   1.972
-52.194.18.196   169.254.169.123  4 u  631 1024  377   13.134   -2.320   1.071
+13.115.129.149  169.254.169.123  4 u  387 1024  377    6.098   -0.293   0.404
*133.243.238.243 .NICT.           1 u  269 1024  377    6.561    0.423   1.373
#10.0.0.7        10.0.0.6         4 b   42   64  377    1.308  -58.528  22.109
 10.0.0.124      (loop)           3 b   20   64  377    4.342  -41.493   1.766
 10.0.0.6        (loop)           3 b   54   64   77    0.249  -17.284   0.510
 10.0.0.79       (loop)           3 b   11   64   77    1.130  -50.357   0.937
 10.0.0.80       (loop)           3 b   13   64   17    4.480  -42.751   4.430

**Comment by danielnelson** [comment] 2019-11-15 22:45
@bunnyevans The `type` tag ought to be a single character based on the `t` column, never a number, it looks like the parsing is being done incorrectly.  However, if I test against the example output from your last comment though it appears to be working, output below.
```
ntpq,refid=.POOL.,remote=ntp.nict.jp,stratum=16,type=p delay=0,jitter=0,offset=0,poll=16i,reach=0i 1573857680000000000
ntpq,refid=.LOCL.,remote=127.127.1.0,stratum=10,type=l delay=0,jitter=0,offset=0,poll=64i,reach=0i,when=5097600i 1573857680000000000
ntpq,refid=.MCST.,remote=224.0.1.1,stratum=16,type=M delay=0,jitter=0,offset=0,poll=64i,reach=0i 1573857680000000000
ntpq,refid=210.171.228.23,remote=210.171.228.6,state_prefix=+,stratum=2,type=u delay=5.53,jitter=0.532,offset=0.288,poll=1024i,reach=377i,when=146i 1573857680000000000
ntpq,refid=210.173.160.57,remote=202.234.233.106,state_prefix=-,stratum=3,type=u delay=6.18,jitter=0.963,offset=2.322,poll=1024i,reach=377i,when=129i 1573857680000000000
ntpq,refid=210.173.160.57,remote=202.234.233.109,state_prefix=-,stratum=3,type=u delay=8.783,jitter=2.562,offset=3.406,poll=1024i,reach=377i,when=63i 1573857680000000000
ntpq,refid=169.254.169.123,remote=18.182.176.94,state_prefix=-,stratum=4,type=u delay=8.933,jitter=1.972,offset=1.818,poll=1024i,reach=377i,when=165i 1573857680000000000
ntpq,refid=169.254.169.123,remote=52.194.18.196,state_prefix=-,stratum=4,type=u delay=13.134,jitter=1.071,offset=-2.32,poll=1024i,reach=377i,when=631i 1573857680000000000
ntpq,refid=169.254.169.123,remote=13.115.129.149,state_prefix=+,stratum=4,type=u delay=6.098,jitter=0.404,offset=-0.293,poll=1024i,reach=377i,when=387i 1573857680000000000
ntpq,refid=.NICT.,remote=133.243.238.243,state_prefix=*,stratum=1,type=u delay=6.561,jitter=1.373,offset=0.423,poll=1024i,reach=377i,when=269i 1573857680000000000
ntpq,refid=10.0.0.6,remote=10.0.0.7,state_prefix=#,stratum=4,type=b delay=1.308,jitter=22.109,offset=-58.528,poll=64i,reach=377i,when=42i 1573857680000000000
```

Are you still experiencing this issue with the updated server?

**Comment by ahothan** [comment] 2020-02-05 00:39
excluding the state_prefix tag will work but you will lose the state prefix information completely.

This issue was reported first by https://github.com/influxdata/telegraf/issues/1161
which was then "fixed" by https://github.com/influxdata/telegraf/pull/1219
but the original issue still not fixed because the state_prefix tag is introducing new time series as the state of a remote server evolves.

The root of the problem is that state_prefix should not be a label but should instead be a new metric, e.g.:
ntpq_state_prefix{host=c15, refid=10.86.130.4,remote=10.86.130.5} = 0 (0=peer,1=candidate for ex)
ntpq_state_prefix{host=c15, refid=10.86.130.4,remote=10.86.130.6} = 1
ntpq_state_prefix{host=c15, refid=10.86.130.4,remote=10.86.130.7} = 1
 
Now if we fix this issue the correct way it will introduce a backward incompatibility in 2 ways:
- ntpq metrics will no longer have the state_prefix label but will always result in the expected number of time series
- to get the state prefix a new query is needed (ntpq_state_prefix)

I can submit a pull request if the backward compatibility is acceptable (or use a config flag to enable that mode)

**Comment by ahothan** [comment] 2020-02-05 01:05
The type tag should be a letter:

t: types available
l = local (such as a GPS, WWVB)
u = unicast (most common)
m = multicast
b = broadcast
– = netaddr

So not sure how you ended up with all these numbers.
I don't have any issue with type but do have issues with state_prefix which I intend to remove and replace with a new metric in my fork

**Comment by danielnelson** [comment] 2020-02-05 01:58
In Telegraf terms, you are proposing that `state_prefix` be emitted as a field instead of a tag, as well as converting to an enum like integer.  I don't think I agree, we commonly emit enum like values as tags, this gives us access to `group by` and `where` queries and avoids needing to apply an arbitrary numbering to the values.  I see this commonly done in Prometheus as well, its even shown in the best practices document: https://prometheus.io/docs/practices/naming/#labels.

If you do want to make this change, you can do it and avoid a code change by using the `converter` and then the `enum` processor to switch to a field and then map the numeric values.

It's still not clear what the cause of the original issue is or how to reproduce it, so I'm inclined to close this issue until we can find a way to reproduce.  If anyone has a way to duplicate, we can reopen this issue.

**Closed by danielnelson** 2020-02-05 01:58 UTC
Labels: bug, need more info, platform/bsd

**Comment by ahothan** [comment] 2020-02-05 16:57
Please do not use general statements about how to use tags and think about use case.

I'll try to explain to you why using a tag to store the state prefix is wrong.
The prometheus document you point to says it clearly: "CAUTION: Remember that every unique combination of key-value label pairs represents a new time series"
For all practical purpose and at the end of the day, a time series is used to track a specific state of a specific resource.
The issue I introduce here has been found in production on very large deployments in service provider market (thousands of telegraf processes running in private clouds). It is relatively easy to reproduce if you are well versed in NTP tuning.

For this specific case of NTPQ, we are monitoring the state of remote servers that are used for NTP protocol.
So the resource to monitor is a remote server. Each time series characterizes one state attribute of each remote server.

Let’s take the example of ntpq_reach, for the sake of simplicity I will only show below the tags host, state_prefix, refid and remote
In this example there are 3 remote servers for which we want to monitor the reach (an octal number which is supposed to be 377 when normal).

Let’s say at given time t0 the ntpq reach returns the following 3 metrics for the 3 time series:
 
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.5,state_prefix=’*’} = 377   (time series ts0)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.6,state_prefix=’+’} = 377  (time series ts1)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.7,state_prefix=’+’} = 377  (time series ts2)

The state_prefix label indicates whether this remote is the elected peer (*) or a candidate/valid backup (+). So normally we would always expect 1 peer and 2 candidates.

And assume that within the next minute there is a change of election and 10.86.130.6 becomes the new elected peer. The next batch of metrics will then be at t0+1m:

ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.5,state_prefix=’+’} = 377 (time series ts3 => this is not ts0 because state_prefix is different)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.6,state_prefix=’*’} = 377 ((time series ts4)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.7,state_prefix=’+’} = 377 (time series ts2)

Because prometheus will return all matching samples within 5m interval, the ntpq_reach PROMQL query will yield:
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.5,state_prefix=’*’} = 377 (time series ts0)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.6,state_prefix=’+’} = 377 (time series ts1)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.5,state_prefix=’+’} = 377 (time series ts3)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.6,state_prefix=’*’} = 377 (time series ts4)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.7,state_prefix=’+’} = 377 (time series ts2)

Since the tuple determines the key identifying a unique time series we end up with 5 time series instead of the expected 3 time series, just because the elected peer changed to a different server. This is clearly wrong.

We see here that the root of the problem is that state_prefix should not be a tag but should instead be a new field to track the elective state of each remote server which can change independently of all other fields for each server (reach, ...):
 
ntpq_state_prefix{host=c15, refid=10.86.130.4,remote=10.86.130.5} = 0 (0=peer,1=candidate for ex)
ntpq_state_prefix{host=c15, refid=10.86.130.4,remote=10.86.130.6} = 1
ntpq_state_prefix{host=c15, refid=10.86.130.4,remote=10.86.130.7} = 1

If state_prefix is removed from the tag list, the peer election transition will no longer cause any issue because it will not introduce new time series:
 
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.5} = 377   (time series ts0)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.6} = 377  (time series ts1)
ntpq_reach{host=c15, refid=10.86.130.4,remote=10.86.130.7} = 377  (time series ts2)

So you see that having the state prefix as a tag is fundamentally wrong.
It would be akin to having the result_code (which is an enum: success = 0, no such host = 1, ping error = 2) be coded as a tag for all fields instead of a field itself
in the ping plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ping)

If that mistake was done in the ping plugin, would you ask people to use the converter/enum processors to fix it or rather fix the root cause with a patch?

We are planning to fix this in the code in our private fork because that is the right thing to do.
I'd be happy to contribute back to upstream if there is interest.

Thank you.
