### ISSUE TITLE
Netstat report incorrect values

### ISSUE THREAD

**Issue by cdgraff** [influxdata/telegraf#719] opened 2016-02-18 23:43 UTC
I has running netstat plugin in telegraf running as ROOT, to avoid privileges issue reported into other issue.

But only get ESTABLISHED metrics, and the counts is not correct.

root@ubuntu:~# telegraf -config /etc/telegraf/telegraf.conf -input-filter netstat -test
* Plugin: netstat, Collection 1
> netstat tcp_close=0i,tcp_close_wait=0i,tcp_closing=0i,tcp_established=9834i,tcp_fin_wait1=0i,tcp_fin_wait2=0i,tcp_last_ack=0i,tcp_listen=8i,tcp_none=0i,tcp_syn_recv=0i,tcp_syn_sent=0i,tcp_time_wait=0i,udp_socket=1i 1455827518629788254

root@ubuntu:~# netstat -nap | grep ESTABLI | wc -l
13840

And is not reporting any other value, at this moment i has +20k time_wait connections and can see that plugin don't report any value there.

some advice? or tests to run for help with debug?

**Comment by sparrc** [comment] 2016-02-18 23:46
what is output of `lsof -i -a -n -P`?

**Comment by sparrc** [comment] 2016-02-18 23:46
dupe of https://github.com/influxdata/telegraf/issues/656, please paste output in other issue

**Closed by sparrc** 2016-02-18 23:46 UTC
