### ISSUE TITLE
Kafka + system inputs and Prometheus output cause error

### ISSUE THREAD

**Issue by HristoMohamed** [influxdata/telegraf#3102] opened 2017-08-08 15:25 UTC
I will let config files talk (full config is below).
Example error is 
2017-08-08T15:19:50Z I! Mixed ValueType for measurement "disk"; dropping point
[root@telecons01 ~]# telegraf -version
Telegraf v1.4.0~pre428455e (git: master 428455e)

/horrible github formatting crossing my text -_-/

[global_tags]
  domain = "blabla'
  location = "sx"
  nodeclass = "telegrafconsumer"

[agent]
  hostname = "telecons01"
  omit_hostname = true
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 5
  collection_jitter = "0s"
  flush_interval = "20s"
  flush_jitter = "0s"
  logfile = ""
  debug = false
  quiet = false

  [[outputs.prometheus_client]]
  expiration_interval = "180s"
  listen = ":9126"

[[inputs.cpu]]
  collect_cpu_time = false
  percpu = true
  totalcpu = true
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
    [[inputs.kafka_consumer]]
  brokers = ["kafka01:9092"]
  consumer_group = "telegraf_metrics_consumers"
  data_format = "influx"
  max_message_len = 65536
  offset = "oldest"
  topics = ["telegrafcommon"]

**Comment by danielnelson** [comment] 2017-08-08 18:16
This must be caused by kafka adding points as untyped while disk adds as gauges.

**Comment by HristoMohamed** [comment] 2017-08-08 18:59
This happens with all outputs, the disk one was just an example.

**Comment by danielnelson** [comment] 2017-08-08 19:27
Does it only occur when the kafka_consumer is active?

**Comment by HristoMohamed** [comment] 2017-08-08 20:13
Yes.
Basically I can only either run kafka_consumer as an input, or the system inputs(disk, cpu, etc...), but cant use both.

**Comment by HristoMohamed** [comment] 2017-08-10 08:52
Sorry for the late reply,
Yes now everything is OK (at least it does not spill out any errors)
[root@telecons01 telegraf]# ./telegraf  --version
Telegraf v1.4.0~pre70169b0 (git: fix-prom-mixed-type-with-consumer 70169b0)
[root@telecons01 ~]# ./telegraf -config /etc/telegraf/telegraf.conf
2017-08-10T08:49:07Z I! Starting Telegraf v1.4.0~pre70169b0
2017-08-10T08:49:07Z I! Loaded outputs: prometheus_client
2017-08-10T08:49:07Z I! Loaded inputs: inputs.kernel_vmstat inputs.mem inputs.swap inputs.system inputs.kafka_consumer inputs.cpu inputs.diskio inputs.disk inputs.net inputs.processes
2017-08-10T08:49:07Z I! Tags enabled: domain=lbdaq.cern.ch location=sx nodeclass=telegrafconsumer
2017-08-10T08:49:07Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"telecons01", Flush Interval:20s 
2017-08-10T08:49:07Z I! Started the kafka consumer service, brokers: [kafka01:9092 kafka02:9092 kafka03:9092 kafka04:9092 kafka05:9092 kafka06:9092 kafka07:9092], topics: [telegrafcommon]

**Comment by danielnelson** [comment] 2017-08-10 17:23
Fix will be in the 1.4 release

**Closed by danielnelson** 2017-08-10 17:23 UTC
Labels: bug
