### ISSUE TITLE
[Wavefront Output Plugin] make internal sender buffer size configurable

### ISSUE THREAD

**Issue by lihaiswu** [influxdata/telegraf#7409] opened 2020-04-24 22:36 UTC
## Feature Request

Make internal sender buffer size configurable in Wavefront Output Plugin

### Current behavior:
Current defaultBufferSize is 50000 in wavefront sdk https://github.com/wavefrontHQ/wavefront-sdk-go/blob/master/senders/configs.go#L5
senders/configs.go:5 . When user configure telegraf with metric_buffer_limit exceed 50000, then extra metrics will be failed to write wavefront because of buffer full returned.

### Desired behavior:
Wavefront Output Plugin should make buffer size configurable to align with telegraf metric_buffer_limit. Otherwise, it's a limitation of Wavefront Output Plugin which can only accept maximum 50000 metrics.

### Use case: 

- Set metric_buffer_limit to 250000 in telegraf.conf.

- Telegraf write 51228 metrics to Wavefront

- Only 50000 metrics are accepted, extra 1228 are failed due to "Wavefront sending error: buffer full, dropping line"

`2020-04-24T20:38:11Z D! [outputs.wavefront] Buffer fullness: 51228 / 250000 metrics
2020-04-24T20:38:38Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 14.219747ms
2020-04-24T20:38:38Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 11.761473ms
2020-04-24T20:38:38Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 10.877892ms
2020-04-24T20:38:38Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 16.069646ms
....
2020-04-24T20:38:39Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 10.612196ms
2020-04-24T20:38:39Z D! [outputs.wavefront] Buffer fullness: 1228 / 250000 metrics
2020-04-24T20:38:39Z E! [agent] Error writing to outputs.wavefront: Wavefront sending error: buffer full, dropping line`

**Comment by danielnelson** [comment] 2020-04-24 23:17
@prydin Can you take a look?

The outputs don't know what the `metric_buffer_limit` is by design, but they should always fully send the batch during the write before returning.  This will prevent them from falling behind and it is also essential in order to work correctly with retries and "tracking metrics" from inputs such as the `kafka_consumer`.  Maybe we need to call Flush on the sender before returning from Write()?

**Comment by prydin** [comment] 2020-05-13 14:29
@danielnelson Please assign this to me!

**Comment by prydin** [comment] 2020-06-04 13:52
I'll try to get a PR filed for this issue later this week.

**Comment by igomura** [comment] 2020-06-11 01:31
Interesting enough, but this plugin fails only on ceph metrics in my case. It never fails on anything else. I wondering which metrics are dropped in original post. @lihaiswu could you add details?

**Comment by lihaiswu** [comment] 2020-06-11 04:28
> Interesting enough, but this plugin fails only on ceph metrics in my case. It never fails on anything else. I wondering which metrics are dropped in original post. @lihaiswu could you add details?

The telegraf wrote 51228 to wavefront proxy which exceeds defaultBufferSize 50000 ,then 1228 out of 51228 are dropped from the log.

`2020-04-24T20:38:11Z D! [outputs.wavefront] Buffer fullness: 51228 / 250000 metrics 2020-04-24T20:38:38Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 14.219747ms 2020-04-24T20:38:38Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 11.761473ms 2020-04-24T20:38:38Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 10.877892ms 2020-04-24T20:38:38Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 16.069646ms .... 2020-04-24T20:38:39Z D! [outputs.wavefront] Wrote batch of 1000 metrics in 10.612196ms 2020-04-24T20:38:39Z D! [outputs.wavefront] Buffer fullness: 1228 / 250000 metrics 2020-04-24T20:38:39Z E! [agent] Error writing to outputs.wavefront: Wavefront sending error: buffer full, dropping line`

**Comment by igomura** [comment] 2020-06-11 21:33
It looks like problem is in SDK
https://github.com/wavefrontHQ/wavefront-sdk-go/blob/master/senders/configs.go#L21

**Comment by ssoroka** [comment] 2020-09-21 14:59
Copying this from #8002 because I think the approach in this issue is misguided.

Wavefront should not have its own internal buffer. You end up with two buffers, and it doesn't matter what the size is, it's going to eventually drop metrics. Wavefront should instead be blocking and actually writing the metrics out when passed batches of 1000 (agent.metric_batch_size) metrics; Telegraf is managing the buffer, and keeping track of retries on failures.

Said another way, because Wavefront is not blocking and applying backpressure, it's not communicating with Telegraf that the buffer is full and to slow down. Due to this lack of communication, Telegraf happily sends all the metrics in, resulting in overflowing the wavefront buffer (at any size).

I'd recommend removing the wavefront buffer and sending the metrics immediately when passed a batch, and blocking until it succeeds or fails. If for some reason you really must have double buffers (I still think this is a mistake), then wavefront needs to block when the buffer is full, until there is room in the buffer to accept the new batch, not return an error and drop messages. However this is a mistake because it looks to Telegraf like messages are being delivered, and you're taking control of the buffer away from Telegraf, and unnecessarily complicating the plugin. If we release features in the future, say, to persist the buffer on shutdown, this plugin would not benefit from it.

**Comment by prydin** [comment] 2020-09-21 15:11
You definitely have a point. The issue is that the Wavefront SDK is designed to be "best effort" in order not to block callers if the downstream connection is saturated. Changing the behavior the way you suggest would unfortunately go beyond the plugin itself and require some redesign of the SDK. That being said, I will take a look at if there are any workarounds available.

**Comment by prydin** [comment] 2020-09-21 18:01
@ssoroka I think there may be a way to solve this. We could introduce a flag (let's call it ```unbuffered```) that causes a flush after each batch. This will ensure that everything gets sent in one burst. It also blocks until the sending has finished, so it provides the back pressure you were referring to. If the link is down, it will keep the data in the buffer and flush it whenever the link is available. I'll build a test version to see how it performs!

**Comment by prydin** [comment] 2020-09-22 00:22
@ssoroka Flushing the buffer after each batch seems to achieve exactly what you're looking for. It will block for as long as it takes to send the entire batch. The only gotcha is that you'll have to keep the batch size reasonable (a few thousand should be fine) so you don't fill up the internal buffers in the Wavefront SDK. I'll let this burn in overnight before I issue a PR.

**Comment by ssoroka** [comment] 2020-11-03 21:16
resolved

**Closed by ssoroka** 2020-11-03 21:16 UTC
Labels: area/wavefront, bug
