### ISSUE TITLE
SNMP Input plugin removal of metrics on timeout polling multiple hosts

### ISSUE THREAD

**Issue by neeles83** [influxdata/telegraf#7470] opened 2020-05-06 10:47 UTC
### Relevant telegraf.conf:
```
[[inputs.snmp]]
  agents = [ "10.x.x.1:161", "10.x.x.2:161", 10.x.x.3:161" ]
  version = 2
  community = "xxxxxx"
  name = "snmp"
  retries = 3
  interval = "180s"
  timeout = "160s"

  [[inputs.snmp.field]]
    name = "sysName"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "sysLocation"
    oid = "SNMPv2-MIB::sysLocation.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "EXPRESSION-MIB::sysUpTimeInstance"
  [[inputs.snmp.field]]
    name = "cisco_product"
    oid = "ENTITY-MIB::entPhysicalModelName"
  [[inputs.snmp.field]]
    name = "cisco_software"
    oid = "SNMPv2-MIB::sysDescr.0"

#CPU Information:

  [[inputs.snmp.table]]
    name = "cisco_CPU"
    inherit_tags = [ "sysName", "sysLocation" ]
    oid = "CISCO-PROCESS-MIB::cpmCPUTotalTable"

#Memory Information:

  [[inputs.snmp.table]]
    name = "cisco_Memory"
    inherit_tags = [ "sysName" , "sysLocation" ]
    oid = "CISCO-ENHANCED-MEMPOOL-MIB::cempMemPoolTable"

#Sensor Information:

  [[inputs.snmp.table]]
    name = "cisco_Sensors"
    inherit_tags = [ "sysName" , "sysLocation" ]
    oid = "CISCO-ENTITY-SENSOR-MIB::entSensorValueTable"

#Interfaces Information:

  [[inputs.snmp.table]]
    name = "cisco_interface"
    oid = "IF-MIB::ifTable"
    inherit_tags = [ "sysName" ,"sysLocation" ]

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifDescr"
      name = "ifDescr"
      is_tag = true

  [[inputs.snmp.table]]
    name = "cisco_interface"
    oid = "IF-MIB::ifXTable"
    inherit_tags = [ "sysName" , "ifDescr" ,"sysLocation"]

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifDescr"
      name = "ifDescr"
      is_tag = true

#BGP Neighbor Information:

  [[inputs.snmp.table]]
    name = "cisco_BGPneighbors"
    inherit_tags = [ "sysName" , "sysLocation" ]
    oid = "BGP4-MIB::bgpPeerTable"
```
### System info:

Using Docker image from https://hub.docker.com/_/telegraf
Telegraf version 1.14.1

### Steps to reproduce:

1. run above configuration input with actual devices.

### Expected behavior:

If a device times-out Telegraf will connect to the next device or dumps the incomplete devices and echo's back the device which has issues, but keeps the relevant SNMP information and push this to the metric output. 

The logs can also be changed to informational instead of an error and more descriptive something like "device x was polled but a timeout was received. Plugin y configuration file z". It now only tells you which device and that it is an SNMP plugin but we run many SNMP plugins one for each part or type of device and part of the configuration CPU, Memory, Interfaces. Were Interfaces are generic.

### Actual behavior:

If one of the devices received an time-out or is enable to retrieve an table all SNMP Metrics are dropped. 

When running large implementations this will result in an inoperable environment as device may go down or are removed form production, which thus cause all other metric to be dropped. Even miss configuration of an IP address may cause this behavior. 

### Additional info:

```
2020-04-30T00:01:44Z W! [agent] [inputs.snmp] did not complete within its interval
2020-04-30T00:02:04Z E! [inputs.snmp] Error in plugin: agent 10.x.x.1:161: gathering table CheckPoint_powerSupply: performing bulk walk for field powerSupplyIndex: Request timeout (after 3 retries)
2020-04-30T00:02:22Z E! [inputs.snmp] Error in plugin: agent 10.x.x.2:161: gathering table PaloAlto_memory: performing bulk walk for field PaloAlto_memory_total: Request timeout (after 3 retries)
2020-04-30T00:02:44Z W! [agent] [inputs.snmp] did not complete within its interval
2020-04-30T00:03:00Z W! [agent] [inputs.snmp] did not complete within its interval
2020-04-30T00:03:02Z E! [inputs.snmp] Error in plugin: agent 10.x.x.2:161: performing get on field sysName: Request timeout (after 3 retries)
2020-04-30T00:03:22Z W! [agent] [inputs.snmp] did not complete within its interval
2020-04-30T00:03:24Z E! [inputs.snmp] Error in plugin: agent 10.x.x.1:161: gathering table CheckPoint_FanSpeed: performing bulk walk for field fanSpeedSensorIndex: Request timeout (after 3 retries)
2020-04-30T00:03:42Z E! [inputs.snmp] Error in plugin: agent 10.x.x.2:161: gathering table PaloAlto_interface: performing bulk walk for field ifDescr: Request timeout (after 3 retries)
2020-04-30T00:04:22Z W! [agent] [inputs.snmp] did not complete within its interval
2020-04-30T00:04:22Z E! [inputs.snmp] Error in plugin: agent 10.x.x.2:161: gathering table PaloAlto_interface: performing bulk walk for field ifDescr: Request timeout (after 3 retries)
2020-04-30T00:04:24Z W! [agent] [inputs.snmp] did not complete within its interval

```

**Comment by danielnelson** [comment] 2020-05-07 00:14
I believe this is a duplicate of #3823

The main workaround is to have one plugin per device, this means there is substantial duplication in the configuration but each plugin will operate fully independently.  I know this isn't ideal and we have some ideas for addressing this, but they aren't scheduled to be worked on currently.

**Closed by danielnelson** 2020-05-07 00:14 UTC

**Comment by danielnelson** [comment] 2020-05-07 00:30
P.S.  It may be helpful to set the `alias` option plugins which give it a name to help differentiate the plugin instance:
```
[[inputs.snmp]]
  alias = "plugin1"
```

The log should then look something like:
```
2020-04-30T00:03:42Z E! [inputs.snmp::plugin1] Something happened.
```

**Comment by neeles83** [comment] 2020-05-07 10:52
@danielnelson Thanks for the explanation and workarounds. Hope it will be resolved in the future. As it indeed causes a lot of overhead in the configuration an possibly in processing/memory. As we are looking at an implementation of 2000+ nodes that are being polled.
