### ISSUE TITLE
[ Feature Request ] Azure Monitor Plugin

### ISSUE THREAD

**Issue by fluffyf-x** [influxdata/telegraf#9292] opened 2021-05-23 12:39 UTC
## Feature Request

Azure monitor collects metrics and logs on a common platform across different [Azure Tiers](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/data-sources). These metrics would be useful to fill in gaps in monitoring for managed services without integrating a third party monitoring agent (e.g., datadog). Ideally we can reduce the scope of this feature request by providing a base which others may contribute or build off of for their desired usage.

### Proposal:

Create the base level integration and begin metrics collection for a handful of services, provide well documented examples so others may easily build and add additional metrics. 

### Current behavior:

I do not see an azure monitor plugin currently

### Desired behavior:

forward desired azure monitor metrics into first party monitoring application.

### Use case: 

- provides observability metrics to aggregate in first party software for air gap and government environments where third party applications cannot be installed

**Comment by reimda** [comment] 2021-05-25 20:20
duplicate of #7930

**Closed by reimda** 2021-05-25 20:20 UTC
Labels: area/azure, feature request
