### ISSUE TITLE
Add ability to query WMI on Windows.

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/telegraf#1857] opened 2016-10-06 09:41 UTC
## Feature Request

Add new input wmi input plugin.
### Proposal:

Add a new wmi input plugin to get arbitrary information from the system 
### Current behavior:

There is no way to get some configuration information from the Performance Counters.
### Desired behavior:

Get data from WMI and perhaps ( not required but interesting) combine with existing win_perf_counters defined measurements. 
### Use case: [Why is this important (helps with prioritizing requests)]

I'm working with Performance Monitor Counters but I seems there is no way to get the RAM  installed RAM memory

But there is other ways to get system information , the more powerful it seems do it from WMI and its own Query Language.

Something like :

![image](https://cloud.githubusercontent.com/assets/5883405/19147553/efa637ce-8bb8-11e6-859f-f9aae9cbd41e.png)

**Comment by sparrc** [comment] 2016-10-06 10:12
It's probably useful to be able to query WMI directly, but FWIW you should be able to get all the system information you need from the regular plugins like [[inputs.cpu]] & [[inputs.mem]]. These plugins use WMI behind the scenes.

@toni-moreno is there something in particular you are missing from these?

**Comment by sparrc** [comment] 2016-10-06 10:48
From what I can tell, any WMI class that we'd want to support would need to be defined natively in Go for us to make the queries: https://msdn.microsoft.com/en-us/library/dn792258(v=vs.85).aspx

There's a lot there, so any feedback on which classes are particularly helpful for Windows users would be nice to hear about.

**Comment by toni-moreno** [comment] 2016-10-07 20:22
Hi @sparrc I have not tested yet the cpu/mem input plugin in windows , perhaps could be enough for us now (to get memory info) but a General  WMI  input plugin will be also a great improvement. I will test next week .Thank you

**Comment by Scott-St** [comment] 2016-10-21 14:25
I'd like to add to this that I want to get sensor readings from WMI.  aida64 uses WMI for its readings so I would like to be able to query WMI (or write my own plugin) to get this same information.

**Comment by sparrc** [comment] 2016-10-21 14:34
@Scott-St You may want to check out the `exec` plugin

**Comment by absolutejam** [comment] 2016-12-08 16:24
This would also be handy for me as WMI exposes tonnes of information from both the OS and third party vendors (e.g. VEEAM). The exec plugin looks like a good stopgap, but will it mean the overhead of firing up a powershell instance for every cycle?

**Comment by sparrc** [comment] 2016-12-09 12:52
yep

**Comment by absolutejam** [comment] 2016-12-12 12:10
Bit of a tangent, but the docs don't reflect that the `mem` (and CPU) plugin works with Windows but after it being mentioned above, I'm now using it, thanks!

**Comment by andrewrmoreland** [comment] 2017-01-13 15:36
In Windows - the disk space of 'Cluster Shared Volumes' ('CSVs') cannot be monitored via performance counters, only WMI or PowerShell. Therefore the ability to use WMI in telegraf on Windows would be awesome.

**Comment by ssvenn** [comment] 2017-04-23 08:38
Being able to configure specific WMI queries would be really cool! I am searching for a way to get temperature and fan stats into influxdb from a Windows host and although it is possible to implement third party performance counters, nowadays it seems all the utilities target WMI instead.
http://openhardwaremonitor.org/ seems the most promising to me, since it's open source maybe it would be possible to bypass WMI entirely...

**Comment by dmitrios** [comment] 2017-08-16 22:04
@ssvenn : Check out https://github.com/infragravity/sonar-docker - it does exactly what you need.

**Comment by danielnelson** [comment] 2017-08-16 22:58
@dmitrios Is there source code available for the sonar tool itself?

**Comment by dmitrios** [comment] 2017-08-24 22:16
@danielnelson Not yet, perhaps sometime in the future. More details are available at https://goo.gl/g9wAJK

**Comment by AdamCavaliere** [comment] 2017-12-22 17:14
Any plans to get this working?

**Comment by danielnelson** [comment] 2017-12-28 00:32
No concrete plans that I know of.

**Comment by dmitrios** [comment] 2018-01-03 17:37
@AdamCavaliere - feel free to try Sonar (see [example]) (https://github.com/infragravity/sonar-docker/tree/master/samples). It can be used on Windows host or as a proxy.

**Comment by pytimer** [comment] 2018-07-10 07:47
What progress of this feature, i found  [wmi_exporter](https://github.com/martinlindhe/wmi_exporter) to query WMI. Can we reference to it?

**Comment by danielnelson** [comment] 2018-07-10 20:17
No news yet, but you should be able to run wmi_exporter and use the prometheus input to scrape from it.  I think these two projects would be good to consider when designing a WMI plugin, but too specific to prometheus/elasticsearch for direct inclusion.

**Comment by pytimer** [comment] 2018-07-11 02:15
@danielnelson yes, you said right. I mean we can reference these two projects collect metrics section and `wmibeat` configuration option section, not use these output section. 

I found @sparrc said:
> There's a lot there, so any feedback on which classes are particularly helpful for Windows users would be helpful for development.

I found `wmibeat` can config WMI Object Class on config file, so i think it maybe helpful for WMI plugin. 
I didn't look deeper for this project.This is my personal thoughts. :)

**Comment by danielnelson** [comment] 2018-07-11 03:13
If this is something you are interested in working on, I would suggest starting by designing a config file for others to review and deciding how the metrics will be encoded to line protocol.

**Comment by TheSilverHawkx** [comment] 2019-12-30 14:44
I personally use a lot of wmi queries (currently though scripts parsing it to line protocol), having something modular can be a big help.
As for what @danielnelson  said about designing a config file:
```
[[inputs.wmi_query]]
	Namespace = "root\cimv2"
	[[inputs.wmi_query.object]]
	Query = "select * from Win32_Service where Name = 'telegraf'"
	Measurement = "win_service"
```
I'm no toml expert, but I think it'd be a good idea to keep the namespace outside the objects because there aren't many and most people use them for the default anyway.

afterwards every object will have it's 'query' and related 'measurement', maybe adding options for extra tags.

I can send my code in Powershell as an example.
Also is there a wmi provider for go? if so how does it outputs the result? object? string?

**Comment by danielnelson** [comment] 2019-12-30 19:06
> Also is there a wmi provider for go? if so how does it outputs the result? object? string?

We have been using https://github.com/StackExchange/wmi in existing plugins.  The [Query](https://github.com/StackExchange/wmi/blob/master/wmi.go#L125) function parses the response into an `interface{}`.

**Comment by TheSilverHawkx** [comment] 2019-12-30 19:32
I'm having a bit of a hard time reading the code (I'm a golang noob), but correct me if I'm wrong:
When creating a wmi client you have a Query function receiving the query, an interface for the information and other arguments ( as interface?).

If the above is correct, a static interface won't do and you need to to have an interface with the matching fields being queried?

Therefore you can adjust the configuration in the following way so you can make a "dynamic" interface:
```
[[inputs.wmi_query_poller]]
	Namespace = "root\cimv2"
	[[inputs.wmi_query_poller.object]]
        field = ["Name","Status","something"]
	Class = "Win32_Service"
	Where = "name = 'telegraf'"
	Measurement = "win_service"
```
Depending on the fact you can use something like 'auto' in an interface:
- Field represents the select clause, this way it'll be easier in constructing an interface (I hope).
- Class is the from clause.
- Where is, well, the where clause.

Proofing the query to select only and forcing users to specify fields instead of pulling all is a good idea imo - less information pulled = better runtimes and less memory usage, and, of course, block people from running malicious wmi commands on remote servers.

**Comment by danielnelson** [comment] 2019-12-30 22:02
Code is pretty hair due to the interaction with the Windows API and the use of reflection.  We need someone to check if we can gather general types dynamically.  Are we able to pass in an interface{}, map[string]interface{}, etc or do we need a type for each possible response?  My brief reading of the code makes me think it may not be possible with this function.

**Comment by AlexHeylin** [comment] 2020-04-29 09:14
I don't think I can add anything technically to the golang at this stage, but if / when this is available I have a bunch of tasty morsels I'm currently running as PowerShell using exec which I'll port over and make available.  The problem with running in PoSh is it skews the CPU / process stats because it sometimes runs at exactly the same time CPU & process stats are polled.

**Comment by TheSilverHawkx** [comment] 2020-10-06 19:05
> Code is pretty hair due to the interaction with the Windows API and the use of reflection. We need someone to check if we can gather general types dynamically. Are we able to pass in an interface{}, map[string]interface{}, etc or do we need a type for each possible response? My brief reading of the code makes me think it may not be possible with this function.

Daniel I managed to pull dynamic properties from Win32 API into a 2d array (vector to be precise), but it is in c++. Will it help?

**Comment by WafflesMcDuff** [comment] 2021-02-11 16:49
I need the ability to access this WMI Class for monitoring ephemeral port exhaustion: http://library.wmifun.net/cimv2/win32_perfformatteddata_tcpip_tcpv4.html

**Comment by rismoney** [comment] 2021-05-14 13:08
I see this issue is 5 years old.  Are there blockers for moving this forward?  Is anyone working on this?

**Comment by basroovers** [comment] 2021-05-14 13:41
Took too long for me. I moved to windows_exporter.

**Comment by rismoney** [comment] 2021-05-14 13:59
@basroovers so are you only just using the prometheus windows_exporter for the windows piece with the rest being a tick/tig stack or what are you doing comprehensively.  I am concerned about excessive polling which i thought telegraf addressed better through push.

**Comment by basroovers** [comment] 2021-05-14 14:06
> @basroovers so are you only just using the prometheus windows_exporter for the windows piece with the rest being a tick/tig stack or what are you doing comprehensively.  I am concerned about excessive polling which i thought telegraf addressed better through push.

I use windows_exporter exclusively with some tasked scripts for some additional metrics (sql ha, app specific etc.). Works like a charm for me.

No concerns because most metrics now come from raw performance counters, not wmi.

**Closed** 2023-02-22 18:28 UTC
Labels: platform/windows, feature request
