### ISSUE TITLE
procstat_lookup always shows 1 when monitoring systemd_unit

### ISSUE THREAD

**Issue by Frakenz** [influxdata/telegraf#5300] opened 2019-01-16 20:38 UTC
### System info:
[Include Telegraf version, operating system name, and other relevant details]
Telegraf 1.9.1 (git: HEAD 20636091)
CentOS 7
InfluxDB shell version: 1.7.2

### Steps to reproduce:

1. `sudo systemctl stop puppet.service`
2. Wait for telegraf interval to update, in my case 1 minute
3. Enter into influxdb CLI with the corresponding database and run this query:
`SELECT last("pid_count") FROM "autogen"."procstat_lookup" WHERE ("systemd_unit" = 'puppet.service') AND time > now()-2m GROUP BY "myTag"`

### Expected behavior:

> name: procstat_lookup
> tags: myTag1
> time                last
> ----                ----
> 1547670360000000000 0

### Actual behavior:

> name: procstat_lookup
> tags: myTag1
> time                last
> ----                ----
> 1547670360000000000 1

### Additional info:
I only learned a bit of GO to read the source code, but from what I understood, the problem is that [here](https://github.com/influxdata/telegraf/blob/e95b88e01b2c664e43ea45faf77569d8db44a656/plugins/inputs/procstat/procstat.go#L132) len(pids) is not enough, since running systemctl show puppet.service when the service is not running will give MainPID=0 (see also #3612) and `systemdUnitPIDs() ` does not check for zero values.

[Include gist of relevant config, logs, etc.]
### Relevant telegraf.d/puppet.conf:
[[inputs.procstat]]
  systemd_unit = "puppet.service"

**Comment by glinton** [comment] 2019-01-17 00:56
There are cases where `MainPID=0` when the service is running, which seems to be caused by using the incorrect systemd unit, or incorrectly constructed file. Maybe `systemdUnitPIDs()` should check for zero values to encourage the proper use of the units/files. ...or maybe it should check for the pids in a different way as many of the units/files are created by default when installing a service.

**Comment by Frakenz** [comment] 2019-01-17 14:06
A different way to check if the service is running could be by [checking](https://unix.stackexchange.com/a/396633) the `SubState` or the `ActiveState` in the same way that the `MainPID` is being currently obtained.
In any case it would be good if someone could confirm if this is a bug or if it has something to do with my setup, so I can know how to proceed :)

**Comment by glinton** [comment] 2019-01-17 17:26
That's a great suggestion. It seems like `pid_count` is a bad place to populate if `MainPID=0` as the service has many child processes. There would also need to be a new path to determine "running" if that is the case, likely using the method you linked to - `systemctl show -p SubState something.service`. I suppose for compatibility sake, we set `pid_count` to 1 if the 'SubState' is "running" and 0 otherwise.

**Comment by Frakenz** [comment] 2019-01-17 22:10
@danielnelson I thought that was what it was meant to do as per #4237

**Comment by danielnelson** [comment] 2019-01-17 22:31
This plugin doesn't report if systemd thinks a service is running or not, it searches for PIDs and then reads the process information for them.  This field should contain the number of PIDs that have been found, if MainPID=0 then it hasn't found any valid PIDs so it should be zero.

This is why if you are using the pidfile method and the file exists containing a PID, the `pid_count` will report 1 no matter if the process is running or not.

It may be that we are not finding the PIDs correctly for systemd, which would be another issue, but I don't think we need to special case systemd in any way.

**Comment by danielnelson** [comment] 2019-06-14 19:46
Closed in #5972

**Closed by danielnelson** 2019-06-14 19:46 UTC
Labels: area/procstat, bug
