### ISSUE TITLE
telegraf --test shows Ceph output, but actual Telegraf run returns failed to find sockets at path '/var/run/ceph': Failed to read socket directory '/var/run/ceph': open /var/run/ceph: permission denied

### ISSUE THREAD

**Issue by victorhooi** [influxdata/telegraf#5590] opened 2019-03-15 19:02 UTC
### Relevant telegraf.conf:

```
# # Collects performance metrics from the MON and OSD nodes in a Ceph storage cluster.
 [[inputs.ceph]]
#   ## This is the recommended interval to poll.  Too frequent and you will lose
#   ## data points due to timeouts during rebalancing and recovery
   interval = '1m'
#
#   ## All configuration values are optional, defaults are shown below
#
#   ## location of ceph binary
#   ceph_binary = "/usr/bin/ceph"
#
#   ## directory in which to look for socket files
#   socket_dir = "/var/run/ceph"
#
#   ## prefix of MON and OSD socket files, used to determine socket type
#   mon_prefix = "ceph-mon"
#   osd_prefix = "ceph-osd"
#
#   ## suffix used to identify socket files
#   socket_suffix = "asok"
#
#   ## Ceph user to authenticate as
#   ceph_user = "client.admin"
#
#   ## Ceph configuration to use to locate the cluster
#   ceph_config = "/etc/ceph/ceph.conf"
#
#   ## Whether to gather statistics via the admin socket
#   gather_admin_socket_stats = true
#
#   ## Whether to gather statistics via ceph commands
   gather_cluster_stats = true
```

### System info:

Telegraf 1.10.0 (git: HEAD fe33ee8)
Proxmox 5.3 (based on Debian Stretch)
sysstat version 11.4.3

Contents of /var/run/ceph - public seems to have both read and execute bits on the relevant socket files. (However, I noticed the directly itself isn't open to public?).

```
root@syd1:/var/run/ceph# ls -lah
total 0
drwxrwx---  2 ceph ceph  160 Mar 14 07:48 .
drwxr-xr-x 27 root root 1.3K Mar 16 05:30 ..
srwxr-xr-x  1 ceph ceph    0 Mar 14 07:45 ceph-mgr.syd1.asok
srwxr-xr-x  1 ceph ceph    0 Mar 14 07:45 ceph-mon.syd1.asok
srwxr-xr-x  1 ceph ceph    0 Mar 14 07:48 ceph-osd.0.asok
srwxr-xr-x  1 ceph ceph    0 Mar 14 07:48 ceph-osd.1.asok
srwxr-xr-x  1 ceph ceph    0 Mar 14 07:48 ceph-osd.2.asok
srwxr-xr-x  1 ceph ceph    0 Mar 14 07:48 ceph-osd.3.asok
```

### Steps to reproduce:

1. Install Telegraf from InfluxData repositories.
2. Edit /etc/telegraf/telegraf.conf and enable ceph input plugin, and various options (per above).
3. Attempt to restart telegraf using systemctl restart telegraf
4. Run `telegraf --test` to check syntax.
5. Run `journalctl -u telegraf` to check status of telegraf.

### Expected behavior:

Ceph data that is shown in `telegraf --test` should also be populated into InfluxDB output.

No permission errors should be seen in Telegraf logs around Ceph.

### Actual behavior:

`telegraf --test` does show ceph data in output.

However, no ceph data is populated into InfluxDB.

`journalctl` shows error messages around Ceph permissions:

```
Mar 16 02:32:00 syd1 telegraf[577778]: 2019-03-15T15:32:00Z E! [inputs.ceph]: Error in plugin: failed to find sockets at path '/var/run/ceph': Failed to read socket directory '/var/run/ceph': open /var/run/ceph: permission denied
```

### Additional info:

I did find this earlier issue around Ceph permissions and Telegraf:

https://github.com/influxdata/telegraf/issues/1657

which mentions this Ceph PR to add a config option for socket permissions:

https://github.com/ceph/ceph/pull/11684

However, as per above, it seems like my actual socket files have public read/execute already set?

Also it's odd that `telegraf --test` returns Ceph output. (Not sure if it's something related to Proxmox, which doesn't include `sudo` by default). What user does `telegraf --test` run under?

(Interestingly - the above Ceph admin socket option is apparently not that well documented - see [this Medium article](https://medium.com/opsops/ceph-permissions-to-access-admin-socket-376b576ae0e5).

**Comment by glinton** [comment] 2019-03-15 19:18
`telegraf --test` runs as the same user who ran the command. Can the `telegraf` user (or whichever user the telegraf service is being run as) stat the sock files?

```
sudo -u telegraf stat /var/run/ceph/ceph-osd.0.asok
```
If not, you'll need to add telegraf to the ceph group

**Comment by victorhooi** [comment] 2019-03-15 19:33
(I had to install `sudo` specifically on Proxmox, as it doesn't include it out of the box, in order to the below testing)

I added the `telegraf` user to the `ceph` group.
```
root@syd1:/var/run# groups telegraf
telegraf : telegraf
root@syd1:/var/run# usermod -a -G ceph telegraf
root@syd1:/var/run# groups telegraf
telegraf : telegraf ceph
```

I then tried running `telegraf --test` under that context - it still failed:
```
root@syd1:/var/run# sudo -u telegraf telegraf -test -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d  -input-filter ceph
2019-03-15T19:10:08Z I! Starting Telegraf 1.10.0
2019-03-15T19:10:08Z E! [inputs.ceph]: Error in plugin: E! error reading from socket '/var/run/ceph/ceph-mon.syd1.asok': error running ceph dump: exit status 22
2019-03-15T19:10:08Z E! [inputs.ceph]: Error in plugin: E! error reading from socket '/var/run/ceph/ceph-osd.0.asok': error running ceph dump: exit status 22
2019-03-15T19:10:09Z E! [inputs.ceph]: Error in plugin: E! error reading from socket '/var/run/ceph/ceph-osd.1.asok': error running ceph dump: exit status 22
2019-03-15T19:10:09Z E! [inputs.ceph]: Error in plugin: E! error reading from socket '/var/run/ceph/ceph-osd.2.asok': error running ceph dump: exit status 22
2019-03-15T19:10:09Z E! [inputs.ceph]: Error in plugin: E! error reading from socket '/var/run/ceph/ceph-osd.3.asok': error running ceph dump: exit status 22
2019-03-15T19:10:09Z E! [telegraf] Error running agent: error executing command: error running ceph status: exit status 1
```
I also tested reading the dump directly:
```
root@syd1:/var/run# sudo -u telegraf ceph --admin-daemon /var/run/ceph/ceph-osd.1.asok perf dump
admin_socket: exception getting command descriptions: [Errno 13] Permission denied
```
I was able to fix the issue by editing `/etc/ceph/ceph.conf`:

```
root@syd1:/var/run/ceph# cat /etc/ceph/ceph.conf
[global]
         auth client required = cephx
         auth cluster required = cephx
         auth service required = cephx
         cluster network = 10.0.15.0/24
         fsid = 7cc13f83-4445-473b-b9ce-83056564ce27
         keyring = /etc/pve/priv/$cluster.$name.keyring
         mon allow pool delete = true
         osd journal size = 5120
         osd pool default min size = 2
         osd pool default size = 3
         public network = 10.0.15.0/24
#         admin socket mode = 0775

[osd]
         keyring = /var/lib/ceph/osd/ceph-$id/keyring
         admin socket mode = 0775

[mon.syd3]
         host = syd3
         mon addr = 10.0.15.5:6789
         admin socket mode = 0775

[mon.syd2]
         host = syd2
         mon addr = 10.0.15.4:6789
         admin socket mode = 0775

[mon.syd1]
         host = syd1
         mon addr = 10.0.15.3:6789
         admin socket mode = 0775
```

It seems you need to add `admin socket mode` to each osd and mon daemon you want to monitor. 

My first question - I assume I need to setup telegraf on each OSD node (and set `admin socket mode` for each OSD on each of those nodes), but only need to set it up for one mon daemon in the cluster, correct?

My second question is - is adding the `telegraf` user to the `ceph` group needed? Or is there another way around this? (I don't mind doing it - but just want to document only the needed steps for this in my PR).

My third question - now that I have `sudo` on this node I tested ceph status from the telegraf user context. It failed on reading `/etc/ceph/ceph.conf`:
```
root@syd1:/var/run/ceph# sudo -u telegraf ceph status
2019-03-16 06:28:14.766280 7f89c7654700 -1 Errors while parsing config file!
2019-03-16 06:28:14.766283 7f89c7654700 -1 parse_file: cannot open /etc/ceph/ceph.conf: (13) Permission denied
Error initializing cluster client: PermissionDeniedError('error calling conf_read_file',)
```
In this case - it seems on Proxmox:
```
root@syd1:/etc/ceph# ls -lah
total 16K
drwxr-xr-x  2 root root 4.0K Mar 16 06:18 .
drwxr-xr-x 96 root root 4.0K Mar 16 06:09 ..
-rw-------  1 ceph ceph  159 Mar 14 07:45 ceph.client.admin.keyring
lrwxrwxrwx  1 root root   18 Mar 14 07:43 ceph.conf -> /etc/pve/ceph.conf
-rw-r--r--  1 root root   92 Nov 20 07:29 rbdmap
```
that `ceph.conf` is a symlink to their shared cluster filesystem, and it's owned by root:root.

I assume that will cause issues with Telegraf's Ceph input?

I'm happy to file a PR for the Ceph input

**Comment by victorhooi** [comment] 2019-03-15 19:37
Checking `journalctl -u telegraf`, I now just see:

```
Mar 16 06:34:40 syd1 telegraf[631785]: 2019-03-15T19:34:40Z I! Starting Telegraf 1.10.0
Mar 16 06:34:40 syd1 telegraf[631785]: 2019-03-15T19:34:40Z I! Loaded inputs: cpu mem processes net sysstat disk diskio kernel swap system ceph
Mar 16 06:34:40 syd1 telegraf[631785]: 2019-03-15T19:34:40Z I! Loaded aggregators:
Mar 16 06:34:40 syd1 telegraf[631785]: 2019-03-15T19:34:40Z I! Loaded processors:
Mar 16 06:34:40 syd1 telegraf[631785]: 2019-03-15T19:34:40Z I! Loaded outputs: influxdb
Mar 16 06:34:40 syd1 telegraf[631785]: 2019-03-15T19:34:40Z I! Tags enabled: host=syd1
Mar 16 06:34:40 syd1 telegraf[631785]: 2019-03-15T19:34:40Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"syd1", Flush Interval:10s
Mar 16 06:35:00 syd1 telegraf[631785]: 2019-03-15T19:35:00Z E! [inputs.ceph]: Error in plugin: error executing command: error running ceph status: exit status 1
Mar 16 06:36:00 syd1 telegraf[631785]: 2019-03-15T19:36:00Z E! [inputs.ceph]: Error in plugin: error executing command: error running ceph status: exit status 1
```

So `ceph status` is still an issue.

**Comment by victorhooi** [comment] 2019-03-15 20:13
OK, I was able to trace the issue down to the `telegraf` user not having read permissions to `/etc/ceph/ceph.conf`. 

```
root@syd1:/etc/ceph# sudo -u telegraf ceph status
2019-03-16 06:37:31.558292 7f3ee7ed1700 -1 Errors while parsing config file!
2019-03-16 06:37:31.558295 7f3ee7ed1700 -1 parse_file: cannot open /etc/ceph/ceph.conf: (13) Permission denied
Error initializing cluster client: PermissionDeniedError('error calling conf_read_file',)
```

I was able to fix this, but then it's hitting issues around the Ceph keyring.

However, I then saw this earlier post on the ceph-users mailing list - which says this isn't the correct approach:

**Comment by glinton** [comment] 2019-03-15 20:18
Is `ceph_user` and `ceph_config` not sufficient, you should be able to specify the user's keyring in the config iirc.

**Comment by victorhooi** [comment] 2019-03-15 23:20
Aha - I seem to have managed to fix things
```
root@syd1:/etc/pve/priv# ceph auth get-or-create client.telegraf mgr 'allow *' osd 'allow r' mon 'allow r'
[client.telegraf]
        key = AQBLFoxcLtZLBxAAmCCd8dPmaWg4c2b5oL4Oow==
```
I then wrote this out to `/etc/pve/priv/ceph.client.telegraf.keyring`.
```
root@syd1:/etc/pve/priv# ls -lah
total 4.0K
drwx------ 2 root www-data    0 Mar  7 00:37 .
drwxr-xr-x 2 root www-data    0 Jan  1  1970 ..
-rw------- 1 root www-data 1.7K Mar  7 00:37 authkey.key
-rw------- 1 root www-data 1.6K Mar 14 07:14 authorized_keys
-rw------- 1 root www-data   63 Mar 14 07:45 ceph.client.admin.keyring
-rw------- 1 root www-data   73 Mar 16 08:20 ceph.client.telegraf.keyring
-rw------- 1 root www-data  236 Mar 14 07:45 ceph.mon.keyring
-rw------- 1 root www-data 2.3K Mar 14 07:14 known_hosts
drwx------ 2 root www-data    0 Mar  7 00:38 lock
-rw------- 1 root www-data 3.2K Mar  7 00:37 pve-root-ca.key
-rw------- 1 root www-data    3 Mar 14 07:14 pve-root-ca.srl
```
I confirmed I can then run the three commands mentioned in the Ceph plugin README:
```
root@syd1:/etc/pve/priv# ceph --name client.telegraf status
  cluster:
    id:     7cc13f83-4445-473b-b9ce-83056564ce27
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum syd1,syd2,syd3
    mgr: syd1(active), standbys: syd2, syd3
    osd: 12 osds: 12 up, 12 in

  data:
    pools:   1 pools, 512 pgs
    objects: 943.64k objects, 23.6GiB
    usage:   115GiB used, 2.50TiB / 2.61TiB avail
    pgs:     512 active+clean
root@syd1:/etc/pve/priv# ceph --name client.telegraf df
GLOBAL:
    SIZE        AVAIL       RAW USED     %RAW USED
    2.61TiB     2.50TiB       115GiB          4.31
POOLS:
    NAME          ID     USED        %USED     MAX AVAIL     OBJECTS
    angus-syd     1      23.6GiB      2.84        806GiB      943642
root@syd1:/etc/pve/priv# ceph --name client.telegraf osd pool stats
pool angus-syd id 1
  nothing is going on
```
I then edited `telegraf.conf` to add:
```
#   ## Ceph user to authenticate as
   ceph_user = "client.telegraf"
```
However, after restarting `telegraf` with `systemctl restart telegraf`, the error message is now:
```
Mar 16 10:14:00 syd1 telegraf[658172]: 2019-03-15T23:14:00Z E! [inputs.ceph]: Error in plugin: error executing command: error running ceph status: exit status 13
```

This is odd - since it seems like ceph status already runs fine under client.telegraf? Also, the exit status code has changed from 1 earlier to 13.

**Comment by glinton** [comment] 2019-03-16 00:38
[Here is a linux build](https://29693-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.11.0~05f674eb_linux_amd64.tar.gz) that will give more information when an error happens with ceph. Hopefully it will give us something that will make it easier to debug

**Comment by victorhooi** [comment] 2019-03-16 12:10
I untarred that file, and replaced my system `telegraf` binary. It now says:
```
Mar 16 22:39:00 syd1 telegraf[753458]: 2019-03-16T11:39:00Z E! [inputs.ceph]: Error in plugin: error executing command: error running ceph status: exit status 13: "2019-03-16 22:39:00.437974 7fef888f2700 -1 auth: unable to find a keyring
```
Does telegraf have different logic to how the `ceph` command tries to find keyfiles?

On my Proxmox system, the keyfiles are in `/etc/pve/priv`:
```
root@syd1:/etc/pve/priv# ls -lah /etc/pve/priv
total 4.0K
drwx------ 2 root www-data    0 Mar  7 00:37 .
drwxr-xr-x 2 root www-data    0 Jan  1  1970 ..
-rw------- 1 root www-data 1.7K Mar  7 00:37 authkey.key
-rw------- 1 root www-data 1.6K Mar 14 07:14 authorized_keys
-rw------- 1 root www-data   63 Mar 14 07:45 ceph.client.admin.keyring
-rw------- 1 root www-data   73 Mar 16 08:20 ceph.client.telegraf.keyring
-rw------- 1 root www-data  236 Mar 14 07:45 ceph.mon.keyring
-rw------- 1 root www-data 2.3K Mar 14 07:14 known_hosts
drwx------ 2 root www-data    0 Mar  7 00:38 lock
-rw------- 1 root www-data 3.2K Mar  7 00:37 pve-root-ca.key
-rw------- 1 root www-data    3 Mar 14 07:14 pve-root-ca.srl
```

Also, `/etc/ceph/ceph.conf` is a symlink to `etc/pve/ceph.conf`.

Could `telegraf` be looking for a keyfile in a different place to `ceph`?

**Comment by victorhooi** [comment] 2019-03-20 21:53
@glinton Curious if you had any thoughts on `telegraf` vs `ceph --name client.telegraf status` here? =)

The former doesn't work, the latter does.

I assume maybe they're looking in different places?

**Comment by danielnelson** [comment] 2019-03-21 03:49
You will need to arrange for the `telegraf` user to have access to the keyring.  With your current permissions only the `root `user can read the keyring.
```
-rw------- 1 root www-data   73 Mar 16 08:20 ceph.client.telegraf.keyring
```

I suggest making a copy of `ceph.conf` and `ceph.client.telegraf.keyring` and placing them in the `/etc/telegraf` directory and setting the owner and permissions:
```
chown telegraf:telegraf /etc/telegraf/ceph.conf /etc/telegraf/ceph.client.telegraf.keyring
chmod 600 /etc/telegraf/ceph.conf /etc/telegraf/ceph.client.telegraf.keyring
```

Don't forget to update the plugins `ceph_config` and `/etc/telegraf/ceph.conf` with the new location of the keyring.

**Comment by danielnelson** [comment] 2019-04-23 23:53
@victorhooi Were you able to get this working?

**Comment by styleart** [comment] 2019-05-23 16:50
Well, copying the `ceph.conf` and the telegraf keyring to `/etc/telegraf/` (and also modifying permissions) gives nothing. I still get the same error: 
```
root@ceph1/etc/telegraf# sudo -u telegraf ceph df
2019-05-23 18:15:15.965 7fe5aa613700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-05-23 18:15:15.965 7fe5aa613700 -1 monclient: authenticate NOTE: no keyring found; disabled cephx authentication
```
So, telegraf is still looking for the admin keyring ignoring the configuration in `ceph.conf` and `telegraf.conf` (yes, even after stopping and starting all the services). 

The only way to get cluster stats with telegraf user is to run it with the `--name` argument like in example of @victorhooi - works fine.
```
root@ceph1/# sudo -u telegraf ceph --name client.telegraf df
GLOBAL:
    SIZE       AVAIL      RAW USED     %RAW USED 
    10 TiB     10 TiB       13 GiB          0.12 
POOLS:
    ...
```

**Comment by styleart** [comment] 2019-05-24 10:53
In the comment above I tried it with copying the keyring and ceph.conf to `/etc/telegraf/` directory, setting permissions and all the stuff... Didn't work. 

To summarize my final setup...

Telegraf is in the ceph group:
```
root@ceph1/# groups telegraf 
telegraf : telegraf ceph
```
The ownership of telegraf keyring is set to telegraf user:
```
root@ceph1/# ls -las /etc/ceph/
total 48
 4 drwxr-xr-x   2 ceph     ceph      4096 Mai 24 11:49 .
12 drwxr-xr-x 114 root     root     12288 Mai 23 14:24 ..
 4 -rw-------   1 ceph     ceph       151 Mär 20 15:39 ceph.client.admin.keyring
 4 -rw-r--r--   1 root     root        64 Mai 15 12:27 ceph.client.nagios.keyring
 4 -rw-r-----   1 telegraf telegraf   132 Mai 24 11:48 ceph.client.telegraf.keyring
 4 -rw-r--r--   1 ceph     ceph      1096 Mai 23 17:42 ceph.conf
``` 
The `ceph.conf` is holding the `client.telegraf` and pointing to the keyring:
```
root@ceph1/etc# cat /etc/ceph/ceph.conf |grep telegraf
[client.telegraf]
keyring = /etc/ceph/ceph.client.telegraf.keyring
```
The `telegraf.conf` is also holding the `client.telegraf` user and the ceph config file:
```
[[inputs.ceph]]
  interval = '30s'
  ceph_binary = "/usr/bin/ceph"
  socket_dir = "/var/run/ceph"
  mon_prefix = "ceph-mon"
  osd_prefix = "ceph-osd"
  socket_suffix = "asok"
  ceph_user = "client.telegraf"
  ceph_config = "/etc/ceph/ceph.conf"
  gather_admin_socket_stats = true
  gather_cluster_stats = true
```
Results:
```
root@ceph1/# sudo -u telegraf ceph df
2019-05-24 12:37:00.117 7f18f616b700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory

root@ceph1/# tail /var/log/syslog
2019-05-24T12:37:00.875204+02:00 ceph1 telegraf[672232]: 2019-05-24T10:37:00Z E! [inputs.ceph]: Error in plugin: error executing command: error running ceph df: exit status 13
```
```
root@ceph1/# sudo -u telegraf ceph --name client.telegraf df
GLOBAL:
    SIZE       AVAIL      RAW USED     %RAW USED 
    10 TiB     10 TiB       13 GiB          0.12
```
---
I also added `--name client.telegraf` to the commands in `ceph.go` plugin and built it on my machine. Results same as above without the change, even if telegraf is running the check with `--name client.telegraf` argument. Still ignoring the `client.telegraf` user in `ceph.conf` and trying to find the keyring... 
```
root@ceph1/# tail /var/log/syslog
2019-05-24T12:43:30.875135+02:00 ceph1 telegraf[672232]: 2019-05-24T10:43:30Z E! [inputs.ceph]: Error in plugin: error executing command: error running ceph --name client.telegraf df: exit status 13
```

Any suggestions?

**Comment by danielnelson** [comment] 2019-05-29 00:56
The `ceph_user` option should be setting `--name client.telegraf` already.  Check the permissions of the socket_dir and file, can `telegraf` read the socket?

**Comment by styleart** [comment] 2019-05-29 10:28
@danielnelson sure it can, otherwise I would get the error
```[inputs.ceph]: Error in plugin: failed to find sockets at path '/var/run/ceph': Failed to read socket directory '/var/run/ceph': open /var/run/ceph: permission denied```

We had this error before, but after setting the `admin socket mode = 0775` in `/etc/ceph/ceph.conf` and restarting all ceph services it was gone. Also the group `ceph` has full access to the socket_dir and user `telegraf` is in the `ceph` group.

```
root@ceph1/var/run# ls -las ceph/
total 0
0 drwxr-xr-x  2 ceph ceph  180 Mai 25 13:22 .
0 drwxr-xr-x 30 root root 1120 Mai 13 15:33 ..
0 srwxrwxr-x  1 ceph ceph    0 Mai 25 13:22 ceph-mgr.ceph1.asok
0 srwxrwxr-x  1 ceph ceph    0 Mai 24 15:45 ceph-mon.ceph1.asok
0 srwxrwxr-x  1 ceph ceph    0 Mai 24 15:45 ceph-osd.0.asok
0 srwxrwxr-x  1 ceph ceph    0 Mai 24 15:45 ceph-osd.3.asok
0 srwxrwxr-x  1 ceph ceph    0 Mai 24 15:45 ceph-osd.6.asok
0 srwxrwxr-x  1 ceph ceph    0 Mai 24 15:45 ceph-osd.9.asok
```
```
root@ceph1~# groups telegraf
telegraf : telegraf ceph
```

**Comment by danielnelson** [comment] 2019-05-29 23:01
Can you run it under strace? (may output sensitive info so check before replying)
```
sudo -u telegraf strace ./telegraf --input-filter=ceph --test 2>&1 | grep exec
```

**Comment by styleart** [comment] 2019-06-04 08:26
@danielnelson 

```
root@ceph1~# sudo -u telegraf strace telegraf --input-filter=ceph --test 2>&1 | grep exec
execve("/usr/bin/telegraf", ["telegraf", "--input-filter=ceph", "--test"], 0x7ffe3ea2d400 /* 15 vars */) = 0
2019-06-04T08:19:18Z E! [telegraf] Error running agent: error executing command: error running ceph osd pool stats: exit status 13
```

**Comment by danielnelson** [comment] 2019-06-05 10:05
I forgot to ask you to add the `-f` flag, can you run again?
```
sudo -u telegraf strace -f ./telegraf --input-filter=ceph --test 2>&1 | grep exec
```

**Comment by styleart** [comment] 2019-06-05 15:57
@danielnelson sure, he it is (anonymized IP addresses)

```
root@ceph1-xx-xx~# sudo -u telegraf strace -f telegraf --input-filter=ceph --test 2>&1 | grep exec
execve("/usr/bin/telegraf", ["telegraf", "--input-filter=ceph", "--test"], 0x7ffd90884f48 /* 15 vars */) = 0
[pid 1530531] execve("/usr/bin/getconf", ["/usr/bin/getconf", "CLK_TCK"], 0xc000278300 /* 15 vars */ <unfinished ...>
[pid 1530531] <... execve resumed> )    = 0
[pid 1530543] execve("/usr/bin/ceph", ["/usr/bin/ceph", "--admin-daemon", "/var/run/ceph/ceph-mon.ceph1-xx-"..., "perfcounters_dump"], 0xc000278100 /* 15 vars */ <unfinished ...>
[pid 1530543] <... execve resumed> )    = 0
[pid 1530543] read(6, "group rw,nosuid,nodev,noexec,rel"..., 1024) = 1024
[pid 1530544] execve("/sbin/ldconfig", ["/sbin/ldconfig", "-p"], 0x55d8f24a12b0 /* 15 vars */) = 0
[pid 1530544] execve("/sbin/ldconfig.real", ["/sbin/ldconfig.real", "-p"], 0x5599495f3bd0 /* 16 vars */) = 0
[pid 1530545] execve("/usr/bin/ceph", ["/usr/bin/ceph", "--admin-daemon", "/var/run/ceph/ceph-osd.0.asok", "perf", "dump"], 0xc00017a100 /* 15 vars */ <unfinished ...>
[pid 1530545] <... execve resumed> )    = 0
[pid 1530545] read(6, "group rw,nosuid,nodev,noexec,rel"..., 1024) = 1024
[pid 1530546] execve("/sbin/ldconfig", ["/sbin/ldconfig", "-p"], 0x5607ce572d50 /* 15 vars */ <unfinished ...>
[pid 1530546] <... execve resumed> )    = 0
[pid 1530546] execve("/sbin/ldconfig.real", ["/sbin/ldconfig.real", "-p"], 0x5629c3885bd0 /* 16 vars */) = 0
[pid 1530547] execve("/usr/bin/ceph", ["/usr/bin/ceph", "--admin-daemon", "/var/run/ceph/ceph-osd.3.asok", "perf", "dump"], 0xc0001a2200 /* 15 vars */ <unfinished ...>
[pid 1530547] <... execve resumed> )    = 0
[pid 1530547] read(6, "group rw,nosuid,nodev,noexec,rel"..., 1024) = 1024
[pid 1530548] execve("/sbin/ldconfig", ["/sbin/ldconfig", "-p"], 0x5653439d82b0 /* 15 vars */ <unfinished ...>
[pid 1530548] <... execve resumed> )    = 0
[pid 1530548] execve("/sbin/ldconfig.real", ["/sbin/ldconfig.real", "-p"], 0x55c482a5cbd0 /* 16 vars */) = 0
[pid 1530549] execve("/usr/bin/ceph", ["/usr/bin/ceph", "--admin-daemon", "/var/run/ceph/ceph-osd.6.asok", "perf", "dump"], 0xc00017a280 /* 15 vars */ <unfinished ...>
[pid 1530549] <... execve resumed> )    = 0
[pid 1530549] read(6, "group rw,nosuid,nodev,noexec,rel"..., 1024) = 1024
[pid 1530550] execve("/sbin/ldconfig", ["/sbin/ldconfig", "-p"], 0x564d55b282b0 /* 15 vars */ <unfinished ...>
[pid 1530550] <... execve resumed> )    = 0
[pid 1530550] execve("/sbin/ldconfig.real", ["/sbin/ldconfig.real", "-p"], 0x5617564c7bd0 /* 16 vars */) = 0
[pid 1530551] execve("/usr/bin/ceph", ["/usr/bin/ceph", "--admin-daemon", "/var/run/ceph/ceph-osd.9.asok", "perf", "dump"], 0xc0001a2380 /* 15 vars */ <unfinished ...>
[pid 1530551] <... execve resumed> )    = 0
[pid 1530551] read(6, "group rw,nosuid,nodev,noexec,rel"..., 1024) = 1024
[pid 1530552] execve("/sbin/ldconfig", ["/sbin/ldconfig", "-p"], 0x560b5451c2b0 /* 15 vars */ <unfinished ...>
[pid 1530552] <... execve resumed> )    = 0
[pid 1530552] execve("/sbin/ldconfig.real", ["/sbin/ldconfig.real", "-p"], 0x55abfab33bd0 /* 16 vars */) = 0
[pid 1530555] execve("/usr/bin/ceph", ["/usr/bin/ceph", "--conf", "/etc/ceph/ceph.conf", "--name", "client.telegraf", "--format", "json", "status"], 0xc000278200 /* 15 vars */ <unfinished ...>
[pid 1530555] <... execve resumed> )    = 0
[pid 1530555] read(6, "group rw,nosuid,nodev,noexec,rel"..., 1024) = 1024
[pid 1530556] execve("/sbin/ldconfig", ["/sbin/ldconfig", "-p"], 0x5572efa4cc70 /* 15 vars */ <unfinished ...>
[pid 1530556] <... execve resumed> )    = 0
[pid 1530556] execve("/sbin/ldconfig.real", ["/sbin/ldconfig.real", "-p"], 0x563c19055bd0 /* 16 vars */) = 0
[pid 1530580] execve("/usr/bin/ceph", ["/usr/bin/ceph", "--conf", "/etc/ceph/ceph.conf", "--name", "client.telegraf", "--format", "json", "df"], 0xc0001a2180 /* 15 vars */ <unfinished ...>
[pid 1530580] <... execve resumed> )    = 0
[pid 1530580] read(6, "group rw,nosuid,nodev,noexec,rel"..., 1024) = 1024
[pid 1530581] execve("/sbin/ldconfig", ["/sbin/ldconfig", "-p"], 0x559ab1eadc70 /* 15 vars */ <unfinished ...>
[pid 1530581] <... execve resumed> )    = 0
[pid 1530581] execve("/sbin/ldconfig.real", ["/sbin/ldconfig.real", "-p"], 0x55a11d7d1bd0 /* 16 vars */) = 0
[pid 1530605] execve("/usr/bin/ceph", ["/usr/bin/ceph", "--conf", "/etc/ceph/ceph.conf", "--name", "client.telegraf", "--format", "json", "osd", "pool", "stats"], 0xc0001a2200 /* 15 vars */ <unfinished ...>
[pid 1530605] <... execve resumed> )    = 0
[pid 1530605] read(6, "group rw,nosuid,nodev,noexec,rel"..., 1024) = 1024
[pid 1530606] execve("/sbin/ldconfig", ["/sbin/ldconfig", "-p"], 0x5627d0799f50 /* 15 vars */ <unfinished ...>
[pid 1530606] <... execve resumed> )    = 0
[pid 1530606] execve("/sbin/ldconfig.real", ["/sbin/ldconfig.real", "-p"], 0x55af622a3bd0 /* 16 vars */) = 0
2019-06-05T15:50:03Z E! [telegraf] Error running agent: error executing command: error running ceph osd pool stats: exit status 13
```

**Comment by styleart** [comment] 2020-01-17 16:02
Ok, months later back to the issue. 

- telegraf user is in the `ceph` group. 
- Sockets run in mode 755 as default (`ls -las /var/run/ceph`).

The issue in this case is that the group `ceph` still has no access to the sockets, as well as the telegraf user. 

Quick fix: `cd /var/run/ceph/ && chmod 775 *`. 

As someone said here https://github.com/influxdata/telegraf/issues/1657#issuecomment-256473889, the issue is not with telegraf, but with Ceph itself. It should create sockets by default in mode 775, but it doesn't. 

It has been fixed here https://github.com/ceph/ceph/pull/11684

**Comment by danielnelson** [comment] 2020-01-17 21:17
Thanks for the update @stylart, it sounds like we can close this issue now then.

**Closed by danielnelson** 2020-01-17 21:17 UTC
Labels: need more info
