### ISSUE TITLE
Enable extracting tag values from MQTT topics

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#10049] opened 2021-11-03 04:10 UTC
### Proposal:
Currently, a whole MQTT topic can be stored as a tag. Proposing an enhancement to `inputs.mqtt_consumer` that allows tag values (measurements, fields as well) to be extracted from the MQTT topic letting you store the information provided in the topic in a more meaningful way. This is especially useful when subscribing to topics with single level wildcards. 

### Current behavior:
Need to configure a regex processor to pull tag values from topics.

### Desired behavior:
A setting in the `mqtt_consumer` plugin configuration to determine which part of the topic you may want to assign as measurement, tag, fields. 

Users would be able to configure the Topic: `abc/123/567/foo/bar`

1. Set measurement:
`topic_measurement = "_/_/_/_/measurement"`

2. Extract tag value and designate tag name: 
`topic_tags = "_/_/_/tag-name/_"`

3. Extract field value and designate field name: 
`topic_fields = "_/field-1-name/field-2-name//_"`

Output:
```
bar,tag-name=foo field-1-name=123, field-2-name=567
```

### Use case: 
IoT / MQTT users aren't developers. Having to defer them to writing a Starlark script or other complex processors isn't the user experience we want. This is an important enough aspect of MQTT ingestion that it should be handled at the input plugin in a simple TOML UX since segments (parents/children) are always delimited with "/". 

### Examples:
**Example 1**
Payload: `{ "temp": 23.1, "status": "ok", "alert": false, "load": 432.6}`
Topic: `meter/9174573134579843517855/7/HQ/energy`

Configuration:
```toml
topic_measurement = "_/_/_/_/measurement"
topic_tags = "_/_/_/location/_"
topic_fields = "_/customer_id/reconnect_count/_/_"
```

Expected Output:
```
energy,location=HQ,status=ok,alert=false customer_id=9174573134579843517855,reconnect_count=7i,load=432.6
```

**Example 2**
Payload: `10`
Topic: `things/abc/xyz/0002/temp`

Configuration:
```toml
topics = ["things/+/temp"]
topic_measurement = "measurement/_/_/_/_"
topic_tag = "_/_/_/device_id/_"
topic_field = "_/_/_/_/_"
```

Expect Output:
```
things,device_id=0002 temp=10
```

**Comment by srebhan** [comment] 2021-11-03 10:15
Duplicate of #2070.

**Comment by srebhan** [comment] 2021-11-03 10:16
Related to #9995.

**Comment by sjwang90** [comment] 2021-11-03 17:54
@srebhan @samhld Everything in the issue makes sense? I wanted to simplify #2070 but make sure everything is still capture.

**Comment by samhld** [comment] 2021-11-10 14:46
@sjwang90 LGTM.  I assume the second `topic_tags` in 3rd bullet under Desired Behavior was meant to be `topic_fields`?

**Comment by sjwang90** [comment] 2021-11-10 16:57
Oops, I updated. @samhld and @srebhan Want to double check that it's common enough that your topics would names and values that you would want to set as your measurements and fields? The initial request was only for tags and I don't want to include extra config options if it's not necessary.

**Comment by samhld** [comment] 2021-11-10 17:28
@sjwang90 I think it's necessary to be flexible so allowing to parse out any Line Protocol element would be good.

Since there can only be one Measurement per parsed line, it would also probably be good to call out that this functionality would overwrite any other Measurement value that may already have (unlikely scenario but still worth mentioning probably, especially if the data source emits Line Protocol directly).

**Comment by srebhan** [comment] 2021-11-11 08:42
I agree with @samhld. We should be able to extract the information coming from the topic and sort it into measurement names, tags and fields.

**Comment by MyaLongmire** [comment] 2021-12-19 23:39
[This](https://github.com/influxdata/telegraf/pull/9995) pr allows the extracting of topics into measurements, tags, and fields. Closing this issue :)

**Closed by MyaLongmire** 2021-12-19 23:39 UTC
Labels: feature request, area/iot, area/mqtt
