### ISSUE TITLE
Plugin "mem" - Values for "available_percent" and "used_percent" not matching

### ISSUE THREAD

**Issue by h4rdL1nk** [influxdata/telegraf#5303] opened 2019-01-17 07:47 UTC
## Read metrics about memory usage
    [[inputs.mem]]

### System info:

Operating system: 
    NAME="Red Hat Enterprise Linux Server"
    VERSION="7.6 (Maipo)"
    Kernel: 3.10.0-957.el7.x86_64

Docker version: 1.13.1
Telegraf: 1.9.1 ( docker alpine container )

### Steps to reproduce:

1. Run telegraf
```
docker run -d --privileged --restart=unless-stopped --log-driver=json-file --log-opt max-size=100m --log-opt max-file=1 -v /var/run/utmp:/var/run/utmp:ro -v /var/dockershared/telegraf/conf:/etc/telegraf:ro -v /sys:/rootfs/sys:ro -v /proc:/rootfs/proc:ro  registry.own/infra/telegraf:1.9.1-alpine
```

2. Check grafana host memory metrics

3. Values for "available_percent" and "used_percent" ( mem input ), sum values higher than 100%

### Expected behavior:

Values for "available_percent" and "used_percent" should sum 100%

### Actual behavior:

Values for "available_percent" and "used_percent" ( mem input ), sum values higher than 100%

### Additional info:

Analyzing the memory metrics calculating method in plugins/inputs/system/ps.go

```
	package system

	import (
		"os"
		"path/filepath"
		"strings"

		"github.com/influxdata/telegraf"
		"github.com/influxdata/telegraf/internal"

		"github.com/shirou/gopsutil/cpu"
		"github.com/shirou/gopsutil/disk"
		"github.com/shirou/gopsutil/host"
		"github.com/shirou/gopsutil/mem"
		"github.com/shirou/gopsutil/net"
	)
```

These are calculated through library https://github.com/shirou/gopsutil/blob/master/mem/mem_linux.go

```
	ret.Used = ret.Total - ret.Free - ret.Buffers - ret.Cached
	ret.UsedPercent = float64(ret.Used) / float64(ret.Total) * 100.0
```

For systems with "MemAvailable" present in "/proc/vmstat", this value is used, instead of being calculated, like "Used" memory value:

```
        switch key {
		case "MemTotal":
			ret.Total = t * 1024
		case "MemFree":
			ret.Free = t * 1024
		case "MemAvailable":
			memavail = true
			ret.Available = t * 1024

       ..........

        if !memavail {
		ret.Available = ret.Free + ret.Buffers + ret.Cached
	}
	ret.Used = ret.Total - ret.Free - ret.Buffers - ret.Cached
	ret.UsedPercent = float64(ret.Used) / float64(ret.Total) * 100.0
```

Calculating values in system:

```
# egrep "MemTotal|MemFree|Buffers|Cached" /proc/meminfo 
MemTotal:       527554164 kB
MemFree:        21906076 kB
Buffers:            7572 kB
Cached:         324482292 kB
SwapCached:            0 kB

### Used memory calculation
$ echo "Used%: $(((527554164-21906076-7572-324482292)*100/527554164))"
Used%: 34

### Available memor calculation

$ egrep "MemTotal|MemFree|Buffers|Cached|Avail" /proc/meminfo 
MemTotal:       527554164 kB
MemFree:        21791844 kB
MemAvailable:   415559452 kB
Buffers:            7572 kB
Cached:         324528116 kB
SwapCached:            0 kB

# Calculated value ( if MemAvailable was not existent )
[root@ESJC-RMNB-MN04P ~]# echo "Used%: $(((21906076+7572+324482292)*100/527554164))"
Used%: 65

# Using MemAvailable ( existent )
$ echo "Used%: $(((415559452)*100/527554164))"
Used%: 78
```

Valued would match if MemAvailable was always calculated, but not if "MemAvailable" system value is used.

This is a "bug" in libraries used for calculating system usage values.

**Comment by glinton** [comment] 2019-01-17 16:23
Duplicate of #5141

**Closed by glinton** 2019-01-17 16:23 UTC
Labels: duplicate
