### ISSUE TITLE
table `inputs.xxx.tags' is in conflict with normal table in line xx

### ISSUE THREAD

**Issue by xin053** [influxdata/telegraf#5021] opened 2018-11-22 06:46 UTC
### System info:

[Include Telegraf version, operating system name, and other relevant details]

- telegraf version: 1.9.0
- operating system: win10 1809 && centos 6.9

### Steps to reproduce:

```toml
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  tags = {project = "test1"}

[[inputs.net_response]]
  protocol = "tcp"
  address = "127.0.0.1:1080"
  timeout = "3s"
  [inputs.net_response.tags]  # line 73
    project = "test2"

[[inputs.net_response]]
  protocol = "tcp"
  address = "127.0.0.1:1081"
  timeout = "3s"
  [inputs.net_response.tags]   # line 80
    project = "test3"
```
```shell
telegraf.exe --config telegraf.conf --test
```

got error:

```
E! [telegraf] Error running agent: Error parsing telegraf.conf, toml: line 80: table `inputs.net_response.tags' is in conflict with normal table in line 73
```

but,

```toml
[[inputs.net_response]]
  protocol = "tcp"
  address = "127.0.0.1:1080"
  timeout = "3s"
  [inputs.net_response.tags]
    project = "test1"

[[inputs.net_response]]
  protocol = "tcp"
  address = "127.0.0.1:1081"
  timeout = "3s"
  [inputs.net_response.tags]
    project = "test2"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  tags = {project = "test1"}
```

or 

```toml
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  [inputs.cpu.tags]
    project = "test"

[[inputs.net_response]]
  protocol = "tcp"
  address = "127.0.0.1:1080"
  timeout = "3s"
  [inputs.net_response.tags]
    project = "test1"

[[inputs.net_response]]
  protocol = "tcp"
  address = "127.0.0.1:1081"
  timeout = "3s"
  [inputs.net_response.tags]
    project = "test2"
```

will work fine.

**Comment by glinton** [comment] 2018-11-27 17:03
Thanks for this, I believe the issue is that the toml parsing library we are using has issues with inline tables. Your last example works fine because you define the cpu input's tags as an explicit table.

I'm going to close this in favor of #4098

**Closed by glinton** 2018-11-27 17:03 UTC
