### ISSUE TITLE
Allow password of the secret store to be entered on the command line when making an entry into  [[secretstores.jose]]

### ISSUE THREAD

**Issue by jackbenimble999** [influxdata/telegraf#12654] opened 2023-02-08 20:37 UTC
### Use Case

This will be used when installing telegraf secrets from a command line in an installer:

This would allow the password for the secretstores.jose  to be set from a command line as follows:

telegraf --config telegraf_mqtt_to_influxdb.conf secrets set jose_secrets my_secret_password xxxxxxx --secret-store-password yyyyy

Thanks!

### Expected behavior

1. telegraf --config telegraf_mqtt_to_influxdb.conf secrets set jose_secrets my_secret_password xxxxxxx --secret-store-password yyyyy
2. password for the secrets store will be by the parameter from the command line on the console and must enter by hand. 

### Actual behavior

1. telegraf --config telegraf_mqtt_to_influxdb.conf secrets set jose_secrets my_secret_password xxxxxxx --secret-store-password yyyyy
2. user is prompted for the secret store password

### Additional info

Here's is a relevant configuration file: 

  [[secretstores.jose]]
  id = "jose_secrets"
  path = "my_secrets"
  
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]

  ## Topics that will be subscribed to.
  topics = [
 	"influxtopic/#",
  ]

  qos = 2
  max_undelivered_messages = 1000
  persistent_session = true
  client_id = "InfluxDataStandalone"

  username = "admin"
  password = "@{josesecrets:my_secret_password}"
  data_format = "influx"

[[outputs.influxdb_v2]]

  urls = ["http://127.0.0.1:8086"]
  token = "@{jose_secrets:my_secret_token}"
  organization = "MYORG"
  bucket = "events"

**Comment by srebhan** [comment] 2023-02-09 10:17
As the function you request should work for all secret-stores, I'm closing this as duplicate of #12651.

**Closed by srebhan** 2023-02-09 10:17 UTC
Labels: feature request
