### ISSUE TITLE
can not find docker metrics in influxdb, anyone can help?

### ISSUE THREAD

**Issue by asdfsx** [influxdata/telegraf#645] opened 2016-02-04 04:51 UTC
I start telegraf with the following config
```
$ more /etc/telegraf/telegraf.d/docker.conf
[[inputs.docker]]
  # Docker Endpoint
  #   To use TCP, set endpoint = "tcp://[ip]:[port]"
  #   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"
  # Only collect metrics for these containers, collect all if empty
  container_names = []
```

and start telegraf by following command:
```
/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d  
```

but can not find any measurements about docker in influxdb:
```
> show measurements;
name: measurements
------------------
name
cpu
disk
diskio
mem
swap
system
```
actually, I can see docker datas collected by telegraf
```
$/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d  -input-filter docker -test
* Plugin: docker, Collection 1
......
> docker_cpu,com.docker.compose.config-hash=2db93f17fb0fdbb2b3be408209d18ac7eb9f44d787af2df58b6f6601771763cf,com.docker.compose.container-number=1,com.docker.compose.oneoff=False,com.docker.compose.project=grafana,com.docker.compose.service=grafana,com.docker.compose.version=1.5.1,cont_id=528cfa640ba2863df3febd0cd28b173527599b8c2d81a26c6965fc3b13b0ea2d,cont_image=grafana/grafana,cont_name=grafana_grafana_1,cpu=cpu1 usage_total=8040078470i 1454561313911620608
......
```

**Comment by asdfsx** [comment] 2016-02-04 06:44
I finally fix this problem~~~~

**Comment by sparrc** [comment] 2016-02-04 06:45
@asdfsx what was the issue/solution?

**Comment by asdfsx** [comment] 2016-02-04 06:51
@sparrc nothing but restart telegraf several times, then it appeared in influxdb......but I think there is still some problems there.
Right now I'm trying to use grafana to display the metrics, but I can only see one point on the graph, not a line.
![caf93ae9-9195-460e-897e-5e75d7af2983](https://cloud.githubusercontent.com/assets/2292716/12807998/a9a3bccc-cb4e-11e5-8d83-16b78cb0f77e.png)
I'm confused by this.....

**Comment by asdfsx** [comment] 2016-02-04 08:30
It's so strange that, when I start telegraf by exec the command:
```
/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d -debug 
```
I can get docker data in influxdb.
Then I create a graph in grafana, by using sql like below
```
SELECT mean("usage_total") FROM "docker_cpu" WHERE "host" = 'mesos36' AND $timeFilter GROUP BY time($interval) fill(null)
```
I get a graph like below
![b73ccc6d-d1b7-415a-932b-83f6e883a399](https://cloud.githubusercontent.com/assets/2292716/12809550/f2594066-cb5a-11e5-8cc1-67d96e3db2a5.png)
It seems docker_cpu.usage_total is continue growing~
Seems not right.

And when I start telegraf by using `systemctl start telegraf`, it seems nothing about docker send to the influxdb~~~

```
SELECT mean(usage_total) FROM docker_cpu WHERE host = 'mesos36' AND time > now() - 1h GROUP BY time(5m)

docker_cpu
time	mean
2016-02-04T07:25:00Z	
2016-02-04T07:30:00Z	
2016-02-04T07:35:00Z	
2016-02-04T07:40:00Z	9535640409061.729
2016-02-04T07:45:00Z	
2016-02-04T07:50:00Z	
2016-02-04T07:55:00Z	9541001545054.232
2016-02-04T08:00:00Z	9542674282644.1
2016-02-04T08:05:00Z	9544248412986.191
2016-02-04T08:10:00Z	
2016-02-04T08:15:00Z	
2016-02-04T08:20:00Z	
2016-02-04T08:25:00Z

```

**Comment by sparrc** [comment] 2016-02-04 16:26
might be a permissions issue, try

```
sudo -u telegraf /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d -debug 
```

The upward slope is normal. Docker's CPU "usage" metric is actually just a counter of CPU ticks used.

**Comment by asdfsx** [comment] 2016-02-05 08:55
I think you are right!
I just notice that the telegraf is running under `telegraf` account.
So I modify the `/etc/systemd/system/telegraf.service`
```
[Service]
EnvironmentFile=-/etc/default/telegraf
#User=telegraf
User=root
ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d ${TELEGRAF_OPTS}
Restart=on-failure
KillMode=process
```
You can see the telegraf was started by user `telegraf` before
And now I can see the new data!

BTW. You said that `Docker's CPU "usage" metric is actually just a counter of CPU ticks used.`
Does that mean I don't need to use `mean` function?
Just query data like this:
```
SELECT "usage_total" FROM "docker_cpu" WHERE "host" = 'mesos36'
```

**Comment by sparrc** [comment] 2016-02-05 16:03
yes, that query would be fine

**Comment by asdfsx** [comment] 2016-02-15 05:27
@sparrc Sorry to bother you again! In telegraf I use `SELECT usage_total FROM telegraf..docker_cpu WHERE tmpltime() AND host = 'mesos36'` and get the curve
![8f7378bc-e293-4d9b-b4c7-ac2a1c28e171](https://cloud.githubusercontent.com/assets/2292716/13040450/36e6a54a-d3e7-11e5-8700-0802e8a8ee73.png)
But how to get the curve in grafana?
I use `SELECT "usage_total" FROM "docker_cpu" WHERE "host" = 'mesos36' AND $timeFilter`,
but the curve is like this
![0efd9fff-e1ea-4266-9d55-c74ac19cb12a](https://cloud.githubusercontent.com/assets/2292716/13040485/ba0bc018-d3e7-11e5-90e8-a6eaf4f68dbe.png)

**Comment by adithyabenny** [comment] 2016-02-18 23:14
```
sudo su telegraf -c '/usr/bin/telegraf -config telegraf.conf -test -filter docker'
```
works fine. However, the service fails to send the docker metrics and the log fills with multiple instances of
> Error getting docker stats: io: read/write on closed pipe

The default permission on the unix socket is 660 (UID:`root`, GID:`docker`), and I've added user `telegraf` to the `docker` group as well. Any idea what's going wrong?

**Comment by zstyblik** [comment] 2016-02-23 08:58
@sparrc I'm seeing the same issue with v0.10.3-1:

```
Feb 23 09:42:21 dev112-12 docker[879]: 2016/02/23 08:42:21 Error getting docker stats: io: read/write on closed pipe
Feb 23 09:42:25 dev112-12 docker[879]: 2016/02/23 08:42:25 Error getting docker stats: read unix @->/var/run/docker.sock: i/o timeout
Feb 23 09:42:25 dev112-12 docker[879]: 2016/02/23 08:42:25 Error getting docker stats: read unix @->/var/run/docker.sock: i/o timeout
```

However, % docker ps; works just fine.

**Comment by zstyblik** [comment] 2016-02-23 09:07
I think this is most likely related to Docker Version as I'm not seeing it at hosts with `Docker version 1.8.3, build f4bf5c7`, but I'm seeing it at `Docker version 1.9.1, build 4419fdb-dirty`.

**Comment by zstyblik** [comment] 2016-02-23 10:36
I've written small app which is scaled down plugin from Telegraf and I'm getting the same error/seeing the same issue even at Host with Docker v1.8.3. However, I can see "requests" being made in logs:

```
Feb 23 11:27:30 builder docker[10341]: time="2016-02-23T11:27:30.054869742+01:00" level=info msg="GET /containers/json"
Feb 23 11:27:30 builder docker[10341]: time="2016-02-23T11:27:30.056860514+01:00" level=info msg="GET /containers/6b864d4d17e370abeff82dc0bb6553905f161fc2ec3b8b2e5998ee9bd637f166/stats?stream=false"
Feb 23 11:27:30 builder docker[10341]: time="2016-02-23T11:27:30.057260630+01:00" level=info msg="GET /containers/616487a45616594a2ca671bd0a6f5691cd71fc2c7eee7dfd85cd6f4d6949e0f1/stats?stream=false"
Feb 23 11:27:30 builder docker[10341]: time="2016-02-23T11:27:30.057576478+01:00" level=info msg="GET /containers/6242042c2f252ab5225f0173090cf37dedda8c18cf2de5f28ed52ce57c22d69c/stats?stream=false"
Feb 23 11:27:30 builder docker[10341]: time="2016-02-23T11:27:30.058421662+01:00" level=info msg="GET /containers/c618e64f04f5d9920119b70477d38d76b4761a1c2a8a92ce704e024d231c4dd1/stats?stream=false"
```

Origin of the message is https://github.com/influxdata/telegraf/blob/master/plugins/inputs/docker/docker.go#L119

I have no idea how to fix this issue, though. I have found no way to increase timeout value or anything related to such setting. It's possible, though, I haven't dug deep enough.

**Comment by tripledes** [comment] 2016-02-23 11:01
@zstyblik the docker plugin has a hardcoded timeout of 5s, https://github.com/influxdata/telegraf/blob/master/plugins/inputs/docker/docker.go#L108-L114 which I guess should be more than enough.

I think that should be a configuration setting, but that's a topic for another discussion.

**Comment by zstyblik** [comment] 2016-02-23 11:44
@tripledes unfortunately, this setting isn't related to the issue.

**Comment by tripledes** [comment] 2016-02-23 12:15
@zstyblik obviously, a closed pipe has nothing to do with a timeout, but you suggested to increase the timeout and I just provided information for regarding it being hardcoded :grey_question:

**Comment by tripledes** [comment] 2016-02-23 16:59
Seems like the closed pipe is a side effect of the timeout over docker socket. Looks to me like it might be some synchronisation issue in dockerClient, but just a guess.

On the other hand, I've been looking how `docker stats` works because it doesn't fail, or at least it doesn't report any issue. The difference is that they use https://github.com/docker/engine-api as a client library. If I get the time I'll try to do a POC just to see if I can reproduce the issue with engine-api.

**Comment by tripledes** [comment] 2016-02-24 14:14
@sparrc should we keep this opened ? As the issue can be reproduced, I believe it should be opened until a fix is found.

**Comment by sparrc** [comment] 2016-02-24 16:03
yep, sure

**Comment by tripledes** [comment] 2016-02-25 16:26
First attempt to switch to Docker's engine-api, if anyone is willing to test it, it's here:

https://github.com/zooplus/telegraf/tree/docker_engine_api

Besides having better compatibility I think one of the advantages of using engine-api is that they use context for all request so they can handle failure better.

I'd be very glad to have some feedback, I tried to keep the output as it was before but the following items would need some love:

* Better error handling (probably using a shared error channel amongst all goroutines)
* Unit tests

And whether possible, I'd like to make the plugin a bit more flexible, using jsonflattener? So we don't need to specify all the metrics upfront. But I guess this could be left for follow-ups.

@sparrc what are your thoughts about the change? I think it could also be done with Go's std lib, but would require a bigger effort to have the same functionalities (context, api version compatibilities, ...).

**Comment by sparrc** [comment] 2016-02-26 11:09
@tripledes I don't have time to test but this sounds fine with me.

There is also a PR up for improving some of the docker metrics: https://github.com/influxdata/telegraf/pull/754, how does that fit in?

**Comment by tripledes** [comment] 2016-02-26 11:31
@sparrc I currently have an instance of Telegraf with my changes running on our test env, no issues for now, just some blkio names that I need to check...other than that it's running fine, still some feedback anyone involved on this issue would be very much appreciated :)

Regarding #754, I just had a quick look and I don't think it'd be an issue, I reapply my changes on top of it once you get it merged.

**Comment by asdfsx** [comment] 2016-02-29 06:13
@tripledes if you make any change to the telegraf, I'd love to try it

**Comment by tripledes** [comment] 2016-02-29 08:12
@asdfsx here: https://github.com/zooplus/telegraf/tree/docker_engine_api you'd need to compile it yourself. I could provide a compiled binary if needed.

**Comment by asdfsx** [comment] 2016-03-01 11:26
@tripledes I just compile it on ubuntu, and run it via the following command
`sudo /home/ubuntu/go/bin/telegraf  -config /home/ubuntu/telegraf/telegraf.conf -debug -test -filter docker  `
It seems ok right now.

**Comment by tripledes** [comment] 2016-03-01 13:27
@asdfsx thanks! Just let us know whether you find any issue so it can be fixed before submitting a PR.

**Comment by sporokh** [comment] 2016-03-14 10:46
any changes considering this issue?

**Comment by tripledes** [comment] 2016-03-15 12:28
@sporokh I understand you're also hitting the issue, right? I'd like to have a PR ready by the end of the week...although cannot really promise, little bit short on time this week, but I'll try.

**Comment by sporokh** [comment] 2016-03-15 12:42
@tripledes Thanks a lot Sergio!
We have the same issue on our staging server, the metrics being collected but I consistently receive this error in my logs.
```
2016/02/23 08:42:21 Error getting docker stats: io: read/write on closed pipe
```

**Comment by sparrc** [comment] 2016-03-30 16:39
@tripledes any possibilities of a PR by the end of this week?

**Comment by tripledes** [comment] 2016-03-31 10:07
@sparrc sorry, little short on time lately, I'll try over the weekend. In case I don't manage to get the time I'll ping u back.

**Comment by tripledes** [comment] 2016-04-02 22:40
@sparrc Just finished modifying the input, haven't done anything on the tests yet and just run a manual test, although looking promising.

I'll get to the tests tomorrow in the meantime anyone willing to test ?

https://github.com/tripledes/telegraf/tree/engine-api

Feedback welcome :+1:

**Comment by sparrc** [comment] 2016-04-06 18:08
thank you @tripledes, this has worked well for me

**Closed** 2016-04-06 18:08 UTC
Labels: bug

**Comment by tripledes** [comment] 2016-04-06 21:59
@sparrc glad to hear! I'd like to have a better look to the input plugin whenever I get a bit of time (quite busy lately at work), as I think it should be checking for API version and also to have some kind of integration tests against the supported docker api versions. Just some ideas.

**Comment by ForzaGreen** [comment] 2017-12-04 15:38
Check the syslogs (`tail -f /var/log/syslog`). If the error is 
```
Error in plugin [inputs.docker]: Got permission denied while trying to connect to the Docker daemon...
``` 
then you have to add `telegraf` user to `docker` group, as explained [here](https://docs.docker.com/engine/installation/linux/linux-postinstall/#manage-docker-as-a-non-root-user):
```
$ sudo usermod -aG docker telegraf
```

**Comment by remiteeple** [comment] 2020-09-09 03:01
To anyone looking for a solution on ARM based architecture...
 
As root open the cmdline.txt file...
`$ sudo nano /boot/firmware/cmdline.txt`

Add the following to the end of the file...
`cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`

Reboot the system...
`$ sudo reboot`

Verify that the changes have worked!
`$ docker stats` (memory values should be non-zero)

Hope this helps.

**Comment by Mrx381** [comment] 2022-01-03 10:12
Try to Run this command  sudo chmod 666 /var/run.docker.sock.
