### ISSUE TITLE
Telegraf repeatedly panics

### ISSUE THREAD

**Issue by F1ERRO** [influxdata/telegraf#2344] opened 2017-01-31 23:27 UTC
## Directions

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb).

Before opening an issue, search for similar bug reports or feature requests on GitHub Issues.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

## Bug report
Telegraf is continually crashing

### Relevant telegraf.conf:
https://gist.github.com/F1ERRO/3746486081dddd52aff14fb4bcc8cf67

### System info:
Running telegraf in docker
```Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x654edb]
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: goroutine 120 [running]:
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: panic(0xf2a2e0, 0xc42000c070)
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: github.com/influxdata/influxdb/client/v2.(*client).Write(0xc420012180, 0x18fd660, 0xc42066d8c0, 0x0, 0x0)
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]:         /home/ubuntu/telegraf-build/src/github.com/influxdata/influxdb/client/v2/client.go:354 +0xfb
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: github.com/influxdata/telegraf/plugins/outputs/influxdb.(*InfluxDB).Write(0xc42000a700, 0xc42066b000, 0x7b, 0x7b, 0xc42001ee58, 0x6b3911
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]:         /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/outputs/influxdb/influxdb.go:202 +0x27b
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: github.com/influxdata/telegraf/internal/models.(*RunningOutput).write(0xc420190a00, 0xc42066b000, 0x7b, 0x7b, 0x7b, 0x30)
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]:         /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:170 +0xa1
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: github.com/influxdata/telegraf/internal/models.(*RunningOutput).Write(0xc420190a00, 0x11562e0, 0xc420686d00)
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]:         /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/internal/models/running_output.go:154 +0x49c
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: github.com/influxdata/telegraf/agent.(*Agent).flush.func1(0xc420686d00, 0xc420190a00)
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]:         /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:232 +0x68
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]: created by github.com/influxdata/telegraf/agent.(*Agent).flush
Jan 31 23:11:30 ip-172-31-8-38.ec2.internal docker[3176]:         /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/agent/agent.go:237 +0xb4```
```

[Include Telegraf version, operating system name, and other relevant details]
running latest telegraf docker image on coreOS

### Steps to reproduce:
1. Run docker run --rm --name telegraf -p 8125:8125/udp -v /home/core/tele.conf:/etc/telegraf/telegraf.conf:ro --env-file /etc/profile.d/vars -e HOSTNAME=${COREOS_PRIVATE_IPV4} -v /var/run/docker.sock:/var/run/docker.sock telegraf

2. ...

### Expected behavior:
Starts up and runs without crashing

### Actual behavior:
Starts up then crashes frequently

**Comment by sparrc** [comment] 2017-02-01 00:00
thanks for the report, this is a dupe of #2317

**Closed by sparrc** 2017-02-01 00:00 UTC
