### ISSUE TITLE
Kafka input plugin (consumer) panic while rolling restarting Kafka cluster

### ISSUE THREAD

**Issue by adrianlop** [influxdata/telegraf#1770] opened 2016-09-15 09:03 UTC
### Relevant telegraf.conf:

[[inputs.kafka_consumer]]
  topics = ["telegraf"]
  zookeeper_peers = ["zookeeper.com:2181"]
  zookeeper_chroot = ""
  consumer_group = "telegraf_metrics_consumers"
  offset = "oldest"
  metric_buffer = 10000
  data_format = "influx"

### System info:
Ubuntu 14.04 server LTS
Telegraf 1.0.0-1
Kafka 0.10.0.1

### Steps to reproduce:

1. Run telegraf using kafka input plugin (kafka consumer)
2. Restart Kafka cluster (rolling restart)
3. Telegraf will panic with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5a48d6]

goroutine 35 [running]:
panic(0x12cefe0, 0xc82000c090)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/influxdata/telegraf/plugins/inputs/kafka_consumer.(*Kafka).receiver(0xc82019c0c0)
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/kafka_consumer/kafka_consumer.go:131 +0x276
created by github.com/influxdata/telegraf/plugins/inputs/kafka_consumer.(*Kafka).Start
        /home/ubuntu/telegraf-build/src/github.com/influxdata/telegraf/plugins/inputs/kafka_consumer/kafka_consumer.go:117 +0x232
```

It only happens with the consumer plugin.
I have several telegraf agents running with kafka output plugin (kafka producers) and the aren't affected by this bug, they continue producing metrics to kafka without problems.

**Comment by sparrc** [comment] 2016-09-15 09:21
thanks for the report, but it's a dupe of #1764

**Closed by sparrc** 2016-09-15 09:21 UTC

**Comment by adrianlop** [comment] 2016-09-15 09:36
oops sorry, thanks :+1: good to know it's already fixed in master
