### ISSUE TITLE
IPMI sensor plugin times out

### ISSUE THREAD

**Issue by m4ce** [influxdata/telegraf#2817] opened 2017-05-16 13:00 UTC
We should be able to specify a timeout for the ipmi_sensor input plugin.

```
2017-05-16T12:55:05Z E! Error in plugin [inputs.ipmi_sensor]: failed to run command /usr/bin/ipmitool sdr: Command timed out. -
```

**Comment by danielnelson** [comment] 2017-05-18 21:16
Turns out this is a duplicate of #1565.

**Closed by danielnelson** 2017-05-18 21:16 UTC
