### ISSUE TITLE
[enhancement]  1.5rc2 How to grab all SMART values with SMART plugin?

### ISSUE THREAD

**Issue by evanrich** [influxdata/telegraf#3595] opened 2017-12-16 03:40 UTC
Using 1.5.0 RC2 (freebsd)
reviewing both the output of the plugin and it's code, it appears that it only picks up a handful of metrics.  I'm not fluent in Go, so I can't be of much help, but would it be possible to grab other useful basic info?   It's a step in the right direction, but It should grab common SMART statuses, like:

Power on hours.
load cycles
wear leveling count
etc.

These should be standard smart values.   I took a look at the read me, but it seems that no option exists to grab ALL smart values.

**Comment by danielnelson** [comment] 2017-12-19 05:11
These should be captured as part of the `smart_attribute` measurement, so it sounds like a bug.  Can you add the output of the following command, changing your device file:
```
/usr/sbin/smartctl --info --health --attributes --tolerance=verypermissive -n standby --format=brief /dev/sda
```

**Comment by danielnelson** [comment] 2018-01-04 21:50
Closing due to lack of info.

**Closed by danielnelson** 2018-01-04 21:50 UTC
Labels: bug, need more info

**Comment by Midori-ch** [comment] 2018-01-05 02:24
My system got similar issue. Telegraf only create and gather information with "exit_status".
# System info: 
CentOS 7.3 (Kernel 3.10) / influxDB 1.4.2 / telegraf 1.5 / smartctl 6.2
Xeon D-1541 @ 2.10GHz / 128G ram
# Steps to reproduce:
1. Make sure smartctl get disk information by command "smartctl --info --health --attributes --format=brief /dev/sdh". 
2. "systemctl start telegraf"
3. Check information from grafana.
# Expected behavior:
Get smart information like (CRC error, temperature...)
# Actual behavior:
Only "exit_status" can find in fieldkey. And one thing that I notice when I execute "telegraf -config /etc/telegraf/telegraf.conf -input-filter smart -debug" will start create and gather metrics normally. (health_ok, temp_c,udma_crc_errors...) InfluxDB will not receive data after left debug mode. 

[smartctl-info.txt](https://github.com/influxdata/telegraf/files/1602961/smartctl-info.txt)
[telegraf.log](https://github.com/influxdata/telegraf/files/1605343/telegraf.log)

**Comment by danielnelson** [comment] 2018-01-05 02:32
Am I understanding correctly that it is working with `--debug` but not without?

**Comment by Midori-ch** [comment] 2018-01-05 06:23
Yes, without --debug the metrics like (temp_c, udma_crc_errors,read/seek error...) will stop receive data immediately except "exit_status".

**Comment by danielnelson** [comment] 2018-01-05 19:09
I doubt this is caused by the `--debug` flag, when you run it without this flag are you also running it as a service?  If this is the case it is probably a permissions issue, perhaps you need to configure sudo for the Telegraf user?

**Comment by Midori-ch** [comment] 2018-01-08 04:02
At the beginning telegraf is running as a service without --debug flag.  --debug flag is when I found after 2 hours the influxDB still empty except "exit_status".  This incident might not a permissions issue since it is a test environment every steps by using root.

**Comment by danielnelson** [comment] 2018-01-08 19:27
@Midori-ch I'm not sure then, it doesn't look like `--debug` would have any effect on this plugin.  The exit status in your log above is from the ceph input.  Can you try to narrow it down by testing with only the smart plugin and a file output?

**Comment by Midori-ch** [comment] 2018-01-11 06:59
Disable ceph plugin but no luck. After re-install system and package, everything just looks fine. I can't reproduce this incident anymore. I will provide new information if this incident happen again. Sorry to bother and thank you for your help.

**Comment by danielnelson** [comment] 2018-01-11 20:35
@Midori-ch Strange, yeah let me know if the issue returns.
