### ISSUE TITLE
mongodb replica set lag awalys 0

### ISSUE THREAD

**Issue by im-vincent** [influxdata/telegraf#2110] opened 2016-12-01 05:24 UTC
## Bug report
mongodb replica set lag awalys 0

### System info:

CentOS Linux release 7.2.1511 (Core)  telegraf 1.1.1

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:
lag time **int** second
### Actual behavior:
lag time awalys 0
### Additional info:

[Include gist of relevant config, logs, etc.]

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by sparrc** [comment] 2016-12-01 08:51
dupe of #1449

**Closed by sparrc** 2016-12-01 08:51 UTC
