### ISSUE TITLE
All plugins should have timeout and retry options

### ISSUE THREAD

**Issue by seanlook** [influxdata/telegraf#598] opened 2016-01-28 03:47 UTC
I see some telegraf plugins have implemented their own check timeout options.  I think all telelgraf agent should have `timeout` and `retries` options. I do not find any docs about that here.

This is what I encountered:
I use telegraf to gather MySQL metrics ( running in another machine). Because of network traffic problem, my telegraf monitor machine can't connect to 3306 . So I saw telegraf stucked for 2 minutes to do nothing. In this 2mins I lost many other key metrics to analyze what caused the stuck, because no timeout for this check .

**Comment by sparrc** [comment] 2016-01-28 06:01
dupe of #457

**Closed by sparrc** 2016-01-28 06:01 UTC
