### ISSUE TITLE
Telegraf breaks after adding conntrack plugin

### ISSUE THREAD

**Issue by realkarmakun** [influxdata/telegraf#12666] opened 2023-02-13 16:09 UTC
### Relevant telegraf.conf
https://gist.github.com/realkarmakun/f0fa9ef886a0b6eb38b185eb6e75e46c

### Logs from Telegraf

```text
2023-02-13T16:02:33Z I! Using config file: /etc/telegraf/telegraf.conf
2023-02-13T16:02:33Z I! Using config file: /etc/telegraf/telegraf.conf
2023-02-13T16:02:33Z I! Starting Telegraf 1.25.1
2023-02-13T16:02:33Z I! Available plugins: 228 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
2023-02-13T16:02:33Z I! Loaded inputs: conntrack cpu mem net netstat nstat
2023-02-13T16:02:33Z I! Loaded aggregators: 
2023-02-13T16:02:33Z I! Loaded processors: 
2023-02-13T16:02:33Z I! Loaded secretstores: 
2023-02-13T16:02:33Z I! Loaded outputs: influxdb_v2
2023-02-13T16:02:33Z I! Tags enabled: host=hestia
2023-02-13T16:02:33Z D! [agent] Initializing plugins
2023-02-13T16:02:33Z D! [agent] Connecting outputs
2023-02-13T16:02:33Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2023-02-13T16:02:33Z D! [agent] Successfully connected to outputs.influxdb_v2
2023-02-13T16:02:33Z D! [agent] Starting service inputs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1387053]

goroutine 84 [running]:
github.com/influxdata/telegraf/plugins/inputs/conntrack.(*Conntrack).Gather(0xc0005a1570, {0x6cb41a0, 0xc0001160e0})
        /go/src/github.com/influxdata/telegraf/plugins/inputs/conntrack/conntrack.go:109 +0x133
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs.func2(0xc000537ae0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:419 +0x2f8
created by github.com/influxdata/telegraf/agent.(*Agent).testRunInputs
        /go/src/github.com/influxdata/telegraf/agent/agent.go:388 +0xcf
ubuntu@hestia:~$ sudo nano /etc/telegraf/telegraf.conf
```

### System info

Ubuntu 22.04

### Steps to reproduce

1. Add same plugins as is the config (I'm guessing the issue lies in conntrack specificly, but maybe it's connected to other plugins I have enabled)
2. Try running telegraf with `sudo telegraf --once --debug`
3. Observe the error

### Expected behavior

Should start normally and expose conntrack's metrics

### Actual behavior

Breaks all metrics pushes (systemd reports it as running though at least for me)

### Additional info

Also tried removing netfiler dirs/files from config that are not present on my system, same result

**Comment by powersj** [comment] 2023-02-13 16:33
I think this is already fixed in the nightly builds via https://github.com/influxdata/telegraf/commit/0ea50fa3b553a32a2266e44b025198ff87c15e17 as I cannot reproduce on master:

I can reproduce with v1.25.1:

```s
❯ ../telegraf-builds/telegraf-v1.25.1 --config config.toml --debug --once
2023-02-13T16:31:10Z I! Starting Telegraf 1.25.1
2023-02-13T16:31:10Z I! Available plugins: 228 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
2023-02-13T16:31:10Z I! Loaded inputs: conntrack
2023-02-13T16:31:10Z I! Loaded aggregators: 
2023-02-13T16:31:10Z I! Loaded processors: 
2023-02-13T16:31:10Z I! Loaded secretstores: 
2023-02-13T16:31:10Z I! Loaded outputs: file
2023-02-13T16:31:10Z I! Tags enabled: host=ryzen
2023-02-13T16:31:10Z D! [agent] Initializing plugins
2023-02-13T16:31:10Z D! [agent] Connecting outputs
2023-02-13T16:31:10Z D! [agent] Attempting connection to [outputs.file]
2023-02-13T16:31:10Z D! [agent] Successfully connected to outputs.file
2023-02-13T16:31:10Z D! [agent] Starting service inputs
2023-02-13T16:31:10Z D! [agent] Stopping service inputs
2023-02-13T16:31:10Z D! [agent] Input channel closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1387033]

goroutine 72 [running]:
github.com/influxdata/telegraf/plugins/inputs/conntrack.(*Conntrack).Gather(0xc0013fed20, {0x6cb41a0, 0xc000a1fa60})
	/tmp/build.sh.XIF2Uy/plugins/inputs/conntrack/conntrack.go:109 +0x133
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs.func2(0xc00132f4f0)
	/tmp/build.sh.XIF2Uy/agent/agent.go:419 +0x2f8
created by github.com/influxdata/telegraf/agent.(*Agent).testRunInputs
	/tmp/build.sh.XIF2Uy/agent/agent.go:388 +0xcf
telegraf on  master [?⇡] via 🐹 v1.20 
❯ ./telegraf --config config.toml --debug --once
2023-02-13T16:31:55Z I! Starting Telegraf 1.26.0-ff89b777
2023-02-13T16:31:55Z I! Available plugins: 230 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
2023-02-13T16:31:55Z I! Loaded inputs: conntrack
2023-02-13T16:31:55Z I! Loaded aggregators: 
2023-02-13T16:31:55Z I! Loaded processors: 
2023-02-13T16:31:55Z I! Loaded secretstores: 
2023-02-13T16:31:55Z I! Loaded outputs: file
2023-02-13T16:31:55Z I! Tags enabled: host=ryzen
2023-02-13T16:31:55Z D! [agent] Initializing plugins
2023-02-13T16:31:55Z D! [agent] Connecting outputs
2023-02-13T16:31:55Z D! [agent] Attempting connection to [outputs.file]
2023-02-13T16:31:55Z D! [agent] Successfully connected to outputs.file
2023-02-13T16:31:55Z D! [agent] Starting service inputs
2023-02-13T16:31:55Z D! [agent] Stopping service inputs
2023-02-13T16:31:55Z D! [agent] Input channel closed
2023-02-13T16:31:55Z I! [agent] Hang on, flushing any cached metrics before shutdown
conntrack,cpu=all,host=ryzen invalid=2i,entries=2304i,searched=0i,found=0i,new=0i,insert_failed=0i,expect_create=0i,ignore=0i,delete=0i,drop=0i,icmp_error=0i,expect_delete=0i,search_restart=0i,delete_list=0i,insert=0i,early_drop=0i,expect_new=0i 1676305915000000000
conntrack,cpu=cpu0,host=ryzen insert=0i,expect_create=0i,invalid=0i,ignore=0i,delete_list=0i,expect_new=0i,found=0i,delete=0i,drop=0i,early_drop=0i,icmp_error=0i,search_restart=0i,entries=72i,new=0i,expect_delete=0i,searched=0i,insert_failed=0i 1676305915000000000
conntrack,cpu=cpu1,host=ryzen early_drop=0i,icmp_error=0i,expect_create=0i,found=0i,invalid=0i,entries=72i,searched=0i,new=0i,delete=0i,insert=0i,expect_delete=0i,ignore=0i,delete_list=0i,insert_failed=0i,drop=0i,expect_new=0i,search_restart=0i 1676305915000000000
conntrack,cpu=cpu2,host=ryzen expect_delete=0i,search_restart=0i,invalid=0i,insert=0i,early_drop=0i,expect_create=0i,delete_list=0i,icmp_error=0i,expect_new=0i,ignore=0i,delete=0i,searched=0i,found=0i,new=0i,entries=72i,insert_failed=0i,drop=0i 1676305915000000000
conntrack,cpu=cpu3,host=ryzen delete_list=0i,expect_new=0i,search_restart=0i,ignore=0i,delete=0i,insert=0i,early_drop=0i,icmp_error=0i,expect_delete=0i,entries=72i,new=0i,expect_create=0i,invalid=0i,insert_failed=0i,drop=0i,searched=0i,found=0i 1676305915000000000
conntrack,cpu=cpu4,host=ryzen drop=0i,expect_new=0i,invalid=0i,delete_list=0i,insert=0i,early_drop=0i,expect_delete=0i,search_restart=0i,found=0i,new=0i,entries=72i,ignore=0i,insert_failed=0i,icmp_error=0i,expect_create=0i,searched=0i,delete=0i 1676305915000000000
conntrack,cpu=cpu5,host=ryzen ignore=0i,expect_create=0i,expect_delete=0i,search_restart=0i,found=0i,new=0i,invalid=0i,insert_failed=0i,early_drop=0i,icmp_error=0i,entries=72i,searched=0i,insert=0i,drop=0i,delete=0i,delete_list=0i,expect_new=0i 1676305915000000000
conntrack,cpu=cpu6,host=ryzen searched=0i,found=0i,invalid=0i,ignore=0i,insert=0i,drop=0i,expect_create=0i,entries=72i,new=0i,delete=0i,delete_list=0i,expect_delete=0i,insert_failed=0i,early_drop=0i,icmp_error=0i,expect_new=0i,search_restart=0i 1676305915000000000
conntrack,cpu=cpu7,host=ryzen entries=72i,insert=0i,insert_failed=0i,drop=0i,expect_new=0i,searched=0i,ignore=0i,delete_list=0i,search_restart=0i,delete=0i,early_drop=0i,icmp_error=0i,expect_create=0i,expect_delete=0i,found=0i,new=0i,invalid=0i 1676305915000000000
conntrack,cpu=cpu8,host=ryzen expect_new=0i,found=0i,early_drop=0i,icmp_error=0i,invalid=1i,insert=0i,expect_create=0i,insert_failed=0i,drop=0i,entries=72i,new=0i,delete=0i,expect_delete=0i,search_restart=0i,searched=0i,ignore=0i,delete_list=0i 1676305915000000000
conntrack,cpu=cpu9,host=ryzen search_restart=0i,entries=72i,new=0i,icmp_error=0i,expect_delete=0i,searched=0i,delete=0i,insert_failed=0i,found=0i,early_drop=0i,expect_create=0i,drop=0i,expect_new=0i,invalid=0i,ignore=0i,delete_list=0i,insert=0i 1676305915000000000
conntrack,cpu=cpu10,host=ryzen new=0i,invalid=0i,delete=0i,expect_delete=0i,icmp_error=0i,searched=0i,found=0i,insert=0i,drop=0i,expect_create=0i,entries=72i,ignore=0i,delete_list=0i,insert_failed=0i,early_drop=0i,expect_new=0i,search_restart=0i 1676305915000000000
conntrack,cpu=cpu11,host=ryzen ignore=0i,delete=0i,insert_failed=0i,early_drop=0i,expect_delete=0i,new=0i,drop=0i,expect_create=0i,search_restart=0i,entries=72i,searched=0i,found=0i,delete_list=0i,insert=0i,invalid=0i,icmp_error=0i,expect_new=0i 1676305915000000000
conntrack,cpu=cpu12,host=ryzen searched=0i,ignore=0i,insert=0i,drop=0i,new=0i,delete=0i,early_drop=0i,icmp_error=0i,expect_create=0i,entries=72i,delete_list=0i,insert_failed=0i,expect_new=0i,expect_delete=0i,found=0i,invalid=0i,search_restart=0i 1676305915000000000
conntrack,cpu=cpu13,host=ryzen icmp_error=0i,invalid=0i,expect_create=0i,search_restart=0i,new=0i,ignore=0i,insert_failed=0i,drop=0i,expect_delete=0i,insert=0i,early_drop=0i,expect_new=0i,entries=72i,searched=0i,found=0i,delete=0i,delete_list=0i 1676305915000000000
conntrack,cpu=cpu14,host=ryzen expect_create=0i,searched=0i,new=0i,invalid=0i,delete=0i,delete_list=0i,insert_failed=0i,icmp_error=0i,entries=72i,found=0i,insert=0i,search_restart=0i,drop=0i,early_drop=0i,ignore=0i,expect_new=0i,expect_delete=0i 1676305915000000000
conntrack,cpu=cpu15,host=ryzen entries=72i,new=0i,ignore=0i,insert_failed=0i,early_drop=0i,expect_delete=0i,invalid=0i,delete=0i,delete_list=0i,icmp_error=0i,expect_create=0i,searched=0i,found=0i,insert=0i,drop=0i,expect_new=0i,search_restart=0i 1676305915000000000
conntrack,cpu=cpu16,host=ryzen expect_create=0i,entries=72i,searched=0i,found=0i,new=0i,invalid=0i,delete=0i,early_drop=0i,drop=0i,ignore=0i,delete_list=0i,insert=0i,icmp_error=0i,expect_delete=0i,search_restart=0i,insert_failed=0i,expect_new=0i 1676305915000000000
conntrack,cpu=cpu17,host=ryzen searched=0i,ignore=0i,insert=0i,new=0i,insert_failed=0i,drop=0i,icmp_error=0i,expect_new=0i,found=0i,expect_create=0i,search_restart=0i,expect_delete=0i,entries=72i,invalid=0i,delete=0i,delete_list=0i,early_drop=0i 1676305915000000000
conntrack,cpu=cpu18,host=ryzen search_restart=0i,invalid=1i,insert=0i,insert_failed=0i,expect_create=0i,expect_delete=0i,early_drop=0i,searched=0i,found=0i,new=0i,ignore=0i,drop=0i,delete_list=0i,entries=72i,delete=0i,icmp_error=0i,expect_new=0i 1676305915000000000
conntrack,cpu=cpu19,host=ryzen insert=0i,early_drop=0i,expect_delete=0i,searched=0i,ignore=0i,delete=0i,drop=0i,expect_new=0i,entries=72i,found=0i,new=0i,delete_list=0i,icmp_error=0i,search_restart=0i,invalid=0i,insert_failed=0i,expect_create=0i 1676305915000000000
conntrack,cpu=cpu20,host=ryzen delete_list=0i,expect_delete=0i,ignore=0i,insert_failed=0i,drop=0i,expect_new=0i,expect_create=0i,entries=72i,insert=0i,icmp_error=0i,invalid=0i,delete=0i,early_drop=0i,search_restart=0i,searched=0i,found=0i,new=0i 1676305915000000000
conntrack,cpu=cpu21,host=ryzen ignore=0i,delete=0i,insert=0i,early_drop=0i,icmp_error=0i,search_restart=0i,entries=72i,expect_create=0i,searched=0i,new=0i,insert_failed=0i,drop=0i,expect_new=0i,found=0i,invalid=0i,delete_list=0i,expect_delete=0i 1676305915000000000
conntrack,cpu=cpu22,host=ryzen entries=72i,expect_new=0i,invalid=0i,ignore=0i,delete=0i,insert_failed=0i,drop=0i,searched=0i,found=0i,delete_list=0i,early_drop=0i,expect_create=0i,expect_delete=0i,search_restart=0i,new=0i,insert=0i,icmp_error=0i 1676305915000000000
conntrack,cpu=cpu23,host=ryzen early_drop=0i,entries=72i,searched=0i,new=0i,delete_list=0i,insert=0i,expect_new=0i,expect_delete=0i,ignore=0i,delete=0i,icmp_error=0i,expect_create=0i,search_restart=0i,found=0i,invalid=0i,insert_failed=0i,drop=0i 1676305915000000000
conntrack,cpu=cpu24,host=ryzen invalid=0i,insert=0i,icmp_error=0i,entries=72i,searched=0i,new=0i,ignore=0i,expect_delete=0i,found=0i,delete=0i,insert_failed=0i,drop=0i,early_drop=0i,expect_new=0i,search_restart=0i,delete_list=0i,expect_create=0i 1676305915000000000
conntrack,cpu=cpu25,host=ryzen new=0i,early_drop=0i,expect_new=0i,expect_create=0i,expect_delete=0i,searched=0i,delete=0i,delete_list=0i,drop=0i,search_restart=0i,ignore=0i,found=0i,insert=0i,insert_failed=0i,icmp_error=0i,entries=72i,invalid=0i 1676305915000000000
conntrack,cpu=cpu26,host=ryzen icmp_error=0i,searched=0i,found=0i,new=0i,delete=0i,invalid=0i,expect_new=0i,search_restart=0i,entries=72i,insert=0i,drop=0i,expect_delete=0i,expect_create=0i,ignore=0i,delete_list=0i,insert_failed=0i,early_drop=0i 1676305915000000000
conntrack,cpu=cpu27,host=ryzen invalid=0i,delete_list=0i,drop=0i,early_drop=0i,entries=72i,searched=0i,ignore=0i,insert_failed=0i,expect_delete=0i,found=0i,insert=0i,icmp_error=0i,expect_create=0i,new=0i,delete=0i,expect_new=0i,search_restart=0i 1676305915000000000
conntrack,cpu=cpu28,host=ryzen expect_new=0i,expect_delete=0i,found=0i,invalid=0i,delete=0i,expect_create=0i,ignore=0i,drop=0i,icmp_error=0i,early_drop=0i,searched=0i,new=0i,delete_list=0i,search_restart=0i,entries=72i,insert=0i,insert_failed=0i 1676305915000000000
conntrack,cpu=cpu29,host=ryzen invalid=0i,delete_list=0i,early_drop=0i,search_restart=0i,found=0i,new=0i,insert_failed=0i,drop=0i,icmp_error=0i,entries=72i,searched=0i,ignore=0i,expect_delete=0i,delete=0i,insert=0i,expect_new=0i,expect_create=0i 1676305915000000000
conntrack,cpu=cpu30,host=ryzen expect_delete=0i,searched=0i,ignore=0i,delete=0i,expect_create=0i,drop=0i,search_restart=0i,icmp_error=0i,entries=72i,invalid=0i,insert=0i,early_drop=0i,expect_new=0i,found=0i,new=0i,delete_list=0i,insert_failed=0i 1676305915000000000
conntrack,cpu=cpu31,host=ryzen searched=0i,delete=0i,delete_list=0i,drop=0i,early_drop=0i,search_restart=0i,invalid=0i,ignore=0i,insert_failed=0i,icmp_error=0i,expect_create=0i,expect_delete=0i,entries=72i,new=0i,found=0i,insert=0i,expect_new=0i 1676305915000000000
conntrack,host=ryzen ip_conntrack_count=72,ip_conntrack_max=262144 1676305915000000000
2023-02-13T16:31:55Z D! [outputs.file] Wrote batch of 34 metrics in 115.641µs
2023-02-13T16:31:55Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-02-13T16:31:55Z I! [agent] Stopping running outputs
2023-02-13T16:31:55Z D! [agent] Stopped Successfully
```

**Comment by realkarmakun** [comment] 2023-02-13 18:57
> edit: we plan to release v1.25.2 today which should have that fix.

Alright than this can be closed.

**Closed** 2023-02-13 18:58 UTC
Labels: bug
