### ISSUE TITLE
[BUG] windows, can not add config-directory with "-service install"

### ISSUE THREAD

**Issue by glz-io** [influxdata/telegraf#1797] opened 2016-09-21 07:23 UTC
Hi,

"-service install" does not install the service with "-config-directory c:\program files\telegraf\telegraf.d" even if we specify it during "service install"

I'm running telegraf 1.0.0 on windows 2012R2

To reproduce, just add the service as written in the documentation and check "path to executable" on windows service.

Regards

**Comment by sparrc** [comment] 2016-09-21 09:18
dupe of #1137

**Comment by glz-io** [comment] 2016-09-21 09:34
I'm not sure this is the same problem.

With version previous 1.0.0, I was using "nssm" and telegraf.d was "working". Files inside were read. But we can only declare one of each input.

About this bug, no file inside telegraf.d are readen. In fact, "-config-directory" is not set on the command line.

**Comment by davestephens** [comment] 2017-03-29 13:46
Whilst annoying, it's reasonably trivial to work around this by using sc.exe to update the the service binPath following installing with `--service install`:

````
c:\telegraf\telegraf.exe --config c:\telegraf\config\telegraf.conf --service install"

sc.exe update telegraf binPath= "c:\telegraf\telegraf.exe -config c:\telegraf\config\telegraf.conf -config-directory c:\telegraf\config.d"
````

**Comment by Papyruse** [comment] 2017-03-29 16:49
Well done @davestephens 

Just replace `sc.exe update` by `sc.exe config` working for me.

**Comment by PierreF** [comment] 2017-04-18 14:11
Isn't this bug fixed by #2330 ?

**Closed** 2017-04-24 20:38 UTC
Labels: bug, help wanted, need more info, platform/windows

**Comment by MaximeDevalland** [comment] 2017-06-07 13:08
I can confirm I still have the problem.

**Comment by MaximeDevalland** [comment] 2017-06-12 13:33
@PierreF : could we re-open this issue ?
It's easy to reproduce the bug. Run telegraf.exe --service install and check the service.
![Imgur](http://i.imgur.com/0dbbrhq.png)

It's missing the config-directory.
