### ISSUE TITLE
[inputs.opcua] StatusBadSessionIDInvalid 

### ISSUE THREAD

**Issue by acejacek** [influxdata/telegraf#8583] opened 2020-12-17 12:14 UTC
In exact 2 minutes intervals I'm getting this message in log:
```
E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
```
It exists in Telegraf 1.16.3, and latest RC: 1.17.0
Connection to OPC-UA in anonymous mode, no security policies nor secure modes, generic configuration.

Telegraf seems to be working, data get collected just this annoying error message. I can't spot from where error comes from: is it a bug in plugin or in its surroundings.

**Comment by helenosheaa** [comment] 2020-12-28 20:41
That error message would be coming from inside the getData function within the opcua client on line 455 but need to explore more. Can you share your telegraf.conf?

**Comment by acejacek** [comment] 2020-12-30 16:13
Complete `opcua.conf`:
```
[[inputs.opcua]]
  name = "opcua"
  interval = "1m"
  endpoint = "opc.tcp://10.10.10.1:4840"
  connect_timeout = "30s"
  security_policy = "None"
  security_mode = "None"
  auth_method = "Anonymous"

nodes = [
  {name="Serial", namespace="3", identifier_type="s", identifier='"OpcData"."FromOpc"."SerNr"', data_type="string"},
  {name="Art", namespace="3", identifier_type="s", identifier='"OpcData"."FromOpc"."ArtNr"', data_type="string"},
]

tagexclude = ["id", "name"]
fielddrop = ["Quality"]

[inputs.opcua.tags]
        plc = "Entry"
```
logs:

```
# grep 'inputs.opcua' /var/log/syslog|tail
Dec 30 17:02:00 ubuntu telegraf[9474]: 2020-12-30T16:02:00Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
Dec 30 17:04:00 ubuntu telegraf[9474]: 2020-12-30T16:04:00Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
Dec 30 17:06:00 ubuntu telegraf[9474]: 2020-12-30T16:06:00Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
Dec 30 17:08:00 ubuntu telegraf[9474]: 2020-12-30T16:08:00Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: The session id is not valid. StatusBadSessionIDInvalid (0x80250000)
```

**Comment by sjwang90** [comment] 2021-11-04 20:18
@acejacek Just to check in on this issue - you aren't having any issues with the data collection just error keeps appearing without any reason?

**Comment by magiconair** [comment] 2022-02-15 05:39
See https://github.com/influxdata/telegraf/issues/9164#issuecomment-1039878729

**Comment by powersj** [comment] 2023-02-09 19:45
Hi,

I am going to close this issue as the referenced upstream issue was fixed and we have since updated the library in telegraf. If it is still an issue, please do file a new issue showing how to reproduce with the latest version of telegraf.

Thanks

**Closed by powersj** 2023-02-09 19:45 UTC
Labels: bug, area/opcua
