### ISSUE TITLE
I am getting "System error 1067" when I try to run telegraf with a remote config file

### ISSUE THREAD

**Issue by itolevy** [influxdata/telegraf#4235] opened 2018-06-05 12:32 UTC
I am installing telegraf service on Windows 10 Enterprise x64 using the following command:
```
telegraf.exe --config \\xxx.xxx.xxx.xxx\library\telegraf.conf --service install
```

But when I try to run the service (net start telegraf), I am getting the following error message: (nothing in the log) 

net start telegraf

The Telegraf Data Collector Service service is starting.
The Telegraf Data Collector Service service could not be started.

A system error has occurred.

System error 1067 has occurred.

The process terminated unexpectedly.

Any idea why or how to overcome this? 

* I am running cmd as admin
* I am able to access the remote directory

**Comment by itolevy** [comment] 2018-06-11 08:06
Reproduces with Today's nightly on Windows x86. 
Nothing in the logs.

**Comment by danielnelson** [comment] 2018-06-11 17:57
@vlastahajek Can you look into this one?

**Comment by vlastahajek** [comment] 2018-06-11 20:42
Sure..
@itolevy, does it work when you have config locally?

**Comment by vlastahajek** [comment] 2018-06-12 15:11
Telegraf, as a Windows service, runs under the Local System account by default and it probably doesn't have privileges for the remote file. Try changing Telegraf's service acount:

Win+X->Computer Management->Services and Applications->Services->Telegraf Data Collector Service:
![image](https://user-images.githubusercontent.com/29980246/41299282-65e724c8-6e63-11e8-8d05-f0f83bb2603a.png)

**Comment by suraganijanakiram** [comment] 2019-11-18 09:55
Hi All,

I have tried with the latest version of the telegraf i.e 1.12.5 with the below command and there is no issue if we provide the full path of the configuration file like below.

PLEASE FOLLOW THE BELOW STEPS.
**step 1:-**
extract the zip file and copy the telegraf folder to the "Program Files" and run the below command 
**step 2:-**
C:\Program Files\telegraf>telegraf.exe -service install -config "C:\Program Files\telegraf\telegraf.conf"

I also got the server error issue when i used the command like below.

C:\Program Files\telegraf>telegraf.exe -service install -config telegraf.conf

also if you are using some different directory please make sure that telegraf have the permission to access the config file.

Hope this helps you.

**Comment by TheSilverHawkx** [comment] 2019-12-30 15:06
@vlastahajek  is it possible to add an option to provide a different RunAs account while installing the service?

That way you can run telegraf as a different user or as systemlocal by default.

**Comment by vlastahajek** [comment] 2020-01-07 13:05
This is basically possible. What is your main installation use case? Installing Telegraf using scripts?
In other cases, manual setting is also easy..

**Comment by TheSilverHawkx** [comment] 2020-01-07 13:20
> This is basically possible. What is your main installation use case? Installing Telegraf using scripts?
> In other cases, manual setting is also easy..

In my case, I have my own powershell module for installing agents and adding configuration, but what it does is essentially open cmd and type "telegraf.exe --service install --config folder --config-directory other_folder"

Adding a flag for the telegraf.exe would be optimal, but the same could be done with a few lines of powershell

**Comment by SoloWinf** [comment] 2020-02-13 11:54
Trying to [install Telegraf](https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md) as a Windows Service on Windows Server 2012 R2 Standard


![Snag_33dc1aad](https://user-images.githubusercontent.com/61010549/74431102-8f856d80-4e5e-11ea-91cc-ccdfaef13d7b.png)

Before installing the service, I ensured the test was successful. It doesn't seem to be a problem with the config.

![Snag_33dde396](https://user-images.githubusercontent.com/61010549/74431296-d70bf980-4e5e-11ea-8695-830d2f887346.png)

I tried to install the service in different ways and none of them made a difference.
`telegraf.exe -service install -config "C:\Program Files\telegraf\telegraf.conf"`
`"c:\program files\telegraf\telegraf.exe" --service install -config "c:\program files\telegraf\telegraf.conf"`
`C:\"Program Files"\Telegraf\telegraf.exe --service install`

It installed the registry key correctly though

![Snag_33e24838](https://user-images.githubusercontent.com/61010549/74432822-80eb8600-4e5f-11ea-955d-c442ffef18a8.png)
![Snag_33e56140](https://user-images.githubusercontent.com/61010549/74433060-fa837400-4e5f-11ea-8f8f-45cf4439ac09.png)

Does anyone have any idea?

**Comment by TheSilverHawkx** [comment] 2020-02-13 12:26
> Trying to [install Telegraf](https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md) as a Windows Service on Windows Server 2012 R2 Standard
> 
> ![Snag_33dc1aad](https://user-images.githubusercontent.com/61010549/74431102-8f856d80-4e5e-11ea-91cc-ccdfaef13d7b.png)
> 
> Before installing the service, I ensured the test was successful. It doesn't seem to be a problem with the config.
> 
> ![Snag_33dde396](https://user-images.githubusercontent.com/61010549/74431296-d70bf980-4e5e-11ea-8695-830d2f887346.png)
> 
> I tried to install the service in different ways and none of them made a difference.
> `telegraf.exe -service install -config "C:\Program Files\telegraf\telegraf.conf"`
> `"c:\program files\telegraf\telegraf.exe" --service install -config "c:\program files\telegraf\telegraf.conf"`
> `C:\"Program Files"\Telegraf\telegraf.exe --service install`
> 
> It installed the registry key correctly though
> 
> ![Snag_33e24838](https://user-images.githubusercontent.com/61010549/74432822-80eb8600-4e5f-11ea-955d-c442ffef18a8.png)
> ![Snag_33e56140](https://user-images.githubusercontent.com/61010549/74433060-fa837400-4e5f-11ea-8f8f-45cf4439ac09.png)
> 
> Does anyone have any idea?

Try these things:
- If you haven't, check if there's anything written about it the telegraf.log
- Try to target the problems source, is it happening on multiple servers or only on specific server?
- From reading the lines you tried to install with there are some syntax error with '-', try installing this way:
1. Open cmd as administrator
2. "C:\Progra~1\Telegraf\telegraf.exe --service install --config "C:\Progra~1\Telegraf\telegraf.conf"


Error 1607 means that the service could not be start due to corrupt files / corrupt service registry key / anything related to windows trying to run the service by itself and failing

Hope it helps

**Comment by SoloWinf** [comment] 2020-02-13 13:02
Thanks for your response.

The telegraf.log doesn't get created
![Snag_3421ea42](https://user-images.githubusercontent.com/61010549/74437883-38d16100-4e69-11ea-90ba-f1499faa06cf.png)


I tried this on 3 Windows Servers (all are Server 2012 R2) out of which, it worked only on one server. I compared the permissions (Registry, Folder, Files) between these servers and I couldn't find a difference though.

Here it is,
![Snag_340d0542](https://user-images.githubusercontent.com/61010549/74436034-070acb00-4e66-11ea-8986-905a9b841b70.png)

It installed the service
![Snag_340ddb6f](https://user-images.githubusercontent.com/61010549/74436104-273a8a00-4e66-11ea-8a45-658b34badbbb.png)

Test was successful
![Snag_340f7299](https://user-images.githubusercontent.com/61010549/74436254-65d04480-4e66-11ea-9680-83cd7a15ddbf.png)

But the service failed to start
![Snag_340fdeb1](https://user-images.githubusercontent.com/61010549/74436290-75e82400-4e66-11ea-8f5b-05ad66944ece.png)

**Comment by TheSilverHawkx** [comment] 2020-02-13 13:52
@SoloWinf 
I installed the new version 1.13.2 on a test server and didn't experience the same error.

Did you try to install an older version? I use 1.11 in my production.

It might sound silly, but did you restart your server during the process, windows operating system have a tendency to "solve themselves" after restarting.

Comparing what you posted to what i have everything seems to be the same.

**Comment by SoloWinf** [comment] 2020-02-13 14:26
I didn't restart the servers yet, believing it'd be unnecessary as it worked on one of 3 servers with 1.13.3

I also tried with 1.13.2 but still the service failed to start
![Snag_346f7ff4](https://user-images.githubusercontent.com/61010549/74444366-0ded0a00-4e75-11ea-9dd6-c6dfb826cd94.png)

**Comment by SoloWinf** [comment] 2020-02-13 15:04
> 1.11

I just tried with 1.11.0, still doesn't work.

**Comment by SoloWinf** [comment] 2020-02-13 16:18
It works with version 1.13.3 (i386) on a couple of Windows 2012 R2 Standard x64 servers.
I'll try to install it on a couple of more servers to see if it works and keep the thread updated.

Thanks @TheSilverHawkx for your time.

**Comment by vlastahajek** [comment] 2020-02-13 16:27
@SoloWinf, When you experience an error during the start of Telegraf, check log entries in Event Viewer->Application, please. There should be an error reported by Telegraf

**Comment by 0x5nc** [comment] 2020-02-14 14:36
So I kept running into posts, same as this one, where people suggest messing with your registries, deleting telegraf, re-installing, etc. 
These are all solutions that assume you didn't edit your telegraf.conf file. 
99% of the time, if not 100%, the issue is that you forgot to add quotes or brackets around URLs or something alike ( I mentionned URLs because they're tricky ones ). 
Just go double check your edits inside the .conf file. It is mainly the reason why the error keeps popping up whenever you start the service. 
If you restart it or reinstall it with a conf file that has errors, it will simply keep rejecting without saying so.

**Comment by vlastahajek** [comment] 2020-02-18 11:51
@0x5nc Indeed, this could be the most often issue of config file problem. 
However, in this case, when running Telegraf  in the test mode, with the same config as in the service mode, without any problem, this is not a problem of config file.

**Comment by SoloWinf** [comment] 2020-02-20 15:52
> 
> 
> It works with version 1.13.3 (i386) on a couple of Windows 2012 R2 Standard x64 servers.
> I'll try to install it on a couple of more servers to see if it works and keep the thread updated.
> 
> Thanks @TheSilverHawkx for your time.

As I mentioned earlier, I've been able to deploy 1.13.3 (i386) on several Windows 2012 R2 Standard x64 servers without a problem. The version that did not work on any of those servers was telegraf-1.13.3_windows_amd64.

**Comment by yashcs** [comment] 2020-02-24 20:23
Can you please share me the config file. Mostly issue will be there in config..

**Comment by evollution** [comment] 2020-04-01 12:17
I have the same Issue, windows server 2016, half servers works but the other half does not

**Comment by evollution** [comment] 2020-04-01 12:20
i tried with the latest version but getting same error, I can start it with 
telegraf --config telegraf.conf        

but when I try to start as a service I get error 1067

**Comment by vlastahajek** [comment] 2020-04-01 20:48
@evollution , could you, please, check for the Telegraf service error in the Windows Event Log? https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md#troubleshooting

**Comment by danielnelson** [comment] 2020-04-01 21:25
I'm going to close this issue since this is a generic error message, there is no particular bug to fix for this issue.  If you experience this error, the advice from @vlastahajek check the Windows Event Log is correct.

**Closed by danielnelson** 2020-04-01 21:25 UTC
Labels: bug, platform/windows

**Comment by evollution** [comment] 2020-04-04 06:53
It seems this was caused by our antivirus, since the exe is not signed the service start is blocked by our AV
