### ISSUE TITLE
Log error when used into plugin and executed through test

### ISSUE THREAD

**Issue by ricrug** [influxdata/telegraf#8843] opened 2021-02-09 11:06 UTC
### System info:

Telegraf v1.17.2
OS Fedora 33

### Steps to reproduce:
1. in perc.go: 
```
type Perc struct {
	Log  telegraf.Logger
}
[...]
func (p *Perc) Apply(in ...telegraf.Metric) []telegraf.Metric {
	p.Log.Debug("-- Start plugin... this log works")

```
2. in perc_test.go
```func Testc(t *testing.T) {
	log.Printf("-- Start testing... this log doesn't work")
	s := &Perc{
	}

	s.Apply()
[...]
```
### Expected behavior:

I would expect the same kind of logging I get when running the application.

### Actual behavior:
When I try to run tests (using vscode) for the plugin I am writing, the log variable in the class is "nil".
Can I initialize it from my test?

### Additional info:
The log works correctly if I run the entire built application. It only fails when running the test.

```
2021/02/09 12:00:16 -- Start plugin... this log works 
--- FAIL: TestPerc (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6620af]
```

**Comment by helenosheaa** [comment] 2021-02-11 21:33
I may be misunderstanding your request but if you want to print out in tests etc you can always use:

`fmt.Println("-- Example...")` or  `t.Log("-- Example...")`

For your test example I think you need to initialize the logger e.g.

```
	s := &Perc{
        Log: testutil.Logger{},
	}
        s.Log.Printf("-- Start testing... this log doesn't work")
	s.Apply()
```

Or import the golang [log ](https://golang.org/pkg/log/#pkg-overview )in your test file to use log("example.."). However the logs will only come up in the case of an error in the test or if you are running them with -v.

**Comment by ricrug** [comment] 2021-02-25 13:15
Sorry for the late reply. I want to be able to run my test as an entrypoint and define debug/inspection points in the plugin.

**Comment by ssoroka** [comment] 2021-03-01 16:47
Sounds like what Helen suggested is what you need. This is definitely not a bug in Telegraf, so I'm going to close it. if you need further help I'd suggest checking out the community slack #Telegraf channel https://influxdata.com/slack

**Closed by ssoroka** 2021-03-01 16:47 UTC
Labels: bug
