### ISSUE TITLE
syslog.input Error "expecting a Stamp timestamp [col 5]"

### ISSUE THREAD

**Issue by Limyoonsu** [influxdata/telegraf#10791] opened 2022-03-08 03:22 UTC
### Relevant telegraf.conf

```toml
[[inputs.syslog]]
  server = "udp://0.0.0.0:514"
  syslog_standard = "RFC3164"
```

### Logs from Telegraf
2022-03-08T03:03:35Z E! [inputs.syslog] Error in plugin: expecting a Stamp timestamp [col 5]
2022-03-08T03:03:35Z E! [inputs.syslog] Error in plugin: expecting a Stamp timestamp [col 5]
2022-03-08T03:03:35Z E! [inputs.syslog] Error in plugin: expecting a Stamp timestamp [col 5]
2022-03-08T03:03:35Z E! [inputs.syslog] Error in plugin: expecting a Stamp timestamp [col 5]
2022-03-08T03:03:35Z E! [inputs.syslog] Error in plugin: expecting a Stamp timestamp [col 5]

<ESXI6.5 syslog>
2022-03-07T09:33:22.936Z <HOSTNAME> Hostd: verbose hostd[79A7B80] [Originator@6876 sub=PropertyProvider opID=ed87cdc2 user=vpxuser] RecordOp ASSIGN: info, haTask--vim.InternalStatsCollector.queryLatestVmStats-122136888. Applied change to temp map.

### System info

telegraf 1.21.4, ESXI 6.5, Centos7.4

### Steps to reproduce

1. Setting up the syslog of "ESSI".
2. Send it to the 514 port of the "Elasticsearch" server.
3. Save logs using "telegraf syslog input plugin".

### Expected behavior

I thought it would work normally, but an error occurred.

### Actual behavior

Why did I send the syslog of "ESXI 6.5" to 514 port of the "Elasticsearch" server and get an error message like "Expecting a Stamp Timestamp [col5]"?

**Comment by powersj** [comment] 2022-03-08 14:22
That message does not look like it is in the correct format and the error message you are getting is saying it cannot parse the message it received correctly:

```
2022-03-07T09:33:22.936Z Hostd: verbose hostd[79A7B80] [Originator@6876 sub=PropertyProvider opID=ed87cdc2 user=vpxuser] RecordOp ASSIGN: info, haTask--vim.InternalStatsCollector.queryLatestVmStats-122136888. Applied change to temp map.
```

This is an example of a valid RFC 3164 format:

```
<34>Jan 12 06:30:00 1.2.3.4 apache_server: 1.2.3.4 - - [12/Jan/2011:06:29:59 +0100] "GET /foo/bar.html HTTP/1.1" 301 96 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9.2.12) Gecko/20101026 Firefox/3.6.12 ( .NET CLR 3.5.30729)" PID 18904 Time Taken 0
```

As this is not a bug in Telegraf, I am going to close this. However, I recommend posting this question in our [Community Slack](https://influxdata.com/slack) or [Community Page](https://community.influxdata.com/), we have a lot of talented community members there who could help answer your question more quickly.

**Closed by powersj** 2022-03-08 14:22 UTC
Labels: bug, area/elasticsearch
