### ISSUE TITLE
FreeBSD - Newsyslog log rotation

### ISSUE THREAD

**Issue by billyhudson** [influxdata/telegraf#4612] opened 2018-08-30 09:47 UTC
I have a question regarding logrotation for telegraf on FreeBSD.

I have configured newsyslog to send SIGHUP to `/var/run/telegraf.pid` in an attempt to restart the service however the telegraf.pid file contains the pid of the daemon and not the child telegraf process, which results in telegraf becoming a child of init and the new log file remaining empty.
I can see that the rc.d/telegraf script uses the -P option to daemon to set the PID of the daemon.
I've modified the rc.d/telegraf script to use the -p option to daemon to store the child processes PID, which when sent the SIGHUP signal successfully restarts telegraf and is able to write to the new log file.

Will I have to do this for all of my FreeBSD instances or am I missing something?

### Relevant telegraf.conf:
```
[agent]
  logfile = "/var/log/telegraf/telegraf.log"
```

### rc.d/telegraf modification
`
command_args="-crP ${pidfile} -p /var/run/${name}child.pid /usr/local/bin/${name} ${telegraf_flags} -config=${telegraf_conf} >> /var/log/telegraf.log 2>&1"
`

### newsyslog.d/telegraf
`
/var/log/telegraf/telegraf.log root:wheel 644 30 * @T06 JC /var/run/telegrafchild.pid
`

### System info:

FreeBSD 11.1-RELEASE-p13
telegraf-1.6.3

**Comment by danielnelson** [comment] 2018-08-30 20:43
The Telegraf package in ports is maintained outside of this repo and includes this file.

@girgen How would you prefer we go about handling these sorts of issues?  Should this be reported to https://www.freebsd.org/support/bugreports.html or is there another place?  We can also just discuss them here too, whatever is best for you.

**Comment by girgen** [comment] 2018-08-31 08:26
Hi, either way of reporting the problem is fine. I'll check it out.

**Comment by adrianlzt** [comment] 2019-10-03 09:48
Now there is a native log rotation system: #5778

**Comment by sspaink** [comment] 2022-05-12 16:01
Closing as this seems resolved with #5778, please re-open if this isn't the case.

**Closed by sspaink** 2022-05-12 16:01 UTC
Labels: area/packaging, platform/bsd
