### ISSUE TITLE
SNMP Plugin don't handel STRINGS with "xxxx"

### ISSUE THREAD

**Issue by urskog84** [influxdata/telegraf#5672] opened 2019-04-03 08:40 UTC
### Relevant telegraf.conf:
```toml
[[inputs.snmp]]
  agents = [ "nrkipklb001" ]
  interval = "1m"
 
  version = 1
  community = "KLBPUB"
  

 [[inputs.snmp.table]]
    name = "b100RSTable"
    inherit_tags = [ "hostname" ]

   [[inputs.snmp.table.field]]
      name = "rSActiveConns"
      oid = "B100-MIB::rSActiveConns"

   [[inputs.snmp.table.field]]
      name = "rSip"
      oid = "B100-MIB::rSip"
      is_tag = true
    
   [[inputs.snmp.table.field]]
      name = "rSvsidx"
      oid = "B100-MIB::rSvsidx"
      is_tag = true
```

### System info:
```
Telegraf 1.10.1 (git: HEAD a6778f46)

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Steps to reproduce:
the snmp walk command show that the string value continas " 
```
[root]# snmpwalk -v1 -c KLBPUB -Os nrkipklb001 B100-MIB::rSip
rSip.83 = STRING: "172.17.6.213"
rSip.84 = STRING: "172.17.6.214"
rSip.85 = STRING: "172.24.100.58"
rSip.86 = STRING: "172.24.100.57"
rSip.87 = STRING: "172.24.200.38"
rSip.88 = STRING: "172.24.200.39"
rSip.91 = STRING: "172.24.1.98"
```

### Expected behavior:
i expect that rSip value are collected as a string.

like this
```
b100RSTable,agent_host=nrkipklb001,host=nrkipnmt001.migrationsverket.se rSip=172.17.6.213,rSvsidx=75 rSActiveConns=0i 1554280388000000000
```
### Actual behavior:
rSip value in not pict upp
```
b100RSTable,agent_host=nrkipklb001,host=nrkipnmt001.migrationsverket.se,rSvsidx=75 rSActiveConns=0i 1554280388000000000
```

**Comment by danielnelson** [comment] 2019-04-04 19:53
Can you show the output of `snmptable -v1 -c KLBPUB nrkipklb001:161 b100RSTable`

**Comment by urskog84** [comment] 2019-04-07 07:40
`snmptable -v1 -c KLBPUB nrkipklb001:161 b100RSTable` is no sucess  
`b100RSTable: Unknown Object Identifier (Sub-id not found: (top) -> b100RSTable)`


works better with :)
` snmptable -v1 -c KLBPUB nrkipklb001:161 B100-MIB::b100RSTable `


```
SNMP table: B100-MIB::b100RSTable

 rSvsidx            rSip rSport rSaddrtype rSidx rSforwardingMethod rSweight   rSstate rSConns  rSInPkts rSOutPkts rSInBytes rSOutBytes rSActiveConns rSInactiveConns
      36  "172.17.6.213"   4711       ipv4    83              "nat"     1000 inService   70638 148406338  65060518         ?          ?            16               0
      36  "172.17.6.214"   4711       ipv4    84              "nat"     1000 inService   70636 132668948  55249121         ?          ?            14               0
      37 "172.24.100.58"   4711       ipv4    85              "nat"     1000 inService    1904    100717     66670         ?          ?             0               0
      37 "172.24.100.57"   4711       ipv4    86              "nat"     1000 inService    1904     96291     65240         ?          ?             0               0
      38 "172.24.200.38"   4711       ipv4    87              "nat"     1000 inService       0         0         0         ?          ?             0               0
      38 "172.24.200.39"   4711       ipv4    88              "nat"     1000 inService       0         0         0         ?          ?             0               0
      40   "172.24.1.98"     80       ipv4    91              "nat"     1000 inService  296646   2078568   1269057         ?          ?             0               0
      40   "172.24.1.99"     80       ipv4    92              "nat"     1000 inService  216466   1486817    887246         ?          ?             0               0
      41   "172.24.1.98"     80       ipv4    93              "nat"     1000 inService 2505713 117866161  60412500         ?          ?            29               6
      41   "172.24.1.99"     80       ipv4    94              "nat"     1000  disabled       0         0         0         ?          ?             0               0
      42 "192.176.91.41"     80       ipv4    95              "nat"     1000 inService       0         0         0         ?          ?             0               0
      42 "192.176.91.42"     80       ipv4    96              "nat"     1000 inService       0         0         0         ?          ?             0               0
      44   "172.24.1.98"     80       ipv4    97              "nat"     1000 inService   34100    208628    106609         ?          ?             0               0
      44   "172.24.1.99"     80       ipv4    98              "nat"     1000 inService   21467    131228     67078         ?          ?             0               0
      48 "192.168.250.4"     80       ipv4   112              "nat"     1000 inService   14443    179165     61745         ?          ?             0               1
      49 "192.168.250.4"     80       ipv4   113              "nat"     1000 inService   14432    171418    101560         ?          ?             0               0
      48 "192.168.250.5"     80       ipv4   114              "nat"     1000 inService   14464    179641     61839         ?          ?             0               0
      48 "192.168.250.6"     80       ipv4   115              "nat"     1000 inService   14414    178782     61478         ?          ?             0               0
      48 "192.168.250.7"     80       ipv4   116              "nat"     1000 inService   14399    178695     61456         ?          ?             0               0
      49 "192.168.250.5"     80       ipv4   117              "nat"     1000 inService   14888    152533     90709         ?          ?             0               0
      49 "192.168.250.6"     80       ipv4   118              "nat"     1000 inService   14519    125106     76037         ?          ?             0               0
      49 "192.168.250.7"     80       ipv4   119              "nat"     1000 inService   14046    122926     75442         ?          ?             0               0
      50 "192.168.250.4"     80       ipv4   120              "nat"     1000 inService      66     53897     36167         ?          ?             0               0
      50 "192.168.250.5"     80       ipv4   121              "nat"     1000 inService      56     18683     12618         ?          ?             0               0
      50 "192.168.250.6"     80       ipv4   122              "nat"     1000 inService      53      8443      5779         ?          ?             0               0
      50 "192.168.250.7"     80       ipv4   123              "nat"     1000 inService      53      6961      4781         ?          ?             0               0
      51 "192.168.250.4"     80       ipv4   124              "nat"     1000 inService 2823506  43934822  36842300         ?          ?             1              12
      51 "192.168.250.5"     80       ipv4   125              "nat"     1000 inService 2824324  32610421  25232701         ?          ?             0              13
      51 "192.168.250.6"     80       ipv4   126              "nat"     1000 inService 2809085  35311787  27728734         ?          ?             0              13
      51 "192.168.250.7"     80       ipv4   127              "nat"     1000 inService 2822074  35581786  28188277         ?          ?             0              13
      52 "192.168.250.4"     80       ipv4   128              "nat"     1000 inService   39442    792468    600207         ?          ?             0               0
      52 "192.168.250.5"     80       ipv4   129              "nat"     1000 inService   39378    752591    561388         ?          ?             0               0
      52 "192.168.250.6"     80       ipv4   130              "nat"     1000 inService   39200    732532    542249         ?          ?             0               0
      52 "192.168.250.7"     80       ipv4   131              "nat"     1000 inService   39105    767484    577294         ?          ?             0               0

```

**Comment by danielnelson** [comment] 2019-04-08 23:32
I'm not sure what the issue is, on a table in the standard MIB I am able to assign a string tag.  Can you try the following config, after editing the connection info, and see what the output is?
```toml
[[inputs.snmp]]
  agents = [ "localhost:161" ]
  version = 1
  community = "public"

  [[inputs.snmp.table]]
    name = "ifTable"

    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "ifOutBroadcastPkts"    
      oid = "IF-MIB::ifOutBroadcastPkts"
```

Here is some of my output:
```
> ifTable,agent_host=localhost,ifDescr=vnet2 ifOutBroadcastPkts=0i 1554766140000000000
> ifTable,agent_host=localhost,ifDescr=bond0 ifOutBroadcastPkts=0i 1554766140000000000
```

**Comment by urskog84** [comment] 2019-04-09 18:34
I think it is " the sign, fist and last in the rSip column that cause the issie!?

**Comment by danielnelson** [comment] 2019-04-09 18:49
Are the quotes part of the string then?  This is weird, but in theory it shouldn't be a problem.

Perhaps it will be best to collect a packet capture and I could try to replay it.  You may need to adjust some values but the basic template is:
```
sudo tcpdump -s 0 -i eth0 -w foo.pcap host nrkipklb001 and port 161
```

Run this in the background and in the foreground:
```
telegraf --input-filter=snmp --test
```

And then attach foo.pcap to this issue.

**Comment by urskog84** [comment] 2019-04-09 19:14
Tanks for the quick answer @danielnelson. no problem here is the pcap/tcpdump file.
 
`tcpdump -s 0 -i ems192 -w foo.pcap host nrkipklb001 and port 161`

`telegraf -config kemp_test.conf --test`

```
#cat kemp_test.conf

[[inputs.snmp]]
  agents = [ "nrkipklb001",  ]
  interval = "1m"
  ## "nrkipelb001", "nrkipelb002"

  version = 1
  community = "KLBPUB"

# Real Server Tables
 [[inputs.snmp.table]]
    name = "b100RSTable"
    inherit_tags = [ "hostname" ]

   [[inputs.snmp.table.field]]
      name = "rSActiveConns"
      oid = "B100-MIB::rSActiveConns"

   [[inputs.snmp.table.field]]
      name = "rSip"
      oid = "B100-MIB::rSip"
      is_tag = true

   [[inputs.snmp.table.field]]
      name = "rSvsidx"
      oid = "B100-MIB::rSvsidx"
      is_tag = true
```

upload of tcpdump file ->
[foo.zip](https://github.com/influxdata/telegraf/files/3060566/foo.zip)

**Comment by danielnelson** [comment] 2019-04-09 21:08
Could you also help me out with these OIDs since I don't have the MIB:
```
snmptranslate -On B100-MIB::rSip
snmptranslate -On B100-MIB::rSvsidx
snmptranslate -On B100-MIB::rSActiveConns
```

**Comment by urskog84** [comment] 2019-04-10 18:07
snmptranslate -On B100-MIB::rSip                        .1.3.6.1.4.1.12196.13.2.1.2
snmptranslate -On B100-MIB::rSvsidx                   .1.3.6.1.4.1.12196.13.2.1.1
snmptranslate -On B100-MIB::rSActiveConns       .1.3.6.1.4.1.12196.13.2.1.17


 you can finde the mig ->
https://kemptechnologies.com/files/packages/current/LM_mibs.zip

**Comment by danielnelson** [comment] 2019-04-11 23:55
I think I know what the cause is, it seems to be related to a bad double type conversion, but to verify could you test this configuration:
```
[[inputs.snmp]]
  agents = ["nrkipklb001"]
  interval = "1m"
  version = 1
  community = "KLBPUB"

 [[inputs.snmp.field]]
    oid = "B100-MIB::rSip.83"
```

Just run with `--test` again and this time attach the output from Telegraf.
```
telegraf -config kemp_test.conf --test
```

**Comment by urskog84** [comment] 2019-04-12 18:45
2019-04-12T18:44:02Z I! Starting Telegraf 1.10.1
2019-04-12T18:44:02Z E! [inputs.snmp]: Error in plugin: agent nrkipklb001: converting "172.17.6.213" (OID .1.3.6.1.4.1.12196.13.2.1.2.83) for field rSip.83: invalid length (12) for ipaddr conversion

**Comment by danielnelson** [comment] 2019-04-12 19:21
This confirms the double type conversion is the cause.

@phemmer I could use some advice here.  The conversion happens once [here in gosnmp](https://github.com/soniah/gosnmp/blob/ea8c875f6b1fd364ae84e6e06333eee11947daa9/helper.go#L114), converting the 4 byte to a dotted string representation based on the type in the response.

We attempt a second conversion in the snmp plugin because when we called snmptranslate during initialization we saw `TEXTUAL CONVENTION InetAddress`.  However since the response has already been converted to a human readable string representation it doesn't succeed.
```
$ snmptranslate -Td -Ob B100-MIB::rSip.83
B100-MIB::rSip.83
rSip OBJECT-TYPE
  -- FROM       B100-MIB
  -- TEXTUAL CONVENTION InetAddress
  SYNTAX        OCTET STRING (0..255) 
  MAX-ACCESS    read-only
  STATUS        current
  DESCRIPTION   "IP address of RS"
::= { iso(1) org(3) dod(6) internet(1) private(4) enterprises(1) one4net(12196) b100(13) b100RSTable(2) rsEntry(1) rSip(2) 83 }
```

It seems like we should just remove this section, and only do the conversion if specifically requested in the configuration file:

https://github.com/influxdata/telegraf/blob/e9fe26f17b839272f32b8c7c8942c9d49b1c913f/plugins/inputs/snmp/snmp.go#L1017-L1024

**Comment by phemmer** [comment] 2019-04-12 23:09
My stance would be that gosnmp needs a way to turn off the conversion, and let telegraf do it.

Why?
In summary, this statement from [RFC-2578](https://tools.ietf.org/html/rfc2578#section-7.1.5):

>    Note that the IpAddress type is a tagged type for historical reasons.
   Network addresses should be represented using an invocation of the
   TEXTUAL-CONVENTION macro [3].

Meaning that the way telegraf is handling it is the standard.
Additionally the RFC even says that it only supports IPv4, not IPv6:

>    The IpAddress type represents a 32-bit internet address.  It is
   represented as an OCTET STRING of length 4, in network byte-order.

While it may be possible to stuff an IPv6 address in an IpAddress data type (by ignoring the rule that it must be 4 bytes long), it's not supported by the standard.

&nbsp;

This would support my experience as well, and why on devices I've had access to, I've never seen this issue. It's likely only seen on old or esoteric devices.

So given that the what telegraf is doing is the standard, I would recommend keeping the current behavior of not requiring explicit configuration. If we can't get gosnmp to allow disabling the conversion, then as evil as it sounds, I might recommend having the code check if the value has already been converted if the conversion step fails.

But I would strongly argue that gosnmp is in the wrong here. We are asking it for an SNMP value, and are expecting a machine usable response, not a human usable response (a formatted string).

**Comment by danielnelson** [comment] 2019-04-16 01:48
As I read more, it seems to me that the agent shouldn't be returning this object with type IpAddress, since this is a more restrictive type than it appears in the MIB.  It feels like we should have gotten a response value that falls into the `OctetString` conversion.

With respect to gosnmp's handling, I can see it both ways.  It would be nicer IMO if gosnmp returned this as a net.IP, but I think strictly speaking it is a matter of API choice what Go-type to turn a value into, assuming that any type conversion is attempted instead of just returning a []byte for everything.  What's really important is us knowing what type we received, if we know that `IpAddress` values will always be stringified we could parse it back to `net.IP`, wasteful as it is, and then display using whatever formatting as desired.

**Comment by phemmer** [comment] 2019-04-16 13:59
> As I read more, it seems to me that the agent shouldn't be returning this object with type IpAddress, since this is a more restrictive type than it appears in the MIB. It feels like we should have gotten a response value that falls into the `OctetString` conversion.

Well we technically did. `IpAddress` is essentially a subclass or a type alias of `OctetString`.

> but I think strictly speaking it is a matter of API choice what Go-type to turn a value into

While I might debate that, at the very least if you're implementing an API, your data types should be deterministic, and machine usable (human usable is the concern of the user interface layer). If the data type (seemingly) randomly changes, that makes an API extremely difficult to work with. This is why go has strong types, and the use of empty `interface{}` is discouraged.

**Comment by MyaLongmire** [comment] 2022-01-11 19:17
I am going to close this as `snmptraslate` is deprecated in telegraf and supported versions no longer use it due to performance issues. If you are having issues with recent `snmp` update, please open another ticket with all relevant information.

**Closed by MyaLongmire** 2022-01-11 19:17 UTC
Labels: bug, area/snmp
