### ISSUE TITLE
Add a CoAP observer input plugin

### ISSUE THREAD

**Issue by amq** [influxdata/telegraf#2994] opened 2017-07-08 18:01 UTC
## Feature Request

CoAP is a new communication protocol for IoT devices created by The Internet Engineering Task Force, supported by ARM.

**Description:**
https://en.wikipedia.org/wiki/Constrained_Application_Protocol
http://coap.technology/
https://www.youtube.com/watch?v=4bSr5x5gKvA

**Implementation reference:**
https://tools.ietf.org/html/rfc7641
https://github.com/eclipse/californium/tree/master/californium-core/src/main/java/org/eclipse/californium/core/observe

**Demo servers which can be used for testing:**
http://vs0.inf.ethz.ch/
http://leshan.eclipse.org/

**Comment by goller** [comment] 2017-07-08 18:48
Very cool. Do you have any suggestions for  go libraries to include in telegraf?  The wiki page has a few but a cursory search leads to several.

**Comment by amq** [comment] 2017-07-08 19:20
I would choose https://github.com/zubairhamed/canopus

It is the most feature-complete library with a support for observing and DTLS.

**Comment by danielnelson** [comment] 2017-07-10 22:04
It seems we could do something similar to the `socket_listener` input?

**Comment by amq** [comment] 2017-08-07 08:10
An implementation in Java which is very similar to your observers: https://github.com/datamountaineer/stream-reactor/tree/master/kafka-connect-coap

I especially like that it uses the discovery feature of CoAP to automatically discover and observe all resources.

**Comment by wz2b** [comment] 2020-12-08 11:20
This is from 2017 (and it's now 2020) but I'm very interested in this.  I would be interested in working on it with a partner if anybody is so motivated.

**Comment by wz2b** [comment] 2020-12-08 11:24
> I would choose https://github.com/zubairhamed/canopus

That project hasn't been updated in 4 years, which scares me a little.  There seems to be another, though:
[go-coap](https://godoc.org/github.com/go-ocf/go-coap)

That project looks active and featureful.  It may be a better bet at this point.

**Comment by medykn-git** [comment] 2022-06-10 13:48
Is this project active ?

**Comment by powersj** [comment] 2022-06-10 14:04
> Is this project active ?

If you have a comment relevant to this issue, please leave it. 

As a previous commenter has stated, the proposed [zubairhamed/canopus](https://github.com/zubairhamed/canopus) project has not been updated in more 4 years now. [dustin/go-coap](https://github.com/dustin/go-coap) is in a similar situation. Telegraf will avoid bringing in new dependencies that are not actively maintained.

[plgd-dev/go-coap](https://github.com/plgd-dev/go-coap) may be an option but needs research.

If you are interested in this issue and want to help it along then coming up with a proposal or ideas would be greatly appreciated.

**Comment by srebhan** [comment] 2023-10-31 16:22
@amq, @goller and @wz2b is there still interest in a CoAP plugin?

**Comment by wz2b** [comment] 2023-10-31 17:20
> @amq, @goller and @wz2b is there still interest in a CoAP plugin?

If it were available I would like to experiment with it, and maybe use it.  CoAP has a foothold in the electric utility industry.  It's nice because it's so compact and has low overhead compared to HTTPS or even MQTT.  The problem is, there has to be much more CoAP traction for it to be worth our while to implement this as a telegraf built-in.

The problem I see is this: the original request issue is more than five years old, how much traction has CoAP gained in the IoT/IIoT world?  My gut feel is "not much."  A complicating factor is that while DTLS (a way to do encryption over UDP) is a thing, actual implementations are even more scarce than CoAP itself.

I would love for CoAP to be a thing.  I just kind of feel like it doesn't have enough gravity around it to warrant the development, absent some specific and significant use case that I'm not aware of.

I'd let it go.

**Comment by srebhan** [comment] 2023-11-01 13:22
Closing this feature-request as there is only very limited interest in such a plugin. If you really need this, please reopen this issue or create a new one!

**Closed by srebhan** 2023-11-01 13:22 UTC
Labels: help wanted, feature request, new plugin, area/iot, plugin/input, size/l
