### ISSUE TITLE
[inputs.cpu]: Error: current total CPU time is less than previous total CPU time

### ISSUE THREAD

**Issue by evollution** [influxdata/telegraf#4629] opened 2018-09-04 11:34 UTC
### Relevant telegraf.conf:
 [[inputs.cpu]]
     percpu = true
     totalcpu = true
     fielddrop = ["time_*"]

### System info:
Windows Server 2016; Telegraf v1.7.4

### Steps to reproduce:

1. ...
2. ...

### Actual behavior:
```
2018-09-04T11:23:53Z I! Starting Telegraf v1.7.4
2018-09-04T11:23:53Z I! Loaded inputs: inputs.win_perf_counters inputs.cpu inputs.disk inputs.mem
2018-09-04T11:23:53Z I! Loaded aggregators: 
2018-09-04T11:23:53Z I! Loaded processors: 
2018-09-04T11:23:53Z I! Loaded outputs: graphite
2018-09-04T11:23:53Z I! Tags enabled: host=prod-web-c-01
2018-09-04T11:23:53Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"prod-web-c-01", Flush Interval:10s 
2018-09-04T11:24:10Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:24:30Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:24:40Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:24:50Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:25:00Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:25:10Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:25:20Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:25:50Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:26:10Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:26:30Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:26:50Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:27:00Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:27:10Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:27:30Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:27:50Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:28:00Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:28:20Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2018-09-04T11:28:30Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU tim
```
### Additional info:

Could you please help me with this issue, i do not actually understand what is this caused by ?

**Comment by danielnelson** [comment] 2018-09-04 19:38
I think this is a bug, as a workaround you can use the `win_perf_counters` plugin on Windows:
```
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% User Time", "% Processor Time"]
    Measurement = "win_cpu"
```

**Comment by zak-pawel** [comment] 2020-11-17 00:11
Seems like a duplicate of: https://github.com/influxdata/telegraf/issues/4269

**Closed** 2020-11-17 15:40 UTC
Labels: area/system, bug, platform/windows
