### ISSUE TITLE
Add XML input data format

### ISSUE THREAD

**Issue by neographikal** [influxdata/telegraf#8757] opened 2021-01-27 11:03 UTC
## Feature Request

Implement XML data format like the input json parser:
https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json

### Use case: 

Same as the json parser, but not everything is json. XML is a valid file format still. I'd use it for the http input plugin.

**Comment by Hipska** [comment] 2021-01-27 16:32
Hi, do you think that the parser from #8047 would resolve your request?

**Comment by Hipska** [comment] 2021-01-27 16:36
After a second look, it seem this is a duplicate of #1758

**Closed by Hipska** 2021-01-27 16:36 UTC
Labels: area/xml, feature request, plugin/parser
