### ISSUE TITLE
Telegraf 1.22.0 / GoSNMP.Conn is missing

### ISSUE THREAD

**Issue by bondskin** [influxdata/telegraf#10890] opened 2022-03-25 09:50 UTC
### Relevant telegraf.conf

```toml
[[inputs.snmp.table]]
    oid = "IF-MIB::ifTable"
    [[inputs.snmp.table.field]]
      is_tag = true
      oid = "IF-MIB::ifDescr"
```

### Logs from Telegraf

```
Mar 25 10:46:00 raspberrypidns telegraf[16226]: 2022-03-25T09:46:00Z E! [inputs.snmp] Error in plugin: agent dreamer.ip: gathering table unifiIfTable: performing bulk walk for field unifiIfName: &GoSNMP.Conn is missing. Provide a connection or use Connect()
Mar 25 10:46:00 raspberrypidns telegraf[16226]: 2022-03-25T09:46:00Z E! [inputs.snmp] Error in plugin: agent dreamer.ip: gathering table hrProcessorTable: performing bulk walk for field hrProcessorFrwID: &GoSNMP.Conn is missing. Provide a connection or use Connect()
Mar 25 10:46:00 raspberrypidns telegraf[16226]: 2022-03-25T09:46:00Z E! [inputs.snmp] Error in plugin: agent dreamer.ip: gathering table laTable: performing bulk walk for field laNames: &GoSNMP.Conn is missing. Provide a connection or use Connect()
Mar 25 10:46:00 raspberrypidns telegraf[16226]: 2022-03-25T09:46:00Z E! [inputs.snmp] Error in plugin: agent area51.ip: performing get on field sysName: &GoSNMP.Conn is missing. Provide a connection or use Connect()
```

### System info

Telegraf, 1.22.0, Raspberry Pi 4

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

no errors and values are correctly captured.

### Actual behavior

For some devices, it produces errors and no SNMP values are being captured

### Additional info

no issue with telegraf_1.20.4-1_armhf.deb

**Comment by Hipska** [comment] 2022-03-25 14:58
This seems like a duplicate of #10554

**Comment by sjwang90** [comment] 2022-03-25 17:18
Let's close this to avoid duplicated. @bondskin - please check out #10554 and comment anything you would like to add on that issue.

**Comment by bondskin** [comment] 2022-03-26 08:19
thanks @sjwang90 for taking care.
Last good version for me (running on Raspberry Pi4 (5.10.103-v8+ #1529 )was  telegraf_1.20.4-1_armhf.deb

With 1.22.0 I get now this:
```
Mar 25 10:46:00 raspberrypidns telegraf[16226]: 2022-03-25T09:46:00Z E! [inputs.snmp] Error in plugin: agent dreamer.ip: gathering table hrProcessorTable: performing
bulk walk for field hrProcessorFrwID: &GoSNMP.Conn is missing. Provide a connection or use Connect()
Mar 25 10:46:00 raspberrypidns telegraf[16226]: 2022-03-25T09:46:00Z E! [inputs.snmp] Error in plugin: agent dreamer.ip: gathering table laTable: performing bulk walk
for field laNames: &GoSNMP.Conn is missing. Provide a connection or use Connect()
Mar 25 10:46:00 raspberrypidns telegraf[16226]: 2022-03-25T09:46:00Z E! [inputs.snmp] Error in plugin: agent area51.ip: performing get on field sysName: &GoSNMP.Conn
is missing. Provide a connection or use Connect()
```

**Comment by Hipska** [comment] 2022-05-19 08:25
@bondskin I just came to some code that might have introduced your problem: https://github.com/influxdata/telegraf/pull/10268

I think we still need to do that reconnect in some cases. Like in your case for example.

**Comment by bondskin** [comment] 2022-05-19 08:32
Hi @Hipska , yes exactly. 1.20.4 was the last good version in regards to this issue.

**Comment by Hipska** [comment] 2022-05-19 08:39
Okay, and what are your settings for `retries` and is it an TCP device?

**Comment by bondskin** [comment] 2022-05-19 08:59
# Polling interval
  interval = "60s"
  # Timeout for each SNMP query.
  timeout = "10s"
  # Number of retries to attempt within timeout.
  retries = 3
  # SNMP version
  version = 2

and yes, TCP

**Comment by Hipska** [comment] 2022-05-19 10:00
Okay, I was suspecting that. I think I can fix it.

**Comment by srebhan** [comment] 2022-05-24 15:48
@bondskin can you please confirm that the linked PR fixes your issue!?

**Comment by bondskin** [comment] 2022-05-24 18:12
Hi @srebhan , this is looking exceptionally great!

it took 1-2 min until the hostnames of the SNMP clients were correctly resolved after restarting the new Telegraf (PR) instance

> May 24 20:06:01 raspberrypidns telegraf[13104]: 2022-05-24T18:06:01Z E! [inputs.snmp] Error in plugin: agent millenniumfalcon.ip: setting up connection: error establishing con
> nection to host: dial udp: lookup millenniumfalcon.ip on 127.0.0.1:53: no such host
> May 24 20:06:01 raspberrypidns telegraf[13104]: 2022-05-24T18:06:01Z E! [inputs.snmp] Error in plugin: agent flash.ip: setting up connection: error establishing connection to
> host: dial udp: lookup flash.ip on 127.0.0.1:53: no such host
> May 24 20:06:01 raspberrypidns telegraf[13104]: 2022-05-24T18:06:01Z E! [inputs.snmp] Error in plugin: agent area51.ip: setting up connection: error establishing connection to
>  host: dial udp: lookup area51.ip on 127.0.0.1:53: no such host
> May 24 20:07:01 raspberrypidns telegraf[13104]: 2022-05-24T18:07:01Z E! [inputs.snmp] Error in plugin: agent millenniumfalcon.ip: reconnecting: error establishing connection t
> o host: dial udp: lookup millenniumfalcon.ip on 127.0.0.1:53: no such host
> May 24 20:07:01 raspberrypidns telegraf[13104]: 2022-05-24T18:07:01Z E! [inputs.snmp] Error in plugin: agent flash.ip: reconnecting: error establishing connection to host: dia
> l udp: lookup flash.ip on 127.0.0.1:53: no such host

 but then everything is working fine, no more errors and all clients are delivering results

**Closed** 2022-05-25 18:47 UTC
Labels: bug, area/snmp

**Comment by Hipska** [comment] 2022-05-30 08:04
Hi @bondskin, would you be able to test the builds from #11197 as well? (Or the latest nightly builds) They did a minor change on my code and I just wanted to make sure it still works for you.. (Since we could not reproduce your issues)

**Comment by bondskin** [comment] 2022-05-30 08:28
Hi @Hipska , thanks for asking, much appreciated.
Still looking good.
