### ISSUE TITLE
Same measurement, two different outputs, errors

### ISSUE THREAD

**Issue by feanorknd** [influxdata/telegraf#3460] opened 2017-11-11 03:34 UTC
## Bug report

Hello:
I have two outputs for same logparser measurements. In this case, I use outputs.influx and outputs.elasticsearch.

The problem seen is sometimes, telegraf insert a line which need to be written in influx, but in elasticsearch, so finally, this line will duplicated at elasticsearch, and will not appear at influx.

I have tested and seen results doing querys, analyzing URLs and timestamps, doing filtering and diffs.

Seen a group of lines were duplicated at elasticsearch and were missing at influxdb. It seems to happen to 10% of the lines or something approximated.

### Relevant telegraf.conf:

in telegraf.tar.gz

Inside, there is a folder with the results queried from nginx logs, elasticsearch, influxdb for a given time, and filtered just to notice the bug.

[telegraf.tar.gz](https://github.com/influxdata/telegraf/files/1463325/telegraf.tar.gz)

### System info:
telegraf 1.4.3-1 / Ubuntu 14.04.5 LTS 

### Steps to reproduce:

Apply my config... it is attached at file telegraf.tar.gz.

[telegraf.tar.gz](https://github.com/influxdata/telegraf/files/1463325/telegraf.tar.gz)

Basic, just logparse to a measurement, and let influx and elasticsearch catch this data via outputs.

### Expected behavior:

everyone logparsed line, sent to influxdb and to elasticsearch. Appear 1 time in each database.

### Actual behavior:

sometimes, a logparsed line is not being sent to influxdb, but sent to elasticsearch twice, so is missing at influx and duplicated at elasticsearch.

**Comment by feanorknd** [comment] 2017-11-11 03:43
I did notice this bug, since graphing metrics at telegraf and noticed influx was not reaching nginx-logs measures, while elastic was passing over the values..

**Comment by danielnelson** [comment] 2017-11-13 21:23
Can you try replacing your outputs with file outputs and see if you can reproduce the issue?
```toml
[[outputs.file]]
  files = ["/tmp/elasticsearch"]
  data_format = "influx"
  namepass = ["nginx_logging"]

[[outputs.file]]
  files = ["/tmp/influx"]
  data_format = "influx"
```

**Comment by danielnelson** [comment] 2018-01-02 22:15
Closing due to lack of update.

**Closed by danielnelson** 2018-01-02 22:15 UTC
Labels: need more info
