### ISSUE TITLE
Inputs.exec causes entire system to hard hang after a few days

### ISSUE THREAD

**Issue by cliffjao** [influxdata/telegraf#9033] opened 2021-03-22 17:37 UTC
### Relevant telegraf.conf:
```
[[inputs.exec]]
  commands = ["sudo /root/influx/speedtest -f json-pretty"]
  name_override = "speedtest"
  interval = "1h"
  data_format = "json"
  json_string_fields = [ "interface_externalIp",
                         "server_name",
                         "server_location",
                         "server_host",
                         "server_ip",
                         "result_url" ]
```

### System info:
Telegraf 1.18.0 (git: HEAD ac5c7f6a)
Proxmox / Debian Linux: pve-manager/6.3-6/2184247e (running kernel: 5.4.103-1-pve)

Speedtest binary from https://www.speedtest.net/apps/cli

Telegraf is running on the host

### Docker

N/A

### Steps to reproduce:

1. Load the config block above to run speedtest every hour (note that I forgot to set a longer timeout and left it to the default 5 seconds)

### Expected behavior:

Runs indefinitely with stable system

### Actual behavior:

System hard hangs a few days. Power button and reset button are both completely unresponsive. Everything stops executing. The only way to recover the system is to pull the AC plug and restart it.

### Additional info:

I've isolated all the changes I made down to this config block, and I'm 99% sure that it's somehow the culprit.

Here's the crash history:
03/11/21 12:52 AM (Telegraf speedtest config enabled 3/10)
03/15/21 01:32 AM (4 days since last crash)
03/17/21 04:48 PM (2 days since last crash)

Syslog at the time of crash doesn't show anything meaningful:
```
Mar 17 16:39:00 pve systemd[1]: pvesr.service: Succeeded.
Mar 17 16:39:00 pve systemd[1]: Started Proxmox VE replication runner.
Mar 17 16:40:00 pve systemd[1]: Starting Proxmox VE replication runner...
Mar 17 16:40:00 pve systemd[1]: pvesr.service: Succeeded.
Mar 17 16:40:00 pve systemd[1]: Started Proxmox VE replication runner.
Mar 17 16:41:00 pve systemd[1]: Starting Proxmox VE replication runner...
Mar 17 16:41:00 pve systemd[1]: pvesr.service: Succeeded.
Mar 17 16:41:00 pve systemd[1]: Started Proxmox VE replication runner.
Mar 17 16:42:00 pve systemd[1]: Starting Proxmox VE replication runner...
Mar 17 16:42:00 pve systemd[1]: pvesr.service: Succeeded.
Mar 17 16:42:00 pve systemd[1]: Started Proxmox VE replication runner.
Mar 17 16:43:00 pve systemd[1]: Starting Proxmox VE replication runner...
Mar 17 16:43:00 pve systemd[1]: pvesr.service: Succeeded.
Mar 17 16:43:00 pve systemd[1]: Started Proxmox VE replication runner.
Mar 17 16:44:00 pve systemd[1]: Starting Proxmox VE replication runner...
Mar 17 16:44:00 pve systemd[1]: pvesr.service: Succeeded.
Mar 17 16:44:00 pve systemd[1]: Started Proxmox VE replication runner.
Mar 17 16:45:00 pve systemd[1]: Starting Proxmox VE replication runner...
Mar 17 16:45:00 pve systemd[1]: pvesr.service: Succeeded.
Mar 17 16:45:00 pve systemd[1]: Started Proxmox VE replication runner.
Mar 17 16:45:01 pve CRON[11441]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Mar 17 16:46:00 pve systemd[1]: Starting Proxmox VE replication runner...
Mar 17 16:46:00 pve systemd[1]: pvesr.service: Succeeded.
Mar 17 16:46:00 pve systemd[1]: Started Proxmox VE replication runner.
Mar 17 16:58:53 pve systemd[1]: Started Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
Mar 17 16:58:53 pve kernel: [    0.000000] Linux version 5.4.103-1-pve (build@pve) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP PVE 5.4.103-1 (Sun, 07 Mar 2021 15:55:09 +0100) ()
Mar 17 16:58:53 pve kernel: [    0.000000] Command line: initrd=\EFI\proxmox\5.4.103-1-pve\initrd.img-5.4.103-1-pve root=ZFS=rpool/ROOT/pve-1 boot=zfs amdgpu.exp_hw_support=1
Mar 17 16:58:53 pve kernel: [    0.000000] KERNEL supported cpus:
Mar 17 16:58:53 pve kernel: [    0.000000]   Intel GenuineIntel
Mar 17 16:58:53 pve kernel: [    0.000000]   AMD AuthenticAMD
Mar 17 16:58:53 pve kernel: [    0.000000]   Hygon HygonGenuine
Mar 17 16:58:53 pve kernel: [    0.000000]   Centaur CentaurHauls
Mar 17 16:58:53 pve kernel: [    0.000000]   zhaoxin   Shanghai
Mar 17 16:58:53 pve kernel: [    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Mar 17 16:58:53 pve kernel: [    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Mar 17 16:58:53 pve kernel: [    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Mar 17 16:58:53 pve kernel: [    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Mar 17 16:58:53 pve kernel: [    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'compacted' format.
Mar 17 16:58:53 pve kernel: [    0.000000] BIOS-provided physical RAM map:
```

Speedtest usually takes about 30s to execute. Since I forgot to set the timeout (and probably also because I'm using sudo), I often see these messages in the log:

```
Mar 15 01:00:07 pve telegraf[4048]: 2021-03-15T08:00:07Z E! [agent] Error terminating process: operation not permitted
```

**Comment by reimda** [comment] 2021-03-23 20:26
Hi @cliffjao, sorry to hear you're having trouble with speedtest and telegraf.

Many telegraf users use inputs.exec with other programs or scripts for much longer time periods and with greater frequency than you described in the issue but without any hanging.  This leads me to believe that telegraf isn't the problem, and it's either the speedtest program itself or something about how telegraf and sudo and the speedtest program interact.

I can't tell what the problem is from your description, but I can tell you what I know and recommend a way for you to find out more about what's going on.

First, the error about "terminating process: operation not permitted" is probably because you're using sudo to run speedtest.  I assume telegraf is running as an unprivileged user.  Telegraf tries to kill speedtest after the 5 second timeout has expired, but since speedtest was run as root with sudo, telegraf isn't privileged enough to kill the process it started.  I don't recommend using sudo under exec for just this reason.  It would be better if you could find a way to run speedtest as the telegraf user.

It's possible that running so many speedtests as root would hang your machine without telegraf.  You may want to write a quick shell script to run it hourly and see if you get the hand.  If you still get the hangs, you will know telegraf isn't the cause.  I know it takes days to reproduce this problem so testing is a pain.

Here's a test script you can try.  You might need to tweak it.  Run it under the account that telegraf is using.
```
#!/bin/bash
while true; do
sudo /root/influx/speedtest -f json-pretty &
sleep 3600
done
```

Also, one of the most common causes long term hangs is running out of memory.  You may want to monitor memory and swap usage on the box while running this shell script test (or even running the speedtest under telegraf's exec).  If linux runs out of memory and swap, it will kill processes almost at random to keep the kernel running.  This often looks and acts like a hang.

If you can show that telegraf is the cause of your hangs we'll be happy to make changes to fix it.  Without information that points clearly to telegraf we will need to close this issue.

**Comment by cliffjao** [comment] 2021-03-23 21:17
Thanks for the detailed response @reimda! A few more notes on things that I've looked into:

- I've confirmed that memory isn't an issue (thanks to Telegraf!). Mem & CPU all look normal leading up to the hang events.
- I've confirmed that speedtest running under root isn't an issue. I set up a crontab from root user to run it every 2 minutes and went a few hours without any hangs. Albeit, I haven't tried running it via sudo from telegraf user like you suggested.
- I actually have a few other input.execs running via sudo without a problem and it goes on indefinitely without hanging. These are the working blocks just for reference:
```
[[inputs.exec]]
  commands = ["sudo /root/influx/hdstate.sh", "sudo /root/influx/gpu.sh"]
  data_format = "influx"
  interval = "1m"
  timeout = "300s"
[[inputs.exec]]
  commands = ["sudo /root/influx/cpu_freq.sh"]
  data_format = "influx"
  interval = "10s"
  timeout = "300s"
```

But as soon as I add the speedtest block above, I start running into the hang issue every few days.

> First, the error about "terminating process: operation not permitted" is probably because you're using sudo to run speedtest. I assume telegraf is running as an unprivileged user. Telegraf tries to kill speedtest after the 5 second timeout has expired, but since speedtest was run as root with sudo, telegraf isn't privileged enough to kill the process it started. I don't recommend using sudo under exec for just this reason. It would be better if you could find a way to run speedtest as the telegraf user.

I'd guess that this is what might be triggering the hang. Maybe some weird interaction with the kernel when trying to send a kill signal to a process it doesn't own? I'd think that the kernel would be more resilient to something like this, but maybe not.

**Comment by cliffjao** [comment] 2021-03-28 20:25
Confirmed that everything looks stable with the speedtest block above with the addition of `timeout = "300s"`. This leads me conclude it's some interaction between sudo, trying to kill the process it doesn't own, and the kernel. What's strange is that it takes several days (instances) before the system hangs. So somehow the state of the system slowly degrades.

In any case, this seems like a rather edge case bug with a workaround available. And also my kernel is an older version (5.4) at this point. So feel free to close this bug and let it serve as documentation for this strange issue.

**Comment by reimda** [comment] 2021-03-29 18:51
I'm glad you found a workaround.  Thanks for reporting back.

**Closed by reimda** 2021-03-29 18:51 UTC
Labels: area/exec, bug
