### ISSUE TITLE
Error in SNMP Plugin

### ISSUE THREAD

**Issue by toketsai** [influxdata/telegraf#10306] opened 2021-12-20 08:04 UTC
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
agents = [
"192.168.1.1"
]
version = 2
community = "public"

[[inputs.snmp.field]]
name = "InterfaceStatus"
oid = 'F5-BIGIP-SYSTEM-MIB::sysInterfaceStatus."1.0"'
```

### System info

1.20.0

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

get value

### Actual behavior

_snmpget -v2c -c public 192.168.1.1 'F5-BIGIP-SYSTEM-MIB::sysInterfaceStatus."1.0"'_  can get value.
Actually,it losts all metrics

**Comment by srebhan** [comment] 2021-12-20 08:06
@toketsai do you see any error message?

**Comment by toketsai** [comment] 2021-12-20 08:38
unable to marshal varbind list: unable to marshal OID: Invalid object identifier

**Comment by toketsai** [comment] 2021-12-20 08:39
> @toketsai do you see any error message?

unable to marshal varbind list: unable to marshal OID: Invalid object identifier

**Comment by srebhan** [comment] 2021-12-20 17:34
@toketsai so I guess this is a duplicate of #10304. I will close this ticket in favor of #10304. Please follow the process there and reopen this issue if necessary.

**Closed by srebhan** 2021-12-20 17:34 UTC
Labels: bug, area/snmp
