### ISSUE TITLE
net_response reports 10 times higher response times when running from telegraf daemon compared to cli with --test

### ISSUE THREAD

**Issue by Y0d0g** [influxdata/telegraf#5025] opened 2018-11-23 07:24 UTC
### Relevant telegraf.conf:

```
cat /etc/telegraf/telegraf.d/targetserver.conf 
[[inputs.net_response]]
  address = "targetserver.tld:3306"
  protocol = "tcp"
  read_timeout = "1s"
  timeout = "1s"
```

### System info:

```
$ telegraf --version
Telegraf 1.8.0 (git: HEAD 07d2f2d8)

```
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)

```
### Steps to reproduce:

Running on the command prompt using the --test switch net_response gives always good response times of around  3ms:

[root@vm-tomcat:~/]$ while true ; do sudo -u telegraf telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --test --input-filter net_response | grep targetserver.tld | perl -ne 'm/response_time=(\d+\.\d+)/g && printf("%f\n", $1*1000)' ; done

```
[root@vm-tomcat:~/]$ while true ; do sudo -u telegraf telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --test --input-filter net_response | grep targetserver.tld | perl -ne 'm/response_time=(\d+\.\d+)/g && printf("%f\n", $1*1000)' ; done
4.533785
4.018298
2.725835
6.233032
6.486917
8.565811
5.261558
2.733615
3.805299
2.159838
3.880774
2.610765
5.737640
6.534685
2.674108
4.143727
5.044055
4.436131
2.447316
2.183578
2.917087
2.823960
3.802844
2.244285
3.303066
2.576451
2.564699
2.705025
2.523843
6.352066
4.256939
2.616506
2.604023
2.935691
2.752335
2.879845
```

But in InfluxDB and grafana we see much higher response times for this targetserver.tld
(see screenshots)

I seems that the telegraf instance which is running as daemon measures much worse
net_response times than a telegraf which is run in foreground on the bash prompt.

We first discovered this behaviour when we switched from bare metal machines to ESX virtual machines.

Since this is based on timing in milliseconds range it could be a problem related to  virtualization ?

### Expected behavior:

Response times around  1ms

### Actual behavior:

Response times around 10 ms

### Additional info:

We set up a parallel monitoring based on tcptraceroute which always reports response times around < 1ms:

```
$ tcptraceroute -w 1 targetserver.tld 3306 | tail -n1 | awk '{print $5}'
0.613

```
![](https://user-images.githubusercontent.com/8320761/48931958-57140f80-eef9-11e8-9efb-5f0efdecc5ef.png)

**Comment by danielnelson** [comment] 2018-11-27 21:13
My only theory for why it would be different when running under `--test` is that with the default settings there could be lots of network activity at the same time.  Just for testing can you try disabling all other plugins and adding some agent `collection_jitter` about half the size of your interval and see if anything changes:
```
[agent]
  interval = "10s"
  collection_jitter = "5s"
```

**Comment by muellejo** [comment] 2018-12-10 08:31
Hello danielnelson,

thanks for looking into this issue.

Unfortunately I can't disable the other plugins since our  Teams can't do without the metrics currently ( we are an ecomerce company and soon it's christmas )

But I can disprove  you theory: 

In that loop running interactively in foreground I removed the **--input-filter net_response** option, so all plugins are run but still the values are good, or at least much better than the onese collected by the telegraf daemon in background:

```
while true ; do sudo -u telegraf telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --test | grep net_response | grep targetserver.tld |  perl -ne 'm/response_time=(\d+.\d+)/g && printf("%f\n", $1*1000)'  ; done

4.236899
6.744682
5.803579
5.587122
5.452683
2.846917
4.928755
5.252099
4.286006
4.844359
3.014253
6.657286
5.519427
6.141176
6.670950
3.804333
6.467533
6.292823
6.242763
4.313044
4.571820
6.534048
5.608852
6.102946
5.249877
4.521583
5.105767
7.215258
4.222901
5.922599
7.418004
6.632511
4.638575
6.455780
6.150610
4.108303
5.380462
4.645628
6.178285
5.304881
```

Also setting the collection_jitter to half the size of  intervall did not change anything noticeable.


```
[agent]
  hostname = "vm-tomcat.mycompany.tld"
  omit_hostname = false
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "5s"
  flush_interval = "10s"
  flush_jitter = "0s"
  logfile = ""
  debug = false
  quiet = false

```

**Comment by danielnelson** [comment] 2018-12-12 19:32
Maybe it is related to dns resolution, could you try switching to an IP address instead of a hostname temporarily:
```
[[inputs.net_response]]
  address = "1.2.3.4:3306"
  protocol = "tcp"
  read_timeout = "1s"
  timeout = "1s"
```

**Comment by muellejo** [comment] 2019-01-11 09:19
I added the hostnames in question to /etc/hosts and confirmed with tshark that there are no more DNS lookups (from telegraf) to these servers.

An it looks like absolutely hit the point with your DNS  suspicion !

With the hosts in /etc/hosts the response times are  MUCH better.
I am still monitoring how much better, but looks like a lot at first glance.

But I am still wondering why DNS latency does not matter using telegraf in foreground on cmdline
and why tcptraceroute does not suffer from DNS latency.

I hoped that that RHEL 7.5 OS would do some kind of DNS caching.

**Comment by Bibz87-CG** [comment] 2021-12-13 21:42
Is there anything new on this? I noticed the same issue happens when using telegraf's Docker image and the `http_response` plugin.

I looked at Go's code to see if something could go wrong with the way times are calculated and everything looked fine to me, so I have no clue where this 10 factor comes from.

**Comment by srebhan** [comment] 2023-07-12 16:31
We currently use code like
```golang
start := time.Now()
functionToMeasure(...)
elapsed := time.Since(start)
```

This has some drawbacks as we measure the actual wall-time which includes waiting time e.g. if the thread is rescheduled or preempted between any of the above calls. As a consequence, the actual `elapsed` time depends on the system state e.g. the load, the number of threads etc. Unfortunately the net-dialer implementation does not provide any timing information so this is the closest we can get... :-(

Closing this issue as there is no way to improve the situation here...

**Closed by srebhan** 2023-07-12 16:31 UTC
Labels: bug, area/tail
