### ISSUE TITLE
Elasticsearch output plugin doesnt gracefully exit

### ISSUE THREAD

**Issue by salarali** [influxdata/telegraf#6634] opened 2019-11-07 21:54 UTC
When using the elasticsearch output, if elasticsearch is inaccessible or down, telegraf is unable to startup. While the influxDB output, even if telegraf is unable to connect to influxdb, telegraf is able to start up.

### Relevant telegraf.conf:

```toml
[[outputs.elasticsearch]]
```

### System info:

Version: 1.12.2
OS: Amazon linux 2

### Steps to reproduce:

1.  Enable elasticsearch output

### Expected behavior:

Even if elasticsearch is down, telegraf should continue on with elasticsearch output disabled

### Actual behavior:

Telegraf fails to start up when elasticsearch is down.

### Additional info:

```
telegraf[8378]: 2019-11-07T21:51:22Z E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'Elasticsearch version check failed: Get http://xxx.xx.0.xx:9200/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)'
systemd[1]: telegraf.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit telegraf.service entered failed state.
systemd[1]: telegraf.service failed.
systemd[1]: telegraf.service holdoff time over, scheduling restart.
systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
systemd[1]: Starting The plugin-driven server agent for reporting metrics into InfluxDB...
telegraf[8399]: 2019-11-07T21:51:42Z I! Starting Telegraf 1.12.2
```

**Comment by danielnelson** [comment] 2019-11-07 23:51
This is a duplicate of #3723 so I'm closing, there is a bit of history there for reading through but the short story is we want to add this, but will probably require the behavior to be opt-in with a cli option at least until Telegraf 2.0.

**Closed by danielnelson** 2019-11-07 23:51 UTC

**Comment by brodbeni1** [comment] 2024-08-20 08:51
I have exactly the same problem:
Failed to connect to [outputs.elasticsearch], retrying in 15s,

I juste want to increase the timeout because my docker is restart to quickly if elastic serveur is offline.

I had a big timeout in my outputs.elasticsearch but with no concequences:
[[outputs.elasticsearch]]
    health_check_interval = "120s"
    index_name = "telegraf-logs"
    manage_template = false
    password = "password"
    timeout = "120s"
    urls = ["myURL"]
    use_pipeline = "pipeline"
    username = "logs-sender"
    [outputs.elasticsearch.tagpass]
        type = ["logs"]

My telegraf version: 1.28.5-r3

Issue: #3723
is only for kafka usage and not for elastic
