### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wtfuzz** [influxdata/telegraf#942] opened 2016-03-30 20:34 UTC
I had a node running Telegraf 0.10 invoke OOM killer on other processes as a result of telegraf process chewing up all RAM (over 900MB resident, on a node with 1GB of physical RAM and no swap).

I installed 0.11.1 on a test system, and set the interval to 1s. The configuration is otherwise default. The resident memory is climbing.

Has anyone else experienced this?

**Comment by sparrc** [comment] 2016-03-30 20:39
any errors in the logs? do you also have influxdb running on localhost and are all writes succeeding?

**Comment by wtfuzz** [comment] 2016-03-30 20:46
The box that was invoking OOM was writing to a remote influxdb over a VPN.

I do have these occasionally

ERROR: Post http://x.x.x.x:8086/write?consistency=&db=telegraf&precision=s&rp=: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

And "cannot allocate memory" on procstat

2016/03/30 20:44:30 Error: procstat getting process, exe: [openvpn]        pidfile: [] pattern: [] user: [] Failed to execute /usr/bin/pgrep. Error: 'fork/exec /usr/bin/pgrep: cannot allocate memory'

**Comment by sparrc** [comment] 2016-03-30 20:50
procstat isn't in the default config, can you post your config and your OS?

**Comment by wtfuzz** [comment] 2016-03-30 20:51
Here's the current memory usage

```
  PID TTY      MAJFLT MINFLT   TRS   DRS  SIZE  SWAP   RSS  SHRD   LIB   DT COMMAND
 4025 ?           743 406109372  0 917488 229372   - 475456    -     -    - /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
```

**Comment by sparrc** [comment] 2016-03-30 20:53
475456 bytes RSS seems pretty reasonable to me ...?

**Comment by wtfuzz** [comment] 2016-03-30 20:54
Config:

```
# Telegraf configuration

# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.

# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.

# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.

# Global tags can be specified here in key="value" format.
[global_tags]
  type = "dns"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will cache metric_buffer_limit metrics for each output, and will
  ## flush this buffer on a successful write.
  metric_buffer_limit = 10000
  ## Flush the buffer whenever full, regardless of flush_interval.
  flush_buffer_when_full = true

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. You shouldn't set this below
  ## interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## Run telegraf in debug mode
  debug = false
  ## Run telegraf in quiet mode
  quiet = false
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""


###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  # The full HTTP or UDP endpoint URL for your InfluxDB instance.
  # Multiple urls can be specified but it is assumed that they are part of the same
  # cluster, this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://localhost:8089"] # UDP endpoint example
  urls = ["http://10.219.100.1:8086"] # required
  # The target database for metrics (telegraf will create it if not exists)
  database = "telegraf" # required
  # Precision of writes, valid values are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  # note: using second precision greatly helps InfluxDB compression
  precision = "s"

  ## Write timeout (for the InfluxDB client), formatted as a string.
  ## If not provided, will default to 5s. 0s means no timeout (not recommended).
  timeout = "5s"
  # username = "telegraf"
  # password = "metricsmetricsmetricsmetrics"
  # Set the user agent for HTTP POSTs (can be useful for log differentiation)
  # user_agent = "telegraf"
  # Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
  # udp_payload = 512


###############################################################################
#                                  INPUTS                                     #
###############################################################################

# Read metrics about cpu usage
[[inputs.cpu]]
  # Whether to report per-cpu stats or not
  percpu = true
  # Whether to report total system cpu stats or not
  totalcpu = true
  # Comment this line if you want the raw CPU time metrics
  fielddrop = ["time_*"]

# Read metrics about disk usage by mount point
[[inputs.disk]]
  # By default, telegraf gather stats for all mountpoints.
  # Setting mountpoints will restrict the stats to the specified mountpoints.
  # mount_points=["/"]

  # Ignore some mountpoints by filesystem type. For example (dev)tmpfs (usually
  # present on /run, /var/run, /dev/shm or /dev).
  ignore_fs = ["tmpfs", "devtmpfs"]

# Read metrics about disk IO by device
[[inputs.diskio]]
  # By default, telegraf will gather stats for all devices including
  # disk partitions.
  # Setting devices will restrict the stats to the specified devices.
  # devices = ["sda", "sdb"]
  # Uncomment the following line if you do not need disk serial numbers.
  # skip_serial_number = true

# Read metrics about memory usage
[[inputs.mem]]
  # no configuration

# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration

# Read metrics about system load & uptime
[[inputs.system]]
  # no configuration

[[inputs.netstat]]

[[inputs.net]]

[[inputs.powerdns]]
  unix_sockets = ["/var/run/pdns.controlsocket"]

[[inputs.procstat]]
  pid_file = "/var/run/pdns.pid"

[[inputs.procstat]]
  exe = "openvpn"

[[inputs.procstat]]
  exe = "pcapdump"
```

```sh
$ cat /etc/issue
Debian GNU/Linux 8 \n \l
```

```sh
$ uname -r
4.4.0-x86_64-linode63
```

**Comment by wtfuzz** [comment] 2016-03-30 20:55
> 475456 bytes RSS seems pretty reasonable to me ...?

That's in KB :)

475MB is far too much for stats gathering ;)

**Comment by sparrc** [comment] 2016-03-30 20:59
agreed, that's too high, do you mind trying running without `procstat` and without `powerdns` and let me know what the memory usage looks like?

**Comment by wtfuzz** [comment] 2016-03-30 21:01
I have it running on a similar test system with default config (no procstat or powerdns modules), but with a 1s interval and flush interval to speed things up.

Memory usage is 25MB and slowly climbing.

**Comment by sparrc** [comment] 2016-03-30 21:15
okay, thanks for the details, I'll try to reproduce.

I would expect some memory usage climb, but then drop after GC cycles. 456MB definitely seems like too much in any situation, we'll have to narrow it down though to see if it's specific to any particular plugin.

**Comment by wtfuzz** [comment] 2016-03-30 21:27
Is there no valgrind like utility that works with go?

**Comment by sparrc** [comment] 2016-03-30 21:30
nothing quite as mature, this is probably the best one to use: https://github.com/pkg/profile

**Comment by wtfuzz** [comment] 2016-03-30 22:19
Ok, so it seems when it can't connect to Influx, memory grows.

I compiled Telegraf from source with pprof supported added

```
(pprof) top
2816.90kB of 2816.90kB total (  100%)
Dropped 151 nodes (cum <= 14.08kB)
Showing top 10 nodes out of 13 (cum >= 512.12kB)
      flat  flat%   sum%        cum   cum%
 2304.77kB 81.82% 81.82%  2304.77kB 81.82%  github.com/zensqlmonitor/go-mssqldb.init
  512.12kB 18.18%   100%   512.12kB 18.18%  github.com/influxdata/influxdb/models.Fields.MarshalBinary
         0     0%   100%   512.12kB 18.18%  github.com/influxdata/influxdb/client/v2.NewPoint
         0     0%   100%   512.12kB 18.18%  github.com/influxdata/influxdb/models.NewPoint
         0     0%   100%   512.12kB 18.18%  github.com/influxdata/telegraf.NewMetric
         0     0%   100%   512.12kB 18.18%  github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1
         0     0%   100%   512.12kB 18.18%  github.com/influxdata/telegraf/agent.(*accumulator).AddFields
         0     0%   100%  2304.77kB 81.82%  github.com/influxdata/telegraf/plugins/inputs/all.init
         0     0%   100%  2304.77kB 81.82%  github.com/influxdata/telegraf/plugins/inputs/sqlserver.init
         0     0%   100%   512.12kB 18.18%  github.com/influxdata/telegraf/plugins/inputs/system.(*CPUStats).Gather
(pprof) quit
fuzz@fire:~$ go tool pprof ~/.go/bin/telegraf http://localhost:6060/debug/pprof/heap?debug=1
Fetching profile from http://localhost:6060/debug/pprof/heap?debug=1
Saved profile in /home/fuzz/pprof/pprof.telegraf.localhost:6060.inuse_objects.inuse_space.015.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top
3841.09kB of 3841.09kB total (  100%)
Dropped 156 nodes (cum <= 19.21kB)
Showing top 10 nodes out of 14 (cum >= 1024.25kB)
      flat  flat%   sum%        cum   cum%
 2304.77kB 60.00% 60.00%  2304.77kB 60.00%  github.com/zensqlmonitor/go-mssqldb.init
 1024.25kB 26.67% 86.67%  1024.25kB 26.67%  github.com/influxdata/influxdb/models.Fields.MarshalBinary
  512.07kB 13.33%   100%  1536.32kB 40.00%  github.com/influxdata/influxdb/models.NewPoint
         0     0%   100%  1536.32kB 40.00%  github.com/influxdata/influxdb/client/v2.NewPoint
         0     0%   100%  1536.32kB 40.00%  github.com/influxdata/telegraf.NewMetric
         0     0%   100%  1536.32kB 40.00%  github.com/influxdata/telegraf/agent.(*Agent).gatherParallel.func1
         0     0%   100%  1536.32kB 40.00%  github.com/influxdata/telegraf/agent.(*accumulator).AddFields
         0     0%   100%  2304.77kB 60.00%  github.com/influxdata/telegraf/plugins/inputs/all.init
         0     0%   100%  2304.77kB 60.00%  github.com/influxdata/telegraf/plugins/inputs/sqlserver.init
         0     0%   100%  1024.25kB 26.67%  github.com/influxdata/telegraf/plugins/inputs/system.(*CPUStats).Gather
(pprof)
```

**Comment by wtfuzz** [comment] 2016-03-30 22:44
When I restart InfluxDB, the points are written out and the memory usage decreases.

Is the default behavior to queue points until they can be flushed to Influx? I've read conflicting reports on Go GC returning resident memory back to the OS.

Is there any configuration option to set an upper bound on the amount of RAM consumed before it will drop metrics? I'll take dropped metrics over the kernel OOMing production processes ;)

**Comment by sparrc** [comment] 2016-03-30 22:55
yes the default behavior is to queue points until they can be written, you could try lowering metric_buffer_limit to 1000 or so, which is the default value in the latest version of telegraf.

**Comment by sparrc** [comment] 2016-03-30 22:56
I'm a bit confused by your pprof report, are you monitoring a sql server instance as well? I don't see that in the config you provided

**Comment by wtfuzz** [comment] 2016-03-30 23:01
No, I do not have a mssql input in the config. I assume the init function is called somewhere, and it's referencing 2.5MB of memory?

```
###############################################################################
#                                  INPUTS                                     #
###############################################################################

# Read metrics about cpu usage
[[inputs.cpu]]
  # Whether to report per-cpu stats or not
  percpu = true
  # Whether to report total system cpu stats or not
  totalcpu = true
  # Comment this line if you want the raw CPU time metrics
  fielddrop = ["time_*"]

# Read metrics about disk usage by mount point
[[inputs.disk]]
  # By default, telegraf gather stats for all mountpoints.
  # Setting mountpoints will restrict the stats to the specified mountpoints.
  # mount_points=["/"]

  # Ignore some mountpoints by filesystem type. For example (dev)tmpfs (usually
  # present on /run, /var/run, /dev/shm or /dev).
  ignore_fs = ["tmpfs", "devtmpfs"]

# Read metrics about disk IO by device
[[inputs.diskio]]
  # By default, telegraf will gather stats for all devices including
  # disk partitions.
  # Setting devices will restrict the stats to the specified devices.
  # devices = ["sda", "sdb"]
  # Uncomment the following line if you do not need disk serial numbers.
  # skip_serial_number = true

# Get kernel statistics from /proc/stat
[[inputs.kernel]]
  # no configuration

# Read metrics about memory usage
[[inputs.mem]]
  # no configuration

# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration

# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration

# Read metrics about system load & uptime
[[inputs.system]]
  # no configuration
```

**Comment by wtfuzz** [comment] 2016-03-30 23:05
It would seem from the tree that it's called from plugins/input/all.init
```
(pprof) tree
2.25MB of 2.25MB total (  100%)
Dropped 245 nodes (cum <= 0.01MB)
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                            2.25MB   100% |   github.com/influxdata/telegraf/plugins/inputs/sqlserver.init
    2.25MB   100%   100%     2.25MB   100%                | github.com/zensqlmonitor/go-mssqldb.init
----------------------------------------------------------+-------------
                                            2.25MB   100% |   main.init
         0     0%   100%     2.25MB   100%                | github.com/influxdata/telegraf/plugins/inputs/all.init
                                            2.25MB   100% |   github.com/influxdata/telegraf/plugins/inputs/sqlserver.init
----------------------------------------------------------+-------------
                                            2.25MB   100% |   github.com/influxdata/telegraf/plugins/inputs/all.init
         0     0%   100%     2.25MB   100%                | github.com/influxdata/telegraf/plugins/inputs/sqlserver.init
                                            2.25MB   100% |   github.com/zensqlmonitor/go-mssqldb.init
----------------------------------------------------------+-------------
                                            2.25MB   100% |   runtime.main
         0     0%   100%     2.25MB   100%                | main.init
                                            2.25MB   100% |   github.com/influxdata/telegraf/plugins/inputs/all.init
----------------------------------------------------------+-------------
         0     0%   100%     2.25MB   100%                | runtime.goexit
                                            2.25MB   100% |   runtime.main
----------------------------------------------------------+-------------
                                            2.25MB   100% |   runtime.goexit
         0     0%   100%     2.25MB   100%                | runtime.main
                                            2.25MB   100% |   main.init
----------------------------------------------------------+-------------
```

**Comment by sparrc** [comment] 2016-03-30 23:08
oh, I see, so this pprof report is not from an instance that has high memory usage?

**Comment by wtfuzz** [comment] 2016-03-30 23:10
I haven't reproduced the high memory usage in a test environment yet. Since pprof isn't built into telegraf on that node, I can't get a profile of it.

**Comment by wtfuzz** [comment] 2016-03-30 23:14
On the node with high memory usage, all I can show you is that memory is still growing. RSS is now ~490MB. In my post above from 2 Hours ago it was ~475MB.

```
$ ps -mxp 4025
  PID TTY      MAJFLT MINFLT   TRS   DRS  SIZE  SWAP   RSS  SHRD   LIB   DT COMMAND
 4025 ?           837 406275109  0 917488 229372   - 490540    -     -    - /usr/bin/telegraf -config /etc/telegraf/telegraf.conf
```

**Comment by sparrc** [comment] 2016-03-31 01:10
that is a very large amount of memory, but actually with your given config, and if you were seeing write failures, I could see this happening. See this change: https://github.com/influxdata/telegraf/pull/780, which reduced the default number of cached metrics from 1,000,000 to 100,000. (you are still using 1,000,000)

So I'm not 100% sure this is a memory _leak_ per-se. I'm going to try to reproduce tonight, I've got a few different telegraf services running on VMs with some tweaks to the way the metric buffer is handled, as well as one with pprof enabled. I will report back tomorrow.

**Comment by wtfuzz** [comment] 2016-03-31 01:17
Awesome, thanks.

One thing of note, the system with high memory usage now has restored connectivity to Influx, and the RSS has not dropped. I get that it may not be a leak per-se, however I would argue that from the perspective of a user, that it is a leak (even if the buffers can be reused in Go-land, if the GC doesn't give the memory back to the kernel, it's of no use to higher priority tasks running on the system).

**Comment by sparrc** [comment] 2016-03-31 01:20
right, so then that would be the motivation for reducing the default buffer size, I'm not sure there is anything I can do about the buffers getting too large and then hanging onto the memory they allocated for themselves.

**Comment by wtfuzz** [comment] 2016-03-31 01:39
It's unclear if the GC does it automatically, or if an explicit debug.FreeOSMemory() is required to reclaim it.

Having some kind of heap bounds specified as a % of total memory or in MB would be useful. The systems I'm currently working on have 1GB of physical memory, so what would be a sane default for some, would not be here :)

Is the buffer size configurable from the 1M default in 0.10?

**Comment by sparrc** [comment] 2016-03-31 05:54
yes, I would recommend setting `metric_buffer_limit = 1000`

**Comment by sparrc** [comment] 2016-03-31 15:07
After running overnight I've determined that there is not a memory leak. I do agree with you that the default buffer size _was_ too large. The latest version of telegraf has metric_buffer_limit=1000 set, which should limit the mem usage to ~90 MB if you are getting large numbers of write failures. I think that I will also solve this by halving the number of full buffers that telegraf will cache, which will limit usage to somewhere closer to 50 MB.

**Comment by wtfuzz** [comment] 2016-03-31 18:02
Excellent, thank you.

I'll run 0.11.1 in this environment for a few days and report back here if there are any issues.

**Comment by sparrc** [comment] 2016-03-31 19:50
note that you'll need to adjust your config file, not just upgrade to version 0.11.1

**Comment by souvik-ray** [comment] 2016-04-03 04:52
I am having a similar issue. Even after setting the metric_buffer_limit the usage is creeping past 500MB and then eventually 1 GB

**Comment by sparrc** [comment] 2016-04-04 16:21
@souvik-ray can you provide your config file? and just to be clear, this memory grows only when you have prolonged write failures, correct?

**Comment by souvik-ray** [comment] 2016-04-05 13:42
# Configuration for telegraf agent
[agent]
  # Default data collection interval for all plugins
  interval = "10s"
  # Rounds collection interval to 'interval'
  # ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  # Default data flushing interval for all outputs. You should not set this below
  # interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "10s"
  # Jitter the flush interval by a random amount. This is primarily to avoid
  # large write spikes for users running a large number of telegraf instances.
  # ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  # Run telegraf in debug mode
  debug = false
  # Override default hostname, if empty use os.Hostname()
  hostname = ""


###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[outputs]

# Configuration for influxdb server to send metrics to
[outputs.influxdb]
  # The full HTTP endpoint URL for your InfluxDB instance
  # Multiple urls can be specified for InfluxDB cluster support.
  urls = ["http://10.140.211.135:8086"]
  # The target database for metrics (telegraf will create it if not exists)
  database = "telegraf" # required
  # Precision of writes, valid values are n, u, ms, s, m, and h
  # note: using second precision greatly helps InfluxDB compression
  precision = "s"

  # Connection timeout (for the connection with InfluxDB), formatted as a string.
  # If not provided, will default to 0 (no timeout)
  # timeout = "5s"
  username = "telegraf"
  password = "metrics"
  # Set the user agent for the POSTs (can be useful for log differentiation)
  # user_agent = "telegraf"


###############################################################################
#                                  PLUGINS                                    #
###############################################################################
# Read metrics about cpu usage
[cpu]
  # Whether to report per-cpu stats or not
  percpu = true
  # Whether to report total system cpu stats or not
  totalcpu = true
  # Comment this line if you want the raw CPU time metrics
  drop = ["cpu_time"]

# Read metrics about disk usage by mount point
[disk]
  # By default, telegraf gather stats for all mountpoints.
  # Setting mountpoints will restrict the stats to the specified ones.
  # mountpoints.
  # Mountpoints=["/"]

# Read metrics about memory usage
[mem]
  # no configuration

# Read metrics about network interface usage
[net]
  # By default, telegraf gathers stats from any up interface (excluding loopback)
  # Setting interfaces will tell it to gather these explicit interfaces,
  # regardless of status.
  #
  # interfaces = ["eth0", ... ]

# Read metrics about swap memory usage
[swap]
  # no configuration


###############################################################################
#                              SERVICE PLUGINS                                #
###############################################################################

# Statsd Server
[statsd]
  # Address and port to host UDP listener on
  service_address = ":8125"
  # Delete gauges every interval (default=false)
  delete_gauges = true
  # Delete counters every interval (default=false)
  delete_counters = true 
  # Delete sets every interval (default=false)
  delete_sets = true 
  # Delete timings & histograms every interval (default=true)
  delete_timings = true
  # Percentiles to calculate for timing & histogram stats
  percentiles = [90]

 templates = [
     "cpu.* measurement*"
 ]

  # Number of UDP messages allowed to queue up, once filled,
  # the statsd server will start dropping packets
  allowed_pending_messages = 10000

  # Number of timing/histogram values to track per-measurement in the
  # calculation of percentiles. Raising this limit increases the accuracy
  # of percentiles but also increases the memory usage and cpu time.
  percentile_limit = 1000

**Comment by souvik-ray** [comment] 2016-04-05 13:44
Note this happen within few minutes of loading telegraf. Is percentile_limit the issue in my case ?

**Comment by sparrc** [comment] 2016-04-05 15:38
what version of telegraf are you using?

**Comment by souvik-ray** [comment] 2016-04-05 16:15
Our beta runs
telegraf_0.10.2-1_amd64.deb
whereas prod runs
telegraf_0.11.1-1_amd64.deb

**Comment by souvik-ray** [comment] 2016-04-05 16:16
In both the versions the memory issue is happening WITHOUT right failures. This is happening in within minutes
I tried metric_buffer_limit=1000 on telegraf_0.10.2-1_amd64.deb. But there was no effect.

**Comment by sparrc** [comment] 2016-04-05 16:24
you run an older version on beta than on production?

**Comment by sparrc** [comment] 2016-04-05 16:31
could you give me an idea of how much data is coming in to your statsd server?

**Comment by sparrc** [comment] 2016-04-15 16:33
@souvik-ray any updates? I haven't been able to reproduce with the provided config. Can you tell me how much traffic your statsd server is getting?

**Comment by sparrc** [comment] 2016-04-29 21:12
Closing this because I haven't been able to reproduce.

I think the problem was that previous versions of Telegraf had a very large default configuration for the number of buffered metrics.

As of Telegraf 0.13 (releasing soon) there is a much more simple and clear configuration of metric buffers, and the default maximum that will be buffered has been reduced to 10,000. (see https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L33)

@souvik-ray 0.13 also includes some improvements to greatly reduce the number and size of memory allocations for the statsd plugin.

**Closed by sparrc** 2016-04-29 21:12 UTC
Labels: bug
