### ISSUE TITLE
Special characters break Telegraf environment variables ("invalid TOML syntax")

### ISSUE THREAD

**Issue by sauvant** [influxdata/telegraf#13845] opened 2023-08-30 21:02 UTC
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"
```

### Logs from Telegraf

```text
error loading config file /etc/telegraf/telegraf.conf: error parsing data: line xx: invalid TOML syntax
```

### System info

Telegraf 1.27.4, Docker 24.0.5, Docker Compose v2.20.2, Debian 11

### Docker

compose.yaml:

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - credentials.env

credentials.env:

MQTT_USERNAME=telegraf
MQTT_PASSWORD=asd3hj2U\c

### Steps to reproduce

1. create an env file containing a string variable that ends for example with \c
2. use this file as an env file in a docker compose configuration starting telegraf
3. use the environment variable in your telegraf.conf file

### Expected behavior

Variable contents is used in the telegraf configuration

### Actual behavior

error loading config file /etc/telegraf/telegraf.conf: error parsing data: line xx: invalid TOML syntax

**Comment by srebhan** [comment] 2023-08-31 09:35
@sauvant can you please try single-quotes like

```toml
[[inputs.mqtt_consumer]]
  username = '${MQTT_USERNAME}'
  password = '${MQTT_PASSWORD}'
```

to get [valid TOML string literals](https://toml.io/en/v0.4.0#string) otherwise you need to escape the backslash in your env file (i.e. `MQTT_PASSWORD=asd3hj2U\\c`) as `\c` is not a valid escape character!

**Comment by sauvant** [comment] 2023-08-31 09:41
Thanks for the quick reply. I am already using single quotes. That works! But: the password was auto generated by my password safe. And randomly ended with \c. Gave me a hard time to figure that out as root cause... If it is not possible to auto-escape such characters I would suggest to change the example .conf code to use single quotes.

**Comment by srebhan** [comment] 2023-09-01 08:37
Closing as this works as intended.

**Closed by srebhan** 2023-09-01 08:37 UTC
Labels: bug
