### ISSUE TITLE
Input plugin win_services provides no information about services that don't return description

### ISSUE THREAD

**Issue by nilsidemia** [influxdata/telegraf#5847] opened 2019-05-13 12:37 UTC
### Relevant telegraf.conf:

problem isn't related to configuration

### System info:

Telegraf version 1.10.1
on Windows Server 2016

### Steps to reproduce:

1. Have a service, who doesn't correctly report its description. In my case this is the service CDPUserSvc_<someHex>, whose description in the service list of Windows reads "<Failed to Read Description. Error Code: 15100>". However, the service is listed as running.
2. Run telegraf with win_services plugin configured to monitor this service (plus some more).
3. Check the produced output of Telegraf to see the other services being listed, while there is no information about CDPUserSvc_...
4. Check telegraf.log to see the following message:
2019-05-13T11:42:00Z E! [inputs.win_services]: Error in plugin: could not get config of service: 'CDPUserSvc_2be425': The resource loader failed to find MUI file.

### Expected behavior:

I would like to have such a service being listed in the output, with fields containing an error message, when their real value couldn't be retrieved. It would be a more exact representation of the (bad) real state of the service and improve monitoring.

### Actual behavior:

The service is not listed in the outputs. Instead an error message is logged. I don't mind the error message (quite the opposite), but I would like to also have the service being listed in the outputs.

### Additional info:

none

**Comment by frank687** [comment] 2019-11-05 17:53
I'd actually like to be able to suppress this error in the log. After running for long enough the log starts filling up the disk.

**Comment by danielnelson** [comment] 2019-11-08 00:04
Can we determine the steps for creating a service that exhibits this error?  This would be helpful as I believe it would need to be a change upstream in golang.org/x/sys/windows/svc/mgr.

@frank687 With the latest Telegraf you might want to use the log rotation feature to avoid too much disk usage.

**Comment by nilsidemia** [comment] 2019-11-08 10:06
I don't know enough about Windows services to suggest a way to create such a service. The main point seems to be that the service refuses to provide a description, but how this can be implemented/reproduced I don't know.
Maybe it will be sufficient to look for the service CDPUserSvc under Windows 10 and/or Windows Server 2016. A google search indicates that there are several users reporting this service (sometimes with different lower-upper-case combination) to be lacking a description or having other problems. So maybe you have access to a device or VM with such a behavior.

**Comment by danielnelson** [comment] 2019-11-08 17:35
Would you be able to export the service registry keys for this service?  I only have Windows 7 setup right now but maybe I can figure out what the problem is or copy the bad description over to another service.

In regedit go to the service, right click on the service folder, and choose export:
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CDPUserSvc
```

**Comment by nilsidemia** [comment] 2019-11-11 09:50
I did the export from a Windows Server 2016 VM, which I have access to. The resulting file is attached.
[CDPUserSvc_be6b8.zip](https://github.com/influxdata/telegraf/files/3830678/CDPUserSvc_be6b8.zip)

**Comment by markcagatandavis** [comment] 2019-11-19 23:05
I am also experiencing this issue and unable to find a solution. It looks like this MUI is no longer required in Server 2016 or is not supplied for some reason. It's not apart of the Language Packs (which is where you get it for other versions of windows).

**Comment by markcagatandavis** [comment] 2019-11-19 23:29
To replicate this issue:
1. Install Server 2016
2. Check Services.msc > CDPUserSvc_xxxx
* You will notice the service is running but the error is due to description with either:
Error: Failed to Read description error code 15100
Error: Failed to read description error code 2

3. The required MUI file should be located C:\Windows\System32\en-US\CDPUserSvc.dll.mui

You will notice that this file does not exist, which means it can't attain the description.

This file is in prior server 2012 and windows 10 (note you can't copy this to server 2016).

I have checked all language packs and performed clean installs, and reviewed the installation ISO's, to no avail and this file does not exist.

**Comment by sspaink** [comment] 2022-04-06 21:40
Closing as this seems to have been a Microsoft issue and not a Telegraf issue.

**Closed by sspaink** 2022-04-06 21:40 UTC
Labels: bug, platform/windows
