### ISSUE TITLE
Data point cache to HDD in case of Internet outage for long time

### ISSUE THREAD

**Issue by joezhoujinjing** [influxdata/telegraf#2064] opened 2016-11-22 01:49 UTC
If increasing the datapoint cached, then the memory will be a problem. Isn't it desirable if those 'might be dropped datapoints' can be cached in an influx database? 

We currently create a local influx database with a few days retention policy, however, the synchronization/transferring between the local database to the remote database is not easy as well. 
Any idea how should we solve this?

**Comment by sparrc** [comment] 2016-11-22 09:17
dupe of #802

**Closed by sparrc** 2016-11-22 09:17 UTC
