### ISSUE TITLE
Given a valid connection string, the MySQL plugin isn't working as expected

### ISSUE THREAD

**Issue by brunomvsouza** [influxdata/telegraf#1842] opened 2016-10-03 21:46 UTC
### Relevant telegraf.conf:
```
[[inputs.mysql]]
  servers = ["root:Test3a#@!@tcp(10.150.1.123:3306)/"]
```
### System info:

- Telegraf 1.0.0
- Ubuntu 14.04.4 LTS

### Steps to reproduce:

1. With a MySQL server configured with the given DSN string
2. Restart the service to apply the new configuration
3. Check the error log
4. 💣 

### Expected behavior:
No errors in the error log.

### Actual behavior:
Error being shown in the error log.

ERROR in input [mysql]: Errors encountered: [default addr for network 'tcp%!.(MISSING)1.123:3306%!'(MISSING) unknown]

### Additional info:

The issue started after upgrading from version `0.13` to `1.0.0`.

**Comment by sparrc** [comment] 2016-10-06 15:42
dupe of https://github.com/influxdata/telegraf/issues/870

**Closed by sparrc** 2016-10-06 15:42 UTC
