### ISSUE TITLE
Case problem in SQL ServerPlugin script

### ISSUE THREAD

**Issue by scott53326** [influxdata/telegraf#1702] opened 2016-09-02 15:28 UTC
I'm not a developer (nor DBA), so I could be way off here,  but it appears that the sql server plugin has an issue with SQL Server instances that have a collation that is set to cases sensitive in the sqlserver.go script.

the baselineDate  and currentlineDate column are originally being set as:

GETDATE() AS **baselineDate**
GETDATE() AS **currentlineDate**

but then later on  are used as:
(DATEDIFF(SECOND,base**L**ineDate,current**L**ineDate))   <-- with Capitalization of the "L"'s  for both.

This produces the following errors when running telegraf with the sqlserver plugin input enabled on A SQL instance that's collation is set to a case sensitive type:

2016/09/02 10:12:13 Invalid column name 'baseLineDate'.
2016/09/02 10:12:13 Invalid column name 'currentLineDate'.
2016/09/02 10:12:13 Invalid column name 'baseLineDate'.
2016/09/02 10:12:13 Invalid column name 'currentLineDate'.
2016/09/02 10:12:13 Invalid column name 'baseLineDate'.
2016/09/02 10:12:13 Invalid column name 'currentLineDate'.
2016/09/02 10:12:13 Invalid column name 'baseLineDate'.
2016/09/02 10:12:13 Invalid column name 'currentLineDate'.
2016/09/02 10:12:13 mssql: Invalid column name 'currentLineDate'.

I am using the latest windows telegraf client.

Thanks,
-Scott

**Comment by sparrc** [comment] 2016-09-02 15:44
by "latest" which version do you mean? 0.13 or 1.0rc?

cc @StianOvrevage @zensqlmonitor

**Comment by scott53326** [comment] 2016-09-02 15:46
Sorry,   I meant telegraf-1.0.0-rc1_windows_amd64.zip from the download page.

-Scott

**Comment by zensqlmonitor** [comment] 2016-09-08 18:53
It is just a problem of collation, not related to any telegraf version.
The case sensitive collation is quite rare :-)
I will update the code soon.

**Comment by scott53326** [comment] 2016-09-08 20:42
Thanks,

Yeah this SQL Server is used for an ERP System.  So case sensitive collation is required for this software.

**Comment by sparrc** [comment] 2016-09-28 15:11
fixed by https://github.com/influxdata/telegraf/pull/1748

**Closed by sparrc** 2016-09-28 15:11 UTC
Labels: bug

**Comment by biohazardxxx** [comment] 2020-02-12 14:04
Hi, this appears again for me with the latest Telegraf version telegraf-1.13.3_windows_amd64.zip.
2020-02-12T14:01:16Z I! Loaded inputs: sqlserver
2020-02-12T14:01:16Z I! Loaded aggregators: 
2020-02-12T14:01:16Z I! Loaded processors: 
2020-02-12T14:01:16Z I! Loaded outputs: influxdb
2020-02-12T14:01:16Z I! Tags enabled: host=SOMeName org=some
2020-02-12T14:01:16Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"SOMeName", Flush Interval:10s
2020-02-12T14:01:20Z I! Invalid column name 'total_cpu_usage_ms'.
2020-02-12T14:01:20Z I! Invalid column name 'total_scheduler_delay_ms'.
2020-02-12T14:01:20Z E! [inputs.sqlserver] Error in plugin: mssql: Invalid column name 'total_scheduler_delay_ms'.

**Comment by danielnelson** [comment] 2020-02-12 18:58
@biohazardxxx Can you open a new issue, please make sure to include your plugin configuration and server version.

**Comment by biohazardxxx** [comment] 2020-02-13 07:30
done #7021
Actually the problem is caused by the columns not existing in older SQL Server versions. Just as reference for future readers.
