### ISSUE TITLE
unknown binary op: int - time.duration

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#9626] opened 2021-08-13 22:40 UTC
My data:
```
{
  "fields": {
    "enabled": true
  },
  "name": "measurement_name",
  "tags": {
    "device": "device_name",
    "host": "host_name",
    "interface-name": "eth0",
    "path": ""
  },
  "timestamp": 1614195164
}
```
StarLark Processor Stanza:
```
[[processors.starlark]]
  source = '''
load('time.star', 'time')
def apply(metric):
  metric.fields["z_test"] = int(metric.time / 1e9) - time.parse_duration("24h")
  return metric
'''
```
Gives the following error:
```
2021-08-13T22:32:40Z E! [processors.starlark] Traceback (most recent call last):
2021-08-13T22:32:40Z E! [processors.starlark]   processor.starlark:7:52: in apply
2021-08-13T22:32:40Z E! [processors.starlark] Error: unknown binary op: int - time.duration
2021-08-13T22:32:40Z E! [processors.starlark] Error in plugin: unknown binary op: int - time.duration
2021-08-13T22:32:40Z E! [processors.starlark] Traceback (most recent call last):
2021-08-13T22:32:40Z E! [processors.starlark]   processor.starlark:7:52: in apply
```

**Comment by srebhan** [comment] 2021-08-23 10:25
Duplicate of #9624.

**Closed by srebhan** 2021-08-23 10:25 UTC
Labels: bug, area/starlark
