### ISSUE TITLE
RFC5424 error on App-Name over 48 characters

### ISSUE THREAD

**Issue by patn03** [influxdata/telegraf#7100] opened 2020-03-02 22:09 UTC
@danielnelson 
I was looking for Max field sizes in the RFC5424 spec and shouldn't seem to find any for app-name field. Since there doesn't seem to be a lot of control on the client side for Syslog, would it make sense to have app-name truncate and display a warning instead?

I can reproduce using LOGSPOUT running on docker swarm to collect logs from all containers. The Containers are all over 48 Characters long and LOGSPOUT will send over app-names greater then 48 characters.

Example container name "chronograf_chronograf.1.3v8p4fjev0jluhhxxcjyki90y"

Error message in Telegraf 1.13.4
`[inputs.syslog] Error in plugin: expecting an app-name (from 1 to max 48 US-ASCII characters) or a nil value`

**Comment by danielnelson** [comment] 2020-03-03 00:09
In https://tools.ietf.org/html/rfc5424#section-6.2.5 I found:
```
      APP-NAME        = NILVALUE / 1*48PRINTUSASCII
```

So this does appear to be per spec, perhaps this is something that could be permitted with the best-effort parser though, can you open a feature request on [go-syslog](https://github.com/influxdata/go-syslog)?

**Comment by patn03** [comment] 2020-03-03 13:02
Thanks, that makes sense. If this was added to go-syslog, would telegraf's go-syslog version need to be updated?

**Comment by danielnelson** [comment] 2020-03-03 18:25
Yes, and we would need to update to v3.  (https://github.com/influxdata/telegraf/issues/7023)

**Comment by pentiumoverdrive** [comment] 2021-03-04 14:48
I have this error as well, and this is the only google hit! :)
I'm not exactly sure what I can do here, am I loosing data due to the error message?

I'm running Telegraf 1.17.3 in docker.
rsyslog is sending using "RSYSLOG_SyslogProtocol23Format".

**Comment by JorgeGT** [comment] 2021-08-04 20:54
Same issue in Telegraf 1.18.1 with rsyslog sending RSYSLOG_SyslogProtocol23Format over UDP.

**Comment by ersoyugur** [comment] 2021-09-04 08:28
> Same issue in Telegraf 1.18.1 with rsyslog sending RSYSLOG_SyslogProtocol23Format template over UDP.

I thought trimming app-names that are longer than 48 chars in rsyslog would work, but it failed. Though I see app-names trimmed, telegraf still logs same error.


```
template(name="trimmer" type="string" string="<%PRI%>1 %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME:1:40% %PROCID% %MSGID% %STRUCTURED-DATA% %msg%\n")

*.* @127.0.0.1:6514;trimmer
```

**Comment by minwal** [comment] 2021-09-20 14:44
> Yes, and we would need to update to v3. (#7023)

Do you plan to fix following error as part of #7023?
[inputs.syslog] Error in plugin: expecting an app-name (from 1 to max 48 US-ASCII characters) or a nil value

**Comment by c0r3dump3d** [comment] 2022-01-12 10:39
I have the same issue with Telegraf 1.21.2 (git: HEAD 30d981d3):

`telegraf[742]: 2022-01-12T10:39:15Z E! [inputs.syslog] Error in plugin: expecting an app-name (from 1 to max 48 US-ASCII characters) or a nil value [col 44]`

**Comment by srebhan** [comment] 2024-02-22 10:28
I added some tests for long app-names and I can confirm that the parser behaves according to the [RFC5424 specification  section 6](https://datatracker.ietf.org/doc/html/rfc5424#section-6) defining a maximum length of 48 characters. As a workaround you can use rsyslog to trim the app-name (see the [comment above](https://github.com/influxdata/telegraf/issues/7100#issuecomment-912934129)).

Closing this as won't fix as this would need upstream support for the best-effort parser...

**Closed by srebhan** 2024-02-22 10:28 UTC
Labels: feature request, upstream, area/syslog
