### ISSUE TITLE
Input SNMP not parsing results from Cisco WLC properly.

### ISSUE THREAD

**Issue by jsnyder81** [influxdata/telegraf#6353] opened 2019-09-05 16:24 UTC
Working on some wireless testing with Telegraf and using SNMP input to a Cisco WLC 3504.  For comparison, I'm running the same input against an Aruba AP, which is working properly.

Verified mibs via snmpwalk
```
snmpwalk -v2c -c xxxx x.x.x.254
...
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (219649000) 25 days, 10:08:10.00
SNMPv2-MIB::sysName.0 = STRING: Cisco-3504
...
```

Verified from the Telegraf box that snmpget works
```
# snmpget -v2c -c xxxx x.x.x.253 SNMPv2-MIB::sysName.0
SNMPv2-MIB::sysName.0 = STRING: Cisco-3504
# snmpget -v2c -c xxxx  x.x.x.253 SNMPv2-MIB::sysName.0
SNMPv2-MIB::sysName.0 = STRING: Aruba-IAP
```

cisco-wlc.conf:
```
[[inputs.snmp]]
  agents = [ "x.x.x.254:161" ]
  version = 2
  community = "xxxx"

  name = "wlc-stats"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"

```

aruba-iap.conf
```
[[inputs.snmp]]
  agents = [ "x.x.x.253" ]
  version = 2
  community = "xxxxx"

  name = "wlc-stats"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
```

The results:
```
#telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d/ --test --debug
2019-09-05T16:20:33Z D! [inputs.snmp] Executing "snmptranslate" "-Td" "-Ob" "SNMPv2-MIB::sysName.0"
2019-09-05T16:20:33Z D! [inputs.snmp] Executing "snmptranslate" "-Td" "-Ob" "DISMAN-EVENT-MIB::sysUpTimeInstance"
> wlc-stats,agent_host=192.168.5.253,host=uidaho-docker,hostname=Aruba-IAP uptime=69221826i 1567700434000000000
2019-09-05T16:20:43Z E! [inputs.snmp]: Error in plugin: agent 192.168.5.254: performing get on field hostname: Request timeout (after 3 retries)
2019-09-05T16:20:43Z E! [telegraf] Error running agent: One or more input plugins had an error
```

As you can see, SNMP works, as SNMPGET returns the value.  You can also see that the config file works, as it is returned by the Aruba IAP.  But the snmp input doesn't seem to be processing the result.  Packet capture shows there are indeed a response coming back.

What further info do you guys need from me?

**Comment by danielnelson** [comment] 2019-09-05 19:02
This might be a duplicate of #3320, I could confirm if you send the packet capture, or you can check it to see if the response IP differs from the request IP.

**Closed** 2019-09-24 18:12 UTC
Labels: area/snmp, bug, need more info
