### ISSUE TITLE
CentOS RPM installs files in /opt/telegraf

### ISSUE THREAD

**Issue by gtirloni** [influxdata/telegraf#472] opened 2015-12-31 16:16 UTC
InfluxDB and Kapacitor install files in /usr/lib, /usr/bin and /etc/$product.

Telegraf on the other hand installs in /opt/telegraf and config files are in /etc/opt/telegraf.

I was wondering what's different in Telegraf that it should be in /opt. 

It's nothing major but I would expect all Influxdata products to follow a similar pattern in terms of install location, systemd units, config files, etc.

**Comment by sparrc** [comment] 2016-01-05 17:27
thanks for the feedback @gtirloni, this is a duplicate of https://github.com/influxdata/telegraf/issues/264

**Closed by sparrc** 2016-01-05 17:27 UTC
