### ISSUE TITLE
nvidia-smi module failing to produce any data

### ISSUE THREAD

**Issue by dbienapfl-dataminr** [influxdata/telegraf#4388] opened 2018-07-05 21:13 UTC
### Relevant telegraf.conf:
```[[inputs.nvidia_smi]]
  ## Optional: path to nvidia-smi binary, defaults to $PATH via exec.LookPath
  # bin_path = /usr/bin/nvidia-smi
  bin_path = "/rootfs/usr/bin/nvidia-smi"
  ## Optional: timeout for GPU polling
  # timeout = 5s
```
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf 1.7
OS Ubuntu 16.04
AWS p3.2xlarge instance
Nvidia 384.111 driver
4.4.0-1048-aws #57-Ubuntu SMP Tue Jan 9 21:45:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Telegraf RUNNING IN A PRIVILEGED DOCKER CONTAINER w/ root disk mounted and all libnvidia* files copied into the container
### Steps to reproduce:

1.  install Telegraf 1.7 into an ubuntu 16.04 docker container
2. Start container interactively mounting '/' to '/rootfs' inside the container
3. cp /rootfs/usr/lib/x86_64-linux-gnu/libnvidia-* /usr/lib/x86_64-linux-gnu/
4. telegraf -config /config/telegraf.conf

### Expected behavior:
nvidia-smi will fire - collecting data that will be forwarded off to influxdb

### Actual behavior:
From telegraf startup sequence:
`2018-07-05T20:47:27Z I! Loaded inputs: inputs.mem inputs.processes inputs.statsd inputs.socket_listener inputs.socket_listener inputs.cpu inputs.net inputs.swap inputs.kernel inputs.kernel_vmstat inputs.netstat inputs.ntpq inputs.diskio inputs.system inputs.docker inputs.linux_sysctl_fs inputs.internal inputs.nvidia_smi inputs.http_listener inputs.disk`

nvidia-smi _is_ running on a schedule (as seen from the parent os):
```root     29096 26237  0 20:40 ?        00:00:00 /rootfs/usr/bin/nvidia-smi --format=noheader,nounits,csv --query-gpu=fan.speed,memory.total,memory.used,memory.free,pstate,temperature.gpu,name,uuid,compute_mode,utilization.gpu,utilization.memory,index
```

captured from the parent OS:
```
dbienapfl@data-workstation-gpu-data-20:~$ sudo strace -p $(ps -ef | grep nvidia-smi | grep -v grep | awk '{print $2}')
strace: Process 29014 attached
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getpid()                                = 385
getpid()                                = 385
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cb20) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5c940) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5c850) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5c850) = 0
openat(AT_FDCWD, "/proc/driver/nvidia/params", O_RDONLY) = 5
fstat(5, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(5, "Mobile: 4294967295\nResmanDebugLe"..., 1024) = 491
close(5)                                = 0
stat("/dev/nvidia0", {st_mode=S_IFCHR|0666, st_rdev=makedev(195, 0), ...}) = 0
openat(AT_FDCWD, "/dev/nvidia0", O_RDWR) = 5
fcntl(5, F_SETFD, FD_CLOEXEC)           = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2b, 0x20), 0x7fffb4a5ca10) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5caa0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5c850) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5c750) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5c750) = 0
openat(AT_FDCWD, "/proc/driver/nvidia/params", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(6, "Mobile: 4294967295\nResmanDebugLe"..., 1024) = 491
close(6)                                = 0
stat("/dev/nvidia0", {st_mode=S_IFCHR|0666, st_rdev=makedev(195, 0), ...}) = 0
openat(AT_FDCWD, "/dev/nvidia0", O_RDWR) = 6
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2b, 0x20), 0x7fffb4a5c910) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5c930) = 0
nanosleep({0, 5000000}, NULL)           = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5c930) = 0
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cb90) = 0
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cac0) = 0
getpid()                                = 385
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cb20) = 0
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5b870) = 0
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x4a, 0xb0), 0x7fffb4a5cc40) = 0
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cc50) = 0
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cba0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cb70) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cac0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cac0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cac0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cac0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cac0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cbe0) = 0
getpid()                                = 385
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cb30) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cb30) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cbb0) = 0
fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
write(1, "[Not Supported]", 15)         = 15
write(1, ", 16152", 7)                  = 7
write(1, ", 0", 3)                      = 3
write(1, ", 16152", 7)                  = 7
write(1, ", P0", 4)                     = 4
write(1, ", 39", 4)                     = 4
write(1, ", Tesla V100-SXM2-16GB", 22)  = 22
write(1, ", GPU-f4596d1f-fb74-a21a-f14c-dd"..., 42) = 42
write(1, ", Default", 9)                = 9
write(1, ", 0", 3)                      = 3
write(1, ", 0", 3)                      = 3
write(1, ", 0", 3)                      = 3
write(1, "\n", 1)                       = 1
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x29, 0x10), 0x7fffb4a5cb30) = 0
close(6)                                = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x29, 0x10), 0x7fffb4a5cb30) = 0
close(5)                                = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fffb4a5cb60) = 0
close(4^[[A)                                = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x29, 0x10), 0x7fffb4a5cba0) = 0
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

Run manually from within the container:
```
root@data-workstation-gpu-data-20:/# /rootfs/usr/bin/nvidia-smi --format=noheader,nounits,csv --query-gpu=fan.speed,memory.total,memory.used,memory.free,pstate,temperature.gpu,name,uuid,compute_mode,utilization.gpu,utilization.memory,index
[Not Supported], 16152, 0, 16152, P0, 39, Tesla V100-SXM2-16GB, GPU-f4596d1f-fb74-a21a-f14c-ddb814c3f6cb, Default, 0, 0, 0
```

### Additional info:
When the container is stood up by hand and telegraf is forced to debug=true quiet=false the following can be seen in the logs:

`2018-07-05T20:47:30Z E! Error in plugin [inputs.nvidia_smi]: exit status 12`

The binary runs properly from within the container, it can be seen producing the expected data via strace while running on a schedule from within the container.

Outwardly it looks like the `[Not Supported]` is not being handled properly (I do see the parseLine function line 112 in nvidia_smi.go) yet it fails?

You can see from the strace above (likley truncated) - the nviida-smi process is producing data and exiting 0.  Yet telegraf reads/produces a status of 12?

[Include gist of relevant config, logs, etc.]
Searching golang docs I cannot find anything speaking to an exit code of 12? and I am unable to force a exit code of 12 from the nvidia-smi tool - furthermore the nvidia-smi tooling appears to be running cleanly and exiting 0 (see strace)

Any help on this would be appricated!

**Comment by danielnelson** [comment] 2018-07-18 18:09
In this [nvidia-smi documention](https://developer.download.nvidia.com/compute/DCGM/docs/nvidia-smi-367.38.pdf) I found a listing of error codes:
```
Return code 12 - NVML Shared Library couldnâ€™t be found or loaded
```

Can you try creating a wrapper script around the call to nvidia-smi that adds the strace and writes it to a file, and then point the `bin_path` at it:
```
#!/bin/sh
strace /rootfs/usr/bin/nvidia-smi "$@" 2> /tmp/nvidia-smi-debug
```

**Comment by dbienapfl-dataminr** [comment] 2018-08-08 18:49
Sorry I missed your request - I hope to get to this in the coming days - I will update this ticket with the results

**Comment by danielnelson** [comment] 2018-09-14 19:21
@dbienapfl-dataminr Have you had a chance to add the wrapper?

**Comment by reachmeselva** [comment] 2019-02-21 12:04
Was that issue fixed?

**Comment by danielnelson** [comment] 2019-02-21 22:42
There is no fix associated with this issue, are you experiencing this @reachmeselva?

**Comment by reachmeselva** [comment] 2019-02-22 04:47
Hi Daneil,

Yes, but not same issue. I was facing the below issue with telegraf plugin
[[Inputs.nvidia_smi]].

*2019-02-22T04:35:20Z E! [inputs.nvidia_smi]: Error in plugin: nvidia-smi
binary not at path /usr/bin/nvidia-smi, cannot gather GPU data*

Environment setup.

I have installed KOPS cluster on AWS EC2 instances. I have 1 Master
(t2.large) and 2 Worker nodes (1 p2.xlarge and 1 t2.medium)

Checked telegraf daemonset logs, where I could see the given inputs in
telegraf.conf has loaded properly but after few seconds. It has started
throwing the below error.

root@ip-172-20-57-116:/home/ubuntu/influxdb-grafana-on-gke/daemonsets#
kubectl  logs telegraf-9966x -n monitoring
2019-02-22T04:34:56Z I! Starting Telegraf 1.9.4
2019-02-22T04:34:56Z I! Using config file: /etc/telegraf/telegraf.conf
2019-02-22T04:34:56Z I! Loaded inputs: inputs.diskio inputs.kernel
inputs.processes inputs.docker inputs.netstat inputs.cpu inputs.disk
inputs.mem inputs.swap inputs.system inputs.net inputs.nvidia_smi
2019-02-22T04:34:56Z I! Loaded aggregators:
2019-02-22T04:34:56Z I! Loaded processors:
2019-02-22T04:34:56Z I! Loaded outputs: influxdb
2019-02-22T04:34:56Z I! Tags enabled: host=telegraf-9966x
2019-02-22T04:34:56Z I! [agent] Config: Interval:10s, Quiet:false,
Hostname:"telegraf-9966x", Flush Interval:10s



*2019-02-22T04:35:00Z E! [inputs.nvidia_smi]: Error in plugin: nvidia-smi
binary not at path /usr/bin/nvidia-smi, cannot gather GPU
data2019-02-22T04:35:10Z E! [inputs.nvidia_smi]: Error in plugin:
nvidia-smi binary not at path /usr/bin/nvidia-smi, cannot gather GPU
data2019-02-22T04:35:20Z E! [inputs.nvidia_smi]: Error in plugin:
nvidia-smi binary not at path /usr/bin/nvidia-smi, cannot gather GPU
data2019-02-22T04:35:30Z E! [inputs.nvidia_smi]: Error in plugin:
nvidia-smi binary not at path /usr/bin/nvidia-smi, cannot gather GPU data*

I was struggling with this issue for the last few days. It would be
thankful if you could please assist me on this as its help me fix the issue
at the earliest.

Regards,
Panneer S

**Comment by reachmeselva** [comment] 2019-02-25 10:37
> There is no fix associated with this issue, are you experiencing this @reachmeselva?

Yes. I have faced the same issue. It would be great if you could please provide your assist in order to fix this issue.

Thanks 
Selva

**Comment by danielnelson** [comment] 2019-02-25 19:57
@reachmeselva Can you show your logging output from Telegraf?

**Comment by reachmeselva** [comment] 2019-02-26 11:28
Hi Daniel,

I was enabled the workdir for host and docker container. It has fixed the
above mentioned issue ( *2019-02-22T04:35:00Z E! [inputs.nvidia_smi]: Error
in plugin: nvidia-smi binary not at path /usr/bin/nvidia-smi, cannot gather
GPU data* ) but now, I am facing the issue that follows which is similar as
dbienapfl-dataminr

Telegraf output logs:

2019-02-26T06:10:02Z I! Starting Telegraf 1.9.4
2019-02-26T06:10:02Z I! Using config file: /etc/telegraf/telegraf.conf
2019-02-26T06:10:02Z I! Loaded inputs: inputs.netstat inputs.nvidia_smi
inputs.disk inputs.diskio inputs.processes inputs.docker inputs.system
inputs.net inputs.cpu inputs.kernel inputs.mem inputs.swap
2019-02-26T06:10:02Z I! Loaded aggregators:
2019-02-26T06:10:02Z I! Loaded processors:
2019-02-26T06:10:02Z I! Loaded outputs: influxdb
2019-02-26T06:10:02Z I! Tags enabled: host=telegraf-q6xnw
2019-02-26T06:10:02Z I! [agent] Config: Interval:10s, Quiet:false,
Hostname:"telegraf-q6xnw", Flush Interval:10s


*2019-02-26T06:10:10Z E! [inputs.nvidia_smi]: Error in plugin: exit status
122019-02-26T06:10:20Z E! [inputs.nvidia_smi]: Error in plugin: exit status
122019-02-26T06:10:30Z E! [inputs.nvidia_smi]: Error in plugin: exit status
12*

*Regards,*

*Panneer S*

**Comment by danielnelson** [comment] 2019-02-28 00:51
Can you try setting up a wrapper script with strace, like in https://github.com/influxdata/telegraf/issues/4388#issuecomment-406023872, and call it from Telegraf?

**Comment by reachmeselva** [comment] 2019-02-28 08:34
Hi Daniel,

I ran the *.sh file and got the below as outcome 

./nvidia.sh: 2: ./nvidia.sh: strace: not found

Note:
1. Able to get the strace details in EC2 Instance without fail using wrapper

2. I couldn't make a call 'nvidia-smi' from container. It was throwing an error that follow though enabled the necessary mountpaths

NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
 
3. Please find the downloadable link of my telegraf.yaml script

https://s3.amazonaws.com/teamdst/EFS/28-Feb-19/telegraf.yaml

Kindly go through and assist me to fix the issue.

**Comment by danielnelson** [comment] 2019-02-28 19:12
You will need to install the strace command in the container, but before doing that make sure you can run the nvidia-smi command manually without error inside the container:
```
nvidia-smi --format=noheader,nounits,csv --query-gpu=fan.speed,memory.total,memory.used,memory.free,pstate,temperature.gpu,name,uuid,compute_mode,utilization.gpu,utilization.memory,index
```

Sorry, I won't have time to assist with the container setup.

**Comment by reachmeselva** [comment] 2019-03-03 14:26
Hi Daniel,

I have created Telegraf container, setup LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64 and executed the command "nvidia-smi" inside container (TELEGRAF) and got the below output.

**Error:
root@telegraf-thfwh:/usr/bin# nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.**

Then, I have created a symbolic link and executed the command but still getting the same issue (above one)

root@telegraf-thfwh:/usr/bin# ln -s /usr/bin/nvidia /usr/local/cuda-9.0/lib64/stubs/libnvidia-ml.so
ln: failed to create symbolic link '/usr/local/cuda-9.0/lib64/stubs/libnvidia-ml.so': File exists
root@telegraf-thfwh:/usr/bin# ln -s /usr/bin/nvidia /usr/lib/nvidia-384/libnvidia-ml.so
ln: failed to create symbolic link '/usr/lib/nvidia-384/libnvidia-ml.so': File exists

I  was able to executed the same command in "HOST" and "container" (created for inhouse project) without any issues but not in Telegraf Container

Kindly point out, what did I missing inside Telegraf container? 

Regards,
Selva

**Comment by reachmeselva** [comment] 2019-03-07 05:46
Hi Daniel,

Can you please provide an update as its help me to move further. 

Thanks a ton in advance.

Regards,
Selva

**Comment by danielnelson** [comment] 2019-03-08 00:37
@reachmeselva You probably need to place `libnvidia-ml.so` into your `LD_LIBRARY_PATH`:
```
ln -s /usr/local/cuda-9.0/lib64/stubs/libnvidia-ml.so /usr/local/cuda-9.0/lib64/libnvidia-ml.so
```

I'm going to close this issue as it isn't caused by Telegraf.

**Closed by danielnelson** 2019-03-08 00:37 UTC
Labels: bug, need more info
