### ISSUE TITLE
mqtt_consumer, Socket error on client Telegraf-Consumer-xxxxx, disconnecting.

### ISSUE THREAD

**Issue by zxshoe** [influxdata/telegraf#723] opened 2016-02-19 16:58 UTC
Hi guys,

So what's happening is this:

```
Device (ESP8266) which posts MQTT (PubSubClient v2.6) to Mosquitto (1.4.8) every 5s, all seems fine here.
1455897565: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455897565: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455897565: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
etc...
```

Telegraf (0.10.3) sends cpu, mem and disk info all fine to InfluxDB (0.10.0) which is graphed with Grafana (2.6). So far so good. But as soon as I forward data with the mqtt_consumer plugin things get wierd. But only for MQTT data. CPU, MEM and disk are all stable through Telegraf.
All on Ubuntu 14.04 3.19.0-49-generic kernel.

The mqtt_consumer plugin can work fine for up to an hour. But suddenly stop. And then work only for five minutes and stop. All at random intervals.

mosquitto.log shows us:
```
---------------------------
1455892503: Sending PUBLISH to Telegraf-Consumer-wduTO (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455892503: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455892503: Sending PUBLISH to Telegraf-Consumer-wduTO (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455892503: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
1455892503: Sending PUBLISH to Telegraf-Consumer-wduTO (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
1455892507: Socket error on client Telegraf-Consumer-wduTO, disconnecting.           <-----
1455892507: New connection from 10.0.0.31 on port 1883.
1455892507: New client connected from 10.0.0.31 as Telegraf-Consumer-wduTO (c1, k60).
1455892507: Sending CONNACK to Telegraf-Consumer-wduTO (0, 0)
1455892507: Received PINGREQ from Telegraf-Consumer-wduTO
1455892507: Sending PINGRESP to Telegraf-Consumer-wduTO
1455892508: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455892508: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455892508: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
1455892513: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455892513: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455892513: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
1455892517: Received PINGREQ from Telegraf-Consumer-wduTO
1455892517: Sending PINGRESP to Telegraf-Consumer-wduTO
1455892518: Received PINGREQ from TheThing
1455892518: Sending PINGRESP to TheThing
1455892518: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455892518: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455892518: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
1455892523: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455892523: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455892523: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
1455892527: Received PINGREQ from Telegraf-Consumer-wduTO
1455892527: Sending PINGRESP to Telegraf-Consumer-wduTO
1455892528: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455892528: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455892528: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
1455892533: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455892533: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455892533: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (32 bytes))
```

You probably understand this better than I do. But as I see it Telegraf reconnects to Mosquitto, continues to PINGREQ and PINGRESP. And my device 'TheThing' keeps PUBLISHing data, but for some reason Mosquitto doesn't want to PUBLISH to to mqtt_consumer after the second reconnect?!

Here are the active bits of my Telegraf config:

```
[global_tags]

[agent]
  interval = "5s"
  round_interval = true
  metric_buffer_limit = 10000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  debug = true
  quiet = false
  hostname = "ds-lx-02.asdf.com"

[[outputs.influxdb]]
  urls = ["http://fluxdb.asdf.com:8086"] # required
  database = "iot5" # required
  precision = "s"

[[inputs.mqtt_consumer]]
  servers = ["io.asdf.com:1883"]
  qos = 0
  topics = [
    "sensors/temperature/",
    "sensors/humidity/",
    "sensors/pressure/",
  ]
  metric_buffer = 100000
  username = "iot"
  password = "xxxx"
  data_format = "influx"
```

I've tried all sorts of things here. Disabling persistence in Mosquitto, different values for intervals, buffers, jitters, etc. And yes, I am fully aware that a 5s interval is rather low. But this is only for testing. I have had it much higher with the same result. I've also done a complete reinstall of the Mosquitto / Telegraf server to a new machine. Same thing. Also just updated today to the latest -3 release of Telegraf. Had to compile the latest one from source a week ago to get the mqtt_consumer plugin. Same result then as now.

Could it be a network problem? It doesn't seem to be my device at least. I've tried to disable ipv6. Same thing. Well, this is all I got, if anyone have this working please let me know so I'm not chasing ghosts here.. And let me know if I can help in any way..

An example on how it can look in Grafana https://goo.gl/h6Jqch

Cheers,
/shoe

**Comment by sparrc** [comment] 2016-02-19 17:11
thanks for the detailed report @zxshoe, are you still building from source?

I know that the paho golang client had an issue with this (see https://git.eclipse.org/r/#/c/65850/) but it was supposedly fixed.

So if you're still building from source, please run `go get -u git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git` and try again

**Comment by sparrc** [comment] 2016-02-19 17:15
Another thing to try if you can build from source, change this line: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mqtt_consumer/mqtt_consumer.go#L201

from

```go
opts.SetKeepAlive(time.Second * 60)
```

to 

```go
opts.SetKeepAlive(time.Duration(0))
```

and try rebuilding. What this does is _disable_ the MQTT consumer KeepAlive, which I think is the root cause of this issue.

**Comment by zxshoe** [comment] 2016-02-19 17:42
Thanks for the fast reply @sparrc . Made the suggested change and recompiled the latest checkout. So good so far (5 min) we'll see in an hour+ if this was the key. I did notice that the PINGREQ/PINGRESP to and from the Telegraf-Consumer disappeared from the mosquitto.log. So at least the keepalive isn't there anymore.

Let's hope!

**Comment by zxshoe** [comment] 2016-02-19 20:35
This is awesome. It's been running now for 3h straight without a single hickup. Nice catch there @sparrc ! Let me know if you need anything else (logs, verification..) from me.

Thanks for all the great work on InfluxDB and Telegraf.

**Comment by sparrc** [comment] 2016-02-19 20:42
no problem :),

would you happen to be able to run without that change (but with an updated paho client)? You can either just update the client to HEAD `go get -u git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git` or use `gdm restore` at HEAD of telegraf.

Reason being, I would like to leave that timeout in place if the paho client library has it fixed. If it's not actually fixed on the paho client I'll use the above change to fix this issue.

**Comment by zxshoe** [comment] 2016-02-20 10:44
OK. Did try that now. I did a:

:~/work/src/github.com/influxdata/telegraf# gdm restore

Although a make seems to do a restore as well (?) We'll see what happens in a few hours.

**Comment by zxshoe** [comment] 2016-02-20 10:54
An important addition though; it seems the PUBLISH:ing continued fine for about 12h. Then halted for some reason.It seems to be this entry in mosquitto.log that best correlates with the problem:

1455947536: Error in poll: Interrupted system call.

That's 05:02, Grafana stoped graphing at 06:52 and I'm GMT+1 so that's about right. But this could be unrelated to mqtt_consumer. Just thought I'd mention it. I'll keep running it, and prefer a long running test for +1 week before I can give this a thumbs up.

Then I'll start scaling to +10k subscribers and a shitload of metrics. As well as encrypting the connections with SSL. Just waiting for my ESP32. Got my Cortex M0 SoC with built in WiFi and BLE yesterday. Good times.

**Comment by zxshoe** [comment] 2016-02-20 11:33
Hmmm, now I'm a bit confused. So wouldn't mind some assistance here.
I reverted the change in mqtt_consumer.go above, and did the `gdm resore` you mentioned. The Telegraf mqtt_consumer failed after just a few minutes agan. After a restart it failed again after 5-10 minutes.

So I checked the patch you mentioned in the paho client. And compared with my local files, like org.eclipse.paho.mqtt.golang.git/ping.go. But my ping.go (even after the update above) doesn't seem to have the patch you mentioned?

Ang I tried to do a manual `go get -u` which fails with "Please specify which branch you want to merge with..." and since I'm not to familiar with go I updated the repo manually with git.

$ git pull --ff-only git://git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang master
From git://git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang
 * branch            master     -> FETCH_HEAD
Already up-to-date.

So it seems to be up to date?

But like I said; now I get the PINGREQ and PINGRESP (like I should) - but, now I get the `socket error` too like before. But I'm not sure I've got the latest paho source...

My entire ping.go is here http://pastebin.com/nqMEBp6r

1455965988: Sending PUBLISH to Telegraf-Consumer-KyXsW (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455965989: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (31 bytes))
1455965989: Sending PUBLISH to Telegraf-Consumer-KyXsW (d0, q0, r0, m0, 'sensors/pressure/', ... (31 bytes))
1455965991: Received PINGREQ from Telegraf-Consumer-KyXsW
1455965991: Sending PINGRESP to Telegraf-Consumer-KyXsW
1455965991: Socket error on client Telegraf-Consumer-KyXsW, disconnecting.
1455965991: New connection from 10.0.0.31 on port 1883.
1455965991: New client connected from 10.0.0.31 as Telegraf-Consumer-KyXsW (c1, k60).
1455965991: Sending CONNACK to Telegraf-Consumer-KyXsW (0, 0)
1455965994: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455965994: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455965994: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (31 bytes))
1455965999: Received PINGREQ from TheThing
1455965999: Sending PINGRESP to TheThing
1455965999: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455965999: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1455965999: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (31 bytes))
1455966001: Socket error on client Telegraf-Consumer-KyXsW, disconnecting.
1455966001: New connection from 10.0.0.31 on port 1883.
1455966001: New client connected from 10.0.0.31 as Telegraf-Consumer-KyXsW (c1, k60).
1455966001: Sending CONNACK to Telegraf-Consumer-KyXsW (0, 0)
1455966004: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1455966004: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))

**Comment by sparrc** [comment] 2016-02-20 14:34
Actually the patch won't be exactly as the one I linked above, that change was abandoned becausae the project maintainer claimed to have fixed the problem in a separate change that he merged. Thanks for the testint @zxshoe

**Comment by zxshoe** [comment] 2016-02-21 09:13
Me again :)

So running another 24h (with opts.SetKeepAlive(time.Duration(0)) ) and lo and behold if the darn thing didn't quit on me almost exactly at the same time this morning?!

1456033858: Error in poll: Interrupted system call.
1456033858: Reloading config.
1456033858: New connection from 10.0.0.31 on port 1883.
1456033858: New client connected from 10.0.0.31 as Telegraf-Consumer-jHXeL (c1, k0).
1456033858: Sending CONNACK to Telegraf-Consumer-jHXeL (0, 0)
1456033868: New connection from 10.0.0.174 on port 1883.
1456033868: New client connected from 10.0.0.174 as TheThing (c1, k15).
1456033868: Sending CONNACK to TheThing (0, 0)
1456033868: Received SUBSCRIBE from TheThing
1456033868:     inTopic (QoS 0)
1456033868: TheThing 0 inTopic
1456033868: Sending SUBACK to TheThing
1456033868: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1456033868: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1456033868: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (31 bytes))
1456033873: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1456033873: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1456033874: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (31 bytes))
1456033879: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/temperature/', ... (27 bytes))
1456033879: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/humidity/', ... (30 bytes))
1456033879: Received PUBLISH from TheThing (d0, q0, r0, m0, 'sensors/pressure/', ... (31 bytes))
1456033884: Received PINGREQ from TheThing
1456033884: Sending PINGRESP to TheThing

http://www.epochconverter.com: Your time zone: 2016-02-21 06:50:58 GMT+1:00
Yesterday it was 06:52 GMT+1:00

Coincedence? I don't think I have any high IO backups or anything running on the LAN. This is an isolated lab/dev environment.

Turning on debugging in telegraf.conf doesn't seem to increase verbosity in the log file. Am I missing something?

**Comment by sparrc** [comment] 2016-02-21 16:02
where's the socket error in the above output?

**Comment by zxshoe** [comment] 2016-02-21 17:11
There is none. Sorry, I was unclear. The error at 06:5x is the first in the log. It was the same at both occurances.

1456033858: Error in poll: Interrupted system call.

So perhaps this in unrelated to the initial issue.

**Comment by sparrc** [comment] 2016-02-21 17:19
could be related, but sounds like the MQTT broker may have received a SIGHUP? because the next line it says it is reloading the config

**Comment by zxshoe** [comment] 2016-02-21 17:33
Noticed that too. But I don't see why that would have happened. Perhaps logrotation. But why would that have killed the mqtt_consumer at the same time?

**Comment by zxshoe** [comment] 2016-02-21 17:50
Yeah. Seems to be the case. Telegraf looses the connection when mosquitto restarts after a SIGHUP and can't reconnect properly.

A `/usr/bin/killall -HUP mosquitto && /usr/bin/killall -HUP telegraf` fixes the problem. A workaround for now I guess. But I guess someone should try to figure out why telegraf doesn't reconnect again.

**Comment by sparrc** [comment] 2016-02-22 18:06
@zxshoe Are you using the 0.10.3 build? I can't reproduce this problem, when I SIGHUP mosquitto my mqtt output and consumers both keep running fine.

Did you adjust `opts.SetAutoReconnect(true)` in your build?

**Comment by sparrc** [comment] 2016-03-02 11:25
closing this as I can't reproduce, please re-open if it's still an issue

**Closed by sparrc** 2016-03-02 11:25 UTC
