### ISSUE TITLE
input plugins in Windows

### ISSUE THREAD

**Issue by AliGouta** [influxdata/telegraf#1183] opened 2016-05-11 08:37 UTC
Using telegraf in windows environement, I figured out that when configuring the input plugins in seperate files (say cpu.conf, mem.conf ...). Then, when starting the telegraf service, Telegraf only loads one single file... I had to dump all files in one global file that includes all config sections. 
In linux, everything works fine.

**Comment by sparrc** [comment] 2016-05-11 15:13
this is a dupe of #1137

**Closed by sparrc** 2016-05-11 15:13 UTC
