### ISSUE TITLE
Telergraf is reading the files from the beginning on every update of log file

### ISSUE THREAD

**Issue by PrasaanthSekar** [influxdata/telegraf#4513] opened 2018-08-03 09:39 UTC
### Relevant telegraf.conf:
```
[[inputs.logparser]]
   files = ["/apps/*.log"]
   from_beginning = false
   [inputs.logparser.grok]
     patterns = <MyPattern>
```
### System info:

Telegraf version - 1.7.1, 
operating system name - CentOS 7

### Steps to reproduce:

1. Point to any log file based on the grok pattern
2. Start the telegraf service.
3. Update some log lines

### Expected behavior:
Telegraf is expected to read only the log lines that has been added new

### Actual behavior:
Telegraf reads the log file from the beginning on every update of the log file

**Comment by danielnelson** [comment] 2018-08-03 19:36
I am not able to reproduce, here is what I tried, can you check how this behaves on your system?

```
[[inputs.logparser]]
  files = ["*.log"]
  from_beginning = false
  [inputs.logparser.grok]
    patterns = ["%{NUMBER:value}"]

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

Log file with some existing data:
```
$ cat foo.log
1
2
3
4
5
```

Start telegraf and in another terminal append to the logfile:
```
$ echo 6 >> foo.log
$ echo 7 >> foo.log
$ echo 8 >> foo.log
```

Output from Telegraf:
```
logparser_grok,path=foo.log value="3" 1533324873599775809
logparser_grok,path=foo.log value="4" 1533324876827593580
logparser_grok,path=foo.log value="5" 1533324878630493154
```

**Comment by PrasaanthSekar** [comment] 2018-08-06 05:15
Yes. I am not able to reproduce the issue in your case. 
That's weird. I am trying to push my parsed log lines to a Kafka queue where I see the entire log file getting pushed on every update.

**Comment by danielnelson** [comment] 2018-08-06 18:44
I'm going to close this issue but if you are able to figure out what the issue is, please comment here and we can reopen if needed.

**Closed by danielnelson** 2018-08-06 18:44 UTC
Labels: area/logparser, need more info
