### ISSUE TITLE
More flexibility in adding the "Authorization" header for inputs.http plugin

### ISSUE THREAD

**Issue by djvanhelmond** [influxdata/telegraf#10386] opened 2022-01-05 21:26 UTC
## Feature Request
As far as I know, there is no way to add an "Authorization" header with the headers = {"Authorization" = "KEYSHERE"} parameter.
Either you use basic auth or a bearer token in an external file, with pretty much generate either:

{"Authorization" = Basic "KEY-HERE"}
{"Authorization" = Bearer "KEY-HERE"}

Opening a feature request kicks off a discussion.

### Proposal:
I want to have the capability to fully construct the Authorization header to allow different authorization types.

### Current behavior:
-

### Desired behavior:
- 

### Use case: 

I want to read from the Tedee API (api.tedee.com) which support Oauth2.0 and a Personal Access Key which a user can generate in the Tedee portal. The PAK is like a shared secret, so much easier to use than OAuth, hence I prefer the PAK way of authenticating with Tedee.

With the following command, I can read the battery level of the Tedee lock.
curl -X GET https://api.tedee.com/api/v1.25/my/device/{DEVICE_ID}/battery -H 'content-type: application/json' -H 'Authorization: PersonalKey {KEY}'

Unfortunately I can't re-construct this query in inputs.http plugin, since the Authorization header is required in the following form:

**'Authorization: PersonalKey {KEY}'**

I can't see a way to get the keyword "PersonalKey" in the Authorization value field.

**Comment by powersj** [comment] 2022-01-05 21:35
There is a generic optional HTTP header configuration value, is that something that works in this case?

```
  ## Optional HTTP headers
  # headers = {"X-Special-Header" = "Special-Value"}
```

**Comment by djvanhelmond** [comment] 2022-01-06 05:31
I tried that but I get the impression that the Authorization header is somehow different and a special case that can't be created with this headers option.

Also, is there a way to get some debug info on which HTTP request incl header and body telegraf actually creates and sends out?

**Comment by powersj** [comment] 2022-01-06 14:23
> I tried that but I get the impression that the Authorization header is somehow different and a special case that can't be created with this headers option.
> 

That is not the case. As you can see with your curl command authorization is just another header. In Telegraf, should you use one of the bearer options, then yes it is set up differently, but in your case if you need something specific you should use the headers option.

> Also, is there a way to get some debug info on which HTTP request incl header and body telegraf actually creates and sends out?

Unfortunately, no.

I am going to go ahead and close this as the headers option is the solution here.

**Comment by djvanhelmond** [comment] 2022-01-06 21:24
So maybe it is not the authorisation header that breaks the comms with the tedee API.

I structured a working curl request towards the Tedee API (https). 
Then I do the identically structured request but then unencrypted and I tcpdumped the http headers.

Raw dump of http header:

```
Hypertext Transfer Protocol
    GET / HTTP/1.1\r\n
        Request Method: GET
        Request URI: <URI-GOES-HERE>
        Request Version: HTTP/1.1
    Host: HOST-GOES-HERE\r\n
    User-Agent: Go-http-client/1.1\r\n
    Accept: application/json\r\n
    Accept-Encoding: json\r\n
    Authorization: PersonalKey KEY-GOES-HERE=\r\n
    \r\n

```

I 100% copy these headers into the http.input.conf file (below), but I still get the gateway 502 error.

`headers = {"User-Agent" = "Go-http-client/1.1", "Accept" = "application/json", "Accept-Encoding" = "json", "Authorization" = "PersonalKey KEY-GOES-HERE"}
`

I can't dump the actual request as it is HTTPS, so at the moment I'm missing debug capabilities in telegraf. I'd like to see the raw query and preferably an option to log the same type of output that you get with "curl -v".

**Comment by powersj** [comment] 2022-01-06 21:46
> the gateway 502 error.

That's a server-side error, but I understand it can be the result of bad input from a user

Using this config:

```toml
[[inputs.http]]
  urls = ["http://google.com"]
  headers = { "Accept" = "applicaiton/json", "Authorization" = "PersonalKey KEY-GOES-HERE" }
```

I added some debug output to print the headers and got:

```
2022-01-06T21:39:26Z D! [inputs.http] 'Accept: applicaiton/json'
2022-01-06T21:39:26Z D! [inputs.http] 'Authorization: PersonalKey KEY-GOES-HERE'
```

That seems to line up right? 

If you could show me some way to reproduce this we might be more help, but based on the above output it does look like Telegraf is doing exactly what it should be doing. If you are concerned the packet doesn't look right, you could use HTTP, and rip it apart since the endpoint isn't working in the first place.

Other ideas?

**Comment by djvanhelmond** [comment] 2022-01-06 22:00
Yeah that does seem right. Can you share with me a (statically compiled?) x86_64 binary of Telegraf with the extended debug?

**Comment by powersj** [comment] 2022-01-06 22:55
I put up a [draft PR](https://github.com/influxdata/telegraf/pull/10396), in a bit you can download artifacts with the debug output. This is what I have it print out:

```
2022-01-06T22:49:46Z D! [inputs.http] GET http://google.com
2022-01-06T22:49:46Z D! [inputs.http]   Authorization: [PersonalKey KEY-GOES-HERE]
2022-01-06T22:49:46Z D! [inputs.http]   Accept: [applicaiton/json]
2022-01-06T22:49:46Z D! [inputs.http] ''
```

First line is the method and URL
The next lines are headers (2-3 in this case)
Last line is the body, here an empty string

Let me know if there are other fields that might be helpful. I am going to re-open this issue and if we find this debug output helpful, I am going to see what the team thinks about adding this in.

Good luck and let me know what you find!

**Comment by djvanhelmond** [comment] 2022-01-07 20:28
Thanks for the PR with the debug code. I tried it.

`ubuntu@devbox:~/src/telegraf/cmd/telegraf$ ./telegraf --config ~/telegraf/telegraf.conf --test --once`
`2022-01-07T20:13:06Z I! Starting Telegraf`
`2022-01-07T21:13:06+01:00 I! Loaded inputs: http`
`2022-01-07T21:13:06+01:00 I! Loaded aggregators:`
`2022-01-07T21:13:06+01:00 I! Loaded processors:`
`2022-01-07T21:13:06+01:00 I! Loaded outputs: influxdb_v2`
`2022-01-07T21:13:06+01:00 I! Tags enabled: host=test-MAC`
`2022-01-07T21:13:06+01:00 D! [agent] Initializing plugins`
`2022-01-07T21:13:06+01:00 D! [agent] Connecting outputs`
`2022-01-07T21:13:06+01:00 D! [agent] Attempting connection to [outputs.influxdb_v2]`
`2022-01-07T21:13:06+01:00 D! [agent] Successfully connected to outputs.influxdb_v2`
`2022-01-07T21:13:06+01:00 D! [agent] Starting service inputs`
`2022-01-07T21:13:06+01:00 D! [inputs.http] GET https://api.tedee.com/api/v1.25/my/device/22011/battery`
`2022-01-07T21:13:06+01:00 D! [inputs.http]   Accept-Encoding: [json]`
`2022-01-07T21:13:06+01:00 D! [inputs.http]   Authorization: [PersonalKey <KEYKEYKEY>]`
`2022-01-07T21:13:06+01:00 D! [inputs.http]   User-Agent: [Go-http-client/1.1]`
`2022-01-07T21:13:06+01:00 D! [inputs.http]   Accept: [application/json]`
`2022-01-07T21:13:06+01:00 D! [inputs.http] ''`
`2022-01-07T21:13:06+01:00 E! [inputs.http] Error in plugin: [url=https://api.tedee.com/api/v1.25/my/device/22011/battery]: received status code 502 (Bad Gateway), expected any value out of [200]`
`2022-01-07T21:13:06+01:00 D! [agent] Stopping service inputs`
`2022-01-07T21:13:06+01:00 D! [agent] Input channel closed`
`2022-01-07T21:13:06+01:00 I! [agent] Hang on, flushing any cached metrics before shutdown`
`2022-01-07T21:13:06+01:00 D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics`
`2022-01-07T21:13:06+01:00 I! [agent] Stopping running outputs`
`2022-01-07T21:13:06+01:00 D! [agent] Stopped Successfully`
`2022-01-07T21:13:06+01:00 E! [telegraf] Error running agent: input plugins recorded 1 errors`

So I get the bad gateway response again, although the options seem right from the output. But I only get the gateway 502 error with the telegraf http input plugin.

With curl:
`ubuntu@devbox:~/tsrc/telegraf/cmd/telegraf$ curl -X GET https://api.tedee.com/api/v1.25/my/device/22011/battery \ -H 'User-Agent: Go-http-client/1.1'  -H 'content-type: application/json' -H 'Authorization: PersonalKey <KEY>' \ -H 'Accept-Encoding: json'`
`{"result":{"level":64,"date":"2022-01-07T15:51:03.659"},"success":true,"errorMessages":[],"statusCode":200}`

With wget:
`ubuntu@devbox:~/tsrc/telegraf/cmd/telegraf$ wget -qO- --header="User-Agent: Go-http-client/1.1" --header='content-type: application/json' --header='Authorization: PersonalKey <KEYKEYKEY>' --header='Accept-Encoding: json' https://api.tedee.com/api/v1.25/my/device/22011/battery`
`{"result":{"level":64,"date":"2022-01-07T15:51:03.659"},"success":true,"errorMessages":[],"statusCode":200}`
`

And with postman I also get the json back. So it appears that the http plugin behaves somewhat differently compared to other http clients.

**Comment by djvanhelmond** [comment] 2022-01-07 20:29
`[[inputs.http]]`
`  # Read the battery status of the Tedee lock`
`  urls = [ "https://api.tedee.com/api/v1.25/my/device/22011/battery" ]`
`  method = "GET"`
`  headers = {"User-Agent" = "Go-http-client/1.1", "Accept" = "application/json", "Accept-Encoding" = "json", "Authorization" = "<KEYKEYKEY"}`
`  data_format = "json"`
`  [inputs.http.tags]`
`    influxdb_bucket= "Test"`
`    source = "Tedee"`

**Comment by powersj** [comment] 2022-01-07 21:26
Thank you for trying that out and give me a bit more info! Given it does not appear to be even hitting the backend server, I can also reproduce the 502:

```
2022-01-07T20:59:53Z D! [inputs.http] &{GET https://api.tedee.com/api/v1.25/my/device/22011/battery HTTP/1.1 1 1 map[Accept:[application/json] Accept-Encoding:[json] Authorization:[<KEYKEYKEY] User-Agent:[Go-http-client/1.1]] {0xc000c14a00} <nil> 0 [] false api.tedee.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0001a2000}
2022-01-07T20:59:53Z E! [inputs.http] Error in plugin: [url=https://api.tedee.com/api/v1.25/my/device/22011/battery]: received status code 502 (Bad Gateway), expected any value out of [200]
```

The only thing that I could think of is the body of the HTTP request. In Telegraf, we build using a `io.NopCloser` and I think a little junk ends up in the request body. Given there should not be a body in this request at all, I wondered if I set it to `nil` would I get further. Sure enough, I got the 401 I was expecting:

```
2022-01-07T21:01:33Z D! [inputs.http] &{GET https://api.tedee.com/api/v1.25/my/device/22011/battery HTTP/1.1 1 1 map[Accept:[application/json] Accept-Encoding:[json] Authorization:[<KEYKEYKEY] User-Agent:[Go-http-client/1.1]] <nil> <nil> 0 [] false api.tedee.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000740a8}
2022-01-07T21:01:34Z E! [inputs.http] Error in plugin: [url=https://api.tedee.com/api/v1.25/my/device/22011/battery]: received status code 401 (Unauthorized), expected any value out of [200]
```

I have updated the [MP](https://github.com/influxdata/telegraf/pull/10396) with a check for an empty body. Once those new artifacts build, in ~20mins, can you give it another shot?

Thanks!

**Comment by djvanhelmond** [comment] 2022-01-08 06:23
SUCCESS!

`ubuntu@devbox:~/t3/telegraf/cmd/telegraf$ ./telegraf --config ~/telegraf/telegraf.conf --test -once`
`2022-01-08T06:20:35Z I! Starting Telegraf`
`2022-01-08T07:20:35+01:00 I! Loaded inputs: http`
`2022-01-08T07:20:35+01:00 I! Loaded aggregators:`
`2022-01-08T07:20:35+01:00 I! Loaded processors:`
`2022-01-08T07:20:35+01:00 I! Loaded outputs: influxdb_v2`
`2022-01-08T07:20:35+01:00 I! Tags enabled: host=test-MAC`
`2022-01-08T07:20:35+01:00 D! [agent] Initializing plugins`
`2022-01-08T07:20:35+01:00 D! [agent] Connecting outputs`
`2022-01-08T07:20:35+01:00 D! [agent] Attempting connection to [outputs.influxdb_v2]`
`2022-01-08T07:20:35+01:00 D! [agent] Successfully connected to outputs.influxdb_v2`
`2022-01-08T07:20:35+01:00 D! [agent] Starting service inputs`
`2022-01-08T07:20:35+01:00 D! [agent] Stopping service inputs`
`2022-01-08T07:20:35+01:00 I! [agent] Hang on, flushing any cached metrics before shutdown`
`2022-01-08T07:20:35+01:00 D! [agent] Input channel closed`
`2022-01-08T07:20:36+01:00 D! [outputs.influxdb_v2] Wrote batch of 1 metrics in 195.253727ms`
`2022-01-08T07:20:36+01:00 D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics`
`2022-01-08T07:20:36+01:00 I! [agent] Stopping running outputs`
`2022-01-08T07:20:36+01:00 D! [agent] Stopped Successfully`



Thank you so much!!
I have this binary running in my environment now, but it would be great if it could be merged in master, as I prefer to use vanilla docker images as much as possible.

**Closed** 2022-01-11 16:22 UTC
Labels: feature request
