### ISSUE TITLE
json_v2 fails if input data contains null values

### ISSUE THREAD

**Issue by igomura** [influxdata/telegraf#10358] opened 2021-12-30 22:07 UTC
### Relevent telegraf.conf

```toml
[[inputs.file]]
  files = ["config.json"]
  data_format = "json_v2"

  [[inputs.file.json_v2]]
    measurement_name = "info.config"
    [[inputs.file.json_v2.object]]
      path = "config"
```

### Logs from Telegraf

2021-12-30T21:56:57Z E! [inputs.file] Error in plugin: unknown format '<nil>' for field  'storage_redis_caCertificates'

### System info

telegraf-1.19.0-0.1.x86_64, CentOS 7

### Steps to reproduce

Input data file:
`{
  "config": {
    "apikey": "*",
    "ipAddressEnabled": true,
    "initialization": {
      "timeoutMS": 10000,
      "forceFreshStartup": false
    },
    "storage": {
      "type": "redis",
      "redis": {
        "host": "localhost",
        "port": 6379,
        "tlsServerName": "",
        "caCertificates": null,
        "tlsSkipNameValidation": false,
        "tlsClientCertificate": "",
        "tlsClientKey": ""
      }
    }
  }
}
`

### Expected behavior

parsed data

### Actual behavior

the plugin fail to read data when one of json attributes has a value *null*
In my example this is `"caCertificates": null`

**Comment by powersj** [comment] 2022-01-04 16:12
This looks like a fix for `null` in json_v2 parser was in https://github.com/influxdata/telegraf/pull/9368 which did go out in https://github.com/influxdata/telegraf/releases/tag/v1.19.0

Are you sure you are running 1.19.0?

I was unable to reproduce this with master:

```
❯ ./telegraf --config config.toml 
2022-01-04T16:12:13Z I! Starting Telegraf 1.22.0-aee26768
2022-01-04T16:12:13Z I! Loaded inputs: file
2022-01-04T16:12:13Z I! Loaded aggregators: 
2022-01-04T16:12:13Z I! Loaded processors: 
2022-01-04T16:12:13Z I! Loaded outputs: file
2022-01-04T16:12:13Z I! Tags enabled: host=ryzen
2022-01-04T16:12:13Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ryzen", Flush Interval:10s
info.config,host=ryzen apikey="*",ipAddressEnabled=true,initialization_timeoutMS=10000,initialization_forceFreshStartup=false,storage_type="redis",storage_redis_host="localhost",storage_redis_port=6379,storage_redis_tlsServerName="",storage_redis_tlsSkipNameValidation=false,storage_redis_tlsClientCertificate="",storage_redis_tlsClientKey="" 1641312740000000000
```

So I am going to go ahead and close this as I think getting a newer version of Telegraf is your best bet.

**Closed by powersj** 2022-01-04 16:12 UTC
Labels: bug, area/redis
