### ISSUE TITLE
Require secret store password for viewing contents of os.secrets

### ISSUE THREAD

**Issue by jackbenimble999** [influxdata/telegraf#12650] opened 2023-02-08 15:55 UTC
### Use Case

When the user specifies this command:

telegraf --config telegraf_mqtt_to_influxdb.conf secrets list --reveal-secret  os_secrets

It will show the contents of all the secrets in the os.secrets. 

Please require a password to be specified when creating os.secrets, then require that passwordrevealing the contents of the os.secret store:

for example:

telegraf --config telegraf_mqtt_to_influxdb.conf secrets list --reveal-secret  os_secrets --password [os secret store password]

Thanks!

### Expected behavior

1. telegraf --config telegraf_mqtt_to_influxdb.conf secrets list --reveal-secret  os_secrets --password [os secret store password]
2. Secrets are shown

If password is not specified: 
1. telegraf --config telegraf_mqtt_to_influxdb.conf secrets list --reveal-secret  os_secrets
2. Error message is displays "password required" 

### Actual behavior

1. telegraf --config telegraf_mqtt_to_influxdb.conf secrets list --reveal-secret  os_secrets --password [os secret store password]
2. Secrets are shown

If password is not specified: 
1. telegraf --config telegraf_mqtt_to_influxdb.conf secrets list --reveal-secret  os_secrets
2. Secrets are shown

**Comment by srebhan** [comment] 2023-02-08 18:21
Which secret-store type are you using @jackbenimble999? Can you share the redacted configuration?

**Comment by jackbenimble999** [comment] 2023-02-08 20:24
Hi @srebhan ,

In this case, I was asking for the password to be required for os.secrets. I don't believe it's currently required. The following configuration does not require a password to create or view secrets (unlike secretstores.jose, which requires a password to be manually entered. I will make another request to allow a "secret-store-password" to be specified on the command line for that one). 

Here is the confuration:

# Telegraf Configuration

[agent]
  ## Log at debug level.
  debug = false
  quiet = false
  

###############################################################################
#                             SECRET STORE OS                                 #
###############################################################################
  
  
  [[secretstores.os]]
  id = "os_secrets"
  
    
###############################################################################
#                             INPUT PLUGINS                                   #
###############################################################################

  
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]

  ## Topics that will be subscribed to.
  topics = [
 	"influxtopic/#",
  ]

  qos = 2

  max_undelivered_messages = 1000

  persistent_session = true

  client_id = "InfluxDataStandalone"

  username = "admin"

  
  password = "@{os_secrets:my_secret_password}"

  data_format = "influx"




###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


[[outputs.influxdb_v2]]

  urls = ["http://127.0.0.1:8086"]
  
  token = "@{os_secrets:my_secret_token}"
  organization = "SICK"

  bucket = "events"

#[[outputs.file]]
#  files = ["stdout"]

**Comment by srebhan** [comment] 2023-02-23 11:33
This is a duplicate of #12661. Closing as passwords are not supported by operating systems' credential managers so there is no point to add one to Telegraf as this will not add any security.

**Closed by srebhan** 2023-02-23 11:33 UTC
Labels: feature request, plugin/secretstores
