### ISSUE TITLE
ZooKeeper Input Plugin writes float values as strings

### ISSUE THREAD

**Issue by xakassi** [influxdata/telegraf#8863] opened 2021-02-16 13:06 UTC
Hi, guys!

ZooKeeper Input Plugin interpret float values as strings. You can check the code here:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/zookeeper/zookeeper.go#L152

It leads to the situation when Prometheus Output Plugin has lots of labels, because it interprets string metrics as labels. And also we cannot use these metrics in Prometheus!

Please, look at this example, here `avg_latency` is written as a label:
`zookeeper_min_latency{avg_latency="3.8042",port="2181",project_name="zookeeper-service-test",server="zookeeper-1",state="leader"} 0`

And there are also metrics with lots of labels, please, see:
`zookeeper_prep_processor_request_queued{avg_admin_read_per_namespace="84.25",avg_admin_write_per_namespace="13.0",avg_brokers_read_per_namespace="147.5815",avg_brokers_write_per_namespace="95.9732",avg_close_session_prep_time="0.0",avg_cluster_read_per_namespace="96.2",avg_cluster_write_per_namespace="32.0",avg_commit_commit_proc_req_queued="0.6415",avg_commit_process_time="0.2647",avg_commit_propagation_latency="5.1162",avg_concurrent_request_processing_in_commit_processor="1.0",avg_config_read_per_namespace="176.1143",avg_config_write_per_namespace="31.5714",avg_connection_token_deficit="0.0",avg_consumers_read_per_namespace="78.0",avg_consumers_write_per_namespace="10.0",avg_controller_epoch_read_per_namespace="85.5",avg_controller_epoch_write_per_namespace="18.0",avg_controller_read_per_namespace="106.0",avg_controller_write_per_namespace="65.0",avg_dbinittime="87.0",avg_dead_watchers_cleaner_latency="0.0",avg_election_time="854.0",avg_follower_sync_time="131.0",avg_fsynctime="0.7422",avg_inflight_diff_count="0.0",avg_inflight_snap_count="0.0",avg_isr_change_notification_read_per_namespace="92.0",avg_isr_change_notification_write_per_namespace="24.0",avg_jvm_pause_time_ms="0.0",avg_latency="1.7906",avg_latest_producer_id_block_read_per_namespace="135.6667",avg_latest_producer_id_block_write_per_namespace="72.0",avg_local_write_committed_time_ms="0.7699",avg_log_dir_event_notification_read_per_namespace="95.0",avg_log_dir_event_notification_write_per_namespace="27.0",avg_netty_queued_buffer_capacity="0.0",avg_node_changed_watch_count="0.0",avg_node_children_watch_count="0.0",avg_node_created_watch_count="0.0",avg_node_deleted_watch_count="0.0",avg_om_commit_process_time_ms="0.0",avg_om_proposal_process_time_ms="0.0",avg_pending_session_queue_size="1.0",avg_prep_process_time="0.0",avg_prep_processor_queue_size="0.0",avg_prep_processor_queue_time_ms="0.0",avg_propagation_latency="6.4621",avg_proposal_ack_creation_latency="4.7058",avg_proposal_latency="2.1641",avg_quorum_ack_latency="0.0",avg_read_commit_proc_issued="0.4338",avg_read_commit_proc_req_queued="0.4338",avg_read_commitproc_time_ms="0.2201",avg_read_final_proc_time_ms="0.157",avg_readlatency="0.61",avg_reads_after_write_in_session_queue="0.0",avg_reads_issued_from_session_queue="0.0",avg_requests_in_session_queue="1.0",avg_server_write_committed_time_ms="1.0247",avg_session_queues_drained="0.2854",avg_snapshottime="0.0",avg_startup_snap_load_time="0.0",avg_startup_txns_load_time="0.0",avg_startup_txns_loaded="0.0",avg_sync_process_time="0.0846",avg_sync_processor_batch_size="1.1282",avg_sync_processor_queue_and_flush_time_ms="2.5669",avg_sync_processor_queue_flush_time_ms="1.463",avg_sync_processor_queue_size="0.3985",avg_sync_processor_queue_time_ms="0.6402",avg_time_waiting_empty_pool_in_commit_processor_read_ms="0.0013",avg_updatelatency="5.8496",avg_write_batch_time_in_commit_processor="0.4962",avg_write_commit_proc_issued="1.0",avg_write_commit_proc_req_queued="0.2518",avg_write_commitproc_time_ms="4.9646",avg_write_final_proc_time_ms="0.4811",avg_zookeeper_read_per_namespace="131.1667",avg_zookeeper_write_per_namespace="299.0",connection_drop_probability="0.0",endpoint="prometheus-cli",host="zookeeper-monitoring",instance="10.233.60.218:8096",job="zookeeper-monitoring",namespace="ocs-f7l2i99hn2-zk",peer_state="following",pod="zookeeper-monitoring-5f4448987d-cb5w5",port="2181",project_name="ocs-f7l2i99hn2-zk",server="zookeeper-1",service="zookeeper-monitoring",state="follower",version="3.6.2--803c7f1a12f85978cb049af5e4ef23bd8b688715"}`

It is a horrible situation.

Could we process float values in a better way here?
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/zookeeper/zookeeper.go#L152

**Comment by xakassi** [comment] 2021-02-16 13:27
Now I use `fieldpass` filter to discard not necessary fields (which is written as labels) and also use `processors.converter` to convert necessary metrics to float.

So it is a work around.

But maybe float values can be just processed better in ZooKeeper Input Plugin code?

**Comment by helenosheaa** [comment] 2021-05-13 16:47
Sorry no one got back to you on this sooner but glad you found a workaround! I'm going to close this as it's a duplicate of #7567 but feel free to also add a comment in the thread on the other issue.

**Closed by helenosheaa** 2021-05-13 16:47 UTC
Labels: area/prometheus, bug
