### ISSUE TITLE
flush_interval / flush_jitter  not doing what expected

### ISSUE THREAD

**Issue by daviesalex** [influxdata/telegraf#1293] opened 2016-05-29 15:47 UTC
We have set this:

```
[agent]
  flush_interval = "10s"
  flush_jitter = "10s"
```

What we want is that telegraf flushes every ten seconds, +/- 10 seconds. With enough nodes, this will result in a uniform load and avoid any microbursts.

What we actually see is that each agent picks a random time, and sticks to it. This is bad:
* Even at our scale, this isnt resulting in a uniform distribution as picking a random time per flush would
* Its 16.00 seconds. We have microbursts on the second (our timesync is very good). The mean difference between packets in tcpdump in this case is 16.001427000 seconds and variance minimal.

Here is a tcpdump of the server showing an even set of packets coming in from one client:
![image](https://cloud.githubusercontent.com/assets/1106249/15634488/00f0ffb2-25bd-11e6-830f-9b2b24279064.png)

If we plot the time between packets in wireshark, we see its exactly 16,00 seconds for each burst.

The client log shows the same:
```
[root@host1~]# grep "wrote batch" /var/log/telegraf/telegraf.log | tail
2016/05/29 07:28:22 Output [influxdb] wrote batch of 32 metrics in 319.224µs
2016/05/29 07:28:22 Output [influxdb] wrote batch of 32 metrics in 413.21µs
2016/05/29 07:28:38 Output [influxdb] wrote batch of 32 metrics in 264.434µs
2016/05/29 07:28:38 Output [influxdb] wrote batch of 32 metrics in 261.492µs
2016/05/29 07:28:54 Output [influxdb] wrote batch of 25 metrics in 253.743µs
2016/05/29 07:28:54 Output [influxdb] wrote batch of 25 metrics in 374.704µs
2016/05/29 07:29:10 Output [influxdb] wrote batch of 23 metrics in 322.524µs
2016/05/29 07:29:10 Output [influxdb] wrote batch of 23 metrics in 487.075µs
2016/05/29 07:29:26 Output [influxdb] wrote batch of 32 metrics in 482.082µs
2016/05/29 07:29:26 Output [influxdb] wrote batch of 32 metrics in 729.194µs
```
22 -> 38 -> 54 -> 10 -> 26 is obviously exactly 16.

Another client shows 10:
```
[root@host2 ~]# grep "wrote batch" /var/log/telegraf/telegraf.log | tail
2016/05/29 07:35:03 Output [influxdb] wrote batch of 16 metrics in 183.542µs
2016/05/29 07:35:03 Output [influxdb] wrote batch of 16 metrics in 184.473µs
2016/05/29 07:35:13 Output [influxdb] wrote batch of 16 metrics in 172.352µs
2016/05/29 07:35:13 Output [influxdb] wrote batch of 16 metrics in 159.924µs
2016/05/29 07:35:23 Output [influxdb] wrote batch of 16 metrics in 169.777µs
2016/05/29 07:35:23 Output [influxdb] wrote batch of 16 metrics in 139.105µs
2016/05/29 07:35:33 Output [influxdb] wrote batch of 16 metrics in 111.461µs
2016/05/29 07:35:33 Output [influxdb] wrote batch of 16 metrics in 257.57µs
2016/05/29 07:35:43 Output [influxdb] wrote batch of 22 metrics in 171.405µs
2016/05/29 07:35:43 Output [influxdb] wrote batch of 22 metrics in 189.031µs
```
And another 20:
```
[root@host3 ~]# grep "wrote batch" /var/log/telegraf/telegraf.log | tail
2016/05/29 07:34:40 Output [influxdb] wrote batch of 32 metrics in 370.291µs
2016/05/29 07:34:40 Output [influxdb] wrote batch of 32 metrics in 403.677µs
2016/05/29 07:34:59 Output [influxdb] wrote batch of 32 metrics in 226.281µs
2016/05/29 07:34:59 Output [influxdb] wrote batch of 32 metrics in 241.475µs
2016/05/29 07:35:19 Output [influxdb] wrote batch of 42 metrics in 239.915µs
2016/05/29 07:35:19 Output [influxdb] wrote batch of 42 metrics in 221.367µs
2016/05/29 07:35:39 Output [influxdb] wrote batch of 38 metrics in 195.99µs
2016/05/29 07:35:39 Output [influxdb] wrote batch of 38 metrics in 221.801µs
2016/05/29 07:35:58 Output [influxdb] wrote batch of 32 metrics in 195.303µs
2016/05/29 07:35:58 Output [influxdb] wrote batch of 32 metrics in 196.709µs
```

What we want is that for this period to be randomized (by the jitter value) for each burst, and that randomization to be to the nanosecond (not second) so its truly random.

**Comment by kostasb** [comment] 2016-05-30 14:50
The flush_jitter has been implemented as such by design, as described under v0.2 changelog:

https://github.com/influxdata/telegraf/blob/d5add07c0b2636563fbcd334b539149bea853765/CHANGELOG.md#v020-2015-10-27

The scope for this feature was that each individual Telegraf instance will flush data at its own fixed interval, so that flushes by different Telegraf instances at the same time will be avoided.

Thus the FlushInterval.Duration is only calculated once, at daemon startup:
https://github.com/influxdata/telegraf/blob/c44ecf54a5eb1c6ff44ad68a986068d223f4ae73/agent/agent.go#L311

So the flush interval is the same for each flush cycle on the same agent:
```
2016/05/30 17:15:18 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"kubuntu", Flush Interval:18.852840233s 
2016/05/30 17:15:39 Output [influxdb] wrote batch of 25 metrics in 3.040052ms
2016/05/30 17:15:57 Output [influxdb] wrote batch of 28 metrics in 2.951867ms
2016/05/30 17:16:16 Output [influxdb] wrote batch of 28 metrics in 2.698953ms
2016/05/30 17:16:35 Output [influxdb] wrote batch of 28 metrics in 3.073988ms
```

A jitter configuration parameter that will introduce variations between each flush operation for the same Telegraf agent should be a new feature request.

I am not sure if this functionality would be compatible with current agent logic though.

Here is the feature request:
https://github.com/influxdata/telegraf/issues/1296

**Closed by kostasb** 2016-05-30 14:50 UTC
