### ISSUE TITLE
global replace not working

### ISSUE THREAD

**Issue by danielarkins** [influxdata/telegraf#6087] opened 2019-07-08 16:49 UTC
expecting this to replace all occurences of / in fieldname to _per
perhaps this is not supported? my config looks like this:

```toml
[[processors.strings]]
	[[processors.strings.replace]]
		field = "*"
		old = "/"
		new = "_per"
```

but output still has / in field nmae. Also tried this but no luck

```toml
[[processors.strings]]
	[[processors.strings.replace]]
		field = ""
		old = "/"
		new = "_per"
```

**Comment by glinton** [comment] 2019-07-08 19:19
In the future, please follow the [provided template for issues](https://github.com/influxdata/telegraf/issues/new?template=Bug_report.md)

What version of telegraf are you running?

The following config works with telegraf 1.11. Note the processor doesn't get applied when running telegraf with `--test`
```toml
[agent]
  interval = "1s"
  flush_interval="1s"
  omit_hostname=true

[[inputs.exec]]
  command = "echo 'logfmt thing=\"stuff/\"'"
  data_format = "influx"

[[processors.strings]]
  [[processors.strings.replace]]
    field = "*"
    old = "/"
    new = "_per"

[[outputs.file]]
```

**Comment by danielnelson** [comment] 2019-07-08 19:33
Not sure if this is the cause, but recall that this plugin only supports modifying field values, and not field keys #5928

**Comment by glinton** [comment] 2019-07-08 19:41
Good point Daniel, I misread and assumed the desired behavior was to modify values.

**Comment by danielarkins** [comment] 2019-07-08 19:50
Ahhh
I want to globally modify the keys

**Comment by danielnelson** [comment] 2019-07-08 20:21
Okay I'm going to close this as a duplicate of #5928 then.

**Closed by danielnelson** 2019-07-08 20:21 UTC
Labels: need more info
