### ISSUE TITLE
Telegraf cloudwatch plugin not working for AWS/S3 name space

### ISSUE THREAD

**Issue by shaahulh** [influxdata/telegraf#1497] opened 2016-07-15 01:27 UTC
I am trying to use Telegraf cloudwatch plugin for retrieving AWS/S3 metrics and the plugin doesn't seem to list any metrics for S3. It works for EC2 and ELB but not for S3. The credentials and the other configs(I haven't listed them here are correct and they work for EC2 and ELB namespace). Buckets are already present for the keys used

```
 [[inputs.cloudwatch]]
# ## Amazon Region

   region = 'ap-southeast-2'
# ## Metric Statistic Namespace (required)

   namespace = "AWS/S3"
```

root@shaahul:/etc/telegraf# telegraf -config telegraf.conf -input-filter cloudwatch -test
- Plugin: cloudwatch, Collection 1
- Internal: 1m0s

Telegraf - version 0.13.1

**Comment by antoiner77** [comment] 2017-02-14 13:45
Same problem here :(

**Comment by sparrc** [comment] 2017-02-14 14:45
can you provide a full config file, and have you confirmed that it is not working on version 1.2.1?

**Comment by antoiner77** [comment] 2017-02-14 14:55
```
$- telegraf --version
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
```

```
[agent]
interval = "1m"
[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  database = "telegraf" # required
  retention_policy = ""
  write_consistency = "any"
  timeout = "10s"

[[inputs.cloudwatch]]
  region = "eu-west-1"
  period = "5m"
  delay = "5m"
  interval = "5m"
  ratelimit = 10
  namespace = "AWS/S3"

  [[inputs.cloudwatch.metrics]]
    names = ["BucketSizeBytes"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "BucketName"
      value = "xxx"
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "StorageType"
      value = "StandardStorage"
```
I have try to change period interval and delay without any success. I can get the metrics using aws cli so that's not a problem with my credentials 
Thanks

**Comment by sparrc** [comment] 2017-02-14 15:04
looks like this is a dupe of #1907, do any of the comments there help? can you leave any information there?

**Closed by sparrc** 2017-02-14 15:04 UTC
Labels: Need More Info
