### ISSUE TITLE
S.M.A.R.T not all devices get auto detected and read

### ISSUE THREAD

**Issue by DEvil0000** [influxdata/telegraf#15095] opened 2024-04-03 07:24 UTC
### Relevant telegraf.conf

```toml
[[inputs.smart]]
    use_sudo = true
    devices = []
```

### Logs from Telegraf

```text
don't matter, smart in general works fine
```

### System info

git: HEAD 806dc283 (does not matter, see below - lets call it master), ubuntu 20.04

### Steps to reproduce

1. run on HP G11 server
2. check if all physical raid disks are read

### Expected behavior

expecting all raid disks read which are returned by `smartctl --scan`

### Actual behavior

actual behavior is it reads out fine block devices listed but not the raid controllers physical disks.

### Additional info

I had a look at master code. The issue is that the scan only takes into account the device but not the `-d` parameter.
The output of my scan looks like that:
```
root@g11:~# smartctl --scan
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/sdb -d scsi # /dev/sdb, SCSI device
/dev/bus/0 -d megaraid,0 # /dev/bus/0 [megaraid_disk_00], SCSI device
/dev/bus/0 -d megaraid,1 # /dev/bus/0 [megaraid_disk_01], SCSI device
/dev/bus/0 -d megaraid,2 # /dev/bus/0 [megaraid_disk_02], SCSI device
```
code causing usage of `/dev/bus/0` (which is invalid) instead of `/dev/bus/0 -d megaraid,0` or full command `smartctl -a /dev/bus/0 -d megaraid,0` which would work.
As a additional note: the bus devices is actually not there as device and does not matter for that call since the megaraid stuff is working differently. device could by any for those calls.

see code at around using `dev[0]` only:
https://github.com/influxdata/telegraf/blob/199abd6bb9ec64afba7cbcfdd148e524ade0e511/plugins/inputs/smart/smart.go#L522

**Comment by DEvil0000** [comment] 2024-04-03 07:27
for completeness the output when command would be used in the correct way:
```
root@wsp68:~# smartctl -A /dev/bus/0 -d megaraid,0
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-173-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     49 C
Drive Trip Temperature:        60 C

Manufactured in week 26 of year 2023
Specified cycle count over device lifetime:  10000
Accumulated start-stop cycles:  16
Specified load-unload count over device lifetime:  300000
Accumulated load-unload cycles:  55
Elements in grown defect list: 0
```
```
root@wsp68:~# smartctl -a /dev/bus/0 -d megaraid,0
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-173-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HPE
Product:              EG001200JXLWA
Revision:             HPD8
Compliance:           SPC-4
User Capacity:        1,200,243,695,616 bytes [1.20 TB]
Logical block size:   512 bytes
Rotation Rate:        10000 rpm
Form Factor:          2.5 inches
Logical Unit id:      0x5000c500ec52e5a3
Serial number:        WFKE015Z
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Wed Apr  3 09:24:15 2024 CEST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Current Drive Temperature:     49 C
Drive Trip Temperature:        60 C

Manufactured in week 26 of year 2023
Specified cycle count over device lifetime:  10000
Accumulated start-stop cycles:  16
Specified load-unload count over device lifetime:  300000
Accumulated load-unload cycles:  55
Elements in grown defect list: 0

Error counter log:
           Errors Corrected by           Total   Correction     Gigabytes    Total
               ECC          rereads/    errors   algorithm      processed    uncorrected
           fast | delayed   rewrites  corrected  invocations   [10^9 bytes]  errors
read:          0        0         0         0          0       7294.436           0
write:         0        0         0         0          0        388.106           0
verify:        0        0         0         0          0       8404.232           0

Non-medium error count:      743

No Self-tests have been logged
```

**Comment by powersj** [comment] 2024-04-03 13:12
Hi,

This is a duplicate of #13090. We are working on a new plugin to use the JSON output from the `smartctl` command to actually collect all devices correctly. Feel free to try the artifacts in PR #15066 and let us know if it resolves the issue.

I'm going to close this as a duplicate.

**Closed by powersj** 2024-04-03 13:12 UTC
Labels: bug

**Comment by DEvil0000** [comment] 2024-04-04 15:11
I did see #13090 but it was not exactly about the same thing so I opened this ticket.
I however missed on #15066 - will comment there from now.
