### ISSUE TITLE
Modbus Plugin - Acquire metrics from two identical devices

### ISSUE THREAD

**Issue by AutomationTeam-ATeam** [influxdata/telegraf#11911] opened 2022-09-30 09:20 UTC
### Use Case

Hi Folks,

I am using the Modbus plugin to acquire metrics from two identical devices.
For this reason, the devices also have the same fields.
Unfortunately, when I configure the two devices the console gives me this error.
![image](https://user-images.githubusercontent.com/114593814/193224698-3bdcb2c1-bba2-439b-bf67-901065ca3028.png)
This problem, I seemed to understand, occurs because it is not possible to have two fields with the same name.

### Expected behavior

Entering two fields with the same name should not give an error.
Subsequently with additional [inputs.modbus.request.tags] it is possible to filter the data.
Here is an example of what a config file would look like
```
[[inputs.modbus.request]]
      slave_id = 1
      byte_order = "ABCD"
      register = "input"
      fields = [
      { address =200 , name = "Voltage" ,type =  "FLOAT32", measurement = "V",omit = false },
      ]

    [inputs.modbus.request.tags]
      element = "EleMeter 1"

[[inputs.modbus.request]]
      slave_id = 2
      byte_order = "ABCD"
      register = "input"
      fields = [
      { address =200 , name = "Voltage" ,type =  "FLOAT32", measurement = "V",omit = false },
      ]

    [inputs.modbus.request.tags]
      element = "EleMeter 2"
```

### Actual behavior

Currently, it is not possible to have fields with the same name.
This worsens the experience when making comparison queries between devices
Here is an example of how it is currently
```
[[inputs.modbus.request]]
      slave_id = 1
      byte_order = "ABCD"
      register = "input"
      fields = [
      { address =200 , name = "Voltage_1" ,type =  "FLOAT32", measurement = "V",omit = false },
      ]

    [inputs.modbus.request.tags]
      element = "EleMeter 1"

[[inputs.modbus.request]]
      slave_id = 2
      byte_order = "ABCD"
      register = "input"
      fields = [
      { address =200 , name = "Voltage_2" ,type =  "FLOAT32", measurement = "V",omit = false },
      ]

    [inputs.modbus.request.tags]
      element = "EleMeter 2"
```

### Additional info

With other plugins like opcua it is possible to have metrics with homonymous fields, so I think it is a limitation of the modbus plugin and not of telegraf.
Let me know if I've been clear enough and what you think

**Comment by srebhan** [comment] 2022-09-30 13:35
@AutomationTeam-ATeam thanks for reporting this issue! However, I cannot reproduce the problem with the attached config 
[modbus.conf.txt](https://github.com/influxdata/telegraf/files/9684581/modbus.conf.txt)

Reading the code, the [duplicate check](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/modbus/configuration_request.go#L256) respects the slave-id, register-type, measurement-name and field-name.

Are you sure that you do not have the same field defined twice **in the same slave**?

**Comment by srebhan** [comment] 2022-09-30 15:36
@AutomationTeam-ATeam if your case is similar to #11865, please checkout PR #11912 and let me know if it solves your issue! can you please check if PR https://github.com/influxdata/telegraf/pull/11912 solves your issue!? You can use the artifacts build by CI once it's finished.

**Comment by AutomationTeam-ATeam** [comment] 2022-10-04 12:34
Yes, my case is very similar to #11865 in my case I was using Modbus TCP to reproduce Modbus RTU.
I haven't read that just setting a different slave id to make the error disappear.
My mistake, the actual functioning is logical.
Thanks for the support @srebhan

**Comment by powersj** [comment] 2022-10-04 16:12
As #11912 is merged and it appears the slave id setting seems to have resolved this, I am going to close this issue. If I have missed something please do feel free to follow up.

**Closed by powersj** 2022-10-04 16:12 UTC
Labels: bug, area/modbus
