### ISSUE TITLE
regex behavior changed since 1.26

### ISSUE THREAD

**Issue by reimerp** [influxdata/telegraf#13460] opened 2023-06-17 14:03 UTC
### Relevant telegraf.conf

```toml
[[processors.regex]]
   [[processors.regex.tags]]
    key = "topic"
    pattern = "^[^/]*/([^/]*).*"
    replacement = "${1}"
```

### Logs from Telegraf

```text
topic="0}"
```

### System info

telegraf 1.25.3 / 1.26.0 and 1.27.0, docker-compose

### Docker

n/a

### Steps to reproduce

For telegraf 1.25.3 I used
`telegraf --config-directory /etc/telegraf.d`
and had:
agent, regex and output in `/etc/telegraf.conf` and various inputs in `/etc/telegraf.d/*.conf`.

while updating to 1.26 I had some issue with the documented behavior (see Release notes) so I restructured
to:
`/etc/telegraf/telegraf.conf` and `/etc/telegraf/telegraf.d/*,conf`

and skipped any config and config-directory arguments in a docker-compose setup.
I still have agent, regex and output in `/etc/telegraf/telegraf.conf`
It seems to work for agent and output definitions, BUT the regex seems not working anymore:

I had:
```
[[processors.regex.tags]]
    key = "topic"
    pattern = "^[^/]*/([^/]*).*"
    replacement = "${1}"
```    
to convert key topic from `something/important/stuff` to just `important` but this seems not to work anymore, i got
some strange values now:
`topic="0}"`
instead of `topic=important`

This behavior is for 1.26 and 1.27, so I switched back to 1.25.3.

Maybe there is something wrong in my regex, but its working in 1.25.3, even after config file restructuring.

### Expected behavior

topic=important

### Actual behavior

topic="0}"

**Comment by neelayu** [comment] 2023-06-18 07:55
Duplicate of #13432

**Comment by reimerp** [comment] 2023-06-18 08:57
It seems duplicate.
Had success with "$1" in the simple case, where
`replacement = "$1"`

but this is not working when
`replacement = "$1-someappendix"`

so i used the `$$` workaround

**Comment by srebhan** [comment] 2023-06-20 06:55
@reimerp can you please test the binary in PR #13457 and let me know if it fixes your issue! You need to use the initial configuration without the `$$` workaround...

**Closed** 2023-06-21 13:58 UTC
Labels: bug

**Comment by reimerp** [comment] 2023-06-23 11:08
in 1.27.1 both notation $${1} as well as ${1} work !
