### ISSUE TITLE
outputs.exec: do not truncate (or truncate not that much) stderr in case of subprocess error

### ISSUE THREAD

**Issue by m-khvoinitsky** [influxdata/telegraf#7538] opened 2020-05-18 17:37 UTC
### Relevant telegraf.conf:
```toml
[[outputs.exec]]
    # doesn't really matter
```

### System info:
Telegraf 1.14.2 (git: HEAD fb74eaf2)

### Steps to reproduce:

1. write some sample python script which throws an exception
2. use it as `outputs.exec`
3. read logs

### Expected behavior:

Full script traceback in logs

### Actual behavior:

```
E! [outputs.exec] Command error: "Traceback (most recent call last):..."
E! [agent] Error writing to outputs.exec: ["/path/to/exec/script"] exited 1 with exit status 1
```
Only first line of stderr is barely useful in this case.

**Comment by powersj** [comment] 2022-03-10 21:17
next steps: reproduce on master, and look into what is truncating the error message

**Comment by powersj** [comment] 2022-08-04 20:10
It looks like in #8333, telegraf will not truncate if debug is enabled. I think this gives you what you need, so I am going to close this for now.

Thanks!

**Closed by powersj** 2022-08-04 20:10 UTC
Labels: help wanted, feature request, area/exec
