### ISSUE TITLE
Parse multiple json queries to form output?

### ISSUE THREAD

**Issue by n1nj4888** [influxdata/telegraf#5058] opened 2018-11-29 05:58 UTC
## Feature Request

Parse multiple json queries to form output?

### Proposal:
Not sure whether this is currently possible, but I'd like to try to run multiple json queries on a single file and parse the combined output to InfluxDB? My JSON data looks like this:

```
"ARRAY" : [
    {
      "ARRAY.0.RECORD1" : [
        {
          ARRAY.0.RECORD1-1
        },
	{
          ARRAY.0.RECORD1-2
        },
		...
      ],
      "ARRAY.0.RECORD2" : [
        {
          ARRAY.0.RECORD2-1
        },
        {
		  ARRAY.0.RECORD2-2
        },
        ...
      ],
      "ARRAY.0.RECORDX" : {
        "ARRAY.0.RECORDX-1" : "XYZ"
        "ARRAY.0.RECORDX-2" : "XYZ"
	"ARRAY.0.RECORDX-3" : "XYZ"
      },
    },
	{
      "ARRAY.1.RECORD1" : [
        {
          ARRAY.1.RECORD1-1
        },
	{
          ARRAY.1.RECORD1-2
        },
		...
      ],
      "ARRAY.1.RECORD2" : [
        {
          ARRAY.1.RECORD2-1
        },
        {
		  ARRAY.1.RECORD2-2
        },
        ...
      ],
      "ARRAY.1.RECORDX" : {
        "ARRAY.1.RECORDX-1" : "XYZ"
        "ARRAY.1.RECORDX-2" : "XYZ"
	"ARRAY.1.RECORDX-3" : "XYZ"
      },
    },
]

```

I can currently output say all records under ARRAY.0.RECORD1 with the json_query = "ARRAY.0.RECORD1" as follows:
> file,host=XXX <FIELD1>=XXX,<FIELD2>=YYY,<FIELD3>=ZZZ <TIME> (Corresponds to ARRAY.0.RECORD1-1)
> file,host=XXX <FIELD1>=XXX,<FIELD2>=YYY,<FIELD3>=ZZZ <TIME> (Corresponds to ARRAY.0.RECORD1-2)
...

BUT, is it: possible to add extra tags to this output (either static, or even better, from somewhere else in the file i.e.:
```
> file,host=XXX **<NEW_FIELD>=AAA,**<FIELD1>=XXX,<FIELD2>=YYY,<FIELD3>=ZZZ <TIME> (Corresponds to ARRAY.0.RECORD1-1)
> file,host=XXX **<NEW_FIELD>=AAA,** <FIELD1>=XXX,<FIELD2>=YYY,<FIELD3>=ZZZ <TIME> (Corresponds to ARRAY.0.RECORD1-2)
```

Where <NEW_FIELD> is looked up as the json query "ARRAY.0.RECORDX-2" or is just a static string "AAA" appended to the output?

Opening a feature request kicks off a discussion.

### Current behavior:
I can currently only return values from a single json query and don't seem to be able to either (A) add additional static fields to the output or (B) combine multiple jsn queries into a single output?

### Desired behavior:
Add static field to output or, ideally, be able to add results from multiple json queries on the same file to a single output...

### Use case: [Why is this important (helps with prioritizing requests)]
Would be useful to add additional data over and above that returned from a single json query...

**Comment by danielnelson** [comment] 2018-11-29 22:10
We have an issue open for a more flexible json parser as well: https://github.com/influxdata/telegraf/issues/1363

Static tags can be added at the input level ([example](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-tags)).  Adding static fields is https://github.com/influxdata/telegraf/issues/2564, there is a workaround using the converter processor https://github.com/influxdata/telegraf/issues/2564#issuecomment-394869828.

If the measurement/tags/timestamps are the same, the two lines are effectively merged by InfluxDB into a single record, though this isn't the case in most output destinations.

I'm going to mark this as a duplicate of #1363, since I believe this is what you really need.

**Closed by danielnelson** 2018-11-29 22:10 UTC
