### ISSUE TITLE
Upgrade from .deb triggers service restart, .rpm does not

### ISSUE THREAD

**Issue by sparr** [influxdata/telegraf#3689] opened 2018-01-17 16:37 UTC
### System info:

Telegraf v1.5.1

### Steps to reproduce:

1. Install telegraf from .deb or .rpm
2. Start telegraf service
3. Upgrade telegraf from new .deb or .rpm

### Expected behavior:

telegraf service either restarts or does not restart from both packages

### Actual behavior:

upgrade from .deb package restarts the service, from .rpm package does not

### Additional info:

Originally identified at https://github.com/yankcrime/puppet-telegraf/issues/86

**Comment by danielnelson** [comment] 2018-01-17 18:58
I think this issue is a duplicate of https://github.com/influxdata/telegraf/issues/3516

**Closed by danielnelson** 2018-01-17 18:58 UTC
Labels: duplicate
