### ISSUE TITLE
FreeBSD 11.2-RELEASE ZFS input fails on parsing capacity

### ISSUE THREAD

**Issue by theory14** [influxdata/telegraf#4390] opened 2018-07-06 00:01 UTC
### Relevant telegraf.conf:

[[inputs.zfs]]
	poolMetrics = true

### System info:

FreeBSD 11.2-RELEASE
telegraf 1.6.3 (from ports/pkg)

### Steps to reproduce:

1. System was previously FreeBSD 11.1-RELEASE
2. See that telegraf was reporting zfs stats
3. Upgrade to 11.2-RELEASE
4. 11.2 added some new zfs features
5. telegraf failed to report zfs stats (zpool status contained message about upgrading the pool)
6. Run "zpool upgrade"
7. Now telegraf reports the following error:

 ```
telegraf -test -config /usr/local/etc/telegraf.conf --input-filter zfs
* Plugin: inputs.zfs, Collection 1
2018-07-05T23:58:41Z E! Error parsing capacity: strconv.ParseInt: parsing "1%": invalid syntax
```

### Expected behavior:

Telegraf to report zfs stats 

### Actual behavior:

Telegraf reports error as listed above.

### Additional info:

```
zpool list -Hp 
data	996432412672	18496188416	977936224256	-	-	1%	1	1.00x	ONLINE	-
zroot	117037858816	10298671104	106739187712	-	-	4%	8	1.00x	ONLINE	-
```

```
zpool list    
NAME    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
data    928G  17.2G   911G        -         -     1%     1%  1.00x  ONLINE  -
zroot   109G  9.59G  99.4G        -         -     4%     8%  1.00x  ONLINE  -
```

**Comment by danielnelson** [comment] 2018-07-06 00:17
This is actually a duplicate of https://github.com/influxdata/telegraf/issues/4059, let's discuss further on that issue.

**Closed by danielnelson** 2018-07-06 00:17 UTC
Labels: bug, platform/bsd
