### ISSUE TITLE
Output from any point in the pipeline

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/telegraf#12523] opened 2023-01-19 14:10 UTC
### Use Case

We want to be able to downsample data before sending it to a central database, but at the same time we need the same data at a high frequency in a local logger. It would be ideal to be able to output to the local logger before downsampling to output to the central logger.

I saw a version of the diagram below [here](https://github.com/influxdata/telegraf/issues/7993#issuecomment-898655657). It would be nice (in version 2.0, if required) to be able to create this structure.

```
 +------------+            Processors, aggregators and outputs can be ordered                     +--------+
 | Input      +---+                        and chained arbitrarily                           +--->+ Output |
 +------------+   |                                                                          |    +--------+
                  |                                                                          |
 +------------+   |   +-----------+    +------------+      +-----------+    +------------+   |    +--------+
 | Input      +------>+ Processor +--->+ Aggregator +----->+ Processor +--->+ Aggregator +-->---->+ Output |
 +------------+   |   +-----------+    +------------+   |  +-----------+    +------------+   |    +--------+
                  |                                     |                                    |
 +------------+   |                                     |    +--------+                      |    +--------+
 | Input      +---+                                     +--->+ Output |                      +--->+ Output |
 +------------+   |                                          +--------+                      |    +--------+
                  |                                                                          |
 +------------+   |                                                                          |    +--------+
 | Input      +---+                                                                          +--->+ Output |
 +------------+                                                                                   +--------+
 
 ```

### Expected behavior

Output from any point in the pipeline

### Actual behavior

Not possible at the moment

**Comment by powersj** [comment] 2023-01-19 14:25
You can do this today:

The simplest option is to have a `starlark` or even `execd` processor that runs before everything else that prints the data as you need prior to downsampling.

The slightly more complicated option is:

1. Use the clone processor to create a duplicate of the metrics, but rename the metric. You could add a tag as well, but renaming makes it more clear.
2. On your additional processors or aggregators that you use to downsample, use the namepass option to only pass the original data through them.
3. Use a `file` output with a namepass of the duplicated, untouched data
4. Use a namepass with the downsampled data on the other outputs

Given these options exist, I am not sure we would do anything different in a future major release.

**Comment by LarsStegman** [comment] 2023-01-19 14:39
Yes, it could also work, but it seems much more complicated. 

In our case we have two Influx instances running. The high frequency is running on dedicated hardware and the low frequency is running in a virtual machine and is replicated over satellite to shore. The amount of data on the high frequency logger is pretty high, so I am concerned about the overhead of printing to stdout and needing to parse the line protocol again.

In addition to this, we have a requirement that we need to have all the identifiers the same, as some of our infrastructure and our people's queries are dependent on this.

**Comment by powersj** [comment] 2023-01-19 15:00
> it seems much more complicated.

The scenario is complicated :)

From the other side, telegraf's [run looop](https://github.com/influxdata/telegraf/blob/master/agent/agent.go#L102) will show you how the current run model operates on inputs, processors, and aggregators. If you dig into how run outputs is called, you will note that outputs are handled differently. Recall that the flush interval, the call to outputs, is handled differently than the collection cycle of inputs/processors/aggregators.

Tearing all this up to allow the arbitrarily of outputs, while it might allow for some interesting use cases, it would also be a fundamental difference in how telegraf operates. I can safely say that this is not something we are interested in doing currently.

**Comment by LarsStegman** [comment] 2023-01-19 15:50
> The scenario is complicated :)

Haha fair enough :)

I understand this is not something that will be looked at soon, but I can imagine it will be a nice feature for version 2.0 as the run loop will already be changed to solve #7993

**Comment by powersj** [comment] 2023-01-23 21:23
> I understand this is not something that will be looked at soon, but I can imagine it will be a nice feature for version 2.0 as the run loop will already be changed to solve https://github.com/influxdata/telegraf/issues/7993

I just went through and closed all the 2.x PRs that we had open this afternoon. While we were headed towards a 2.x, we no longer have the ability to manage two major versions for the foreseeable future.

**Comment by Hipska** [comment] 2023-02-23 14:23
@LarsStegman may we invite you to our Slack? https://join.slack.com/t/influxcommunity/shared_invite/zt-1pvg99v03-RdUvuVtz~fE_PI58WdmTsQ

Come join us in the #telegraf and #telegraf-dev channels!

**Closed** 2024-11-12 20:35 UTC
Labels: feature request
