### ISSUE TITLE
[Feature Request] JSON Input support a timestamp field

### ISSUE THREAD

**Issue by fromanator** [influxdata/telegraf#1554] opened 2016-07-27 20:46 UTC
# Feature Request

## Proposal:

Support a "timestamp" field for JSON metric input to define when the metric event occurred. 

## Current behavior:

Uses the local system time when the JSON message was parsed.

## Desired behavior:

If a "timestamp" field is in the JSON message, use that time for when the metric even occurred instead of the when the message was received.

## Use case: [Why is this important (helps with prioritizing requests)]
As described in the [Telegraf Input Data Formats](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md) every metric has a Timestamp as a basic part, currently that is missing for JSON input data. 

Right now we have a use case where there is a Kafka topic of JSON metrics to be consumed by telegraf. However since a timestamp can't be provided, if the ingestion of the messages (lag) is large, then time when the metric happened can be drastically different.

**Comment by sparrc** [comment] 2016-07-27 21:43
I believe that @neonmori may actually have a PR up for this soon

**Comment by fromanator** [comment] 2016-07-27 22:00
Awesome. I was also thinking is that the JSON Parser should be able to parse the format that the [JSON Serializer outputs](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md#json) or have it has a "mode" or something. Because currently it would parse everything as fields_{fields here} and the prefix of fields is kind of undesirable. 

One of my other use cases would be to have telegraf output JSON to a Kafka topic, and then have other telegraf agents consume the JSON messages and load it to a metric storage backend (like influx). That way we can buffer metrics in Kafka, and have the ability to stream metrics directly from Kafka instead of having to scrape a storage backend. My current workaround is to just put the metrics in Kafka as InfluxDB Line Protocol.

**Comment by sparrc** [comment] 2016-09-05 12:57
closing as a dupe of https://github.com/influxdata/telegraf/issues/1363

@fromanator, can you talk more about the drawbacks of using line-protocol? This protocol is ideal for working with influxdb and is able to be encoded & decoded much faster than JSON.

**Closed by sparrc** 2016-09-05 12:57 UTC
