### ISSUE TITLE
problem with telegraf input cpu 

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3555] opened 2017-12-08 08:36 UTC
Hello,

We have installed telegraf 1.2.0-amd64 in our linux servers and we are sending metrics data to elasticsearch(output plugin) 

when working with this we are getting the following error and we are not able to get cpu metrics because of this error:

2017-12-08T08:25:00Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2017-12-08T08:26:00Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2017-12-08T08:27:00Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time
2017-12-08T08:28:00Z E! Error in plugin [inputs.cpu]: Error: current total CPU time is less than previous total CPU time

in elasticsearch the value for cpu_utilization is showing 100 percent
![elasticsearch_screenshot](https://user-images.githubusercontent.com/27216870/33758030-9be00dfc-dc22-11e7-801f-db251046a5bd.JPG)

but actual utilization is not 100 percent...can we know what factor is affecting this

can we have any suggestion to get rid of this....
and get metrics continuously with out any error

Thanks,

**Comment by danielnelson** [comment] 2017-12-08 18:58
This has been fixed, can you update to the latest stable release?

The caused if the counters in `/proc/stat` decrease, I have seen it after a system suspends or after a virtual machine is transferred between hosts.

**Closed by danielnelson** 2017-12-08 18:58 UTC
