### ISSUE TITLE
Very easy bug to fix in OPC UA plugin in: OPC Expert/NI/Siemens PLC value quality not well managed

### ISSUE THREAD

**Issue by hybuild-project** [influxdata/telegraf#9144] opened 2021-04-17 13:58 UTC
### Relevant telegraf.conf:

```toml

[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "telegraf"

[[inputs.opcua]]
  name = "opcua"
  endpoint = "opc.tcp://127.0.0.1:57895/simulation"
  security_policy = "None"
  security_mode = "None"
  nodes = [
    { name="test", namespace="3", identifier_type="s", identifier="Instrument01" },
  ]

```

### System info:

telegraf 1.17.2, win10

### Steps to reproduce:

Start influxDB and [OPC Expert](https://opcexpert.com/) with Simulation Server active and e.g. Instrumentation01 automatically calculated. Start Telegraf with the included snippet in config file.

### Expected behavior:

Simulation server provides values with quality 0xC0, which is a Good quality value. Values should be written by the Telegraf OPCUA plugin in into influxdb.

### Actual behavior:

The Telegraf plugin prompts an error:
`2021-04-17T13:49:21Z E! [inputs.opcua] Error in plugin: Get Data Failed: Status not OK: 0xC0`
The value is not written in influx.
![image](https://user-images.githubusercontent.com/78462235/115116067-0a34a600-9f98-11eb-9e93-3c1a0de2f1e0.png)

### Additional info:

Considering 0xC0 a "bad quality" data is an error: it should be included in the code as a good quality value. This is also the return code of some PLCs from NI and Siemens, which prevents collecting data from those PLCs via OPC UA.

**Comment by helenosheaa** [comment] 2021-04-19 18:43
Hi, @hybuild-project, thanks for opening this. It seems to be a duplicate of an existing issue #8826, so I'm going to close it. If you could add your comment over on the other issue that would be appreciated. I will also add this comment to the other issue -->

We seem to be doing a check against status codes from [here](https://github.com/gopcua/opcua/blob/main/ua/status_gen.go#L22) where Status must match StatusOk which is `0x0`.

So I think either an additional check is needed of Status being `0xC0` in our code and/or opening an issue to the [gopcua package](https://github.com/gopcua/opcua) we are using to add `0xC0` as an OK status option also that we check against.

**Closed by helenosheaa** 2021-04-19 18:43 UTC
Labels: area/opcua, bug
