### ISSUE TITLE
snmp plugin not producing any data 

### ISSUE THREAD

**Issue by ayounas** [influxdata/telegraf#2628] opened 2017-04-04 19:16 UTC
## Bug report
I am using snmp input to query different checkpoint firewall oids and writing them to a tcp socket which is a splunk instance. snmpget returns data but telegraf doesn't return any thing. e.g

[abc@xxxxxx telegraf.d]# snmpget  -c public -v2c 10.xxx.xxx.xxx .1.3.6.1.4.1.2620.1.1.25.4.0                                 
SNMPv2-SMI::enterprises.2620.1.1.25.4.0 = INTEGER: 1250140
[abc@xxxxxx telegraf.d]# snmpget  -c public -v2c 10.xxx.xxx.xxx .1.3.6.1.4.1.2620.1.1.25.3.0
SNMPv2-SMI::enterprises.2620.1.1.25.3.0 = INTEGER: 129196

I have tried converting to float, int and without conversion but still nothing.

### Relevant telegraf.conf:
[global_tags]
   dc = "DC1" # will tag all metrics with dc=us-east-1

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = "myhost"
  omit_hostname = true

[[outputs.socket_writer]]
  address = "tcp://10.xxx.xxx.xxx:2005"
  data_format = "json"

[[inputs.snmp]]
  agents = [ "10.xx.xx.xx:161" ]
  version = 2
  timeout = "5s"
  retries = 3
  community = "public"

[[inputs.snmp.field]]
 name = "maxconns"
 oid = ".1.3.6.1.4.1.2620.1.1.25.4.0"
 conversion = "int"

[[inputs.snmp.field]]
 name = "currconns"
 oid = ".1.3.6.1.4.1.2620.1.1.25.3.0"
 conversion = "int"

[[inputs.snmp.field]]
  name = "hmem_failed"
  oid = ".1.3.6.1.4.1.2620.1.1.26.1.21.0"

[[inputs.snmp.field]]
  name = "kmem_failed"
  oid = ".1.3.6.1.4.1.2620.1.1.26.2.15.0"
  conversion = "int"

### System info:

telegraf version : Telegraf vdev-112-g8bf193d (git: master 8bf193d)
kernel version : 2.6.18-411.0.0.0.1.el5

### Steps to reproduce:

no data output by telegraf 

telegraf -test -debug  -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
* Plugin: inputs.snmp, Collection 1
[abc@xxxxx telegraf.d]

### Expected behavior:

value of the oid.

snmpget  -c public -v2c 10.xxx.xxx.xxx .1.3.6.1.4.1.2620.1.1.25.3.0
SNMPv2-SMI::enterprises.2620.1.1.25.3.0 = INTEGER: 129196

### Actual behavior:

no data output

### Additional info:
I have tried with below version with influxdb as output and still same
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)

**Comment by danielnelson** [comment] 2017-04-06 17:55
@phemmer Do you think this is a duplicate of #2590?

**Comment by phemmer** [comment] 2017-04-06 18:09
Not likely. Doesn't look like opaque values are in use here. At glance I don't see anything that would cause a problem. The `conversion` statements are unnecessary, but shouldn't cause problems.

**Comment by ayounas** [comment] 2017-04-06 22:57
Yes the conversion statement are unnecessary because expected output is an int. This was just a stab in dark to find if conversion makes any difference.

**Comment by phemmer** [comment] 2017-04-08 16:38
Found the issue. PR is over at #2639 
However you can work around the issue by just setting the name property. Example:

```
[[inputs.snmp]]
agents = [ "10.xx.xx.xx:161" ]
version = 2
timeout = "5s"
retries = 3
community = "public"
name = "snmp" # <-- this
```

**Comment by ayounas** [comment] 2017-04-09 20:35
Thanks for the help 
snmp plugin is now producing data after adding name= "snmp" as suggested

 telegraf -test -debug -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
* Plugin: inputs.snmp, Collection 1
> snmp,agent_host=10.xx.xx.xx,dc=DC1,hostname=checkpoint kmem_failed=0i,max_conns=1250140i,curr_conns=118678i,hmem_failed=0i 1491769764000000000

**Closed** 2017-04-10 23:45 UTC
Labels: bug
