### ISSUE TITLE
Segmentation fault in 1.15.3 processor plugin

### ISSUE THREAD

**Issue by bofh16** [influxdata/telegraf#8277] opened 2020-10-16 08:05 UTC
### Relevant telegraf.conf:

```
[processors.converter.fields]
	unsigned  =  [
		"field1"
	]
```

### System info:
Telegraf 1.15.3, various CentOS and Debian versions.

### Steps to reproduce:

1. Start Telegraf.
2. It crashes immediately.

### Expected behavior:
This configuration causes no problems in versions up to 1.14.5.

### Actual behavior:
Telegraf crashes.

[telegraf_core.txt](https://github.com/influxdata/telegraf/files/5390083/telegraf_core.txt)

**Comment by ssoroka** [comment] 2020-10-16 15:52
duplicate of https://github.com/influxdata/telegraf/issues/8173

Resolved in nightly, will be in 1.16.0-rc2 and 1.15.4

**Closed by ssoroka** 2020-10-16 15:52 UTC
Labels: bug
