### ISSUE TITLE
CSV parser does not handle csv_header_row_count correctly

### ISSUE THREAD

**Issue by NielsH** [influxdata/telegraf#10678] opened 2022-02-18 09:21 UTC
### Relevant telegraf.conf

```toml
[[inputs.exec]]
  commands = ["sudo /usr/local/sbin/repquota4.06 -P -sk, -a -O csv"]

  data_format = "csv"
  csv_header_row_count = 1
  csv_column_types = ["string", "string", "string", "string", "string", "string", "string", "int", "int", "int", "string"]
  csv_tag_columns = ["Project"]
  name_override = "quota_project"

  # Means to skip empty strings
  csv_skip_values = [""]

  # Only expose these fields, drop others
  fieldpass = ["Project", "SpaceUsed", "FileUsed"]

[[processors.regex]]
  order = 1
  namepass = ["quota_project"]
  [[processors.regex.fields]]
  key = "SpaceUsed"
  pattern = "^(.*)K$"
  replacement = "${1}"

[[processors.converter]]
  order = 2
  namepass = ["quota_project"]
  [processors.converter.fields]
    integer = ["SpaceUsed"]
```

### Logs from Telegraf

2022-02-18T09:06:31Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 449.287µs
2022-02-18T09:06:31Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:31Z D! [outputs.influxdb] Wrote batch of 25 metrics in 45.592603ms
2022-02-18T09:06:31Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:40Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:06:41Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 221.635µs
2022-02-18T09:06:41Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:41Z D! [outputs.influxdb] Wrote batch of 25 metrics in 4.141917ms
2022-02-18T09:06:41Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:50Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:06:51Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 233.676µs
2022-02-18T09:06:51Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:51Z D! [outputs.influxdb] Wrote batch of 25 metrics in 4.00893ms
2022-02-18T09:06:51Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:00Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:07:01Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 235.754µs
2022-02-18T09:07:01Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:01Z D! [outputs.influxdb] Wrote batch of 25 metrics in 3.653304ms
2022-02-18T09:07:01Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:10Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:07:11Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 221.834µs
2022-02-18T09:07:11Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:11Z D! [outputs.influxdb] Wrote batch of 25 metrics in 40.921214ms
2022-02-18T09:07:11Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:20Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:07:21Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 255.106µs
2022-02-18T09:07:21Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:21Z D! [outputs.influxdb] Wrote batch of 25 metrics in 3.244573ms
2022-02-18T09:07:21Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics

### System info

Telegraf 1.21.4-1 - Debian 11

### Docker

N/A

### Steps to reproduce

1. Run the supplied telegraf.conf with repquota4.06 (older versions dont have all the flags we use included)
2. The first metric works correctly
3. All other metrics (every 10 seconds) give the error shown in the logs
...

### Expected behavior

Metrics collected every interval (10 seconds) don't give an error

### Actual behavior

Every 10 seconds we get an error

### Additional info

So I *think* this is related to https://github.com/influxdata/telegraf/issues/10347

What I think is happening, the output of the command we run is:
```
Project,SpaceStatus,FileStatus,SpaceUsed,SpaceSoftLimit,SpaceHardLimit,SpaceGrace,FileUsed,FileSoftLimit,FileHardLimit,FileGrace
timtest_a68e,ok,ok,849892K,0K,0K,,196,0,0,
#0,ok,ok,8446956K,0K,0K,,95870,0,0,
```

So the first, initial run of collecting metrics, the `csv_header_row_count = 1` is applied correctly to see the first row as a header. However every secondary run (every 10 seconds) I think it is trying to parse the header row as metric data and as such it is failing. It's supposed to always see the first row as the header every time we run the command.

We can sort of work around it by adding
```
csv_column_names = ["Project", "SpaceStatus", "FileStatus", "SpaceUsed", "SpaceSoftLimit", "SpaceHardLimit", "SpaceGrace", "FileUsed", "FileSoftLimit", "FileHardLimit", "FileGrace"]

# And removing:
#csv_header_row_count = 1

```

And then changing the command to:

```
commands = ["/var/tmp/quota-test.sh"]
```

And in `/var/tmp/quota-test.sh` we do: 
```
#!/bin/bash

sudo /usr/local/sbin/repquota4.06 -P -sk, -a -O csv | tail +2
```

Note that under Debian 11, the `repquota` command included in the `quota` package under `/usr/sbin/repquota` can also be used to reproduce it. But if you're using Debian 10 which has an older repquota version you have to use 4.06 specifically.

**Comment by srebhan** [comment] 2022-02-20 09:56
Sorry mate, but in my world `0K` is **not** an `int`... ;-)

**Comment by NielsH** [comment] 2022-02-20 10:20
Hi @srebhan 
Thanks for your reply.

We've been fiddling a bit with the `-s` flag which allows some human-readable finetuning, so perhaps there's an error in my initial message somewhere. But I think it is correct...?

For example this is the output of a row:
```
Project,SpaceStatus,FileStatus,SpaceUsed,SpaceSoftLimit,SpaceHardLimit,SpaceGrace,FileUsed,FileSoftLimit,FileHardLimit,FileGrace
timtest_a68e,ok,ok,849892K,0K,0K,,196,0,0,
```

-->

```
timtest_a68e (Project)        => string
ok           (SpaceStatus)    => string
ok           (FileStatus)     => string
849892K      (SpaceUsed)      => string
0K           (SpaceSoftLimit  => string
0K           (SpaceHardLimit) => string
,(empty)     (SpaceGrace)     => string
196          (FileUsed)       => int
0            (FileSoftLimit)  => int
0            (FileHardLimit)  => int
,(empty)     (FileGrace)      => string
```

Which is also as we assign it, right?
```
csv_column_types = ["string", "string", "string", "string", "string", "string", "string", "int", "int", "int", "string"]
```

**Comment by rkorn86** [comment] 2022-02-21 13:52
I have the same problem using https://github.com/vmware/vrops-export and `[[inputs.exec]]` with csv data format.
```
[inputs.exec] Error in plugin: column type: parse float error strconv.ParseFloat: parsing "cpuUsage": invalid syntax
```
While nothing has changed in my csv format, nor my telegraf config.

Config:
```
[[inputs.exec]]
  commands = [
    "/opt/telegraf/vrops-export/vrop.sh"
  ]
  timeout = "1m"
  interval = "10m"
  name_override = "vmware"
  name_suffix = ""
  data_format = "csv"
  csv_header_row_count = 1
  csv_column_names = ["timestamp", "resName", "guestOS", "hostName", "cpuUsage", "memUsage", "diskUsage"]
  csv_column_types = ["string", "string", "string", "string", "float", "float", "float"]
  csv_skip_rows = 0
  csv_skip_columns = 0
  csv_delimiter = ","
  csv_comment = ""
  csv_trim_space = false
  csv_tag_columns = ["resName", "guestOS", "hostName"]
  csv_measurement_column = ""
  csv_timestamp_column = "timestamp"
  csv_timestamp_format = "2006-01-02 15:04:05-0700"
```


Truncated output of `telegraf --test --input-filter exec`:
```
2022-02-21T13:47:38Z I! Starting Telegraf 1.21.4
2022-02-21T13:47:38Z I! Using config file: /etc/telegraf/telegraf.conf
2022-02-21T13:47:38Z I! Loaded inputs: exec (7x)
2022-02-21T13:47:38Z I! Loaded aggregators: 
2022-02-21T13:47:38Z I! Loaded processors: 
2022-02-21T13:47:38Z W! Outputs are not used in testing mode!
2022-02-21T13:47:38Z I! Tags enabled: 
2022-02-21T13:47:38Z D! [agent] Initializing plugins
2022-02-21T13:47:38Z D! [agent] Starting service inputs
> vmware,guestOS=Microsoft\ Windows\ Server\ 2012\ (64-bit),hostName=xxx-1,resName=yyy-1 cpuUsage=341.6666564941406,diskUsage=294.0859375,memUsage=2137695.5 1645450734000000000
> vmware,guestOS=Microsoft\ Windows\ Server\ 2012\ (64-bit),hostName=xxx-2,resName=yyy-2,cpuUsage=833.4666748046875,diskUsage=294.0859375,memUsage=2383760.25 1645451034000000000
....
```
without errors.

**Comment by powersj** [comment] 2022-02-22 14:51
In this example:

```
Project,SpaceStatus,FileStatus,SpaceUsed,SpaceSoftLimit,SpaceHardLimit,SpaceGrace,FileUsed,FileSoftLimit,FileHardLimit,FileGrace
timtest_a68e,ok,ok,849892K,0K,0K,,196,0,0,
```

You have 11 header columns and 10 data columns this won't work.

Please provide a full example set of data + a working configuration for us to help.

**Comment by fuegas** [comment] 2022-02-22 15:31
Hi @powersj,

The problem is not happening  when you run the test only _once_. The problem lies in the running agent. It will show up on the _second_ time the agent tries to gather the data. The first run will work correctly. Could you try running the agent without `--once` and wait for the second gathering of metrics to pass?

**Comment by fuegas** [comment] 2022-02-22 15:34
The version used is 1.21.4.

**Comment by powersj** [comment] 2022-02-22 15:39
I believe https://github.com/influxdata/telegraf/pull/10575 fixes this. You can grab a nightly build to confirm, but this is not reproducible with master.

**Comment by fuegas** [comment] 2022-02-22 15:51
I've tried it with the current nightly build:

```
2022-02-22T15:48:08Z I! Starting Telegraf 1.22.0-2ca5cfed
2022-02-22T15:48:08Z I! Loaded inputs: exec (4x)
2022-02-22T15:48:08Z I! Loaded aggregators:
2022-02-22T15:48:08Z I! Loaded processors:
2022-02-22T15:48:08Z I! Loaded outputs: influxdb prometheus_client
2022-02-22T15:48:08Z I! Tags enabled: host=REDACTED
2022-02-22T15:48:08Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"REDACTED", Flush Interval:10s
2022-02-22T15:48:08Z I! [outputs.prometheus_client] Listening on http://[::]:9273/metrics
2022-02-22T15:48:20Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "numberCol": invalid syntax
^C2022-02-22T15:48:29Z I! [agent] Hang on, flushing any cached metrics before shutdown
2022-02-22T15:48:29Z I! [agent] Stopping running outputs
```

One thing I noticed was that you have `input.file` in your config, while we see the errors for `input.exec`, could you verify this is not influencing the results you see?

**Comment by powersj** [comment] 2022-02-22 16:29
> cat is a simplified version of the output we generate

Ah ok I lost that part from earlier

**Comment by srebhan** [comment] 2022-02-23 20:33
> @srebhan does your PR in #10575 need to be extended to exec?
@powersj certainly yes. Basically it has to be extended to all plugins where (at least) CSV is an option...

**Comment by petr-tichy** [comment] 2022-09-21 15:39
This had just bitten me badly with
```
[[inputs.exec]]
  commands = [ ... ]
  data_format = "csv"
  csv_header_row_count = 1
```
All but first runs try to send the header as data.

downgrading way back to 1.20.4 helps

**Comment by srebhan** [comment] 2022-09-27 08:59
@NielsH, @rkorn86 and @petr-tichy can you please try version 1.24? We introduced a new `csv_reset_mode` setting which accounts for the two possible use-cases

1. The data-producer (e.g. `inputs.exec`) will return the header (metadata, etc) only _once_, e.g. at the first call. In this case, please set `csv_reset_mode = "none"` which is also the default.
2. The data-producer (e.g. `inputs.exec`) will always return a completely self-contained CSV chunk including the header (metadata, etc) in _every_ call. In this case, please set `csv_reset_mode = "always"`.

Let me know if this issue still persists with 1.24!

**Comment by Hipska** [comment] 2022-10-13 08:33
I agree that `always` is the logical default. But as this is a new option and changes previous behaviour it is opted to default to `none` which is backward compatible. This default setting makes sense in the tail plugin or similar plugins.

Closing this issue as it seems the setting resolves this problem.

**Closed by Hipska** 2022-10-13 08:33 UTC
Labels: bug, area/exec
