### ISSUE TITLE
config parser error hidden by telegraf-1.0.0 init script

### ISSUE THREAD

**Issue by lukebigum** [influxdata/telegraf#1740] opened 2016-09-09 12:29 UTC
### Relevant telegraf.conf:

Specifically broken:

```
[[outputs.influxdb]]
  database = "telegraf"
  interval = "1s"

```
### System info:

telegraf 1.0.0 on CentOS 6.

### Steps to reproduce:

Break the config with an invalid param. Attempt to start the service using the Red Hat LSB init script. 

### Expected behavior:

I should be told the service failed to start (the binary does return a non zero exit code it just gets lost in all the Bash / Su / nohup in there). At the very least I should see the config parser error in the log file.

### Actual behavior:

The service starts but dies immediately, but it tells me it started ok. No error message in the log because the init script sends STDOUT to /dev/null.

Actual error message is this:

```
[root@server ~]# /usr/bin/telegraf -pidfile /var/run/telegraf/telegraf.pid -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
Error parsing /etc/telegraf/telegraf.conf, line 24: field corresponding to `interval' is not defined in `*influxdb.InfluxDB'
```

### Proposal:

Quick fix would be to just not bury STDOUT, so you can at least see error in the log. More robust ways of handling this would be to introduce a config parser option, so you could test the config file validity first before you tried to spawn the real instance.

Another way might be to use the Red Hat daemon() function in /etc/rc.d/init.d/functions, but then you don't have a cross platform init script.

**Comment by sparrc** [comment] 2016-09-09 12:32
dupe of https://github.com/influxdata/telegraf/issues/1344

**Closed by sparrc** 2016-09-09 12:32 UTC
