### ISSUE TITLE
SQL Server input has conflicting field types

### ISSUE THREAD

**Issue by nogweii** [influxdata/telegraf#4438] opened 2018-07-19 17:50 UTC
### Relevant telegraf.conf:

```
# It's expected that the user this service is running as can log into
# SQL Server as the same user by reusing the domain credentials
[[inputs.sqlserver]]  
  servers = [ "Server=127.0.0.1;Port=1433;app name=telegraf;log=1" ]
  [inputs.sqlserver.tags]
    source = "sqlserver"
```

### System info:

Running telegraf 1.7.1 on Windows Server 2016, with SQL Server 2016 SP1.

### Steps to reproduce:

1. Run telegraf 1.5.1 on SQL Server, and have it send metrics for a while.
2. Notice that you need to update your agent and do so
3. 2 measurements and related fields break due to type conflicts

### Expected behavior:

That the v1 SQL metrics don't change field types.

### Additional info:

`telegraf.log` output:

```
2018-07-18T16:07:00Z E! [outputs.influxdb]: when writing to [https://devmonitor:8086]: received error partial write: field type conflict: input field "Cache (objects)" on measurement "Memory breakdown (%)" is type string, already exists as type float dropped=24; discarding points
2018-07-18T16:07:10Z E! [outputs.influxdb]: when writing to [https://devmonitor:8086]: received error partial write: field type conflict: input field "G: (TempLogs)" on measurement "Volume total space (bytes)" is type string, already exists as type float dropped=24; discarding points
2018-07-18T16:07:20Z E! [outputs.influxdb]: when writing to [https://devmonitor:8086]: received error partial write: field type conflict: input field "Other" on measurement "Memory breakdown (%)" is type string, already exists as type float dropped=24; discarding points
2018-07-18T16:07:30Z E! [outputs.influxdb]: when writing to [https://devmonitor:8086]: received error partial write: field type conflict: input field "Buffer pool" on measurement "Memory breakdown (%)" is type string, already exists as type float dropped=24; discarding points
2018-07-18T16:07:40Z E! [outputs.influxdb]: when writing to [https://devmonitor:8086]: received error partial write: field type conflict: input field "F: (TempData)" on measurement "Volume total space (bytes)" is type string, already exists as type float dropped=24; discarding points
2018-07-18T16:07:50Z E! [outputs.influxdb]: when writing to [https://devmonitor:8086]: received error partial write: field type conflict: input field "Cache (sql plans)" on measurement "Memory breakdown (%)" is type string, already exists as type float dropped=24; discarding points
```

**Comment by glinton** [comment] 2018-07-20 14:59
According to the commit history for the `sqlserver` plugin, you shouldn't need to, but can you try manually setting `query_version = 1`?

**Comment by evaryont** [comment] 2018-07-20 18:40
Unfortunately, setting `query_version` did not fix it, I'm still getting field conflicts.

**Comment by glinton** [comment] 2018-07-20 20:44
Can you run `telegraf --input-filter=sqlserver --test` with both 1.5.1 and 1.7.1 and post the output of each?

**Comment by evaryont** [comment] 2018-07-20 21:34
See this gist: https://gist.github.com/evaryont/5874c9128f75efd4043da7cc72ac57ff

**Comment by danielnelson** [comment] 2018-07-21 01:01
I haven't been able to determine the cause of the error

For the record, here is an example of the error, we appear to be adding some
results as string fields:
```diff
- Volume\ available\ space\ (bytes),environment=Development,host=devsqldist,owner=$MACHINE_OWNER,role=$MACHINE_ROLE,servername=DEVSQLDIST,source=sqlserver,type=OS\ Volume\ space D:\ (Data)=1094026952704,E:\ (Logs)=107073253376,F:\ (TempData)=42549424128,G:\ (TempLogs)=42708811776
+ Volume\ available\ space\ (bytes),environment=Development,host=devsqldist,owner=$MACHINE_OWNER,role=$MACHINE_ROLE,servername=DEVSQLDIST,source=sqlserver,type=OS\ Volume\ space D:\ (Data)="1094026952704.00",E:\ (Logs)="107073253376.00",F:\ (TempData)="42549424128.00",G:\ (TempLogs)="42708811776.00"
```

This is odd because we explicitely skip strings:

https://github.com/influxdata/telegraf/blob/f37b503f686cbeb985c24c90c96d622da32712b3/plugins/inputs/sqlserver/sqlserver.go#L226-L229

@evaryont Any chance you would be able to use `git bisect` to find the commit that introduced the error?

**Comment by evaryont** [comment] 2018-07-25 23:40
> Any chance you would be able to use git bisect to find the commit that introduced the error?

Unfortunately, I don't think I'll be able to get the time to do that. We've rolled back to 1.5 in the mean time and I've been tasked on other things.

**Comment by nwneisen** [comment] 2019-11-23 04:20
I did a `git bisect` and found the commit this issue was introduced in.

`[1c0f63a90d60da228ff32944b4078e57d826dc83] Add new line protocol parser and serializer, influxdb output (#3924)`

This is a big commit to look through.  @danielnelson any thoughts on where to start?

**Comment by danielnelson** [comment] 2019-11-25 23:54
I presume it has to do with the conversion of field types into the telegraf.Metric, before `[]byte` were added as `[]byte` fields, and now they are converted into string.  This is in metric/metric.go convertField().

My guess is that these columns are []byte type, similar to the #6679 issue, that would explain why they are not being marked as tags.

**Comment by sjwang90** [comment] 2021-04-05 17:06
Closing this since #6679 has been fixed.

**Closed by sjwang90** 2021-04-05 17:06 UTC
Labels: area/sqlserver, bug, platform/windows
