### ISSUE TITLE
Elasticsearch input panic error on invalid metric name

### ISSUE THREAD

**Issue by dahendel** [influxdata/telegraf#908] opened 2016-03-22 16:20 UTC
We are using Azul Zing as our JRE/JDK and when the elasticsearch input plugin runs it hits an unexpected metric name and causes telegraf to crash. I attached the es excerpt from the config and the stack trace in the attached zip.

[stack_trace-es-conf.zip](https://github.com/influxdata/telegraf/files/184484/stack_trace-es-conf.zip)

bash-4.3# ./telegraf version
Telegraf - Version 0.11.1-47-g7f65ffc

**Comment by sparrc** [comment] 2016-03-22 17:21
the problem here is actually your prometheus output, dupe of #907

**Closed by sparrc** 2016-03-22 17:21 UTC
Labels: bug
