### ISSUE TITLE
SIGHUP config reload broken for prometheus_client

### ISSUE THREAD

**Issue by samrees** [influxdata/telegraf#8726] opened 2021-01-21 00:48 UTC
cant reload the configuration via sighup on anything newer than 1.14.5 with prometheus_client enabled.

```
2021-01-21T00:43:13Z I! Reloading Telegraf config
2021-01-21T00:43:13Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-01-21T00:43:13Z I! Starting Telegraf 1.16.3
2021-01-21T00:43:13Z I! Loaded inputs: dns_query (2x)
2021-01-21T00:43:13Z I! Loaded aggregators:
2021-01-21T00:43:13Z I! Loaded processors:
2021-01-21T00:43:13Z I! Loaded outputs: prometheus_client
2021-01-21T00:43:13Z I! Tags enabled: host=${NODE_NAME}
2021-01-21T00:43:13Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"${NODE_NAME}", Flush Interval:10s
2021-01-21T00:43:13Z E! [agent] Failed to connect to [outputs.prometheus_client], retrying in 15s, error was 'listen tcp :9273: bind: address already in use'
2021-01-21T00:43:28Z E! [telegraf] Error running agent: connecting output outputs.prometheus_client: Error connecting to output "outputs.prometheus_client": listen tcp :9273: bind: address already in use
```

```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "${NODE_NAME}"
  omit_hostname = false

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  metric_version = 2

  # expiration_interval = "60s"
  collectors_exclude = ["gocollector", "process"]
  export_timestamp = false
```

**Comment by dtrejod** [comment] 2021-02-09 16:40
Duplicate of https://github.com/influxdata/telegraf/issues/8726?

**Comment by samrees** [comment] 2021-02-09 16:57
> Duplicate of #8726?

While a bit existential, I would answer yes.

**Comment by samrees** [comment] 2021-02-09 17:00
I think this is a duplicate of https://github.com/influxdata/telegraf/issues/8185

**Closed** 2021-03-16 19:50 UTC
Labels: bug
