### ISSUE TITLE
Should the 64 bit binaries work on Alpine?

### ISSUE THREAD

**Issue by djMax** [influxdata/telegraf#590] opened 2016-01-27 04:52 UTC
I can't even unzip/untar the distro...

```
/tmp # gunzip telegraf-0.10.0_linux_amd64.tar.gz
gzip: telegraf-0.10.0_linux_amd64.tar.gz has more than one entry -- unchanged
/tmp # tar xvfz telegraf-0.10.0_linux_amd64.tar.gz
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by mark-rushakoff** [comment] 2016-01-27 05:48
Dupe of https://github.com/influxdata/telegraf/issues/562 / fixed by https://github.com/influxdata/telegraf/pull/578 / fix will be included in 0.10.1.

**Closed by mark-rushakoff** 2016-01-27 05:48 UTC
