### ISSUE TITLE
[Procstat Plugin] If process does not exist telegraf starts consuming more and more cpu

### ISSUE THREAD

**Issue by discoduck2x** [influxdata/telegraf#2472] opened 2017-02-27 10:53 UTC
When using the procstat plugin and if a process isnt running resulting in that the following error can be observed in /var/log/messages "**Feb 27 11:37:06 centos7 telegraf: 2017-02-27T10:37:06Z E! Error: procstat getting process, exe: [snapteld] pidfile: [] pattern: [] user: [] Failed to execute /usr/bin/pgrep. Error: 'exit status 1**'
"
cpu usage of the telegraf process will steadily increase as shown in picture below.
Does not happen if all processes procstat plugin is configured to monitor is actually present and running

### System info:
Centos7 , telegraf 1.2.1

### telegraf.conf:
[[inputs.procstat]]
  exe = "telegraf"
  fieldpass = ["cpu_usage"]

[[inputs.procstat]]
  exe = "snapteld"
  fieldpass = ["cpu_usage"]

[[inputs.cpu]]
    percpu = true
    totalcpu = true
    collect_cpu_time = false
  
![image](https://cloud.githubusercontent.com/assets/12600004/23357977/59b9dcae-fce0-11e6-8cbe-39a37a11e4b1.png)

topleft graph - host cpu usage (system cpu iput)
topright graph - procstat cpu usage
bottom barcharts - count of collected metrics by interval (shows the issue https://github.com/influxdata/telegraf/issues/2315 - but also that its fine for other inputs , system cpu in this case)

**Comment by sparrc** [comment] 2017-02-28 12:16
could be related to https://github.com/shirou/gopsutil/pull/320 and https://github.com/shirou/gopsutil/pull/319

**Comment by sparrc** [comment] 2017-02-28 12:45
@discoduck2x Are you running 64-bit linux? could you try running this binary and see if it fixes your issue?: https://6188-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.hjZlqFh/telegraf.gz

**Comment by discoduck2x** [comment] 2017-03-01 09:12
@sparrc yes 64bit centos, ill try the file and report back

**Comment by discoduck2x** [comment] 2017-03-01 09:23
@sparrc , im not able to get any procstat data with that bin , getting the following error:

**Mar  1 10:21:16 centos7 telegraf: 2017-03-01T09:21:16Z E! Error: procstat: Failed to open process with pid '4543'. Error: 'open /proc/4543: no such file or directory'**

and my conf for procstat:
[[inputs.procstat]]
  exe = "telegraf"
  fieldpass = ["cpu_usage"]

**Comment by sparrc** [comment] 2017-03-01 10:53
does /proc/4543 exist? did you restart the process? reloading probably won't work here

**Comment by discoduck2x** [comment] 2017-03-01 11:03
@sparrc no the pid does not exist - ive restarted a few times same thing,, have to go off for a while but will try more later today

**Comment by sparrc** [comment] 2017-03-01 11:04
can you try using a pidfile?

**Comment by discoduck2x** [comment] 2017-03-01 12:07
@sparrc  , with pidfile im getting nothing.. no errors no data...

**Comment by sparrc** [comment] 2017-03-01 13:18
are you sure this is not a permissions issue?

**Comment by sparrc** [comment] 2017-03-01 13:26
@discoduck2x how are you confirming that there is no data?

**Comment by sparrc** [comment] 2017-03-01 14:04
I can confirm that this is an issue on master, doesn't appear to be collecting cpu usage properly, currently investigating....

**Comment by discoduck2x** [comment] 2017-03-01 14:06
@sparrc - confirmed by: (then reverting to original 1.2.1 telegraf binary and then data getting picked up by pidfile usage.

![image](https://cloud.githubusercontent.com/assets/12600004/23463071/8f2e78ca-fe90-11e6-9c54-f65be6e63363.png)

**Comment by sparrc** [comment] 2017-03-01 15:08
@discoduck2x it seems that a fix for a separate bug resulted in breaking the cpu_usage metric. (see https://github.com/influxdata/telegraf/pull/2479)

Once I merge that PR I will provide another build that has both fixes.

**Comment by discoduck2x** [comment] 2017-03-01 15:57
@sparrc ok thanks for your effort!

**Comment by sparrc** [comment] 2017-03-08 13:17
@discoduck2x could you try out the following binary? https://6254-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.KlLekoO/telegraf.gz

**Comment by discoduck2x** [comment] 2017-03-10 16:14
@sparrc , im still seein the same behaviour:
checksum: 43e159ebe073a14467ac0ce325c68296

![image](https://cloud.githubusercontent.com/assets/12600004/23802845/e6b109b6-05b4-11e7-8a85-a7c1507ea76d.png)

**Comment by sparrc** [comment] 2017-03-10 16:41
OK, didn't mean to close this anyways so reopening

**Comment by danielnelson** [comment] 2017-03-13 21:38
@discoduck2x Does the process sometimes exist?  From #1636 we know that procstat caches the pids indefinitely.  If the process sometimes was found on occasion you would eventually build up a large list of pids that would need to be checked.

**Comment by discoduck2x** [comment] 2017-03-14 08:18
@danielnelson no, ive got one/the same telegraf.conf for all my test hosts and one host has influxdb,, one has grafana etc so no,, there are no pid´s coming and going so to say on the hosts. 

with regards to #1636 it seems to me that if i have pattern configured in for procstat,, and lets say its for "telegraf",,, then if i use nano to edit the telegraf.conf then the "nano" process will be caught by the telegraf procstat process thus showing nano as a process.... Im gonna test some more coz cant replicate it consistently...but it looks very strange

**Comment by danielnelson** [comment] 2017-03-14 16:09
If you use the pattern option I think it should pick up the text editor or anything with the pattern in one of the args, but if you use the `exe` option it should only pick it up if the name of process aka arg0 matches.  I'll fix #1636 today and then we should retest this to see if its related.

**Comment by discoduck2x** [comment] 2017-03-15 07:48
@danielnelson thats true, the pattern option catches them. running another test now for a while - will get back with hopefully some more details

**Comment by danielnelson** [comment] 2017-03-17 23:50
@discoduck2x Will you retest with the latest master?  This might be fixed.

**Comment by discoduck2x** [comment] 2017-03-18 19:26
i would if i could , cant build from master , u got bin anywhere i can pull it from? @danielnelson

**Comment by danielnelson** [comment] 2017-03-21 01:07
@discoduck2x Here is the latest build: https://6349-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.eKuio1V/telegraf.gz

**Comment by discoduck2x** [comment] 2017-03-21 05:11
@danielnelson , is that built for centos? getting this error with that binary:
![image](https://cloud.githubusercontent.com/assets/12600004/24133407/22d5e362-0dfd-11e7-8c8a-f8035aae9a86.png)

**Comment by danielnelson** [comment] 2017-03-21 20:28
@discoduck2x Sorry, was just a bug in my change, try this one: https://6363-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.H35AC4G/telegraf.gz

**Comment by discoduck2x** [comment] 2017-03-21 21:14
@danielnelson thanks,, deployed and will let it simmer over night.
On one other note the "missing collections" seems better by looking at the count of metrics beein collected (previously telegraf missed procstat process cpu data if cpu usage was low)
On this pic the new bin shows the correct expected number of metrics collected per interval. so fingers crossed !

![image](https://cloud.githubusercontent.com/assets/12600004/24171194/be781c14-0e83-11e7-9cf4-1849ee77a904.png)

**Comment by discoduck2x** [comment] 2017-03-22 07:22
@danielnelson  - the cpu growth seems to be gone ! nice work
![image](https://cloud.githubusercontent.com/assets/12600004/24186440/8f3ef7a6-0ed8-11e7-905d-de27ba5a5a0e.png)

does this build also include some fix for multiple instances of the same process name?

**Comment by danielnelson** [comment] 2017-03-22 17:15
Just the 3 bugs listed in #2540.  I believe this bug was caused by procstat caching the pid and tags forever, which would require more and more memory and cpu to check.

**Closed by danielnelson** 2017-03-22 17:15 UTC
Labels: bug
