### ISSUE TITLE
Fatal errors running telegraf

### ISSUE THREAD

**Issue by sybrandy** [influxdata/telegraf#2269] opened 2017-01-13 13:30 UTC
## Bug report

Running telegraf on a node, it ended up crashing.  There was an issue writing to Kafka for a while and other nodes appear to have recovered properly.

The first messages I see look similar to this:

    fatal error: runtime.unlock: lock count (The period is a unicode dot in the log)

That message appears a large number of times with the exact same timestamp.  I did see this message shortly into the burst of messages:

    fatal error: unexpected signal during runtime execution

Towars the end, a stack trace appeared that looks like this (apologies for typoes):

    [signal 0xb code 0x1 addr=<addr> pc=0x4173cc]
    runtime stack:
    runtime.throw(...)
    /usr/local/go/src/runtime/panic.go:547
    runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12
    runtime.systemstack(...)
    /usr/local/go/src/runtime/asm_amd64.s:291
    runtime.mstart()
    /usr/local/go/src/runtime/proc.go:1051
    goroutine ... [running]:
    runtime.systemstack_switch()
    /usr/local/go/src/runtime/malloc.go:643
    runtime.newarray(...)
    /usr/local/go/src/runtime/malloc.go:798
    runtime.makeslice(...)
    /usr/local/go/src/runtime/slice.go
    /usr/local/go/src/os/dir_unix.go:23
    /usr/local/go/src/os/doc.go:138
    /usr/local/go/src/os/file_unix.go:196
    os.(*File).Readdir(...)
    /usr/local/go/src/os/doc.go:119
    /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/net/net_linux.go:368
    /home/ubuntu/telegraf-build/src/github.com/shirou/gopsutil/net/net_linux.go:440

### Relevant telegraf.conf:

outputs.kafka
inputs.docker
inputs.cpu
inputs.mem
inputs.processes
inputs.system
inputs.disk
inputs.dns_query
inputs.netstat
inputs.net_response
inputs.net
inputs.diskio

### System info:

Telegraf 1.0.0

### Steps to reproduce:

1. Start telegraf on a node and let it run as a daemon.

**Comment by sparrc** [comment] 2017-01-13 13:36
@sybrandy any chance you could upgrade to 1.1.2?

**Comment by sybrandy** [comment] 2017-01-13 13:42
@sparrc I should be able to.  I have to deal with another fire first.

**Comment by sybrandy** [comment] 2017-01-19 13:26
@sparrc O.K.  So, I finally got to this yesterday and so far 1 node has crashed while running 1.1.2, but with a different error.

    entersyscall inconsistent ...
    fatal error: entersyscall
    runtime: newstack ...
    morebuf=...
    runtime.entersyscallblock(0x0)
    /usr/local/go/src/runtime/proc.go:2440
    runtime.notetsleepg(...)
    /usr/local/go/src/runtime/lock_futex.go:205
    runtime.timerproc()
    /usr/local/go/src/runtime/time.go:209
    runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086
    fatal error: runtime: stack split at bad time

That's all it's reporting.  I'm using the following plugins:

output = kafka
input = docker, cpu, mem, processes, system, disk, dns_query, netstat, net_response, net, diskio

**Comment by sparrc** [comment] 2017-01-21 22:35
hm, sounds like memory corruption. Can you provide your full system/OS info?

**Comment by sybrandy** [comment] 2017-01-25 14:26
Apologies for the late reply...I've been sick and this is my first day back.

These are CentOS 7 systems with an upgraded kernel (4.9.1-1.el7).  256G of RAM and 8-8 core CPUs.  Intel Xeon CPU E5-4620 v2 @2.60GHz.  Unfortunately, I don't have the hardware specs.

If it is memory corruption, I'll try to keep track of which nodes it crashes on and try to get the sysadmins to run memcheck on them.  Do you know of a way to get more details about the error I got?  I'd like to get more details the next time it happens.

Thanks.

**Comment by hollow** [comment] 2017-01-27 16:26
same issue here:

```
Jan 27 15:39:00 as2 telegraf[19330]: 2017-01-27T15:39:00Z E! ERROR in input [inputs.exec]: Errors encountered: [metric parsing error, reason: [buffer too short], buffer: [], index: [0]]
Jan 27 15:39:00 as2 telegraf[19330]: fatal error: exitsyscall: syscall frame is no longer valid
Jan 27 15:39:00 as2 telegraf[19330]: fatal error: stack growth after fork
Jan 27 15:39:00 as2 telegraf[19330]: fatal error: runtime·lock: lock count
Jan 27 15:39:00 as2 telegraf[19330]: fatal error: runtime·unlock: lock count
Jan 27 15:39:00 as2 telegraf[19330]: fatal error: runtime·unlock: lock count
...
```

```
$ uname -a
Linux as2 4.8.6-gentoo #2 SMP Mon Nov 7 12:03:12 CET 2016 x86_64 Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz GenuineIntel GNU/Linux
```

**Comment by sparrc** [comment] 2017-02-01 14:52
@hollow can you provide your full config file? do you have steps to reproduce?

**Comment by sparrc** [comment] 2017-02-01 14:52
@sybrandy can you narrow down which plugin(s) are causing this? do you have steps to reproduce?

**Comment by sybrandy** [comment] 2017-02-01 14:58
@sparrc Yeah, I can do that.  May take some time as I don't have any real way to reproduce it.  I just start it up on a node and after some period of time, it crashes.

**Comment by sybrandy** [comment] 2017-02-10 13:14
@sparrc Just wanted to give you a quick update that I'm running 11 instances of telegraf on a single node, one for each input I was running previously, and none of them have crashed yet.  I'm starting to suspect that perhaps there's some interaction between two or more of them that's causing the issue.  I'll let this current config run for a few more days to see what happens.

**Comment by sybrandy** [comment] 2017-02-22 19:31
@sparrc So, still no change.  I'm going to start trying out different combinations to see if I can narrow it down.

**Comment by sybrandy** [comment] 2017-03-16 16:38
So, I'm not sure whether to close this or not.  I've been running 1.2 for a while and I get an number of different errors that don't match the initial problem.  The one I'm seeing today is this:

fatal error runtime.unlock: lock count (repeats 30 times)
fatal error: malloc deadlock
runtime: unexpected return pc for reflect.(*structType).Field called from 0x0
fatal error: unknown caller pc
fatal error: unexpected signal during runtime execution

Unfortunately, that's it.  I'll look and see if any other issues match this one.

**Comment by danielnelson** [comment] 2017-03-16 18:37
@sybrandy Are you still using one telegraf per input plugin, or is this with all of them running within a single instance?

**Comment by sybrandy** [comment] 2017-03-17 11:57
@danielnelson I'm back to running all of the plugins on a single instance as per the original report.  I had tried to run different combinations, but I wasn't getting anywhere quickly and I needed to test out some changes in the newer version for some metrics we're collecting, so I went back to the normal configuration.  I can try some different combinations if you like.

**Comment by danielnelson** [comment] 2017-03-17 17:43
@sybrandy So to attempt to recap, you were running n plugins on n telegrafs, and had no problems.  Then after switching back to n plugins on 1 telegraf, the fatal error returned.  Does this seem correct?

**Comment by sybrandy** [comment] 2017-03-17 18:08
Almost.  After the n plugins to n telegrafs, I attempted to isolate the exact combination of plugins that was causing the error, or at least a combination.  Unfortunately, I didn't get very far and wasn't able to reproduce the errors.

**Comment by ms7s** [comment] 2017-03-24 09:18
Just got a possibly related crash here as well.

These three panics were in the logs after Telegraf crashed:
https://gist.github.com/ms7s/770cff8796e7911f6e25a369b5d11f86

```
$ telegraf -version
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
$ strings /usr/bin/telegraf | grep -E -o 'go1\.[0-9]+\.[0-9]+'
go1.7.5
```

All seem to be related to executing fork while gathering the metrics about system.

**Comment by danielnelson** [comment] 2017-03-27 23:17
@ms7s Can you link to your config?

**Comment by ms7s** [comment] 2017-03-28 08:26
@danielnelson sure, here is the config: https://gist.github.com/ms7s/6256599637367161bf7ddd98ee4ff872

**Comment by danielnelson** [comment] 2017-03-28 21:29
@ms7s, I split out your crashes into some new tickets since I think it's different than the original issue here.  Looks like there are two types of crashes.  #2585 #2586.

**Comment by sybrandy** [comment] 2017-03-31 12:37
Quick update:

On one node over the past two days, I've seen the malloc deadlock error twice.  I also see the following:

```
releasep: ...
fatal error: releasep: invalid p state
panic: runtime error: invalid memory address or nil pointer dereference
<snip>
github.com/shirou/gopsutil/net/net_linux.go:40
github.com/shirou/gopsutil/net/net_linux.go:26
github.com/influxdata/telegraf/plugins/inputs/system/ps.go:116
github.com/influxdata/telegraf/plugins/inputs/system/net.go
github.com/influxdata/telegraf/agent/agent.go:153
github.com/influxdata/telegraf/agent/agent.go:154
<snip>
```

This last one was seen on two different nodes
```
fatal error: scan missed a g
go/src/runtime/panic.go:566
go/src/runtime/mgcmark.go:124
go/src/runtime/mgc.go:1079
go/src/runtime/mgc.go:1497
go/src/runtime/asm_amd64.s:2086
go/src/runtime/mgc.go:1341
```

**Comment by danielnelson** [comment] 2017-03-31 17:44
@sybrandy Can you attach the full stacks for these?

**Comment by sybrandy** [comment] 2017-03-31 17:51
Unfortunately, no.  I can't copy logs from the servers.

**Comment by mldailey** [comment] 2017-06-02 14:31
We ran into this error on one of our systems, using Telegraf 1.3.0 (specifically the 1.3.0-1 Ubuntu package). The system had been running 1.2.1 since 5/11 and then upgraded to 1.3.0 on 5/19. The telegraf process was still running, but was not gathering data or sending it to the influx server - once I restarted telegraf, it started working again.

This is one of four identical servers, and one of over 100 other systems (mostly linux, but some FreeBSD and macOS) and the only one that has thrown this error. I'm attaching the logs and telegraf.conf, both lightly-anonymized.

This system is Ubuntu 16.04.2 LTS, running kernel 4.4.0-78.

Let me know what other info I can provide to help track this down.

[telegraf_logs.gz](https://github.com/influxdata/telegraf/files/1047973/telegraf_logs.gz)
[telegraf.conf.gz](https://github.com/influxdata/telegraf/files/1047974/telegraf.conf.gz)

**Comment by danielnelson** [comment] 2017-06-03 01:06
@mldailey Thanks for adding your logs.  Has this occurred more than the once?

**Comment by mldailey** [comment] 2017-06-04 12:53
@danielnelson Nope - just the one so far, but I saw this bug report and figured I'd send along the logs. I'm keeping an eye on all our other instances and will update this if any others show these symptoms. I'll also try to get an strace of the process next time to see if that sheds any light.

**Comment by danielnelson** [comment] 2018-01-30 22:37
I think this has been fixed in recent Go releases, if anyone is still seeing this on Telegraf 1.5+ let me know and we can reopen.

**Closed by danielnelson** 2018-01-30 22:37 UTC
Labels: bug
