### ISSUE TITLE
[Feature Request] Download config file from remote configuration manager server .

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/telegraf#1496] opened 2016-07-14 20:25 UTC
## Feature Request

Could be a good idea if all telegraf agents could ask for their configuration to a centralized configuration service. This improvement will aid a lot to deploy fast changes over big infrastructures where no other configuration manager exist ( like puppet) , in other organizations there is puppet deployed but its administration is owned by other team.

### Proposal:

Add telegraf the ability to check if telegraf.conf has a remote tag before Parse it. 

### Desired behavior:

Telegraf could add this new feature in a easy way , this could be a proposal.

Instead of the real configuration  telegraf.conf could be something like.
````
[remoteconfig]
             url =  https://mycentral.config.manager.org:3456/
             agent_id = e4b130a00d0daddb03eecebf0f22a6a1b285a07c59251a5b74d38c9b1aa842b0
             remote_ssl_ca = "/etc/telegraf/remote_ca.pem"
             remote_ssl_cert = "/etc/telegraf/remote_cert.pem"
             remote_ssl_key = "/etc/telegraf/remote_key.pem"
             check_new_config_freq = 3600
````
After detected the remoteconfig tag the agent should try to download  from any REST service, and ignore any else in the file ( something like)

```
             https://mycentral.config.manager.org:3456/<product>/<ag_id>/config/
```

by example
```
https://mycentral.config.manager.org:3456/telegraf/e4b130a00d0daddb03eecebf0f22a6a1b285a07c59251a5b74d38c9b1aa842b0/config/

```
Then downloaded config should be parsed as it were the original telegraf.conf TOML  based config file, and then stored in a temporal file /tmp/e4b130a00_<timestamp>.conf .  Then it should create a new  goroutine to check every check_new_config_freq  seconds if there is any change on the configuration served by the remote server. Once detected a SIGHUP should be sent to the process to reconfigure it.

What do you think about this idea?

**Comment by sparrc** [comment] 2016-07-14 21:20
this is a good idea, but basically a dupe of #272

**Closed by sparrc** 2016-07-14 21:20 UTC
