### ISSUE TITLE
inputs.exec with data_format = "csv" 

### ISSUE THREAD

**Issue by petr-tichy** [influxdata/telegraf#12022] opened 2022-10-14 19:04 UTC
### Relevant telegraf.conf

```toml
[[outputs.file]]
  files = ["stdout"]
[[inputs.exec]]
  commands = [ "echo -e 'a,b\n1,2'" ]
  data_format = "csv"
  csv_header_row_count = 1
```

### Logs from Telegraf

```text
2022-10-14T18:48:56Z I! Starting Telegraf 1.20.4
exec,host=8876c39e66a4 a=1i,b=2i 1665773340000000000
exec,host=8876c39e66a4 a=1i,b=2i 1665773350000000000

2022-10-14T18:53:15Z I! Starting Telegraf 1.21.1
exec,host=31f77c233dd2 a=1i,b=2i 1665773600000000000
exec,host=31f77c233dd2 a="a",b="b" 1665773610000000000
exec,host=31f77c233dd2 a=1i,b=2i 1665773610000000000
```

### System info

Telegraf 1.21.1

### Steps to reproduce

Run Telegraf with the provided config

### Expected behavior

Correct metric points containing only data minus header

### Actual behavior

All except the first metric points include the headers as metric points

### Additional info

See discussion in #10678. I think this is is really a regression since 1.21 and current configs won't work without additional `csv_reset_mode = "always"` added to `inputs.exec`

**Comment by MyaLongmire** [comment] 2022-10-17 10:43
@srebhan you have done a lot of work on the csv parser. Do you have any ideas?

**Comment by powersj** [comment] 2022-10-18 13:35
> There is a new option for that: https://github.com/influxdata/telegraf/pull/11288

There is, but his point under `Additional info` is that the behavior changed. Given we try not to break the user either:

1) we change the default setting of csv_reset_mode and treat this as a regression so we can stop telling people who are upgrading that they have to suddenly turn this option on
2) we say this is expected and close this

I am inclined to say we go down the path of option 1. @srebhan ?

**Comment by Hipska** [comment] 2022-10-18 13:46
The behaviour changed between 1.20.4 and 1.21.1 as pointed out by @petr-tichy, but should be resolved with 1.24.

@petr-tichy can you test if your config works as expected with 1.24 ?

**Comment by powersj** [comment] 2022-10-25 16:30
Hi,

Team had a discussion about this issue today and below are the next steps:

* Come up with a list of versions where behavior has changed and determine the oldest version to call "expected behavior"
* Research file & tail behavior of the CSV parser using the above determined versions and how it has changed
* Use this research to develop unit tests on tail and file plugin to aid in future changes 
* Add a warning out to users of the CSV parser about reset mode

Other notes:

* For tail we need a new parser for each time - concern around what happens with CSV reset mode due to the number of "modes"
* For plugins, it is entirely up to the user if they actually need a new one depending on data

**Comment by srebhan** [comment] 2022-10-26 16:55
Here are my fix-points for the historic CSV behavior and a point where behavior changed likely:
- last ensured point of old behavior before PR #8400
- likely change of behavior in PR #9865
Behavior might have changed between those versions, but I'm not 100% sure.

**Comment by powersj** [comment] 2022-10-26 18:39
#6318 was introduced in v1.16.2
#9865 was introduced in v1.21.0

## Versions to test

I propose we build a table using the following versions:

v1.16.1 - pre #6318
v1.16.2 - post #6318
v1.20.4 - pre #9865
v1.21.0 - post #9865
v1.24.0 - current behavior

## Exec Test

Run each test for at least 2 intervals to ensure consistent output.

```
[[inputs.exec]]
  commands = [ "echo -e 'a,b\n1,2'" ]
  data_format = "csv"
  csv_header_row_count = 1
[[outputs.file]]
```

### v1.16.1

```
exec,host=ryzen a=1i,b=2i 1666809190000000000
exec,host=ryzen a=1i,b=2i 1666809200000000000
```

### v1.16.2

```
exec,host=ryzen a=1i,b=2i 1666809210000000000
exec,host=ryzen a=1i,b=2i 1666809220000000000
```

### v1.20.4

```
exec,host=ryzen a=1i,b=2i 1666809490000000000
exec,host=ryzen a=1i,b=2i 1666809500000000000
```

### v1.21.0

```
exec,host=ryzen a=1i,b=2i 1666809240000000000
exec,host=ryzen a="a",b="b" 1666809250000000000
exec,host=ryzen a=1i,b=2i 1666809250000000000
```

### v1.24.0

```
exec,host=ryzen a=1i,b=2i 1666809290000000000
exec,host=ryzen a="a",b="b" 1666809300000000000
exec,host=ryzen a=1i,b=2i 1666809300000000000
```

@srebhan can you come up with a similar test with tail?

**Comment by srebhan** [comment] 2022-11-07 18:15
After some internal discussion we decided to revert CSV behavior back to what it was on 1.20.x, which is what you expect @petr-tichy... This involves:

1. Define test-cases for at least `tail`, `file` and maybe `exec` to make sure we catch potential behavior changes on follow-up versions of Telegraf.
2. Implement a plugin dependent _default_ reset-behavior (i.e. `always` reset for `!tail` and `none` for `tail`) in the config phase. The user should still be able to overwrite the reset behavior with an explicit setting.

**Closed** 2023-01-26 20:51 UTC
Labels: bug
