### ISSUE TITLE
Vsphere plugins error with trlegraf 1.10 version

### ISSUE THREAD

**Issue by vidalsysadmin** [influxdata/telegraf#5548] opened 2019-03-07 16:35 UTC
### Relevant telegraf.conf:
```
[[inputs.vsphere]]
    interval = "60s"
    vcenters = [ "https://123.local/sdk" ]
    username = "user@local"
    password = "123"
    insecure_skip_verify = true
    force_discover_on_init = true

# Exclude all historical metrics
    datastore_metric_exclude = ["*"]
    cluster_metric_exclude = ["*"]
    datacenter_metric_exclude = ["*"]

    collect_concurrency = 5
    discover_concurrency = 5
```

### System info:

Telegraf 1.10
CentOS 7
Vsphere 6.0
InfluxDB 1.7.4

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. Install Telegraf 1.10
2. Vsphere metrics are not written to influxdb

### Expected behavior:

vsphere metrics are written to influxdb

### Actual behavior:

No vsphere metrics are written to influxdb

### Additional info:

```
mars 07 14:40:44 telegraf[8141]: 2019-03-07T13:40:44Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
mars 07 14:40:44 telegraf[8141]: 2019-03-07T13:40:44Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
mars 07 14:40:44 telegraf[8141]: 2019-03-07T13:40:44Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
mars 07 14:40:45 telegraf[8141]: 2019-03-07T13:40:45Z E! [inputs.influxdb]: Error in plugin: [url=http://localhost:8086/debug/vars]: Get http://localhost:8086/debug/vars: dial tcp 127.0.0.1:8086: connect: connection refu
mars 07 14:40:47 telegraf[8141]: 2019-03-07T13:40:47Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
mars 07 14:40:47 telegraf[8141]: 2019-03-07T13:40:47Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
```

These logs occurs even in 1.9.5.1 version of Telgeraf but metrics are written in influxdb, but with the version 1.10, there're same logs but metrics are not written.

**Comment by prydin** [comment] 2019-03-09 16:43
Can you run it with the -debug flag please? I have been unable to reproduce this.

**Comment by prydin** [comment] 2019-03-09 16:44
I'm also seeing a connection refused error to your InfluxDB. Could that be what's causing the issue?

**Comment by vidalsysadmin** [comment] 2019-03-12 09:39
Thanks for your reply, i've these logs too for each vsphere measurements : 

`mars 12 10:13:51 server-X [51321]: 2019-03-12T09:13:51Z E! [outputs.influxdb]: when writing to [http://XXX:8086]: received error partial write: field type conflict: input field "used_summation" on measurement "vsphere_host_cpu" is type float, already exists as type integer dropped=1000; discarding points
`

Here is the result of telegraf -debug : 
`[root@XXXX5 ~]# telegraf -debug
2019-03-12T09:14:05Z I! Starting Telegraf 1.10.0
2019-03-12T09:14:05Z I! Using config file: /etc/telegraf/telegraf.conf
2019-03-12T09:14:05Z I! Loaded inputs: net swap netstat processes system cpu disk diskio mem
2019-03-12T09:14:05Z I! Loaded aggregators:
2019-03-12T09:14:05Z I! Loaded processors:
2019-03-12T09:14:05Z I! Loaded outputs: influxdb
2019-03-12T09:14:05Z I! Tags enabled: host=XXXXX
2019-03-12T09:14:05Z I! [agent] Config: Interval:5s, Quiet:false, Hostname:"XXXXX", Flush Interval:10s
2019-03-12T09:14:05Z D! [agent] Connecting outputs
2019-03-12T09:14:05Z D! [agent] Attempting connection to output: influxdb
2019-03-12T09:14:05Z D! [agent] Successfully connected to output: influxdb
2019-03-12T09:14:05Z D! [agent] Starting service inputs
2019-03-12T09:14:20Z D! [outputs.influxdb] wrote batch of 57 metrics in 15.195224ms
2019-03-12T09:14:20Z D! [outputs.influxdb] buffer fullness: 26 / 10000 metrics.
2019-03-12T09:14:30Z D! [outputs.influxdb] wrote batch of 62 metrics in 9.933028ms
2019-03-12T09:14:30Z D! [outputs.influxdb] buffer fullness: 24 / 10000 metrics.
2019-03-12T09:14:40Z D! [outputs.influxdb] wrote batch of 62 metrics in 13.621473ms
2019-03-12T09:14:40Z D! [outputs.influxdb] buffer fullness: 25 / 10000 metrics.
2019-03-12T09:14:50Z D! [outputs.influxdb] wrote batch of 62 metrics in 27.562078ms
2019-03-12T09:14:50Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:15:00Z D! [outputs.influxdb] wrote batch of 62 metrics in 24.218162ms
2019-03-12T09:15:00Z D! [outputs.influxdb] buffer fullness: 26 / 10000 metrics.
2019-03-12T09:15:10Z D! [outputs.influxdb] wrote batch of 62 metrics in 31.062307ms
2019-03-12T09:15:10Z D! [outputs.influxdb] buffer fullness: 29 / 10000 metrics.
2019-03-12T09:15:20Z D! [outputs.influxdb] wrote batch of 75 metrics in 24.158838ms
2019-03-12T09:15:20Z D! [outputs.influxdb] buffer fullness: 14 / 10000 metrics.
2019-03-12T09:15:30Z D! [outputs.influxdb] wrote batch of 49 metrics in 31.639941ms
2019-03-12T09:15:30Z D! [outputs.influxdb] buffer fullness: 29 / 10000 metrics.
2019-03-12T09:15:40Z D! [outputs.influxdb] wrote batch of 63 metrics in 28.595647ms
2019-03-12T09:15:40Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:15:50Z D! [outputs.influxdb] wrote batch of 62 metrics in 36.455065ms
2019-03-12T09:15:50Z D! [outputs.influxdb] buffer fullness: 30 / 10000 metrics.
2019-03-12T09:16:00Z D! [outputs.influxdb] wrote batch of 61 metrics in 15.564832ms
2019-03-12T09:16:00Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:16:10Z D! [outputs.influxdb] wrote batch of 63 metrics in 29.39629ms
2019-03-12T09:16:10Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:16:20Z D! [outputs.influxdb] wrote batch of 61 metrics in 20.891633ms
2019-03-12T09:16:20Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:16:30Z D! [outputs.influxdb] wrote batch of 83 metrics in 18.341145ms
2019-03-12T09:16:30Z D! [outputs.influxdb] buffer fullness: 8 / 10000 metrics.
2019-03-12T09:16:40Z D! [outputs.influxdb] wrote batch of 47 metrics in 36.680284ms
2019-03-12T09:16:40Z D! [outputs.influxdb] buffer fullness: 24 / 10000 metrics.
2019-03-12T09:16:50Z D! [outputs.influxdb] wrote batch of 67 metrics in 13.315226ms
2019-03-12T09:16:50Z D! [outputs.influxdb] buffer fullness: 17 / 10000 metrics.
2019-03-12T09:17:00Z D! [outputs.influxdb] wrote batch of 51 metrics in 27.371381ms
2019-03-12T09:17:00Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:17:10Z D! [outputs.influxdb] wrote batch of 63 metrics in 22.395121ms
2019-03-12T09:17:10Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:17:20Z D! [outputs.influxdb] wrote batch of 61 metrics in 16.815098ms
2019-03-12T09:17:20Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:17:30Z D! [outputs.influxdb] wrote batch of 63 metrics in 16.084795ms
2019-03-12T09:17:30Z D! [outputs.influxdb] buffer fullness: 21 / 10000 metrics.
2019-03-12T09:17:40Z D! [outputs.influxdb] wrote batch of 62 metrics in 25.805732ms
2019-03-12T09:17:40Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:17:50Z D! [outputs.influxdb] wrote batch of 61 metrics in 10.893697ms
2019-03-12T09:17:50Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:18:00Z D! [outputs.influxdb] wrote batch of 62 metrics in 17.276528ms
2019-03-12T09:18:00Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:18:10Z D! [outputs.influxdb] wrote batch of 62 metrics in 30.97794ms
2019-03-12T09:18:10Z D! [outputs.influxdb] buffer fullness: 30 / 10000 metrics.
2019-03-12T09:18:20Z D! [outputs.influxdb] wrote batch of 62 metrics in 23.45242ms
2019-03-12T09:18:20Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:18:30Z D! [outputs.influxdb] wrote batch of 62 metrics in 10.237165ms
2019-03-12T09:18:30Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:18:40Z D! [outputs.influxdb] wrote batch of 63 metrics in 29.204846ms
2019-03-12T09:18:40Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:18:50Z D! [outputs.influxdb] wrote batch of 62 metrics in 15.718363ms
2019-03-12T09:18:50Z D! [outputs.influxdb] buffer fullness: 26 / 10000 metrics.
2019-03-12T09:19:00Z D! [outputs.influxdb] wrote batch of 62 metrics in 32.452522ms
2019-03-12T09:19:00Z D! [outputs.influxdb] buffer fullness: 30 / 10000 metrics.
2019-03-12T09:19:10Z D! [outputs.influxdb] wrote batch of 74 metrics in 25.484367ms
2019-03-12T09:19:10Z D! [outputs.influxdb] buffer fullness: 15 / 10000 metrics.
2019-03-12T09:19:20Z D! [outputs.influxdb] wrote batch of 49 metrics in 29.390184ms
2019-03-12T09:19:20Z D! [outputs.influxdb] buffer fullness: 29 / 10000 metrics.
2019-03-12T09:19:30Z D! [outputs.influxdb] wrote batch of 63 metrics in 25.182756ms
2019-03-12T09:19:30Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:19:40Z D! [outputs.influxdb] wrote batch of 62 metrics in 24.687013ms
2019-03-12T09:19:40Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:19:50Z D! [outputs.influxdb] wrote batch of 61 metrics in 29.230384ms
2019-03-12T09:19:50Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:20:00Z D! [outputs.influxdb] wrote batch of 63 metrics in 28.845693ms
2019-03-12T09:20:00Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:20:10Z D! [outputs.influxdb] wrote batch of 62 metrics in 45.746932ms
2019-03-12T09:20:10Z D! [outputs.influxdb] buffer fullness: 26 / 10000 metrics.
2019-03-12T09:20:20Z D! [outputs.influxdb] wrote batch of 62 metrics in 23.843144ms
2019-03-12T09:20:20Z D! [outputs.influxdb] buffer fullness: 19 / 10000 metrics.
2019-03-12T09:20:30Z D! [outputs.influxdb] wrote batch of 61 metrics in 35.294097ms
2019-03-12T09:20:30Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:20:40Z D! [outputs.influxdb] wrote batch of 63 metrics in 32.143936ms
2019-03-12T09:20:40Z D! [outputs.influxdb] buffer fullness: 26 / 10000 metrics.
2019-03-12T09:20:50Z D! [outputs.influxdb] wrote batch of 78 metrics in 17.527326ms
2019-03-12T09:20:50Z D! [outputs.influxdb] buffer fullness: 11 / 10000 metrics.
2019-03-12T09:21:00Z D! [outputs.influxdb] wrote batch of 46 metrics in 16.922572ms
2019-03-12T09:21:00Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:21:10Z D! [outputs.influxdb] wrote batch of 61 metrics in 23.704961ms
2019-03-12T09:21:10Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:21:20Z D! [outputs.influxdb] wrote batch of 62 metrics in 20.650776ms
2019-03-12T09:21:20Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:21:30Z D! [outputs.influxdb] wrote batch of 62 metrics in 27.134651ms
2019-03-12T09:21:30Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:21:40Z D! [outputs.influxdb] wrote batch of 63 metrics in 17.336013ms
2019-03-12T09:21:40Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:21:50Z D! [outputs.influxdb] wrote batch of 61 metrics in 30.197158ms
2019-03-12T09:21:50Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:22:00Z D! [outputs.influxdb] wrote batch of 62 metrics in 22.41613ms
2019-03-12T09:22:00Z D! [outputs.influxdb] buffer fullness: 28 / 10000 metrics.
2019-03-12T09:22:10Z D! [outputs.influxdb] wrote batch of 70 metrics in 36.786157ms
2019-03-12T09:22:10Z D! [outputs.influxdb] buffer fullness: 23 / 10000 metrics.
2019-03-12T09:22:20Z D! [outputs.influxdb] wrote batch of 54 metrics in 31.348443ms
2019-03-12T09:22:20Z D! [outputs.influxdb] buffer fullness: 27 / 10000 metrics.
2019-03-12T09:22:30Z D! [outputs.influxdb] wrote batch of 84 metrics in 34.977264ms
2019-03-12T09:22:30Z D! [outputs.influxdb] buffer fullness: 5 / 10000 metrics.`

**Comment by vidalsysadmin** [comment] 2019-03-12 10:58
I've deleted  all data ans some measurements of vsphere in influxdb (i couldn't remove some measurements by "delete from" or "drop measurements" commands).

I've started telegaf agent and metrics go up well in influxdb.

But, i still have the same error logs concerned the field type conflict.

**Comment by prydin** [comment] 2019-03-12 12:25
Can you try the latest nightly build, please? Make sure your config includes the following: ```use_int_samples = true```

**Comment by jgeusebroek** [comment] 2019-03-12 18:22
Same problem here. I tried the nightly + `use_int_samples = true` and now I have: 

`received error partial write: field type conflict: input field "usage_average" on measurement "vsphere_vm_net" is type integer, already exists as type float dropped=922; discarding points`

`vsphere_vm_net` is not the only measurement, there are more. Also, I find it strange I cannot drop all the measurements from InfluxDB. No error, it just stays in the database.

**Comment by vidalsysadmin** [comment] 2019-03-13 17:05
> `vsphere_vm_net` is not the only measurement, there are more. Also, I find it strange I cannot drop all the measurements from InfluxDB. No error, it just stays in the database.

Yep ! I've the same issues on influxdb, i can't delete some measurements. I've the same errors still, but telegraf agent go up well metrics from vsphere. :/

Where can i find the ngihtly build ? I don't find it on github and influw website.

**Comment by glinton** [comment] 2019-03-13 19:48
Nightly builds for telegraf can be found at https://github.com/influxdata/telegraf#nightly-builds

**Comment by danielnelson** [comment] 2019-03-24 02:09
Very sorry about the type conflict error, the only workaround I know of is to set `name_prefix` or `name_suffix` for the plugin to rename the measurements.  Here is the issue for InfluxDB about the deletion issue https://github.com/influxdata/influxdb/issues/10052.

@vidalsysadmin Can you try the workaround and then let us know if that clears up the issue sending data into InfluxDB?  If it's working are you still seeing this log message:
```
E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
```

**Comment by jgeusebroek** [comment] 2019-03-24 16:02
I was finally able to delete all the measurements. Suddenly it was possible?
However I'm having the same issues with both the nightly build as well as 1.10.

Random measurements drop because of the field type conflicts.

`[outputs.influxdb]: when writing to [https://xxx]: received error partial write: field type conflict: input field "numStandbyGuest_latest" on measurement "vsphere_datacenter_vmop" is type float, already exists as type integer dropped=2; discarding points`

**Comment by prydin** [comment] 2019-03-24 19:20
@danielnelson I'm the one who should apologize. I've been thinking of a "lenient mode" for the InfluxDB output that tries to coerce the measurements into the right type if it gets an error. Looked at the code and it seems possible. 6hem again, might be too much of a bandaid.

**Comment by vidalsysadmin** [comment] 2019-03-29 16:32
@danielnelson I've tested with `name_suffix` and i've metrics well in influxdb, but i still have this error in the logs.

**Comment by danielnelson** [comment] 2019-03-29 21:20
> I've been thinking of a "lenient mode" for the InfluxDB output that tries to coerce the measurements into the right type if it gets an error.

I don't want to go down this path in Telegraf as I feel that this type of behavior would be the databases job.

@jgeusebroek Would it be possible for you to `create database telegraf_vsphere` in InfluxDB and setup your output to send to this fresh database?  If the error still occurs in there then could you open an new issue?  If it doesn't occur then it must be residual in the database.

I know this isn't the cause of the data not showing in the database, but for this issue let's focus on trying to determine the source of this error:
```
Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
```

**Comment by huntervp** [comment] 2019-04-25 18:03
I'm experiencing a similar problem with getting historical data from vCenter. I have a different frequency of get statistics in the vCenter settings (Interval Duration = 2 minutes). I met a similar bug when integrating with Cisco UCSD, when UCSD could not work at intervals other than the standard 5 minutes. Maybe this is a similar situation?

Log:
```
2019-04-25T17:44:33Z D! [inputs.vsphere] Find(Datastore, /*/datastore/**) returned 13 objects
2019-04-25T17:44:33Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
2019-04-25T17:44:33Z D! [inputs.vsphere] Found 0 metrics for datastore01
2019-04-25T17:44:33Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
2019-04-25T17:44:33Z D! [inputs.vsphere] Found 0 metrics for datastore02
2019-04-25T17:44:33Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
2019-04-25T17:44:33Z D! [inputs.vsphere] Found 0 metrics for datastore03
2019-04-25T17:44:33Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
2019-04-25T17:44:33Z D! [inputs.vsphere] Found 0 metrics for datastore04
2019-04-25T17:44:33Z E! [inputs.vsphere]: Error while getting metric metadata. Discovery will be incomplete. Error: ServerFaultCode: A specified parameter was not correct: interval
2019-04-25T17:44:33Z D! [inputs.vsphere] Found 0 metrics for datastore05
```

config:
```
# # Read metrics from VMware vCenter
## Realtime instance
[[inputs.vsphere]]
  interval = "60s"
  vcenters = [ "https://url" ]
  username = "***"
  password = "***"
  insecure_skip_verify = true
  force_discover_on_init = true
  # Exclude all historical metrics
  datastore_metric_exclude = ["*"]
  cluster_metric_exclude = ["*"]
  datacenter_metric_exclude = ["*"]
  collect_concurrency = 5
  discover_concurrency = 5

# Historical instance
[[inputs.vsphere]]
  interval = "120s"
  vcenters = [ "https://url" ]
  username = "***"
  password = "***"
  insecure_skip_verify = true
  force_discover_on_init = true
  # Exclude realtime metrics
  host_metric_exclude = ["*"]
  vm_metric_exclude = ["*"]
  collect_concurrency = 3
  max_query_metrics = 256
```

**Comment by prydin** [comment] 2019-04-25 18:40
@huntervp Check that your vCenter has 5 minute samples for datastores turned on.

**Comment by huntervp** [comment] 2019-04-25 18:50
@prydin We replaced them by 2 minutes(this is our standard). Is it possible to use an interval of 2 minutes or does telegraf support only 5 mins?

**Comment by prydin** [comment] 2019-04-25 18:52
Unfortunately, that's currently not supported. The plugin expects there to be a 5 minute interval. You may file an enhancement request and we'll address that as soon as we can.

**Comment by huntervp** [comment] 2019-04-25 18:54
@prydin Ok, thanks for the consultation!

**Comment by AndySilvia** [comment] 2019-05-29 10:21
Hi!

We have 5-minute-interval set on our test-vcenter -> everything OK, on our prod-vcenter there we have 1-minute-interval and therefore no historical metrics like datastores are logged (log-messages like these in the comments). 

As you wrote this is because telegraf expects 5-minute-interval and you talked about an enhancement request - is something like that done? Will be of interest for us too...

**Comment by sspaink** [comment] 2022-01-20 02:26
Closing because lots of improvements have been made since v1.10, if your still experiencing problems please re-open or create a new issue.

**Closed by sspaink** 2022-01-20 02:26 UTC
Labels: bug, area/vsphere
