### ISSUE TITLE
Processes input plugin - Higher CPU usage than expected

### ISSUE THREAD

**Issue by AlbinOS** [influxdata/telegraf#2666] opened 2017-04-13 09:43 UTC
### Relevant telegraf.conf:

```
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply prepend
# them with $. For strings the variable must be within quotes (ie, "$STR_VAR"),
# for numbers and booleans they should be plain (ie, $INT_VAR, $BOOL_VAR)


# Global tags can be specified here in key="value" format.
[global_tags]
   env = "prod"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
  ## output, and will flush this buffer on a successful write. Oldest metrics
  ## are dropped first when this buffer fills.
  ## This buffer only fills when writes fail to output plugin(s).
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "3s"

  ## Default flushing interval for all outputs. You shouldn't set this below
  ## interval. Maximum flush_interval will be flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default, precision will be set to the same timestamp order as the
  ## collection interval, with the maximum being 1s.
  ## Precision will NOT be used for service inputs, such as logparser and statsd.
  ## Valid values are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Logging configuration:
  ## Run telegraf with debug log messages.
  debug = false
  ## Run telegraf in quiet mode (error log messages only).
  quiet = false
  ## Specify the log file name. The empty string means to log to stderr.
  logfile = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
  ## The full HTTP or UDP endpoint URL for your InfluxDB instance.
  ## Multiple urls can be specified as part of the same cluster,
  ## this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://localhost:8089"] # UDP endpoint example
  urls = ["https://myinfluxdb.com"] # required
  ## The target database for metrics (telegraf will create it if not exists).
  database = "telegraf" # required

  ## Retention policy to write to. Empty string writes to the default rp.
  retention_policy = ""
  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all"
  write_consistency = "any"

  ## Write timeout (for the InfluxDB client), formatted as a string.
  ## If not provided, will default to 5s. 0s means no timeout (not recommended).
  timeout = "5s"
  username = "telegraf"
  password = "maawesomepassword"
  ## Set the user agent for HTTP POSTs (can be useful for log differentiation)
  # user_agent = "telegraf"
  ## Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
  # udp_payload = 512

  ## Optional SSL Config
  ssl_ca = "/etc/telegraf/my_ca_cert.crt"
  # ssl_cert = "/etc/telegraf/cert.pem"
  # ssl_key = "/etc/telegraf/key.pem"
  ## Use SSL but skip chain & host verification
  # insecure_skip_verify = false



###############################################################################
#                            SERVICE PLUGINS                                  #
###############################################################################

[[inputs.cpu]]
    percpu = true
    totalcpu = true
    collect_cpu_time = false
[[inputs.disk]]
    ignore_fs = [ "tmpfs", "devtmpfs" ]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]
[[inputs.netstat]]
[[inputs.nstat]]
    interval = "2s"
[[inputs.procstat]]
    exe = "telegraf"
[[inputs.zfs]]
[[inputs.mysql]]
    servers = [ "telegraf:telegraf@tcp(mysql-host:3306)/?tls=false" ]
[[inputs.procstat]]
    exe = "switcheroo"
```

### System info

```
$> telegraf version
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
```

```
$> uname -a
Linux myhostname 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue description

Dear all,

I have two host running the same hardware, the same OS, the same telegraf version and using the same telegraf.conf but I have higher telegraf CPU usage on one of them. One of the most notably difference between the two is the one with the higher CPU usage is running ZFS.

Doing some investigation, I found that the inputs.processes plugin is consuming 1-1.5% alone (using collection_jitter = "3s") more on the host using ZFS :

![screen shot 2017-04-10 at 11 40 25](https://cloud.githubusercontent.com/assets/1978405/24855646/8ac06f8e-1de2-11e7-9b1c-b9482728ff3e.png)

![screen shot 2017-04-10 at 11 39 18](https://cloud.githubusercontent.com/assets/1978405/24855807/f9d2910e-1de2-11e7-96e2-0041c09c6f80.png)

The difference about the inputs.processes plugin is that on the ZFS host, the number of process is drastically higher : 

![screen shot 2017-04-10 at 11 49 30](https://cloud.githubusercontent.com/assets/1978405/24856089/ca9ed996-1de3-11e7-9a20-dc24c76b7d97.png)

![screen shot 2017-04-10 at 11 49 14](https://cloud.githubusercontent.com/assets/1978405/24856090/caa235dc-1de3-11e7-8d80-871c1e3a92ed.png)

Do you have any idea why is it causing this kind of load ?

Thanks a lot for the awesome work though !

**Comment by ssoroka** [comment] 2020-05-15 23:28
Unfortunately this is really old, and a lot has changed since Telegraf 1.2.1. It's not clear if this is still an issue. To track it down I'd be looking for a docker container with zfs that reproduces the issue.

i'm going to close it, but please feel free to to re-raise it if you still have any concerns.

Thanks!

**Closed by ssoroka** 2020-05-15 23:28 UTC
Labels: performance
