### ISSUE TITLE
Documentation for rabbitmq plugin

### ISSUE THREAD

**Issue by sLuvpreet33** [influxdata/telegraf#2744] opened 2017-05-01 20:34 UTC
Rabbitmq plugin must be documented.

We need to enable the Rabbitmq management plugin to collect stats for rabbitmq,, and that is nowhere written. I ended up wasting complete day as I did not know this.

So, It would be better for everyone if it is documented well.

**Comment by danielnelson** [comment] 2017-05-01 20:42
Duplicate of #2712

**Closed by danielnelson** 2017-05-01 20:42 UTC
