### ISSUE TITLE
input/mongodb output counters from db.serverStatus().opcounters

### ISSUE THREAD

**Issue by m3nthal** [influxdata/telegraf#4296] opened 2018-06-15 12:45 UTC
## Feature Request

Hi, it would be very nice to output counters from `db.serverStatus().opcounters`. I could see from the code that these metrics are already collected and made into throughput metric with `*_per_sec`. 

MongoDB Reference on `opcounters`: https://docs.mongodb.com/manual/reference/command/serverStatus/#opcounters

### Proposal:

What I suggest is to output also `*_count` metrics that would display raw counter for `db.serverStatus().opcounters`.

### Current behavior:
`db.serverStatus().opcounters` yields:

- inserts_per_sec
- queries_per_sec 
- updates_per_sec
- deletes_per_sec
- getmores_per_sec
- commands_per_sec

### Desired behavior:
`db.serverStatus().opcounters` yields:

- inserts_per_sec
- inserts_counter
- queries_per_sec
- queries_counter
- updates_per_sec
- updates_counter
- deletes_per_sec
- deletes_counter
- getmores_per_sec
- getmores_counter
- commands_per_sec
- commands_counter

### Use case: [Why is this important (helps with prioritizing requests)]
Since we collect metrics every 30s, the `*_per_sec` metric would not reveal much information about what happened between the measurements. Counter would be useful to get more information for rare metrics collection.

**Comment by danielnelson** [comment] 2018-06-15 19:40
Agreed, I would like to remove the per_sec metrics as well at the next major release (2.0).  I believe this is a duplicate of https://github.com/influxdata/telegraf/issues/3121 though so I'm going to close this issue.

**Closed by danielnelson** 2018-06-15 19:40 UTC
