### ISSUE TITLE
procstat input cpu_usage too high values

### ISSUE THREAD

**Issue by miniskipper** [influxdata/telegraf#2196] opened 2016-12-22 08:40 UTC
The procstat input is generating too high values for the cpu_usage field.
The values for the process pigz are ok (ran it with 4 threads) but the others are way too high. Its a 4 Core / 2 Threads Xeon CPU.

CentOS Linux release 7.2.1511 (Core)
Telegraf v1.1.1 (git: release-1.1.0 94de9dca1fc6efb3a4bf3ec6869c356278c6755a)

> select host, process_name, cpu_usage from procstat where cpu_usage>100 order by time
name: procstat
time                    host            process_name    cpu_usage
----                    ----            ------------    ---------
1482392520000000000     host      pigz            398.5449421379077
1482392530000000000     host      pigz            395.8271164623208
1482392540000000000     host      pigz            386.8910854788462
1482392550000000000     host      pigz            369.96374405295273
1482392560000000000     host      pigz            377.6163310338972
1482392570000000000     host      pigz            395.47233573885563
1482392580000000000     host      pigz            380.39056552038323
**1482394440000000000     host      less            4520.342322820127
1482394960000000000     host      sleep           977.0279217270308
1482395100000000000     host      kdmflush        3536.102794654274
1482395290000000000     host      sleep           1953.137071089795**

**Comment by miniskipper** [comment] 2016-12-23 07:27
Some more with even higher cpu_usage

```
time			host		process_name	cpu_usage
----			----		------------	---------
1482397650000000000	host	sleep		40737.05693058064
1482408530000000000	host	sleep		12110.124643413938
1482408770000000000	host	sleep		11868.973132942669
1482425200000000000	host	qemu-kvm	15953.945299359415
1482438840000000000	host	udevadm		80322.78039799824
1482449270000000000	host	backupmysql.sh	40593.719194668025
1482467410000000000	host	sleep		41234.46292959501
1482476450000000000	host	udevadm		16348.302791503804
1482477480000000000	host	udevadm		11661.19199136133
```

**Comment by sparrc** [comment] 2017-01-06 10:39
certainly seems wrong, do you have steps to reproduce?

**Comment by matthew-churcher** [comment] 2017-03-15 16:23
Hi, we are seeing something similar cpu_usage is sometimes impossibly high and at other times negative. The 'cpu_user' etc appears to be ok, but we are seeing some weird duplicates of data where the same processes are duplicated with the incorrect user tag. We are current on version 1.0.0. This is a 56 core cent0s 6.7 system. And our config looks like this..

[[inputs.procstat]]
  user = "tungsten"
  interval = "5s"

[[inputs.procstat]]
  user = "mysql"
  interval = "5s"

I'm about to try with 1 input configured, will upgrade, perhaps try pid or exe_name. and we have go devs available to debug.

What information can we provide you with to help?

**Comment by danielnelson** [comment] 2017-03-15 18:00
The incorrect user tag could be related to #1636, I'm working on a fix for that now.  I wonder if gopsutil is detecting the number of cpu's incorrectly, although a negative usage might mean that it is being calculated incorrectly.

Can you check the number of cpu's gopsutil detects over here: https://github.com/shirou/gopsutil/blob/master/process/process.go#L131 and, if possible, capture the value of the intermediate calculations during a bad collection.

**Comment by matthew-churcher** [comment] 2017-03-15 18:34
When I try, runtime.NumCPU(). It returns 56 as expected. So I would thought it would for them too.
I'm not sure what they use that for though, the first line of the /proc/(pid)/stat is the total anyway but i can take that you with them.

I have seen some instances of cpu_user being wacky as well as cpu_usage so it could certainly be gopsutil.

I'd have to get one of the devs to help me with debug values  tomorrow for now that's beyond my humble skills.

**Comment by matthew-churcher** [comment] 2017-03-22 13:14
We had multiple instances of the plugin enabled. When all but one it appears to behave as expected. I'm thinking it could be a concurrency issue.

**Comment by danielnelson** [comment] 2017-03-22 19:22
@matthew-churcher I pushed a fix for #1636 to master, can you check if it helps?

**Comment by matthew-churcher** [comment] 2017-03-28 14:22
Thanks for the patch. I’ve managed to build trunk and testing is underway in a test environment (no problems today). I’m going to discuss with the team tomorrow, see if we can push this to one of the 56 core staging environments.

Will let you know how it goes.

**Comment by danielnelson** [comment] 2017-04-06 21:01
@miniskipper Can you also test the fix with the code from master?

**Comment by miniskipper** [comment] 2017-04-07 04:15
Just built the master. Telegraf is running. Fingers crossed.

**Comment by matthew-churcher** [comment] 2017-04-07 11:27
@danielnelson Looks good, I've had it two multi-core environments for over a week and no signs of implausible values.

**Comment by danielnelson** [comment] 2017-04-12 00:13
Great, thanks for the updates.

**Closed by danielnelson** 2017-04-12 00:13 UTC
