### ISSUE TITLE
win_perf_counters ignore instances with '#' in instance name

### ISSUE THREAD

**Issue by lucadistefano** [influxdata/telegraf#2557] opened 2017-03-21 17:31 UTC
### Relevant telegraf.conf:
```

###############################################################################
#                                  INPUTS                                     #
###############################################################################

[[inputs.win_perf_counters]]
	PrintValid=true

	[[inputs.win_perf_counters.object]]
		ObjectName = "Process"
		Counters = ["Handle Count"]
		Instances = ["spoolsv","svchost","svchost#1","svchost#2"]
		Measurement = "win_proc1"
				
```

### System info:
windows server 2012R2 , telegraf 1.2.1

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

`telegraf.exe --debug --config test-instancedash.conf`

### Expected behavior:
metrics of all instances (spoolsv,svchost,svchost#1,svchost#2) must be captured

### Actual behavior:
metrics of instances with '#' in instance name are omitted

### Additional info:

```
C:\Program Files\Telegraf>telegraf.exe --debug --config test-instancedash.conf
2017-03-21T17:25:11Z D! Attempting connection to output: influxdb
2017-03-21T17:25:11Z D! Successfully connected to output: influxdb
2017-03-21T17:25:11Z I! Starting Telegraf (version 1.2.1)
2017-03-21T17:25:11Z I! Loaded outputs: influxdb
2017-03-21T17:25:11Z I! Loaded inputs: inputs.win_perf_counters
2017-03-21T17:25:11Z I! Tags enabled: host=WIN-MONTEST
2017-03-21T17:25:11Z I! Agent Config: Interval:5s, Quiet:false, Hostname:"WIN-MONTEST", Flush Interval:10s
Valid: \Process(spoolsv)\Handle Count
Valid: \Process(svchost)\Handle Count
Valid: \Process(svchost#1)\Handle Count
Valid: \Process(svchost#2)\Handle Count
win_proc1,instance=spoolsv,objectname=Process,host=WIN-MONTEST Handle_Count=368 1490117115000000000

win_proc1,instance=svchost,objectname=Process,host=WIN-MONTEST Handle_Count=451 1490117115000000000

win_proc1,instance=spoolsv,objectname=Process,host=WIN-MONTEST Handle_Count=368 1490117120000000000

win_proc1,host=WIN-MONTEST,instance=svchost,objectname=Process Handle_Count=451 1490117120000000000

win_proc1,instance=spoolsv,objectname=Process,host=WIN-MONTEST Handle_Count=368 1490117125000000000

win_proc1,instance=svchost,objectname=Process,host=WIN-MONTEST Handle_Count=451 1490117125000000000

2017-03-21T17:25:25Z D! Output [influxdb] buffer fullness: 6 / 1000 metrics.
2017-03-21T17:25:25Z D! Output [influxdb] wrote batch of 6 metrics in 5.0028ms
```

**Comment by willemdh** [comment] 2017-03-21 19:11
This seems like a duplicate of https://github.com/influxdata/telegraf/issues/1827

**Closed** 2017-03-21 21:33 UTC
