### ISSUE TITLE
[Feature Request] Custom application metrics

### ISSUE THREAD

**Issue by AlexKapustin** [influxdata/telegraf#582] opened 2016-01-26 05:07 UTC
Hello!

Please let us know, are you planning to add possibility to send custom metrics from application to telegraf ?

Ideally it would be:

tcp/udb server socket (depends on config) which accepts metrics in JSON format, gather it, aggregate (?) and flush into db each N seconds (depends on config)

Thanks,
Have a great day! :)

**Comment by sparrc** [comment] 2016-01-26 05:10
yes, dupe of https://github.com/influxdata/telegraf/issues/481

**Closed by sparrc** 2016-01-26 05:10 UTC

**Comment by AlexKapustin** [comment] 2016-01-26 07:00
Thank you for your response!
