### ISSUE TITLE
Marshal error with SNMP plugin 1.21.0

### ISSUE THREAD

**Issue by mabnz** [influxdata/telegraf#10305] opened 2021-12-19 08:26 UTC
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "udp://fgt01:161" ]
  version = 2
  timeout = "5s"
  retries = 3
  community = "public"
  name = "fortisnmp"

	[[inputs.snmp.field]]
		name = "hostname"
		oid = "SNMPv2-MIB::sysName.0"
		is_tag = true

	[[inputs.snmp.field]]
		name = "cpu"
		oid = "FORTINET-FORTIGATE-MIB::fgSysCpuUsage.0"

	[[inputs.snmp.field]]
		name = "memory"
		oid = "FORTINET-FORTIGATE-MIB::fgSysMemUsage.0"
```

### System info

Telegraf 1.20.0, Ubuntu 20.04.3.

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

No errors.

### Actual behavior

After upgrade to 1.21.0, the snmp agent is having trouble fetching certain OIDs.

```
telegraf[505949]: 2021-12-18T21:14:00Z E! [inputs.snmp] Error in plugin: agent 192.168.62.11:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:00Z E! [inputs.snmp] Error in plugin: agent 192.168.60.122:161: performing get on field model: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.60.1:161: performing get on field cpu: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.62.10:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.62.11:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier

```

**Comment by srebhan** [comment] 2021-12-20 07:37
I think this is a duplicate of #10304... At least it seems to share the cause...

**Comment by MyaLongmire** [comment] 2021-12-21 17:36
Due to the holidays coming up the team will not have time to have another bug release. There are a few options while you wait for this fix:
1) Roll back to 1.20.4
2) Grab a nightly build -> the snmp panic fix has been merged into master but we are still diligently working on the marshal error
3) clone master

Thank you for your continued support of Telegraf and for your patience with this switch to `gosmi`!

**Comment by MyaLongmire** [comment] 2021-12-21 19:58
A [pr](https://github.com/influxdata/telegraf/pull/10322) for the marshal issue is now up. If you would please test it out.

**Closed** 2021-12-22 20:41 UTC
Labels: bug, area/snmp, regression
