### ISSUE TITLE
Adding support of SFlow drop packets

### ISSUE THREAD

**Issue by akarneliuk** [influxdata/telegraf#15375] opened 2024-05-17 20:12 UTC
### Use Case

Hey team,

I'm evaluating usage of SFlow to collect data from internet devices, where BGP information is crucial. Sflow v5 supports this information per their specification: https://sflow.org/SFLOW-STRUCTS5.txt
```
/* Extended Gateway Data */
/* opaque = flow_data; enterprise = 0; format = 1003 */

struct extended_gateway {
   next_hop nexthop;           /* Address of the border router that should
                                  be used for the destination network */
   unsigned int as;            /* Autonomous system number of router */
   unsigned int src_as;        /* Autonomous system number of source */
   unsigned int src_peer_as;   /* Autonomous system number of source peer */
   as_path_type dst_as_path<>; /* Autonomous system path to the destination */
   unsigned int communities<>; /* Communities associated with this route */
   unsigned int localpref;     /* LocalPref associated with this route */
}
```
This information is missing however in input.sflow plugin.

### Expected behavior

Telegraf parses struct extended_gateway and this information is available within tags along with already parsed structs `extended_router` and `extended_switch`. [SFlow plugin configuration](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sflow/README.md)

### Actual behavior

This struct is currently not parsed and therefore information isn't available.

**Comment by powersj** [comment] 2024-05-17 20:21
Hi,

Can you please look at using the inputs.netflow plugin instead. It does look to already support the [extended gateway](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/netflow/sflow_v5.go#L247).

Thanks

**Comment by akarneliuk** [comment] 2024-05-17 20:39
Hey @powersj ,

Thanks for prompt response. I did look into that plug-in, but sadly I was getting errors for every packet I was receiving; hence, I switched to sflow plug-in, which worked quite nicely apart from missing this struct.

What is the long-term goal in InfluxData? are you supporting both plug-ins or going to sunset one in a favour of another?

Thanks,
Anton

**Comment by powersj** [comment] 2024-05-17 20:40
sflow is deprecated in favor of netflow. If you are getting errors please do let us know and we can take a look.

**Comment by akarneliuk** [comment] 2024-05-18 09:22
Hey @powersj ,

understood. So, here is my issue with `netflow` plug-in.
Telegraf version: `1.30.2`
Configuration
```
[[inputs.netflow]]
  service_address = "udp://:6343"
  protocol = "sflow v5"
```

When I send sFlow data to Telegraf, I see the following errors in the Telegarf log:
```
2024-05-18T09:08:13Z E! [inputs.netflow] Error in plugin: sFlow sample [[format:5 seq: 71837279] unknown format 5]; raw data ...
```

Thanks,
Anton

**Comment by powersj** [comment] 2024-05-20 13:57
> format:5

Looking at the upstream goflow2 code, format 5 is not defined:

>	FORMAT_RAW_PKT     = 1
>	FORMAT_ETH         = 2
>	FORMAT_IPV4        = 3
>	FORMAT_IPV6        = 4

From [slofw.go](https://github.com/netsampler/goflow2/blob/3dd0e8a90d6850f54af1bf2ff7ab43f395f1f802/decoders/sflow/sflow.go#L14-L17). Is this some sort of extended data? @srebhan thoughts?

**Comment by srebhan** [comment] 2024-05-21 09:07
@powersj will look into it...

@akarneliuk could you please post the data after the `raw data` part of the log message so I can reproduce the issue locally!?

**Comment by akarneliuk** [comment] 2024-05-21 18:18
Hey @srebhan ,

Thanks for looking into that one. I'm looking how I can anonymise the packet for compliance reasons. What I was able to detect by digging into pcap with [sflowtool](https://github.com/sflow/sflowtool) is that the packets causing problems are drop notifications:
https://sflow.org/sflow_drops.txt

Which I believe raises an interesting difference in behaviour between sflow plugins and netflow plguins in Telegraf: sflow plugin ignnores things it cannot decode and decode the rest. The netflow throws an error.  Perhaps, the later is more preferable (it would be nice though to have possibility (like flag or so ) to ignore problematic issues.

Going back to original issue, do you think you can look into implementing drop notifications? Also if you can DM me your mail so I can share anonymised pcap.

Best,
Anton

**Comment by akarneliuk** [comment] 2024-05-28 11:18
Hey @srebhan,
I have tested, it worked nicely for me! Thank you so much for doing that quickly.
I have another request for sflow as well, but i will open separate issue for that

**Comment by srebhan** [comment] 2024-05-31 08:41
@akarneliuk please be aware that merging my required changes upstream (into the goflow2 library) might take some time, so do not expect this feature to land in v1.31.0 yet!

**Comment by srebhan** [comment] 2024-06-25 19:02
@akarneliuk rebase the PR against the latest master to include additional fields for extended-gateway etc...

**Comment by srebhan** [comment] 2024-07-18 14:22
@akarneliuk please test the binary in PR #15396 _again_ after CI finished the build. Upstream has merged the required PRs and I would like to make sure that everything still works as intended.

**Closed** 2024-07-19 15:30 UTC
Labels: feature request
