### ISSUE TITLE
Error writing to outputs.sql: ERROR: type “double” does not exist (SQLSTATE 42704)

### ISSUE THREAD

**Issue by waqaskhan137** [influxdata/telegraf#9562] opened 2021-07-30 14:03 UTC
Please redirect question about Telegraf usage to the InfluxData Community
site: https://community.influxdata.com/t/error-writing-to-outputs-sql-error-type-double-does-not-exist-sqlstate-42704/20979

### Relevant telegraf.conf:

```toml
# PUT TELEGRAF CONFIG HERE
[global_tags]

# Configuration for telegraf agent
[agent]
    interval = "60s"
    debug = true
    hostname = ""
    round_interval = true
    flush_interval = "10s"
    flush_jitter = "5s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    omit_hostname = false
###############################################################################
#                                  OUTPUTS                                    #
###############################################################################
[[outputs.sql]]
  driver = "pgx"
  data_source_name = "postgres://postgres:postgres@10.32.22.179:5438/postgres"
```

### System info:

Telegraf version 1.19.2
Operating System : CentOS 7 

### Docker

```
telegraf:
    container_name: nms-telegraf
    image: telegraf:latest
    ports:
      - "162:162/udp"
    volumes:
      - /usr/share/snmp/mibs/:/usr/share/snmp/mibs/
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - INFLUXDB_DB=monitoring
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=P@ssword1
      - POSTGRES_HOST=10.32.22.179:5438
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SSLMODE=disable
      - POSTGRES_DBNAME=postgres
      - INFLUXDB_URL=http://influxdb:8086
      - AGENT_URL=udp://docker-host:1061
    depends_on:
      - influxdb_cli
    restart: always
    logging:
      options:
        max-file: "10"
        max-size: "50m"
```
### Steps to reproduce:

1. Use the output.sql plugin 
2. Fetch some snmp.input which includes double 

### Expected behavior:

It should write the metrics normally

### Actual behavior:

it throws an error about double data type not being in Postgres. 

### Additional info:

it seems the data type isn't handled properly in the output plugin. Although there is a conversion method mentioned in the [readme of the plugin](https://github.com/influxdata/telegraf/tree/release-1.19/plugins/outputs/sql) but there isn't any clear instructions for using it to eliminate the mentioned issue. 

```
  ## Metric type to SQL type conversion
  #[outputs.sql.convert]
  #  integer              = "INT"
  #  real                 = "DOUBLE"
  #  text                 = "TEXT"
  #  timestamp            = "TIMESTAMP"
  #  defaultvalue         = "TEXT"
  #  unsigned             = "UNSIGNED"
```

**Comment by bvilnis** [comment] 2021-08-02 00:11
I came across this issue as well and had the same line of thought as you (using the type conversion).

I have my type conversion set as follows:
```
  [outputs.sql.convert]
    integer            = "BIGINT"
    real                 = "REAL"
    text                 = "TEXT"
    timestamp      = "TIMESTAMP"
    defaultvalue   = "TEXT"
    unsigned        = "BIGINT"
```

Which appears to have fixed the initial problem of:

`Error writing to outputs.sql: ERROR: type “double” does not exist (SQLSTATE 42704)`

but now produces:

`Error writing to outputs.sql: 358503060759561 is greater than maximum value for Int4`.

It would appear the type conversion is not mapping correctly as `BIGINT` should be converting the value to Int8, not Int4.

Any ideas @srebhan @reimda?

**Comment by thyseus** [comment] 2021-08-02 09:50
I would like to add my issue here instead of creating a new one. I get the message:

```
2021-08-02T09:44:50Z E! [agent] Error writing to outputs.sql: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''kernel'("timestamp" TIMESTAMP,"host" TEXT,"context_switches" INT,"boot_time"...' at line 1
```

when connecting the `[outputs.sql]` plugin to a mariadb 10.3.29-0+deb10u1 instance.

**Comment by srebhan** [comment] 2021-08-03 09:52
@waqaskhan137 please check the solution of @bvilnis 
```toml
  [outputs.sql.convert]
    integer = "BIGINT"
    real = "REAL"
    text = "TEXT"
    timestamp = "TIMESTAMP"
    defaultvalue = "TEXT"
    unsigned = "BIGINT"
```
and set `real = "REAL"`.

**Comment by srebhan** [comment] 2021-08-03 09:56
@bvilnis thanks for your solution. Not sure why `DOUBLE` is there in the first place, couldn't find it in the SQL docu... @reimda how about changing the type to "REAL" by default?

> but now produces:
> 
> `Error writing to outputs.sql: 358503060759561 is greater than maximum value for Int4`
> 
> It would appear the type conversion is not mapping correctly as `BIGINT` should be converting the value to Int8, not Int4.

Do you know which type the field has? Looking at the code, for `uint64` the SQL type is inferred as `${unsigned} ${integer}` which is unfortunate. We should change `unsigned = "UNSIGNED INT"` and do not do magic in the plugin to give the user full control. @reimda any thoughts?

@bvilnis if the failing field is of type `uint64` by change, can you try to set `unsigned = ""` as a workaround?

**Comment by waqaskhan137** [comment] 2021-08-03 10:51
@srebhan I have used that and I am getting following error. 

`2021-08-03T10:47:15Z E! [agent] Error writing to outputs.sql: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"linuxPerf"("timestamp" TIMESTAMP,"agent_host" TEXT,"host" TEXT,"linuxPerf-host"' at line 1`

**Comment by srebhan** [comment] 2021-08-03 12:46
@waqaskhan137 please check your `table_template`. It seems like it might be broken (e.g. missing closing bracket)...

**Comment by waqaskhan137** [comment] 2021-08-03 12:52
> @waqaskhan137 please check your `table_template`. It seems like it might be broken (e.g. missing closing bracket)...

I haven't used any template as shown in the telegraf configuration posted by me above.

**Comment by waqaskhan137** [comment] 2021-08-03 16:30
I have used the basic template provided in the [readme file of the plugin](https://github.com/influxdata/telegraf/tree/release-1.19/plugins/outputs/sql)

the configurations are given below. 
  ```
  table_exists_template = "SELECT 1 FROM {TABLE} LIMIT 1"
  table_template = "CREATE TABLE {TABLE}({COLUMNS})"
 ```
But I keep getting this error for some of the signals. 

2021-08-03T16:22:11Z E! [outputs.sql] Error during insert: ERROR: column "nChoiceUsedCaller-comments" of relation "nChoiceUsedCaller" does not exist (SQLSTATE 42703), INSERT INTO "nChoiceUsedCaller"("timestamp","agent_host","host","nChoiceUsedCaller-comments","nChoiceUsedCaller-modelScopeId","nChoiceUsedCaller-program","nChoiceUsedCaller-value","nChoiceUsedCaller-alerted","nChoiceUsedCaller-raised","nChoiceUsedCaller-generatedOn") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)

**Comment by jareware** [comment] 2021-11-05 13:23
@waqaskhan137 ran into the same issue. I think it's due to this plugin knowing how to create tables when needed, but not alter them as new columns would be needed.

Did you ever sort this out?

**Comment by rafalkrupinski** [comment] 2021-12-27 15:50
I suspect the problem is with the timestamp. in Influx it's nanosecond precision, while in PG it's only microsecond

**Comment by powersj** [comment] 2022-01-04 21:32
Hi,

The original issue was about `real` vs `double`. To level-set, my understanding is the value in the ConvertStruct is the datatype used by the destination database. 

`double` appears to be a [MySQL value](https://dev.mysql.com/doc/refman/8.0/en/numeric-types.html) that is a synonym for `double precision. MySQL also treats `double` as a synonym for `real`, unless `real_as_float` is enabled.

[PostgreSQL](https://www.postgresql.org/docs/current/datatype-numeric.html) uses `double precision. 

I do not think suggesting `real` makes sense as this could lead to confusion depending on the setting in MySQL and it would also reduce the amount of precision in PostgreSQL. This is clearly an area of confusion, so I put up a [PR](https://github.com/influxdata/telegraf/pull/10378) to specify that the user should check what data types their platform supports. This is to resolve the original issue reported here.

As far as the recent comments about creating additional fields in a database table, telegraf does not know how to do that. I have not looked into this at all, but if someone wants to look it would be helpful, but it should be tracked in a different issue, please.

Thanks!

**Comment by jareware** [comment] 2022-01-05 07:15
The [Timescale one](https://docs.timescale.com/timescaledb/latest/tutorials/telegraf-output-plugin/#configuring-the-postgresql-output-plugin) ([image here](https://github.com/FGRibreau/telegraf-timescaledb-docker)) does, at least.

**Closed** 2022-01-05 15:18 UTC
Labels: bug, area/sql
