### ISSUE TITLE
telegraf logparser fails silently on permissions issues

### ISSUE THREAD

**Issue by patrickqbis** [influxdata/telegraf#3296] opened 2017-10-02 21:05 UTC
I spent a bit of time chasing down why I couldn't get the log parser to parse web logs to discover that telegraf didn't have read permissions on the relevant files.

It didn't produce any message on this failure including with debugging on, so this would likely be a feature request to not have it fail silently on errors, especially if you have debug on.

[Include Telegraf version, operating system name, and other relevant details]

1.4.1-1, Ubuntu 16.04 

### Steps to reproduce:

1.  Create a config file with [[inputs.logparser]] present where telegraf doesn't have read permissions to the listed file(s) it should be parsing.

### Expected behavior:

Some sort of error produced, especially with debugging turned on.

### Actual behavior:
It continues to work as it should for other metrics.

## Feature Request

Do not fail silently on errors. Include errors on STDOUT and/or in the logs, especially when debug is present.

**Comment by danielnelson** [comment] 2017-10-02 23:51
This seems to happen when the directory containing the log cannot be read.  If an unreadable file is in a readable directory you get the error:
```
2017-10-02T23:47:46Z E! Error in plugin [inputs.logparser]: open test: permission denied
```

**Comment by patrickqbis** [comment] 2017-10-04 20:24
That's likely true as when I encountered the issue both the directory and file itself was unreadable, and I did not test enabling read on them separately.

**Comment by halfa** [comment] 2017-10-25 11:14
This one is particularly nasty, as [the doc](https://www.influxdata.com/blog/telegraf-correlate-log-metrics-data-performance-bottlenecks/) don't say anything about permissions...

**Comment by cjpit** [comment] 2017-11-29 03:35
I can't seem to get it to work at all for me, unless running the telegraf service as root.  using setfacl for the user telegraf, permissions are all there, for both directories, and file,  but yet still a silent fail and have no idea :/ Centos 7

**Comment by halfa** [comment] 2017-11-29 08:27
@cjpit that sound like a `selinux` issue

**Comment by russorat** [comment] 2018-07-16 21:12
- [ ] verify this isn't an issue with the `tail` plugin

**Comment by omarkohl** [comment] 2018-08-31 17:21
I can confirm this issue. It caused a few hours of wasted time. As stated above:

> This seems to happen when the directory containing the log cannot be read.

**Comment by rajalokan** [comment] 2018-11-19 08:46
I can verify this is still an issue on latest telegraf (1.8.3) and wasted couple of hours on this. 
> I can't seem to get it to work at all for me, unless running the telegraf service as root. using setfacl for the user telegraf, permissions are all there, for both directories, and file, but yet still a silent fail and have no idea :/ Centos 7
As stated above, I tried all permission stuffs as well as disabled SELINUX but no luck. Had to run telegraf service as root to get this working. 

More clarity on this on doc or clear log entry about failing permission will be a lot useful.

**Comment by sjwang90** [comment] 2020-10-20 17:54
> As stated above, I tried all permission stuffs as well as disabled SELINUX but no luck. Had to run telegraf service as root to get this working.
More clarity on this on doc or clear log entry about failing permission will be a lot useful.

Would anyone be willing to open a PR for this?

**Comment by SaromChars** [comment] 2021-05-21 11:01
mark. It is still a bug

**Comment by sjwang90** [comment] 2021-08-30 18:30
If this issue does not exist in inputs.tail as mentioned in https://github.com/influxdata/telegraf/issues/3296#issuecomment-405383669 we will just make a docs change in the readme as the logparser plugin is deprecated and no longer officially supported.

**Comment by sspaink** [comment] 2022-10-26 13:55
Closing because logparser is deprecated.

**Closed by sspaink** 2022-10-26 13:55 UTC
Labels: bug, docs, area/tail
