### ISSUE TITLE
Losing data when using two input plugins for the same measurement name?

### ISSUE THREAD

**Issue by pcman312** [influxdata/telegraf#4348] opened 2018-06-26 21:24 UTC
### Relevant telegraf.conf:
```
[[inputs.socket_listener]]
    service_address = "udp://:8094"
    data_format = "influx"
[[inputs.statsd]]
    protocol = "udp"
    service_address = ":8125"
    metric_separator = "." 
```

### System info:
OS: `Centos 7`
Telegraf version: `1.7.0`
InfluxDB version: `1.3.1` (also happens on `1.5.4` after an upgrade)

### Steps to reproduce:
1. Setup statsd input plugins with config referenced above (I suspect the specific details don't matter, just as long as there are two input plugins - though I don't have any evidence to support this)
2. Send a metric to one of the input plugins (it doesn't appear to matter which one goes first)
3. Send a different metric with the same measurement name to the other input plugin

### Expected behavior:
Both metrics are recorded

### Actual behavior:
Second metric is lost

### Additional info:
```
# Send to socket_listener plugin
$ echo "multi.test.udp value=241 1530054953000000000" | nc -u -w1 127.0.0.1 8094
$ influx -ssl -unsafeSsl -database tac_monitor -execute "SELECT value FROM \"multi.test.udp\" WHERE time > now() - 1h" 
name: multi.test.udp
time                value
----                -----
1530054953000000000 241 

# Send to statsd plugin
$ echo "multi.test.udp:200|c" | nc -u -w1 127.0.0.1 8125
$ influx -ssl -unsafeSsl -database tac_monitor -execute "SELECT value FROM \"multi.test.udp\" WHERE time > now() - 1h" 
name: multi.test.udp
time                value
----                -----
1530054953000000000 241 
```

The exact same behavior happens when I reverse the order.
If I drop the entire measurement and then try again, the behavior resets. For instance: If I send via the `socket_listener` then via `statsd` then the `statsd` metric is lost. If I then drop the measurement and reverse the order (`statsd` then `socket_listener`) the `statsd` metric is retained and the `socket_listener` is lost.
Restarting telegraf and/or influxdb did not seem to make any difference.

## Original Bug Report (incorrect assumptions, but leaving it here for posterity)
This appears to be unrelated to using periods as my original bug report claims. My first response comment describes an odd behavior if you try to write to the same measurement name with two input plugins.

### Relevant telegraf.conf:
```
[[inputs.statsd]]
    protocol = "udp"
    service_address = ":8125"
    metric_separator = "."
```

### System info:
OS: `Centos 7`
Telegraf version: `1.7.0`
InfluxDB version: `1.3.1`

### Steps to reproduce:
1. Setup statsd input plugin with config referenced above
2. Send metrics with `.` in them to statsd endpoint (such as `messages.received`)

### Expected behavior:
Either:
- Telegraf uses `.` as its separators
Or:
- Telegraf errors on startup because `.` isn't supported on the statsd plugin

### Actual behavior:
Telegraf starts up without issue
No data for that metric is received by influx

### Additional info:
Specifying these other separators work as expected: `-`, `--`, `_` (default), `\\.`
However, specifying `\.` causes telegraf to fail on startup

Clearly periods are in some way supported (as evidenced by the fact that I can use `\\.` and the metric shows up as `messages\.received`). However, plain periods somehow break the plugin in a subtle enough way that it doesn't error. The plugin should either explicitly disallow `.` as the separator (preferably with a descriptive error message), or allows plain periods through to the output plugins.

**Comment by pcman312** [comment] 2018-06-26 23:19
Update after further research:
It appears this doesn't have anything to do with periods but instead appears to do with existing metrics created via a different input plugin.

We have two input plugins configured (amongst some others):
```
[[inputs.socket_listener]]
    service_address = "udp://:8094"
    data_format = "influx"
[[inputs.statsd]]
    protocol = "udp"
    service_address = ":8125"
    metric_separator = "."
```

If we send a metric via one endpoint, then the same metric name (different value/timestamp) via the other endpoint, the second endpoint does not appear to send the metric off to influx.

```
# Send to socket_listener plugin
$ echo "multi.test.udp value=241 1530054953000000000" | nc -u -w1 127.0.0.1 8094
$ influx -ssl -unsafeSsl -database tac_monitor -execute "SELECT value FROM \"multi.test.udp\" WHERE time > now() - 1h"
name: multi.test.udp
time                value
----                -----
1530054953000000000 241

# Send to statsd plugin
$ echo "multi.test.udp:200|c" | nc -u -w1 127.0.0.1 8125
$ influx -ssl -unsafeSsl -database tac_monitor -execute "SELECT value FROM \"multi.test.udp\" WHERE time > now() - 1h"
name: multi.test.udp
time                value
----                -----
1530054953000000000 241
```
Note: we waited more than enough time for the second metric (via the statsd plugin) to show up and it never did.

The behavior is identical when you reverse the order (statsd then socket_listener)

**Comment by danielnelson** [comment] 2018-06-29 19:04
@pcman312 Are there any errors in the Telegraf logs?  I think this may be caused by a the type of metric being different, float vs integer, with the two inputs.

**Comment by pcman312** [comment] 2018-06-29 19:20
@danielnelson it looks like you're correct:
```
received error partial write: field type conflict: input field "value" on measurement "multi.test" is type float, already exists as type integer dropped=4; discarding points
```

**Comment by pcman312** [comment] 2018-06-29 19:28
@danielnelson my previous statement appears to be partially true. If I do statsd, then socket_listener I get that log message. If I do socket_listener then statsd I don't get any message about it. It could be the same underlying problem, just without a log.

**Comment by pcman312** [comment] 2018-07-27 15:59
@danielnelson have you had a chance to look into this any further?

**Comment by danielnelson** [comment] 2018-07-27 18:16
It seems like there are two issues:

In order to use the same measurement/field name, you will need both pieces of data to have the same type.  When you send data in over the socket_listener perhaps you can switch to sending integers (add a trailing `i` char after the value):
```
multi.test.udp value=241i 1530054953000000000
```

The second problem is more complicated.  Recall that for any series, InfluxDB stores one value for each field at a timestamp.  This means that if you send a value to both inputs for the same timestamp, one of the values, whichever is written secondly, will overwrite the first one.  It is undefined what the ordering of the metrics will be in this case.  I would have to understand more about your actual metrics to make an informed recommendation, but why not just send all the data to the statsd input?

I'm going to close this issue as I don't think there is anything that should be changed in Telegraf, but we can continue discussing here if you have more questions.

**Closed by danielnelson** 2018-07-27 18:16 UTC
Labels: area/statsd, bug

**Comment by pcman312** [comment] 2018-08-01 19:54
The scenario we have is that we are currently using the socket_listener plugin but are migrating our services over to using statsd. That unfortunately requires data to be sent to the same measurement from multiple services through the two different plugins while that migration is in progress.

There are two issues I'm seeing:
1) The two input plugins are interpreting the same data as different types. One is saying a float, the other an integer. The value is formatted the same (as seen in my initial report) yet there's inconsistent interpretation.
2) When used in a particular order (in this case statsd, then socket_listener) there is no error in the log. If you invert the order, there is an appropriate error message. That makes debugging this issue more difficult.

**Comment by danielnelson** [comment] 2018-08-01 20:37
1. The statsd input treats all counter types as integers, but the line protocol you are sending to the socket_listener the value set as a float.  Line protocol encodes an integer with a trailing `i` character, otherwise it is a float even if there is no decimal part.  You can change your line protocol to send an integer instead with `value=241i`.  There is no way currently to request the statsd input to produce a float for a counter, although it has been proposed #1978.

2. Yeah this seems confusing, however I am unable to reproduce this behavior.  In my testing I am switching the measurement name between each attempt to ensure that there is no existing data in InfluxDB about the type of the fields:
   ```
   2018-08-01T20:22:12Z E! [outputs.influxdb]: when writing to [http://localhost:8086]: received error partial write: field type conflict: input field "value" on measurement "d" is type integer, already exists as type float dropped=1; discarding points
   ```
   ```
   2018-08-01T20:23:20Z E! [outputs.influxdb]: when writing to [http://localhost:8086]: received error partial write: field type conflict: input field "value" on measurement "e" is type float, already exists as type integer dropped=1; discarding points
   ```
   One change I needed to do in order to test this is send the line protocol with a current timestamp.  I'm not sure if this was important originally but it is when testing now due to the passage of time.  This is need because InfluxDB does allow the type of a field to be different on different "shards".  Since the shard changes periodically to test this you must make sure that both the statsd and the line protocol message have approximately the same timestamp.
