### ISSUE TITLE
[Feature request]Support insecure_skip_verify in input.nginx

### ISSUE THREAD

**Issue by wei-hai** [influxdata/telegraf#2142] opened 2016-12-09 05:43 UTC
### Proposal:
Add `insecure_skip_verify = true|false` in input.nginx
### Current behavior:
It cannot skip verification.
### Desired behavior:
It shall be able to skip verification.
### Use case: 
We use intput.nginx to collect metric data from local server, however the certificate doesn't cover domain `localhost` so the connection fails. It would be better to provide option to skip the verification.

**Comment by phemmer** [comment] 2017-01-28 04:09
See also #2053

**Comment by sparrc** [comment] 2017-01-29 00:37
closing as dupe of #2053.

**Closed by sparrc** 2017-01-29 00:37 UTC
