### ISSUE TITLE
high load average every 1h 45m

### ISSUE THREAD

**Issue by akaDJon** [influxdata/telegraf#3465] opened 2017-11-13 07:00 UTC
every 1h 45m load average my server up to 3-4 (normal 0.2-0.5)
if stop telegraf service load average dont up every 1h 45m. 

Why is this happening?
Is it possible to adjust the time or period?

telegraf v1.4.3
influxdb v1.3.7

**Comment by danielnelson** [comment] 2017-11-13 19:45
Unless you have an input configured to run every 1h45m, there isn't any periodic tasks that would get ran by Telegraf.  Is InfluxDB on the same system?

**Comment by akaDJon** [comment] 2017-11-14 04:45
I have standart config for telegraf and dont have special inputs. InfluxDB on the same server. Maybe Telegraf send data to InfluxDB and InfluxDB up load average?
![image](https://user-images.githubusercontent.com/19344497/32763254-c988628e-c928-11e7-8dc1-2363c2c489a3.png)

**Comment by svartulv** [comment] 2017-11-14 09:28
Also having this on my Telegraf servers (version 1.4.3, InfluxDB version 1.3.6). I have no specific periodic tasks configured to run every 1.5 hours, and I'm using almost default configuration with one HTTP listener input and two InfluxDB outputs.

Is it something like garbage collection?

**Comment by danielnelson** [comment] 2017-11-15 19:27
Could you try using the procstat input to watch the Telegraf and the InfluxDB processes, this should allow us to see which process is causing the extra load.  I think it could also be useful to enable the internal plugin, which will report the memory usage by Telegraf, and you could use the influxdb input to monitor InfluxDB.

**Comment by akaDJon** [comment] 2017-11-16 05:39
> Error in plugin [inputs.influxdb]: [url=http://127.0.0.1:8086/debug/vars]: Get http://127.0.0.1:8086/debug/vars: dial tcp 127.0.0.1:8086: getsockopt: connection refused

But wget "http://127.0.0.1:8086/debug/vars" works normal and get json

**Comment by akaDJon** [comment] 2017-11-16 13:27
procstat info
![image](https://user-images.githubusercontent.com/19344497/32893526-0cc5e6ac-cb04-11e7-93a1-ce31dec982eb.png)
![image](https://user-images.githubusercontent.com/19344497/32893540-1bd201e4-cb04-11e7-9796-d04c6be0d73f.png)

**Comment by danielnelson** [comment] 2017-11-17 00:30
Hmm, nothing appears to line up.  Can you try to discover which process is causing the high load?

**Comment by akaDJon** [comment] 2017-11-17 03:01
I trying stop service telegraf and get data load average in script

> while true; do uptime >> uptime.log; sleep 10; done

and load average dont up. now try again

**Comment by akaDJon** [comment] 2017-11-17 07:23
I do "systemctl stop telegraf" and for 4 hours load average dont up even upper 0.9

[uptime.zip](https://github.com/influxdata/telegraf/files/1481361/uptime.zip)

**Comment by danielnelson** [comment] 2017-11-17 08:45
I suspect it may be caused by a process that Telegraf is starting, or possibly a subprocess of InfluxDB, because when we monitored the Telegraf process there was no corresponding spike in cpu usage.  Can you try to find the name of the process that is producing the cpu usage during one of the spikes?  It might be easiest to just run top during the time period with the increase.

**Comment by akaDJon** [comment] 2017-11-17 08:50
visually on htop program i see 3-4 influxdb and telegraf. I try do print screen htop in spike period

**Comment by akaDJon** [comment] 2017-11-17 09:45
![image](https://user-images.githubusercontent.com/19344497/32940886-2ee7b418-cbae-11e7-8a62-a488b64bb674.png)
![image](https://user-images.githubusercontent.com/19344497/32940890-32ed3754-cbae-11e7-833f-1c7a6136a8c6.png)
![image](https://user-images.githubusercontent.com/19344497/32940896-3634be28-cbae-11e7-94ee-d6c655e82d06.png)
![image](https://user-images.githubusercontent.com/19344497/32940903-39b2b956-cbae-11e7-9d83-a4c61086eb16.png)
![image](https://user-images.githubusercontent.com/19344497/32940919-43817e40-cbae-11e7-98bc-55de1d7a31d7.png)
![image](https://user-images.githubusercontent.com/19344497/32940925-49513c02-cbae-11e7-942e-6cade7f3fe7b.png)
![image](https://user-images.githubusercontent.com/19344497/32940939-4e75bd0c-cbae-11e7-8a3f-eb0964cdf417.png)
![image](https://user-images.githubusercontent.com/19344497/32940945-52aec922-cbae-11e7-9070-503d932845ad.png)

**Comment by danielnelson** [comment] 2017-11-17 10:17
It looks to me that the load is not caused by cpu, telegraf is still only taking 7% as a peek reading, but I do notice that the influxdb process is often in state `D`.  It might be interesting to take a look at the data collected by the processes input, which is enabled by default in telegraf.

**Comment by akaDJon** [comment] 2017-11-17 10:18
What I need do?

**Comment by danielnelson** [comment] 2017-11-17 10:22
If you have it, let's take a look at the graph of the the `processes` measurement with all fields.

**Comment by akaDJon** [comment] 2017-11-17 10:26
![image](https://user-images.githubusercontent.com/19344497/32942691-fdc08404-cbb3-11e7-924a-da4e0fe6fdc5.png)

that?

**Comment by danielnelson** [comment] 2017-11-17 10:30
Yeah, can you remove total and sleeping so we can see the blocked processes?

**Comment by akaDJon** [comment] 2017-11-17 10:32
![image](https://user-images.githubusercontent.com/19344497/32942999-e70d781a-cbb4-11e7-8ba6-f207cfd5b400.png)

**Comment by danielnelson** [comment] 2017-11-17 20:25
Can you try looking at these two [sample queries](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/DISK_README.md#sample-queries) with the diskio input.

**Comment by akaDJon** [comment] 2017-11-18 03:35
on 6-00 system do autobackup.

![image](https://user-images.githubusercontent.com/19344497/32976572-a59f2894-cc43-11e7-877a-b9576d9bce28.png)

**Comment by akaDJon** [comment] 2017-11-18 03:48
i have all default statistics and nothing not show problems exclude load average. if you contact this me on vk.com or facebook.com I may give you access to web grafana

**Comment by danielnelson** [comment] 2017-11-18 03:52
Who would have thought it could be so hard to track down the source of the high system load averages... It would be interesting to separate out the servers that Telegraf and InfluxDB are running on, is this something you would be able to try?

My best guess is it has something to do with the [InfluxDB cache writing](https://docs.influxdata.com/influxdb/v1.3/concepts/storage_engine/#cache).

**Comment by akaDJon** [comment] 2017-11-18 03:54
sorry, i have only one server. if you give connect to you influxdb I may send statistics to you

**Comment by akaDJon** [comment] 2017-11-18 04:01
my system Ubuntu 16.04.3 LTS [xenial] 4.4.0-98-generic on KVM VPS
all programs updated.

**Comment by danielnelson** [comment] 2017-11-18 04:22
I think this is probably just normal behavior of InfluxDB, either writing its cache or perhaps [compacting]( https://docs.influxdata.com/influxdb/v1.3/concepts/storage_engine/#compactions) the data files.  I would have liked to be able to find the exact cause of the load, but this turned out to be tricky, and I don't think it is something that we can solve in Telegraf anyway.

You could try disabling some of the inputs, and see if this will result in an adjusted period between load increases.

**Comment by akaDJon** [comment] 2017-11-18 04:27
the more statistics the telegraph collects then more the load average in peak moment. if I turn off the collection of statistics then the load will be lost. but this is not normal when you collect a minimum of statistics the server is highly loaded. and very strange pereodic 1h 45m

**Comment by akaDJon** [comment] 2017-11-18 04:40
need I open ticket in influxdb forum? may be their specialists help me? or this favorably for buy cloud influxdb service?

**Comment by danielnelson** [comment] 2017-11-20 22:06
Thanks for opening the issue on InfluxDB, I'm sure they will be able to help you in more detail.  If you have questions about InfluxCloud you can also contact sales@influxdata.com.

**Comment by Zbychad** [comment] 2017-11-24 14:55
Re-opening the issue. Multiple servers (physical and virtual) on Debian 9.1, telegraf 1.4.4-1 sending the data to separate machine with InfluxDB, load jumps every 1h45 min.
![image](https://user-images.githubusercontent.com/33961206/33215377-cd72576a-d12f-11e7-95a9-61b0565bae79.png)

**Comment by omacchioni** [comment] 2017-11-24 15:31
It looks oddly similar to https://github.com/influxdata/telegraf/issues/743 - same symptoms, same mention of 104 / 105 minutes - ping @sparrc

**Comment by danielnelson** [comment] 2017-11-27 20:47
Here are a few more debugging avenues, if someone can do these **one at a time** and see if either help:
- Set `quiet=true` in the agent config.
- Change the influxdb output to a file output.

**Comment by akaDJon** [comment] 2017-11-28 09:31
> Change the influxdb output to a file output.
How? Comment [[outputs.influxdb]]?

**Comment by danielnelson** [comment] 2017-11-28 18:02
Comment out the `[[outputs.influxdb]]` and add in:
```
[[outputs.file]]
  files = ["/dev/null"]
```

**Comment by akaDJon** [comment] 2017-11-29 07:13
![image](https://user-images.githubusercontent.com/19344497/33362556-2574468c-d507-11e7-8687-7823d9b6ebcf.png)

![image](https://user-images.githubusercontent.com/19344497/33362544-13e75dfa-d507-11e7-938f-ce969128f79a.png)

**Comment by Zbychad** [comment] 2017-11-29 09:31
> Set quiet=true in the agent config.

-> no change as well, exactly same behaviour as before:

![image](https://user-images.githubusercontent.com/33961206/33367906-5b45f63c-d4f0-11e7-9c44-1852abe5ec56.png)

**Comment by danielnelson** [comment] 2017-11-29 09:41
Just to double check, anything interesting in the logfiles at this time points? (with `quiet=false`)?

Also, what is the system specs for your machine?

**Comment by akaDJon** [comment] 2017-11-29 09:45
logfiles dosnt have any lines every 1h45. What "system specs for your machine"?

**Comment by danielnelson** [comment] 2017-11-29 09:54
I know a bit of this for you @akaDJon, but would be especially interested for others, maybe there is some commonality.  Here are a few things that would be helpful:
- Number of CPUs
- Amount of memory
- Platform (Distro/Arch)
- Bare Metal/Hypervisor/Container Runtime/Cloud Provider and which one.

**Comment by akaDJon** [comment] 2017-11-29 09:56
ok, sorry)

**Comment by Zbychad** [comment] 2017-11-29 10:09
> Also, what is the system specs for your machine?

Varies: 
- from 1 to 4 CPU
- 1 to 65 GB RAM
- Debian 9.2 x86-64
- bare metal + VMware 5.5

"1h45 effect" is visible on all of them.

**Comment by james-lawrence** [comment] 2017-12-08 02:14
just out of curiousity, has anyone checked GC stats?

**Comment by danielnelson** [comment] 2017-12-08 02:26
I don't think so, it seemed too long between occurrences to be GC related and there doesn't seem to be much change on the memory usage.

**Comment by danielnelson** [comment] 2017-12-08 02:39
Should be able to see the last gc time by starting Telegraf with `--pprof-addr :6060` and browsing to `http://localhost:6060/debug/pprof`.  Under heap you can see the `LastGC`

**Comment by james-lawrence** [comment] 2017-12-08 02:57
memory isn't always returned to the OS after a GC, as the assumption is the program will use it again. but the machines in the htop images don't have enough ram to account for a minute + duration of GC.

GC also doesn't trigger unless memory is consumed so it could be a slow build up. 

another thing i find interesting that leads me towards other sources of load. locks, timers, etc?

**Comment by akaDJon** [comment] 2018-01-08 08:43
this? 
![image](https://user-images.githubusercontent.com/19344497/34663692-3006b2e8-f482-11e7-9b97-290be6d021a3.png)

**Comment by akaDJon** [comment] 2018-01-08 08:44
or full log? 
[heap.txt](https://github.com/influxdata/telegraf/files/1610960/heap.txt)

**Comment by akaDJon** [comment] 2018-01-08 09:52
after hour
[heap2.txt](https://github.com/influxdata/telegraf/files/1611106/heap2.txt)

![image](https://user-images.githubusercontent.com/19344497/34665806-db3b74c4-f48b-11e7-9a02-3284c61b3c25.png)

**Comment by ekeih** [comment] 2018-01-18 23:04
After upgrading to 1.5.1 yesterday I have the same issue with virtual machines and the hardware machine itself. The interval is also 1h 45m but the starting time is a little different on every machine.
I will try to collect some more information from my machines as soon as possible.
I attached a screenshot. `hetzner02` is the hardware machine and `git` and `data` are two virtual machines running on `hetzner02`.

![github](https://user-images.githubusercontent.com/3430656/35126052-313be052-fcac-11e7-8fc5-c576bd2215bc.png)

**Comment by aldem** [comment] 2018-01-19 01:06
Same issue:

![image](https://user-images.githubusercontent.com/754722/35129420-d3ecd7d4-fcbb-11e7-92f2-338d7a639d0e.png)

This is idle physical system (16GB RAM, Intel i5-6400T, Ubuntu 16.04.3), running only telegraf (1.5.0).

Similar effect I observe on another system (a bit more powerful), which is serving as proxmox node (though with very small activity).

I have tried to find out what is going on during those peaks - but found nothing. No disk, cpu or any other activity, nothing that could cause such load (on second system it was above 4(!) - while normal is around 0.1-0.2).

Increasing collection interval from 10 to 60 seconds significantly reducing load, but it is still there (same interval).

With collectd running on same system (instead of telegraf) nothing like this happens.

**Comment by danielnelson** [comment] 2018-01-19 01:13
Would be useful to know if it matters what plugins are enabled, or if the load occurs with any plugin so long as there is enough traffic.  I think the best way to check would be to enable only a single plugin and see if the issue still occurs, if it does, enable another single plugin and retest.

**Comment by akaDJon** [comment] 2018-01-19 06:14
> Would be useful to know if it matters what plugins are enabled, or if the load occurs with any plugin so long as there is enough traffic. I think the best way to check would be to enable only a single plugin and see if the issue still occurs, if it does, enable another single plugin and retest.

I checked it already, Load average have reducing load, but same interval. If collect very little data, then load average almost invisible

**Comment by aldem** [comment] 2018-01-19 13:44
> Would be useful to know if it matters what plugins are enabled, or if the load occurs with any plugin so long as there is enough traffic.

Well, with single plugin enabled (system, obviously), the situation is even "worse":

![image](https://user-images.githubusercontent.com/754722/35151273-0487155a-fd1e-11e7-8262-c3fb20140d12.png)

Now I have _constant_ load of 1. I do not believe that querying for system load every 10 seconds could produce such load...

PS: After analyzing strace output, I am starting to suspect that all this behavior is not related to telegraf only - as it only uses futex/epoll/pselect/read/write call, and not so often. Most likely, this is related to how Linux computes load average based on process states, and several sleeping threads (depending on state and method) *may* cause such strange behavior (especially when user-space is involved - a case of futex).

**Comment by apooniajjn** [comment] 2018-02-06 20:15
I am seeing the same behavior on my host where telegraf agent is being installed and it's happening every 7 hours. CPU load increases and triggers an alert (which I am also using zabbix to monitor this host) .. Hosts where I have installed telegraf agents are showing the same behavior... should I open a new issue for 7 hour ?

**Comment by danielnelson** [comment] 2018-02-06 20:24
@apooniajjn When this issue occurs there does not seem to be a cpu increase, only load average. Please ask over at the [InfluxData Community](https://community.influxdata.com) site and I'll help you there.

**Comment by apooniajjn** [comment] 2018-02-06 20:37
@danielnelson  thanks .. yeah my bad I meant ```system load``` ... let me reach out to you there

**Comment by danielnelson** [comment] 2018-02-06 20:43
@apooniajjn If it matches this issue closely other than the period, then you can just use this issue.  At this time it is unknown what might be causing the problem.

**Comment by apooniajjn** [comment] 2018-02-06 22:25
@danielnelson  yeah it matches closely to this issue except the period ...

**Comment by ekeih** [comment] 2018-02-06 23:07
I just want to point out that 7hours = 4 * 1h45m 😉

**Comment by danielnelson** [comment] 2018-02-06 23:22
https://youtu.be/J9Y9GsPtbmQ

**Comment by 8h2a** [comment] 2018-02-22 02:00
I have the same issue but with collectd (and rrdcached as backend) (on Debian Stretch) instead of Telegraf:
![collectd](https://user-images.githubusercontent.com/1588661/36515956-28627ca8-177c-11e8-868a-2feaa9edb269.png)

**Comment by gentstr** [comment] 2018-02-23 17:33
Here's a good article talking about how this is calculated in the linux kernel and why it happens.
https://blog.avast.com/investigation-of-regular-high-load-on-unused-machines-every-7-hours

**Comment by Zbychad** [comment] 2018-02-26 11:31
Very useful article, thanks for sharing. Based on that, we've changed "collection_jitter" from 0 to 5s. Here's the result:
![image](https://user-images.githubusercontent.com/33961206/36668231-eb65f6ae-1af0-11e8-9512-d6c5811a9c48.png)

**Comment by danielnelson** [comment] 2018-03-05 18:11
@gentstr I think that pretty much explains it, thanks for the link.  Though I do wonder why in our case the interference occurs so frequently, and not every 14 hours since most users probably have a 10s interval.

I'm going to close this issue since there isn't an action to take on our part, anyone who wants to reduce this artifact can use `collection_jitter`.

**Closed by danielnelson** 2018-03-05 18:11 UTC
Labels: bug

**Comment by dynek** [comment] 2019-10-23 16:35
Was experimenting same behaviour and really liked the article explaining the artefact.
Ended up using collection and flush jitter and it went beyond what I was expecting. It is even lowering the CPU frequencies (using powersave governor):
![2019-10-23 at 18 32](https://user-images.githubusercontent.com/591091/67414658-cdb30480-f5c3-11e9-9b48-251a1e7b6e70.jpeg)

**Comment by alpiua** [comment] 2021-10-01 17:57
Hello from the 2021 ... Read the article, it is very nice explanation.
I faced this issue with about 20+ virtual machines. And all of them got cured with the collection_jitter option.
All except one. An nfs server with the 1 cpu and 1 gb ram
.

It  constantly getting high la every 7 hours.
Iny ideas where to look at?
```
[global_tags]

[agent]
   interval = "30s"
   round_interval = true
   metric_batch_size = 100 
   metric_buffer_limit = 1000
   collection_jitter = "15s"
   flush_interval = "20s"
   flush_jitter = "5s"
   precision = ""
   hostname = ""
   omit_hostname = false

 [[outputs.prometheus_client]]
   listen = ":9273"
   metric_version = 2 

 [[inputs.cpu]]
   percpu = true
   totalcpu = true
   collect_cpu_time = false
   report_active = false

 [[inputs.disk]]
   ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

 [[inputs.diskio]]
 [[inputs.kernel]]
 [[inputs.mem]]
 [[inputs.processes]]
 [[inputs.swap]]
 [[inputs.system]]

[[inputs.net]]
  interfaces = ["ens*"]
```
