### ISSUE TITLE
inputs.httpjson plugin tag_keys is not working correctly

### ISSUE THREAD

**Issue by gregserver** [influxdata/telegraf#3805] opened 2018-02-19 11:19 UTC
# ## Bug report
tag_keys setting doesn't seem to filter the tags and send the correct metrics.
If I tag_keys setting is commented out, flypool metrics is sent.

## Relevant telegraf.conf:
[[inputs.httpjson]]
  name = "Flypool"
  servers = ["https://api-zcash.flypool.org/miner/t1eQppEPbp7Cij3k8o7By2y6ejoSNByc33q/payouts"]
  response_timeout = "5s"
  method = "GET"
  tag_keys = ["paidOn"]

## System info:
Telegraf v1.5.2

## Steps to reproduce:
Requirements:

Have a telegraf configuration with the relevant configuration
Have an endpoint that returns a json :

{"status":"OK","data":[{"start":273769,"end":274817,"amount":2003375,"txHash":"b39f285f29f519104997aa036876e5f0e31937e72ac04b25b00500665e58f2c4","paidOn":1519031821},{"start":272123,"end":273768,"amount":2001058,"txHash":"8534fa210a587f026224e645b1d88466d4103b41af2fdc72b622046492c49be5","paidOn":1518874821},{"start":271470,"end":272122,"amount":1001015,"txHash":"7326a581be04d63d7564b6ec16f75aa0266d0b5987ba8f59eed4aca9bb6d124f","paidOn":1518627845},{"start":267660,"end":271468,"amount":5018316,"txHash":"ede5499fa428a456a816ce4026afe486490882016579eb003223411a2f1fad33","paidOn":1518526700},{"start":262974,"end":267659,"amount":5001703,"txHash":"c4fb4dc177c5b5991323cda1d57a9f8d9d8f969ca2d0a444b96b59c94edebbb9","paidOn":1517953011},{"start":258534,"end":262973,"amount":5004772,"txHash":"d2b48d7f0fea00a346775606469455557c0ad882f17593dc337888dfdaf95145","paidOn":1517247769},{"start":257667,"end":258532,"amount":1002161,"txHash":"bcdcca9170147e0527f52455abafc4da16da75fd46977637cde35cec74424d3a","paidOn":1516578143},{"start":256732,"end":257666,"amount":1000746,"txHash":"53e4897845197afd79a71f1c05af19fbf75afec5edf287ace4df0599ea4c13ea","paidOn":1516446332}]}

## Expected behavior:
Receive flypool with the values when tag_keys = ["paidOn"] is present, like this :
httpjson,server=http://....,paidOn=1519031821 start=273769,etc...,response_time=0.003 httpjson,server=http://....,paidOn=1518874821 start=272123,etc...,response_time=0.003

## Actual behavior:
flypool is not sent when tag_keys = ["paidOn"] is present.
flypool is sent when tag_keys setting is not present.

## Additional info:
...

**Comment by danielnelson** [comment] 2018-02-20 22:57
Only the top level values are available for use with `tag_keys`, when I use the JSON parser with this data I get this, regardless of what is set in `tag_keys`:
```
httpjson data_1_paidOn=1518874821,data_7_start=256732,data_1_amount=2001058,data_7_end=257666,data_3_paidOn=1518526700,data_0_end=274817,data_6_start=257667,data_7_paidOn=1516446332,data_6_paidOn=1516578143,data_0_paidOn=1519031821,data_3_amount=5018316,data_5_start=258534,data_4_end=267659,data_2_amount=1001015,data_4_start=262974,data_4_amount=5001703,data_2_start=271470,data_5_amount=5004772,data_2_end=272122,data_3_start=267660,data_1_start=272123,data_5_paidOn=1517247769,data_4_paidOn=1517953011,data_0_amount=2003375,data_0_start=273769,data_5_end=262973,data_3_end=271468,data_7_amount=1000746,data_6_amount=1002161,data_1_end=273768,data_6_end=258532,data_2_paidOn=1518627845 1519166862000000000
```

I would like to replace the current JSON parser with something a little more flexible, we have an issue open about this: https://github.com/influxdata/telegraf/issues/1363

**Comment by danielnelson** [comment] 2018-02-20 22:58
I'm going to close this issue since I believe the json data format is working as intended, we can discuss how to address this on #1363.

**Closed by danielnelson** 2018-02-20 22:58 UTC
