### ISSUE TITLE
Telegraf is consuming tons of memory

### ISSUE THREAD

**Issue by spawnazzo** [influxdata/telegraf#1185] opened 2016-05-11 14:02 UTC
I'm running telegraf on my servers, sending to that a lot of metrics from our python code, as a result it always allocate 500m up to 1gb of ram, is there any option to reduce the memory usage?

**Comment by sparrc** [comment] 2016-05-11 14:13
Please provide more information. OS, telegraf version, config file, etc

**Comment by spawnazzo** [comment] 2016-05-11 14:23
Telegraf - Version 0.12.1
running on cento 6.7 

config file attached 

[telegaf.txt](https://github.com/influxdata/telegraf/files/259502/telegaf.txt)

**Comment by sparrc** [comment] 2016-05-11 15:06
Have you tried adjusting allowed_pending_messages in your statsd input? 10,000,000 is exceptionally high, I wouldn't recommend setting that above 10,000 unless your UDP socket becomes very overloaded.

**Comment by spawnazzo** [comment] 2016-05-11 15:17
could this actually affect the number of metrics i can gather?

**Comment by sparrc** [comment] 2016-05-11 15:24
not sure what you mean exactly, but there will be log messages if metrics get dropped. If you are in a very high-traffic environment I'd also recommend upgrading to 0.13, which will be available later today.

**Comment by sparrc** [comment] 2016-05-18 10:59
closing because memory usage was caused by a configuration setup

**Closed by sparrc** 2016-05-18 10:59 UTC
Labels: Need More Info
