### ISSUE TITLE
Req: Ability to Not Have Local Hostname in Outputs

### ISSUE THREAD

**Issue by s1m0** [influxdata/telegraf#848] opened 2016-03-14 15:36 UTC
My primary use-case for telegraf is to collect stats off remote appliances (storage mostly) via exec or, in the future, snmp, so the local hostname is irrelevant and confusing. It can also clash with datapoints coming from plugins.

Currently there are 2 possibilities:-
1. Use the os.hostname() by setting hostname = "", or no hostname setting
2. Use the supplied hostname by setting hostname = "hostname.local.com"

So as not to break current .conf files, I propose using a new boolean in the [agent] section:-
usehostname = true <<-- generate the hostname tag from the hostname parameter
usehostname = false <<-- do not generate the hostname tag

**Comment by sparrc** [comment] 2016-03-14 15:48
I'm going to close this because it's basically a dupe of https://github.com/influxdata/telegraf/issues/706, if users could filter out _any_ tag, then they could filter the hostname tag out of all of their metrics.

**Comment by s1m0** [comment] 2016-03-14 20:28
..IF users could filter - which we don't and anyway, adding a tag then filtering it out is a waste of resources and makes configuration more complicated.

**Comment by sparrc** [comment] 2016-03-15 00:35
okay, fair enough, I'll keep this issue open

**Closed** 2016-03-21 21:51 UTC
