### ISSUE TITLE
Disk Usage for RBD devices.

### ISSUE THREAD

**Issue by box-daxter** [influxdata/telegraf#4985] opened 2018-11-13 11:22 UTC
## Feature Request
I'm using a lot of RBD devices in my hosts using CEPH. 
Telegraf read properly the iops and other stuff for the /dev/rbd devices, but not the usage.

I think this is a new feature not a bug.
### Proposal:
I want to be able to monitor my rbd devices by host.

### Current behavior:

```
# TYPE disk_used gauge
disk_used{device="192.168.111.249:6789:/",fstype="ceph",host="weworker05",mode="rw",path="/mnt/datavolumes"} 0
disk_used{device="192.168.111.249:6789:/devops_volumes",fstype="ceph",host="weworker05",mode="rw",path="/mnt/devops_volumes"} 0
disk_used{device="192.168.111.249:6789:/weconfig",fstype="ceph",host="weworker05",mode="rw",path="/etc/weconfig"} 0
disk_used{device="192.168.111.249:6789:/wp_dk_volumes",fstype="ceph",host="weworker05",mode="rw",path="/mnt/wp_volumes"} 0
disk_used{device="tmpfs",fstype="tmpfs",host="weworker05",mode="ro",path="/sys/firmware"} 0
disk_used{device="tmpfs",fstype="tmpfs",host="weworker05",mode="ro",path="/sys/fs/cgroup"} 0
disk_used{device="tmpfs",fstype="tmpfs",host="weworker05",mode="rw",path="/dev/shm"} 0
disk_used{device="tmpfs",fstype="tmpfs",host="weworker05",mode="rw",path="/run"} 1.20086528e+08
disk_used{device="tmpfs",fstype="tmpfs",host="weworker05",mode="rw",path="/run/lock"} 0
disk_used{device="tmpfs",fstype="tmpfs",host="weworker05",mode="rw",path="/run/user/0"} 0
disk_used{device="udev",fstype="devtmpfs",host="weworker05",mode="rw",path="/dev"} 0
disk_used{device="vda1",fstype="ext4",host="weworker05",mode="rw",path="/"} 7.049527296e+09
# HELP disk_used_percent Telegraf collected metric
# TYPE disk_used_percent gauge
disk_used_percent{device="192.168.111.249:6789:/",fstype="ceph",host="weworker05",mode="rw",path="/mnt/datavolumes"} 0
disk_used_percent{device="192.168.111.249:6789:/devops_volumes",fstype="ceph",host="weworker05",mode="rw",path="/mnt/devops_volumes"} 0
disk_used_percent{device="192.168.111.249:6789:/weconfig",fstype="ceph",host="weworker05",mode="rw",path="/etc/weconfig"} 0
disk_used_percent{device="192.168.111.249:6789:/wp_dk_volumes",fstype="ceph",host="weworker05",mode="rw",path="/mnt/wp_volumes"} 0
disk_used_percent{device="tmpfs",fstype="tmpfs",host="weworker05",mode="ro",path="/sys/firmware"} 0
disk_used_percent{device="tmpfs",fstype="tmpfs",host="weworker05",mode="ro",path="/sys/fs/cgroup"} 0
disk_used_percent{device="tmpfs",fstype="tmpfs",host="weworker05",mode="rw",path="/dev/shm"} 0
disk_used_percent{device="tmpfs",fstype="tmpfs",host="weworker05",mode="rw",path="/run"} 9.531798127972795
disk_used_percent{device="tmpfs",fstype="tmpfs",host="weworker05",mode="rw",path="/run/lock"} 0
disk_used_percent{device="tmpfs",fstype="tmpfs",host="weworker05",mode="rw",path="/run/user/0"} 0
disk_used_percent{device="udev",fstype="devtmpfs",host="weworker05",mode="rw",path="/dev"} 0
disk_used_percent{device="vda1",fstype="ext4",host="weworker05",mode="rw",path="/"} 35.40497824263703
# HELP diskio_io_time Telegraf collected metric
# TYPE diskio_io_time counter
diskio_io_time{host="weworker05",name="rbd0"} 224892
diskio_io_time{host="weworker05",name="rbd1"} 368324
diskio_io_time{host="weworker05",name="rbd10"} 18088
diskio_io_time{host="weworker05",name="rbd2"} 275312
diskio_io_time{host="weworker05",name="rbd3"} 164676
diskio_io_time{host="weworker05",name="rbd4"} 435072
diskio_io_time{host="weworker05",name="rbd5"} 397224
diskio_io_time{host="weworker05",name="rbd6"} 68336
diskio_io_time{host="weworker05",name="rbd7"} 2.162584e+06
diskio_io_time{host="weworker05",name="rbd8"} 295392
diskio_io_time{host="weworker05",name="rbd9"} 135860
diskio_io_time{host="weworker05",name="vda"} 2.6003364e+07
diskio_io_time{host="weworker05",name="vda1"} 2.6002548e+07
# HELP diskio_iops_in_progress Telegraf collected metric
# TYPE diskio_iops_in_progress counter

```

### Desired behavior:
Same output in disk_used and disck_used_percent than for regular mountpoints.

### Use case: [Why is this important (helps with prioritizing requests)]
We use a rbd driver for docker, we can't monitorice the rbd usage of the rbd in the whole system.

**Comment by danielnelson** [comment] 2018-11-13 19:54
I'm guessing the cause is that these devices are not mounted, can you run `cat /proc/self/mounts`?  Also, have you tried the ceph input and does it contain the data that you need?

**Comment by box-daxter** [comment] 2018-11-13 21:53
Hi, 

If I use the ceph input, I have the ceph-side of the system, but I need to know the usage of the ext4 filesystem on top of the rbd devices.

```
root@weworker05:~# cat /proc/self/mounts| grep rbd
/dev/rbd7 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod000000000000000000000047 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd7 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod000000000000000000000047 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd8 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40bfdbca2259380c34598 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd8 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40bfdbca2259380c34598 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd2 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40c01bca2259380c345ee ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd2 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40c01bca2259380c345ee ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd1 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d34bca2259380c34649 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd1 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d34bca2259380c34649 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd4 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d35bca2259380c34655 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd4 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d35bca2259380c34655 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd0 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod591c31958f05c809cc3f0cbe ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd0 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod591c31958f05c809cc3f0cbe ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd3 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d39bca2259380c346ac ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd3 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d39bca2259380c346ac ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd5 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d36bca2259380c34673 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd5 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d36bca2259380c34673 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd9 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod591c318b8f05c809cc3f0bf7 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd9 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod591c318b8f05c809cc3f0bf7 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd10 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d3abca2259380c346b7 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd10 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d3abca2259380c346b7 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd6 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod000000000000000000000012 ext4 rw,noatime,stripe=1024,data=ordered 0 0
/dev/rbd6 /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod000000000000000000000012 ext4 rw,noatime,stripe=1024,data=ordered 0 0
```

```
root@weworker05:~# df -h| grep rbd
/dev/rbd7                              40G  1.3G   37G   4% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod000000000000000000000047
/dev/rbd8                              40G  444M   37G   2% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40bfdbca2259380c34598
/dev/rbd2                              40G  1.6G   36G   5% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40c01bca2259380c345ee
/dev/rbd1                              40G  326M   37G   1% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d34bca2259380c34649
/dev/rbd4                              40G  902M   37G   3% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d35bca2259380c34655
/dev/rbd0                              40G  465M   37G   2% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod591c31958f05c809cc3f0cbe
/dev/rbd3                              40G  240M   37G   1% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d39bca2259380c346ac
/dev/rbd5                              40G  670M   37G   2% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d36bca2259380c34673
/dev/rbd9                              40G  580M   37G   2% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod591c318b8f05c809cc3f0bf7
/dev/rbd10                             40G  240M   37G   1% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod59a40d3abca2259380c346b7
/dev/rbd6                              57G   39G   16G  72% /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod000000000000000000000012
```

I don't understand why they are been excluded.

Thanks.

**Comment by danielnelson** [comment] 2018-11-13 22:56
Can the `telegraf` user stat the mount points?
```
sudo -u telegraf -- /var/lib/docker/plugins/0096874ee62f2725e8e9f18dc11104f6392026ca39d86b996b34343aed7c8b7b/propagated-mount/wepod000000000000000000000047
```

**Comment by danielnelson** [comment] 2018-11-14 19:43
On my system `/var/lib/docker/plugins/` is:
```
drwx------  4 root root  4096 Jul 24  2017 plugins
```

I'm not sure what the best way to allow this access, and I'm not sure what the implications are of giving access to this directory.  One idea you could consider is using a posix acl to give the telegraf user read access:
```
sudo setfacl -R -m user:telegraf:rX /var/lib/docker/
```

I'm going to close this issue since I don't think there are any code changes we will need to make, but I added some troubleshooting info to the disk plugin readme based on what we found.

**Closed by danielnelson** 2018-11-14 19:43 UTC
Labels: area/ceph, feature request
