### ISSUE TITLE
Prometheus is unable to scrape metrics once per second

### ISSUE THREAD

**Issue by shvez** [influxdata/telegraf#5073] opened 2018-11-30 11:50 UTC
### Relevant telegraf.conf:
https://www.dropbox.com/s/e0a1b83vjihbxlk/config.conf?dl=0
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Windows 10 Pro, Telegraf unknown (git: master 8d0ec993)
### Steps to reproduce:

1. start telegraf with provided config
2. start prometheus with 1s scrape interval

here is prometheus config:
```
# my global config
global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'cloud'
    static_configs:
    - targets: ['localhost:9273']
```

### Expected behavior:
The expected behavior is to be able to get metrics every 1 second. 
### Actual behavior:
Actual behavior is 'context deadline exceeded' in prometheus logs and web interface

### Additional info:
I've written POC which use promethues-net library and was able to scrape 10K metrics every second without any issue.

May be I just missed some config settings which may help to resolve this issue?

**Comment by danielnelson** [comment] 2018-11-30 18:58
This is running pretty fast on my laptop, well under a second, can you run this command and let me know how long it takes for you?
```
$ time curl localhost:9273/metrics > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25524  100 25524    0     0  24.3M      0 --:--:-- --:--:-- --:--:-- 24.3M

real    0m0.005s
user    0m0.003s
sys     0m0.001s
```

**Comment by timhallinflux** [comment] 2018-12-01 00:52
The real question here is why?  Is there an action you need to take on a 1s or less basis?  
Are you running a control system?
I'd love to understand more about the use case here. thanks.

**Comment by shvez** [comment] 2018-12-01 08:04
@danatinflux I'm somewhat puzzled by this situation.
On one side I have my POC which is able to provide 10 000 metrics within a 1-second interval. Everything just works. At the same time in the same environment, telegraf is not able to provide just a few

On another side, I see in Prometheus that if scrape_timeout is above 1050 ms then scraping happens within just 10 ms! but if it is less, then it starts to take scrape_timeout + few (3-4) milliseconds

So, I'm really puzzled.

@timhallinflux we are monitoring game servers. and we used to use windows perf counters. usually, we collect counters every five seconds, but during load-tests, we collect every second to get situation better. 
This is probably windows per counters specific case because they provide a lot of per second counters instead just 'counter's which constantly grow.
Now after explaining to you, I think, I see this situation better, but still, it may take some time to transit from the current way of thinking to new. We want to be sure.

**Comment by shvez** [comment] 2018-12-04 13:41
guys, any ideas?

**Comment by danatinflux** [comment] 2018-12-04 15:48
@danielnelson , I think I'm getting tagged instead of you?

-dd

**Comment by shvez** [comment] 2018-12-04 15:53
@danatinflux ah, I'm sorry, my bad

**Comment by danielnelson** [comment] 2018-12-11 02:19
I tried to reproduce this issue in Windows 7 and was unable to replicate the issue.  I was running both Telegraf 1.9.0 and Prometheus 2.5.0 on the same host, collecting and scraping at 1s interval.  Ran a taxing game a bit to see if it only fell behind when the system was under load but did not receive any errors in the prometheus log and data is updated every second.  I tried setting `scrape_interval` lower, and needed to have it around 10ms before I began seeing any errors, which were the same as you reported.

In have heard reports that win_perf_counters are a lighter system load, but it doesn't seem to be much of an issue with this configuration.  If the input was struggling to keep up you would receive an error from Telegraf, but it shouldn't interfere with the prometheus scraping.

Does the description above sound like the correct test to you?  If so, I'm really not sure why you are experiencing timeout errors.  Is the system you are running on resource constrained in some way?

**Comment by shvez** [comment] 2018-12-11 08:05
@danielnelson thank you for your efforts. The main difference is that I'm running on Windows 10 and Windows Server 2016. Other then that is same. The system is in an idle state. so it has enough power to scrape quickly, that it actually does if scrape_timeout is 1050ms or more.

do you have any ideas where it is useful to extend logging? I would run this version on my machine to get a hint

**Comment by danielnelson** [comment] 2018-12-11 22:24
The first thing to determine is if the timeout is caused by Telegraf being slow or if this is an issue with Prometheus.  Try running the system with the timeout at 500ms (timeout errors are expected to be occurring) and at the same time make a request to Telegraf using curl or a similar tool.  Make the request from the same server as Telegraf, and if you have Prometheus on another system then measure from there too, this will help isolate the network speed as a source of problems.  If the time it takes to make the request is low, then it must be an issue with Prometheus, but if it is >1s then it will indicate that Telegraf is not able to keep up.

**Comment by baryluk** [comment] 2020-10-16 12:17
I would like to use Prometheus for sub-second scraping too. I have a system where I would like to scrape about 10 times per second. The full latency to provide data from my HTTP endpoint is 1ms from same machine in text format, slightly less in protobuf format. I would like to connect it to prometheus on the same machine and gather this data. Yes, it is unusual for many systems, but I do have a complex embedded electrical system where it would really helpful to have very high resolution data like this, about 200 metric values total across about 60 different metrics. It is for diagnostic, troubleshooting, research and trend analysis mostly. (Prometheus will not be a low level control loops or anything like that). In terms of storage and storage speed, the system can handle it. Prometheus data would then be asynchronously scraped from a master Prometheus server (or two) from multiple such systems, for analysis of even more data. Also as a note, majority of these 200 metrics do change slowly and often are exactly the same for minutes, but few change very rapidly and frequently, so the storage layer would compress most of these slow changing metrics really very well.

There are two issues however.

The timestamp resolution. I am pretty sure the prometheus data format on disk and all the other processing isn't really expected to get below 1s in timestamps.  Maybe if there was some compilation flag to scale the internal timestamps, so they are still stored as integers, but mean something else now.

Even if set to 1Hz, prometheus still might have limitations not making it easy to do.

If Prometheus can't do it, I would need to reinvent a lot of things or use inferior (like text files or writing directly to some local sql database with async and journaling, then somehow sync things in batches to some other system for visualisation) methods to get something up and running.

**Comment by powersj** [comment] 2022-08-23 20:24
Hi,

Based on the previous comments and the lack of updates, I am going to close this issue for now. If there is still updates or outstanding questions, feel free to open a new issue. Thanks!

**Closed by powersj** 2022-08-23 20:24 UTC
Labels: platform/windows, performance, area/prometheus
