### ISSUE TITLE
inputs.exec fails silently if json values have wrong types

### ISSUE THREAD

**Issue by anlutro** [influxdata/telegraf#566] opened 2016-01-21 14:20 UTC
I had a script that was basically returning `{"something": true}`. This didn't write anything to InfluxDB, but didn't generate any errors in the InfluxDB or Telegraf logs.

Changing it to an integer instead of a boolean made it work.

**Comment by sparrc** [comment] 2016-01-21 15:39
closing as dupe of https://github.com/influxdata/telegraf/issues/521

This really is by design, the plugin is meant to be able to deal with a wide range of different JSON blobs and extract the numeric data out.

I suppose it could support booleans by converting to 0/1 though

**Closed by sparrc** 2016-01-21 15:39 UTC

**Comment by anlutro** [comment] 2016-01-21 16:35
Gotcha! I'll comment on the other issue.
