### ISSUE TITLE
[inputs.graylog] Error in plugin: has status code 400 (Bad Request)

### ISSUE THREAD

**Issue by junior466** [influxdata/telegraf#5081] opened 2018-12-04 02:09 UTC
### Relevant telegraf.conf:
[[inputs.graylog]]
  servers = [
    "http://192.168.2.11:9000/api/system/metrics/multiple",
  ]
  metrics = [
    "org.graylog2.journal.size",
    "org.graylog2.journal.size-limit",
    "org.graylog2.throughput.input.1-sec-rate",
    "org.graylog2.throughput.output.1-sec-rate"
  ]
  username = "token"
  password = "token"
  insecure_skip_verify = true
### System info:

[Include Telegraf version, operating system name, and other relevant details]
Telegraf 1.9.0
Ubuntu 16.04

### Steps to reproduce:

1. ...Upgrade Graylog to 2.5
2. ...Restart telegraf

### Expected behavior:
No errors. 
### Actual behavior:
[inputs.graylog]: Error in plugin: Response from url "http://192.168.2.11:9000/api/system/metrics/multiple" has status code 400 (Bad Request), expected 200 (OK)
### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by kpointer** [comment] 2018-12-04 13:08
https://github.com/Graylog2/graylog2-server/issues/5358

"All API requests now need to set the X-Requested-By HTTP header"

**Comment by glinton** [comment] 2018-12-05 19:53
closing as duplicate of https://github.com/influxdata/telegraf/issues/5010

**Closed by glinton** 2018-12-05 19:53 UTC
