### ISSUE TITLE
[Feature request] Ability to parse array in httpjson responce

### ISSUE THREAD

**Issue by freeseacher** [influxdata/telegraf#1882] opened 2016-10-11 13:34 UTC
i have a data designed in that way 
```
[
    {
        "lag": 0, 
        "late_tasks": 0, 
        "pool": "web01", 
        "running_tasks": 0, 
        "total_tasks": 0
    }, 
    {
        "lag": 0, 
        "late_tasks": 0, 
        "pool": "web02", 
        "running_tasks": 0, 
        "total_tasks": 0
    }, 
    {
        "lag": 0, 
        "late_tasks": 0, 
        "pool": "web03", 
        "running_tasks": 0, 
        "total_tasks": 0
    }
]
```
i want to do such scrape 
```
[[inputs.httpjson]]
  name = "monitor"

  servers = [
    "https:/balancer/monitor/"
  ]
  method = "GET"
  tags = ["pool"]

  [inputs.httpjson.headers]
    Authorization = "Basic XXXXX"
```
Currently such scrape will fail with `2016/10/11 16:15:50 unable to parse out as JSON, json: cannot unmarshal array into Go value of type map[string]interface {}
`
i am expecting such  data from it 
```
httpjson_monitor,env=prod,host=xx,server=https:/balancer/monitor/,pool=web01 lag=0,late_tasks=10,running_tasks=2,total_tasks=30 1476192573000000000
httpjson_monitor,env=prod,host=xx,server=https:/balancer/monitor/,pool=web02 lag=0,late_tasks=0,running_tasks=0,total_tasks=0 1476192573000000000
httpjson_monitor,env=prod,host=xx,server=https:/balancer/monitor/,pool=web03 lag=0,late_tasks=0,running_tasks=0,total_tasks=0 1476192573000000000
```

**Comment by freeseacher** [comment] 2016-10-11 13:39
or maybe there is a way how to redesign data to archive such functionality ?

**Comment by sparrc** [comment] 2016-10-11 13:41
closing as a dupe of https://github.com/influxdata/telegraf/issues/1363

**Closed by sparrc** 2016-10-11 13:41 UTC
