### ISSUE TITLE
[Ping Input Plugin] Strange behavior with method = "native"

### ISSUE THREAD

**Issue by zszia** [influxdata/telegraf#7892] opened 2020-07-24 11:08 UTC
### Actual behavior:

Config file
```
[[inputs.ping]]
  urls = [
    "10.153.4.7",
    "10.153.0.5"
  ]
  method = "native"
  #method = "exec"
  count = 2
  timeout = 1.5
```

systemd Config
```
[Service]
LimitNOFILE=8192
CapabilityBoundingSet=CAP_NET_RAW
AmbientCapabilities=CAP_NET_RAW
```

Additionally I did:
```
sudo setcap cap_net_raw=eip /opt/telegraf/usr/bin/telegraf
```

Ping is working:
```
ping -c 2 10.153.4.7
PING 10.153.4.7 (10.153.4.7) 56(84) bytes of data.
64 bytes from 10.153.4.7: icmp_seq=1 ttl=246 time=12.4 ms
64 bytes from 10.153.4.7: icmp_seq=2 ttl=246 time=11.8 ms

--- 10.153.4.7 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 11.869/12.155/12.442/0.306 ms
```

Exec method is working too:
method = "exec"
```
2020-07-24T11:05:23Z I! Starting Telegraf 1.15.1
> ping,host=xxxxx,url=10.153.4.7 average_response_ms=12.215,maximum_response_ms=12.683,minimum_response_ms=11.747,packets_received=2i,packets_transmitted=2i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0.468,ttl=246i 1595588724000000000
> ping,host=xxxxx,url=10.153.0.5 average_response_ms=177.759,maximum_response_ms=177.961,minimum_response_ms=177.558,packets_received=2i,packets_transmitted=2i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0.467,ttl=244i 1595588724000000000
```

native method is working only for one of the hosts. For 10.153.4.7 I get every time packets_received=0, percent_packet_loss=100 and result_code=1
method = "native"
```
2020-07-24T11:04:24Z I! Starting Telegraf 1.15.1
> ping,host=xxxxx,url=10.153.0.5 average_response_ms=177.825233,maximum_response_ms=178.026935,minimum_response_ms=177.623532,packets_received=2i,packets_transmitted=2i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0.201701,ttl=244i 1595588667000000000
> ping,host=xxxxx,url=10.153.4.7 packets_received=0i,packets_transmitted=2i,percent_packet_loss=100,result_code=1i 1595588669000000000
```
Unfortunately method exec is not an alternative, because with 315 urls I'm getting errors like this:
```
E! [inputs.ping] Error in plugin: host xxxxx: fork/exec /usr/bin/ping: resource temporarily unavailable
```
Thanks.

**Comment by ssoroka** [comment] 2020-07-24 16:07
Thanks. What OS (or OSes) are you seeing this problem on?

**Comment by zszia** [comment] 2020-07-24 16:12
```
lsb_release -a

LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP5
Release:        12.5
Codename:       n/a
```

**Comment by ssoroka** [comment] 2020-08-03 22:51
I think I'm able to reproduce the problem. if you run Telegraf with `--debug`, do you see any additional output related to ping?

**Comment by zszia** [comment] 2020-08-04 08:13
```
2020-08-04T08:07:51Z I! Starting Telegraf 1.15.1
2020-08-04T08:07:51Z D! [agent] Initializing plugins
2020-08-04T08:07:51Z D! [agent] Starting service inputs
> ping,host=zbm-sl-muc-0025,url=10.153.0.5 average_response_ms=178.075472,maximum_response_ms=178.088165,minimum_response_ms=178.062779,packets_received=2i,packets_transmitted=2i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0.012693,ttl=244i 1596528474000000000
2020-08-04T08:07:55Z D! [agent] Stopping service inputs
> ping,host=zbm-sl-muc-0025,url=10.153.4.7 packets_received=0i,packets_transmitted=2i,percent_packet_loss=100,result_code=1i 1596528475000000000
2020-08-04T08:07:55Z D! [agent] Input channel closed
2020-08-04T08:07:55Z D! [agent] Stopped Successfully
```

```--debug``` is not very helpfull here.
Is there some switch to get verbose messages from the ping input plugin?

**Comment by reimda** [comment] 2020-08-10 22:56
I ran your telegraf config on debian and suse and wasn't able to reproduce the problem you described.  Ping with native method on both platforms worked.  I didn't run telegraf through systemd, so I suspect there's something wrong with capabilities and the systemd service config.

**Comment by zszia** [comment] 2020-08-11 07:07
systemd is not involved.
I'm getting the same results running it with 
```
./telegraf -config telegraf_ping.conf --test
```

Important: I see this behavior only for some of the ip addresses. And I can reproduce it every time. So I suppose it has something to do with the ping destination. I'm only surprise, that the exec method works correctly for the same ping destination.

**Comment by zszia** [comment] 2020-08-11 11:25
The project is using https://github.com/glinton/ping
I installed it and tested with the ping command.

Ping with the "problem" destination
```
~/go/bin/ping 10.153.4.7
PING 10.153.4.7 (10.153.4.7) 56 bytes of data.
failed to ping: context deadline exceeded
failed to ping: context deadline exceeded
failed to ping: context deadline exceeded
failed to ping: context deadline exceeded
failed to ping: context deadline exceeded
failed to ping: context deadline exceeded
^Cfailed to ping: context deadline exceeded
Sent: 7 Received: 0
```
Standard Ping with the "problem" destination works
```
ping 10.153.4.7
PING 10.153.4.7 (10.153.4.7) 56(84) bytes of data.
64 bytes from 10.153.4.7: icmp_seq=1 ttl=246 time=12.5 ms
64 bytes from 10.153.4.7: icmp_seq=2 ttl=246 time=11.9 ms
64 bytes from 10.153.4.7: icmp_seq=3 ttl=246 time=11.9 ms
^C
--- 10.153.4.7 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 11.930/12.139/12.554/0.293 ms
```

GO Ping with another working destination
```
~/go/bin/ping 10.153.0.5
PING 10.153.0.5 (10.153.0.5) 56 bytes of data.
64 bytes from DNSNAME (<nil>): icmp_seq=1 ttl=244 time=178.4ms
64 bytes from DNSNAME (<nil>): icmp_seq=2 ttl=244 time=177ms
64 bytes from DNSNAME (<nil>): icmp_seq=3 ttl=244 time=176.9ms
64 bytes from DNSNAME (<nil>): icmp_seq=4 ttl=244 time=176.9ms
```

**Comment by reimda** [comment] 2020-08-11 18:38
Thanks for showing the ping output from the different programs.  Earlier I didn't understand that telegraf native ping was working on some destinations but not working on 10.153.4.7.

Could you make packet captures with standard ping and with glinton/ping and attach them to this issue?

sudo tcpdump -w standard_ping.pcap -nn icmp &
ping 10.153.4.7 #^C it after a few responses
fg
#hit ^C to stop tcpdump

Then repeat but write to glinton_ping.pcap and run ~/go/bin/ping.

Also could you send the output of traceroute 10.153.4.7?

Thanks!

**Comment by zszia** [comment] 2020-08-12 14:30
We have decided to exclude this one system from the monitoring. 
Of course, I would still like to provide further support by troubleshooting of this problem.  

I have collected the requested data, but for security reasons I cannot post it here in the public channel. 
If it will help you, then I could sent the data and some additional information about the target system on some private channel.

Thanks for your support!

**Comment by ssoroka** [comment] 2020-09-15 19:07
hey @zszia , can you mail it to ssoroka at influxdata dot com ?

**Comment by redrumdk** [comment] 2021-01-21 18:50
Did you ever manage to get it fixed ? 
i have all my pings failing in the same way when using native on windows 2019.

**Comment by schmorgs** [comment] 2021-01-25 14:01
Not sure if this is related to the issue reported, but with 1.17.0 of agent using "native" mode, I can't ping any hosts.
The debug log shows this message : 
```
2021-01-25T13:53:01Z D! [inputs.ping] error listening for ICMP packets: listen ip4:icmp : socket: operation not permitted: socket: permission denied
```
I'm not running as root user (nor would I want to) so any ideas what is needed?

I'm trying to get this working on a Raspberry Pi
```
Linux pi-2 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux
```
When running in "exec" mode, it works fine.

**Comment by sjwang90** [comment] 2021-01-27 23:00
Fixed in #8679

**Comment by sjwang90** [comment] 2021-01-28 17:24
@schmorgs @redrumdk  Could you download Telegraf 1.17.1 and see if the issue is fixed by #8679 or not?

**Comment by schmorgs** [comment] 2021-01-28 19:56
Just tried version 1.17.1 and Telegraf now crashes when executing the ping module, regardless of whether "native" or "exec" is used.
```
2021-01-28T19:46:32Z I! Starting Telegraf 1.17.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130c860]

goroutine 48 [running]:
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0x4b6c870, 0x4c8c4c1, 0xd, 0x27a4828, 0x4c48640)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x11c
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0x4b6c870, 0x27a4828, 0x4c48640, 0x4c8c4c1, 0xd)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0xc0
created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0x90
```

Restored the 1.17.0 binary with same config and agent stays up, it but just doesn't collect data for native setting.

Telegraf version : 
```
wget https://dl.influxdata.com/telegraf/releases/telegraf_1.17.1-1_armhf.deb

./telegraf --version
Telegraf 1.17.1 (git: HEAD 8907e61a)

file telegraf
telegraf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=HT53ykxOV12tAyohBJBW/ztAGAEFVoraM-L985vmu/5KlnOiqm2ZqHU5ALsL4r/6-rG6jxVzPKAZn0SWFTW, stripped
```

**Comment by redrumdk** [comment] 2021-01-28 22:05
> @schmorgs @redrumdk Could you download Telegraf 1.17.1 and see if the issue is fixed by #8679 or not?

Tried, also tried 1.18 nightly, still not working for me :(

**Comment by sjwang90** [comment] 2021-01-29 02:59
Please try with 1.17.2 that was just released that implemented the patches in the [change log](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md#v1172-2021-01-28)

**Comment by schmorgs** [comment] 2021-01-29 07:04
Just tested with 1.17.2 and this works.  

Not sure if this is expected behaviour but the native mode only gives a single metric (result_code) instead of the rich set offered by exec.

exec mode
```
Starting Telegraf 1.17.2
ping,host=pi-2,site=mytest,url=192.168.1.200 packets_transmitted=1i,percent_packet_loss=0,standard_deviation_ms=0,result_code=0i,packets_received=1i,ttl=64i,minimum_response_ms=0.97,average_response_ms=0.97,maximum_response_ms=0.97 1611903600000000000
```

native mode
```
Starting Telegraf 1.17.2
ping,host=pi-2,site=mytest,url=192.168.1.200 result_code=2i 1611903630000000000
```

**Comment by schmorgs** [comment] 2021-01-29 07:35
Actually, just tested a bit more.

The result_code shows 2i whether the site is pingable or not, so as it stands, the native method is not usable.
```
#2021-01-29T07:34:40Z I! Starting Telegraf 1.17.2
ping,host=pi-2,site=fake-ip,url=192.168.1.249 result_code=2i 1611905700000000000
ping,host=pi-2,site=good-ip,url=192.168.1.200 result_code=2i 1611905700000000000
```

**Comment by redrumdk** [comment] 2021-01-29 09:56
> Please try with 1.17.2 that was just released that implemented the patches in the [change log](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md#v1172-2021-01-28)

Tried 1.17.2 and new nightly.
Same issue, i ping a down IP and it shows various values in the percent_packets_loss column, and no errors in the debug log

**Comment by sspaink** [comment] 2021-01-29 15:54
@schmorgs using 1.17.2 and "native" I get the same metrics as using "exec", I also see the appropriate result codes. Result code 2 does mean "ping error" maybe the correct permissions weren't set yet? The [readme](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ping/README.md) has a section talking about it, if that doesn't help you we are using go-ping  under the hood and their [readme](https://github.com/go-ping/ping#linux) also has a section about permissions that might help. 

Here is some output I am getting using native if that helps:
```
ping,host=sspaink-influxdata,url=127.0.0.1 minimum_response_ms=0.268369,average_response_ms=0.268369,standard_deviation_ms=0,ttl=64i,percent_packet_loss=0,maximum_response_ms=0.268369,result_code=0i,packets_transmitted=1i,packets_received=1i 1611935070000000000
ping,host=sspaink-influxdata,url=192.128.1.123 percent_packet_loss=100,result_code=1i,packets_transmitted=1i,packets_received=0i 1611935071000000000
```
My basic config (the 192 IP's are purposely invalid):

```
[[inputs.ping]]
  method="native"
  urls = ["127.0.0.1", "192.128.1.123", "192.128.1.124", "influxdata.com", "google.com"]

[[outputs.file]]
  files = ["stdout"]
```

**Comment by sspaink** [comment] 2021-01-29 15:55
@redrumdk regarding the strange values in percent_packet_loss I would recommend trying the Telegraf build from this pull request that might resolve your issue: https://github.com/influxdata/telegraf/pull/8771 we believe it is an underlying issue with the library we are using.

**Comment by schmorgs** [comment] 2021-01-29 17:16
@sspaink Thanks, I didn't realise there was another step for native which was to enable the group that the user Telegraf runs in to listen for ICMP packets.  I added this and it worked, although it does require root access to set so would have to be rolled out to hosts in addition to agents.

Anyway, can confirm it works now.

**Comment by sspaink** [comment] 2021-02-05 18:52
I believe this issue has been resolved with the recent pr's related to `inputs.ping`.

@redrumdk I opened a new issue to handle the problems you reported: #8819

**Closed by sspaink** 2021-02-05 18:52 UTC
Labels: area/ping, bug
