### ISSUE TITLE
Windows Event Log plugin

### ISSUE THREAD

**Issue by natejgardner** [influxdata/telegraf#4957] opened 2018-11-05 03:12 UTC
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Windows Event Logs can be accessed with the `Get-WinEvent` command in Powershell. With very similar structure to the Windows performance counters input plugin, Windows Events could also be captured. This would be huge for logging crashes and hardware failures on Windows-based systems.

### Current behavior:
There's not a plugin to access Windows Event Logs.

### Desired behavior:
Windows Events can be captured by Telegraf.

### Use case: [Why is this important (helps with prioritizing requests)]
* Windows Events are the primary way logging works in Windows. Most Windows applications write their logs here.

**Comment by danielnelson** [comment] 2018-11-07 00:09
This looks like a duplicate of #4525

**Closed by danielnelson** 2018-11-07 00:09 UTC
Labels: feature request, platform/windows
