### ISSUE TITLE
Telegraf should be able to write rollup data

### ISSUE THREAD

**Issue by pauldix** [influxdata/telegraf#1419] opened 2016-06-24 22:32 UTC
Telegraf should have an ability to write rollup data. For example, it samples every 10s, but you want to write 5m and 1h rollups. The syntax in the config file should look like influxdata/influxdb#6910.

It should just keep everything in memory and not worry about persisting on restarts.

**Comment by sparrc** [comment] 2016-06-25 21:47
This is a dupe of https://github.com/influxdata/telegraf/issues/380

**Closed by sparrc** 2016-06-25 21:47 UTC
