### ISSUE TITLE
Telegraf output plugin for postgresql 

### ISSUE THREAD

**Issue by gssprakash** [influxdata/telegraf#12277] opened 2022-11-24 06:03 UTC
### Relevant telegraf.conf

```toml
[[outputs.postgresql]]
  ## Specify connection address via the standard libpq connection string:
     host=localhost port=5432 user=postgres password=xxxxx sslmode=disable dbname=xxxxx
```

### Logs from Telegraf

```text
2022-11-24T05:09:46Z E! [telegraf] Error running agent: Error loading config file csvtelegraf.conf: Error parsing data: line 386: invalid TOML syntax
```

### System info

telegraf 1.24.2  on windows 11 

### Steps to reproduce

1. Just add the output plugin postgresql  with [outputs.postgresql]
2. enter the line host=localhost port=5432 user=postgres password=xxxxx sslmode=disable dbname=anydb
3. telegraf throws TOML error 
...

### Expected behavior

No  TOML error as the libpq  syntax is valid  and it is working  fine when  tried to connect  directly using psql . It seems  telegraf is unable to find the right parser for the output plugin of postgresql 

### Actual behavior

telegraf  throwing  TOML error  as invalid TOML syntax

**Comment by srebhan** [comment] 2022-11-24 08:27
I'm pretty sure your line `host=localhost port=5432 user=postgres password=xxxxx sslmode=disable dbname=xxxxx` is the value for the `connection` option. Have you tried
```toml
[[outputs.postgresql]]
  ## Specify connection address via the standard libpq connection string:
  connection="host=localhost port=5432 user=postgres password=xxxxx sslmode=disable dbname=xxxxx"
```

Anyway, as the error message suggests, the config part you sent is _not_ vaild TOML!

**Comment by gssprakash** [comment] 2022-11-24 09:25
Excellent .It worked .Thanks for your quick reply srebhan ..  Please add this an example here https://github.com/influxdata/telegraf/blob/release-1.24/plugins/outputs/postgresql/README.md

Also Iam looking for a way to use tags  with Postgresql output plugin .. using database_tag = "tag3"  for influxdb . How can I do this with postgres. 

This tags are needed to push data into different databases .

**Comment by srebhan** [comment] 2022-11-25 10:08
Please use the [community forums](https://community.influxdata.com/c/ts-collect/6) or our [Slack channel](https://www.influxdata.com/slack) for these kind of questions!

Closing this issue as this is not a bug. :-)

**Closed by srebhan** 2022-11-25 10:08 UTC
Labels: bug
