### ISSUE TITLE
unexpected fault address 0x13d739f0

### ISSUE THREAD

**Issue by yesman85** [influxdata/telegraf#2892] opened 2017-06-06 13:45 UTC
When I run telegraf on Windows 2016 version 1.3.1, I receive the following error:
[error.txt](https://github.com/influxdata/telegraf/files/1055195/error.txt)

This my config:

```
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  hostname = "Prod-1"

[[outputs.influxdb]]
  urls = ["http://1.2.3.4:8086"] 
  database = "telegraf"
  precision = "s"
  timeout = "5s"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Processor Time"]
    Measurement = "win_cpu"
```

**Comment by danielnelson** [comment] 2017-06-06 20:31
I think this is a duplicate of #2468

**Closed by danielnelson** 2017-06-06 20:31 UTC

**Comment by ronnix** [comment] 2017-09-04 14:13
FYI, the default configuration enables `win_perf_counter` plugins, which works fine on 64-bit Windows, but causes a crash on 32-bit Windows (see #2468).

A workaround is to comment all the `[[inputs.win_perf_counters.*]]` sections, and to uncomment the following sections:
```
[[inputs.cpu]]
[[inputs.disk]]
[[inputs.diskio]]
[[inputs.mem]]
[[inputs.swap]]
```

Maybe changing the default config shipped with the 32-bit build would prevent this bad out-of-the-box experience?
