### ISSUE TITLE
Stackdriver output sometimes writes TimeSeries out of order

### ISSUE THREAD

**Issue by Legogris** [influxdata/telegraf#5963] opened 2019-06-06 15:17 UTC
Even with the recentish changes to the Stackdriver output, we are still seeing regular out-of-order errors:

```
Jun 04 20:22:40  telegraf[23336]: 2019-06-04T20:22:40Z E! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[140] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[140]; Field timeSeries[77] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[77]
Jun 04 20:22:40  telegraf[23336]: 2019-06-04T20:22:40Z E! [agent] Error writing to output [stackdriver]: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[140] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[140]; Field timeSeries[77] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[77]
Jun 05 01:22:40  telegraf[23336]: 2019-06-05T01:22:40Z E! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = Unavailable desc = transport is closing
Jun 05 01:22:40  telegraf[23336]: 2019-06-05T01:22:40Z E! [agent] Error writing to output [stackdriver]: rpc error: code = Unavailable desc = transport is closing
Jun 05 02:22:40  telegraf[23336]: 2019-06-05T02:22:40Z E! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = Unavailable desc = transport is closing
Jun 05 02:22:40  telegraf[23336]: 2019-06-05T02:22:40Z E! [agent] Error writing to output [stackdriver]: rpc error: code = Unavailable desc = transport is closing
Jun 05 04:22:40  telegraf[23336]: 2019-06-05T04:22:40Z E! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = Unavailable desc = transport is closing
Jun 05 04:22:40  telegraf[23336]: 2019-06-05T04:22:40Z E! [agent] Error writing to output [stackdriver]: rpc error: code = Unavailable desc = transport is closing
Jun 05 05:22:40  telegraf[23336]: 2019-06-05T05:22:40Z E! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = Unavailable desc = transport is closing
Jun 05 05:22:40  telegraf[23336]: 2019-06-05T05:22:40Z E! [agent] Error writing to output [stackdriver]: rpc error: code = Unavailable desc = transport is closing
```
Interestingly enough these errors often seem to occur with exactly 1h intervals. Config as below.
```
```

When this happens, metrics end up being >5 min late, resulting in triggered alarms and other shenanigans.

### Relevant telegraf.conf:
```toml
    interval = "1m"
    round_interval = true
    flush_interval = "40s"
```

### System info:
`Telegraf 1.10.1 (git: HEAD a6778f46)`
`Linux #36-Ubuntu SMP Tue Mar 5 23:17:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by StephenWithPH** [comment] 2019-08-02 20:49
> Interestingly enough these errors often seem to occur with exactly 1h intervals.

We see similar behavior, but ours is far less regularly-timed than hourly.

* version: `Telegraf 1.11.3` (official Docker image)
* /etc/telegraf/telegraf.conf:
```toml
[global_tags]
  cluster = "<redacted>"
[agent]
  collection_jitter   = "0s"
  debug               = true
  flush_interval      = "1m"
  flush_jitter        = "10s"
  interval            = "1m"
  logfile             = ""
  metric_batch_size   = 1000
  metric_buffer_limit = 10000
  omit_hostname       = false
  precision           = "1s"
  quiet               = false
  round_interval      = true
[[inputs.statsd]]
  allowed_pending_messages = 10000
  datadog_extensions       = false
  delete_counters          = true
  delete_gauges            = true
  delete_sets              = true
  delete_timings           = true
  metric_separator         = "_"
  percentiles              = []
  protocol                 = "udp"
  service_address          = ":8125"
[[outputs.stackdriver]]
  namespace     = "telegraf"
  project       = "<redacted>"
  resource_type = "global"
  [outputs.stackdriver.resource_labels]
    project_id = "<redacted>"

```

* log lines:
```
2019-08-02T20:15:08Z E! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[23] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[23]; Field timeSeries[51] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[51]
2019-08-02T20:15:08Z D! [outputs.stackdriver] buffer fullness: 17 / 10000 metrics. 
2019-08-02T20:15:08Z E! [agent] Error writing to output [stackdriver]: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[23] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[23]; Field timeSeries[51] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[51]
2019-08-02T20:16:04Z E! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[12] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[12]; Field timeSeries[15] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[15]; Field timeSeries[26] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[26]; Field timeSeries[29] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[29]; Field timeSeries[31] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[31]; Field timeSeries[38] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[38]; Field timeSeries[42] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[42]; Field timeSeries[53] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[53]; Field timeSeries[55] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[55]; Field timeSeries[60] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[60]; Field timeSeries[64] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[64]; Field timeSeries[66] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[66]; Field timeSeries[67] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[67]
2019-08-02T20:16:04Z D! [outputs.stackdriver] buffer fullness: 30 / 10000 metrics. 
2019-08-02T20:16:04Z E! [agent] Error writing to output [stackdriver]: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[12] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[12]; Field timeSeries[15] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[15]; Field timeSeries[26] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[26]; Field timeSeries[29] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[29]; Field timeSeries[31] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[31]; Field timeSeries[38] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[38]; Field timeSeries[42] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[42]; Field timeSeries[53] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[53]; Field timeSeries[55] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[55]; Field timeSeries[60] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[60]; Field timeSeries[64] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[64]; Field timeSeries[66] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[66]; Field timeSeries[67] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[67]
2019-08-02T20:17:00Z D! [outputs.stackdriver] unable to write to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[16] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[16]; Field timeSeries[19] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[19]; Field timeSeries[20] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[20]; Field timeSeries[27] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[27]; Field timeSeries[30] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[30]; Field timeSeries[31] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[31]; Field timeSeries[42] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[42]; Field timeSeries[43] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[43]; Field timeSeries[44] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[44]; Field timeSeries[50] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[50]; Field timeSeries[51] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[51]; Field timeSeries[52] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[52]; Field timeSeries[54] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[54]; Field timeSeries[56] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[56]; Field timeSeries[58] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[58]; Field timeSeries[59] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[59]; Field timeSeries[61] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[61]; Field timeSeries[63] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[63]; Field timeSeries[64] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[64]; Field timeSeries[66] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[66]; Field timeSeries[67] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[67]; Field timeSeries[68] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[68]; Field timeSeries[71] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[71]; Field timeSeries[75] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[75]; Field timeSeries[77] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[77]; Field timeSeries[80] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[80]; Field timeSeries[81] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[81]; Field timeSeries[83] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[83]; Points must be written in order. One or more of the points specified had an older end time than the most recent point.: timeSeries[2,7,17,28,40,76]
2019-08-02T20:17:00Z D! [outputs.stackdriver] wrote batch of 43 metrics in 91.8126ms
2019-08-02T20:17:00Z D! [outputs.stackdriver] buffer fullness: 0 / 10000 metrics. 

```



Anecdotally, it seems to happen in waves. Eventually, things stabilize. We then run for a time with no problems. And then the wave begins again.

Of note, the problems seem to always end once we see the log line `One or more of the points specified had an older end time than the most recent point`. This is a **far** less-frequent message in our case than `Only one point can be written per TimeSeries per request`.

**Comment by Legogris** [comment] 2019-10-01 08:44
@StephenWithPH Are you also aggregating metrics from separate instances? I just returned to this and realized this seems to happen coinciding in time with NTP updates. I don't get exactly how though - telegraf should still sort them before sending, which should be independent of time on the agent instance.

**Comment by Legogris** [comment] 2019-10-01 09:23
From https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#Point on `interval`:

> The time interval to which the data point applies. For GAUGE metrics, the start time is optional, but if it is supplied, it must equal the end time. For DELTA metrics, the start and end time should specify a non-zero interval, with subsequent points specifying contiguous and non-overlapping intervals. For CUMULATIVE metrics, the start and end time should specify a non-zero interval, with subsequent points specifying the same start time and increasing end times, until an event resets the cumulative value to zero and sets a new start time for the following points. 

With just this to go by, the initial implementation seems like it should be correct, but maybe there's some newly introduced undefined behavior with very early `startTime`... It also doesn't make sense that cumulative values get constantly increasing (climbing staircase) when constantly supplying newer `startTime` for each point as per this PR.

**Comment by StephenWithPH** [comment] 2019-10-01 16:26
> Are you also aggregating metrics from separate instances?

@Legogris No... we are not aggregating metrics on this host. There's a single source of metrics emitting to the statsd port where Telegraf listens.

**Comment by arturgspb** [comment] 2020-07-31 22:39
@Legogris , you can fix it in summary?

**Comment by reimda** [comment] 2022-09-01 20:16
This issue hasn't been updated in a while. Since the last discussion here #7814 was merged. It tries to make sure metrics are written first in first out. I think it may have fixed this issue.

Since this is 2+ years old and has a related fix I'm going to close it. If anyone can still reproduce it with a recent telegraf build, feel free to reopen. Thanks!

**Closed by reimda** 2022-09-01 20:16 UTC
Labels: cloud
