### ISSUE TITLE
Docker input panics with "slice bounds out of range"

### ISSUE THREAD

**Issue by aleho** [influxdata/telegraf#9029] opened 2021-03-21 11:19 UTC
Using `inputs.docker` fails with the following panic:

```
panic: runtime error: slice bounds out of range [:4] with capacity 0
goroutine 86 [running]:
github.com/influxdata/telegraf/plugins/inputs/docker.parseContainerStats(0xc000f0f200, 0x42dc618, 0xc00007c3a0, 0xc000d06000, 0xc0005663c0, 0x40, 0xc0000b47c0, 0x3, 0x4, 0xc0
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:742 +0x256a
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainerInspect(0xc0005898c0, 0xc0005663c0, 0x40, 0xc00027a680, 0x1, 0x4, 0xc00055c060, 0x26, 0xc00067e0
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:630 +0x29c
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainer(0xc0005898c0, 0xc0005663c0, 0x40, 0xc00027a680, 0x1, 0x4, 0xc00055c060, 0x26, 0xc00067e000, 0x4
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:557 +0x919
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather.func1(0xc000476d90, 0xc0005898c0, 0x42dc618, 0xc00007c3a0, 0xc0005663c0, 0x40, 0xc00027a680, 0x1, 0x4, 0
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:281 +0xbd
created by github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:279 +0x3f8
```

### Relevant telegraf.conf:
```toml
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"

  container_names = [
    "some",
    "containers"
  ]

  gather_services = false
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  timeout = "5s"
  perdevice = true
  total = false
  docker_label_include = []
  docker_label_exclude = []
```

### System info:

Debian Buster
Telegraf 1.18.0
Docker CE 20.10.5

```
$ id telegraf
uid=996(telegraf) gid=995(telegraf) groups=995(telegraf),997(docker)
```

**Comment by helenosheaa** [comment] 2021-03-22 18:58
I think this is a duplicate of this [issue](https://github.com/influxdata/telegraf/issues/8692)

There is a [fix](https://github.com/influxdata/telegraf/pull/9009)waiting to be merged for the issue above, once it's merged I will post a link to the nightly builds so you can test it out

**Comment by helenosheaa** [comment] 2021-03-23 14:08
The fix has been merged so you can now test from a nightly build or master: 

- [telegraf-nightly_darwin_amd64.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_darwin_amd64.tar.gz)
- [telegraf_nightly_amd64.deb](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_amd64.deb)
- [telegraf_nightly_arm64.deb](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_arm64.deb)
- [telegraf-nightly.arm64.rpm](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.arm64.rpm)
- [telegraf_nightly_armel.deb](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_armel.deb)
- [telegraf-nightly.armel.rpm](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.armel.rpm)
- [telegraf_nightly_armhf.deb](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_armhf.deb)
- [telegraf-nightly.armv6hl.rpm](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.armv6hl.rpm)
- [telegraf-nightly_freebsd_amd64.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_freebsd_amd64.tar.gz)
- [telegraf-nightly_freebsd_i386.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_freebsd_i386.tar.gz)
- [telegraf_nightly_i386.deb](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_i386.deb)
- [telegraf-nightly.i386.rpm](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.i386.rpm)
- [telegraf-nightly_linux_amd64.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_linux_amd64.tar.gz)
- [telegraf-nightly_linux_arm64.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_linux_arm64.tar.gz)
- [telegraf-nightly_linux_armel.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_linux_armel.tar.gz)
- [telegraf-nightly_linux_armhf.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_linux_armhf.tar.gz)
- [telegraf-nightly_linux_i386.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_linux_i386.tar.gz)
- [telegraf-nightly_linux_s390x.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_linux_s390x.tar.gz)
- [telegraf_nightly_s390x.deb](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_s390x.deb)
- [telegraf-nightly.s390x.rpm](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.s390x.rpm)
- [telegraf_nightly_ppc64el.deb](https://dl.influxdata.com/telegraf/nightlies/telegraf_nightly_ppc64el.deb)
- [telegraf-nightly.ppc64le.rpm](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.ppc64le.rpm)
- [telegraf-nightly_windows_amd64.zip](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_windows_amd64.zip)
- [telegraf-nightly_windows_i386.zip](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_windows_i386.zip)
- [telegraf-nightly.x86_64.rpm](https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly.x86_64.rpm)
- [telegraf-static-nightly_linux_amd64.tar.gz](https://dl.influxdata.com/telegraf/nightlies/telegraf-static-nightly_linux_amd64.tar.gz)

If that fixes it, you can close the issue

**Comment by helenosheaa** [comment] 2021-03-25 18:02
I'm going to close this issue due to the fix that was merged, if the issue is still present please reopen the issue

**Closed by helenosheaa** 2021-03-25 18:02 UTC
Labels: area/docker, bug
