### ISSUE TITLE
Not able to read rotated log file without missing lines

### ISSUE THREAD

**Issue by kingluo** [influxdata/telegraf#3522] opened 2017-11-29 08:55 UTC
## Feature Request

the rotate procedure:
* step1: the program keeps appending log entries into the log file
* step2: mv logfile logfile.1
* step3: kill -USR1 program
* step4: the program reopens the log file

### Current behavior:

If I specify one file in conf:

```
files = ["logfile"]
```

telegraf losts log entries written between step2 and step4.

If I specify glob in the file:

```
files = ["logfile*"]
```

Then telegraf would resend all log entries in logfile.1 (mostly duplicated from logfile) from the beginning, because logfile.1 is created when telegraf running.

Both ways give wrong result.

### Desired behavior:

telegraf should not stop reading the old renamed file, because the program may keep writing into that file for a while. The watch period could be configured.

**Comment by sgtsquiggs** [comment] 2019-06-10 20:55
This issue is causing me problems right now - when telegraf is sent a SIGHUP to reload its configuration, it will miss log lines written during the reload. I'm not sure how to solve this elegantly since reloading destroys and reloads all plugin instances. Perhaps tail could hold a global state to keep track of offsets of files watched for the duration of the telegraf process.

**Comment by danielnelson** [comment] 2019-06-10 23:03
I think this would be okay, sure there are some corner cases where it doesn't work as expected such as more than one plugin tailing the same file or if the file is switched out exactly at reload time, but I think overall this would work.

**Comment by danielnelson** [comment] 2019-07-12 00:43
Reopening since #6074 won't actually fix the original issue here.

**Comment by rajat23495** [comment] 2019-12-09 11:36
any update on this, it seems many log lines are missing which is resulting in loss of some significant data points.

**Comment by reimda** [comment] 2022-08-22 18:52
It sounds this caused by using the tail plugin with from_beginning=false. In step 4, telegraf opens the new file, seeks to the end and skips any data that was written when it was restarting, then waits for new data. I don't see a way to change this behavior without the tail plugin saving some state. It needs to know that the file it was reading has been moved. Then if it has, it needs to start reading from the beginning of the file.

Since plugins don't have a way to save state, it's not currently possible to do this.

There is a PR that adds plugin state (https://github.com/influxdata/telegraf/pull/9476). Once that has been finished, reviewed, and merged, we can look into modifying the tail plugin to use it, specifically to keep track of whether the file has been moved. I suspect we'll have to have it record the inode of the file since we're dealing with renaming files.

**Closed** 2023-07-26 18:09 UTC
Labels: bug, area/tail, waiting for response
