### ISSUE TITLE
Error response from daemon: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### ISSUE THREAD

**Issue by wyaopeng** [influxdata/telegraf#6874] opened 2020-01-08 02:02 UTC
I used Linux telegraf client to collect windows docker info, but the error info
![image](https://user-images.githubusercontent.com/12064306/71943921-1f4f5080-31fd-11ea-8fcb-9ac95c144d8d.png)

linux docker version:
![image](https://user-images.githubusercontent.com/12064306/71943986-62a9bf00-31fd-11ea-87b6-9a417fb0ed8d.png)

windows docker version
![image](https://user-images.githubusercontent.com/12064306/71944175-e9f73280-31fd-11ea-8dbe-f2b99b98df3f.png)

how can I use telegraf to collect windows docker info ? Or tell me how  to upgrade client api version?

I used  TCP ,The endpoint is windows server
![Uploading image.png…]()

**Comment by wyaopeng** [comment] 2020-01-08 02:04
err pic is this
![image](https://user-images.githubusercontent.com/12064306/71944263-3b9fbd00-31fe-11ea-9b17-e172b98546f4.png)

**Comment by danielnelson** [comment] 2020-01-08 02:14
This is a duplicate of #4666, I'll update the other issue with next steps.

**Closed by danielnelson** 2020-01-08 02:14 UTC
