### ISSUE TITLE
[inputs.minecraft] Error in plugin: Server failed to mirror request challenge.

### ISSUE THREAD

**Issue by ZachMyers3** [influxdata/telegraf#8103] opened 2020-09-10 03:19 UTC
### Relevant telegraf.conf:

```toml
# minecraft input
[[inputs.minecraft]]
  server = "paper"
  port = "25575"
  password = ""
# prometheus export endpoint
[[outputs.prometheus_client]]
  listen = ":9012"
  metric_version = 2
```

### System info:

Telegraf docker, latest (1.15.2)

### Docker

Telegraf docker-compose:

```yml
---
version: "3"

networks:
  prom_network:
    external: true

services:
  telegraf:
    image: telegraf:latest
    restart: unless-stopped
    networks:
      - prom_network
    volumes:
      - "./data:/etc/telegraf/"
```

A paper minecraft server, docker-compose:

```yml
version: "3"

networks:
  minecraft:
  prom_network:
    external: true
services:
  paper:
    image: itzg/minecraft-server
    restart: unless-stopped
    networks:
      - minecraft
      - prom_network
    ports:
      - 25575:25575
    environment:
      EULA: "TRUE"
      MEMORY: "16G"
      TYPE: PAPER
      VERSION: 1.16.2
      USE_AIKAR_FLAGS: "true"
    volumes:
      - "./paper:/data"
      - /etc/timezone:/etc/timezone:ro
```

### Steps to reproduce:

1. Run minecraft server with docker-compose
2. Run telegraf and attempt to connect to RCON with given configuration

### Expected behavior:

Parsing of minecraft data via RCON

### Actual behavior:

The following error, full logs included.

Telegraf
```
2020-09-10T03:06:55Z I! Starting Telegraf 1.15.2
2020-09-10T03:06:55Z D! [agent] Initializing plugins
2020-09-10T03:06:55Z D! [agent] Starting service inputs
2020-09-10T03:06:55Z E! [inputs.minecraft] Error in plugin: Server failed to mirror request challenge.
2020-09-10T03:06:55Z D! [agent] Stopping service inputs
2020-09-10T03:06:55Z D! [agent] Input channel closed
2020-09-10T03:06:55Z D! [agent] Stopped Successfully
2020-09-10T03:06:55Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

### Additional info:

Minecraft logs, showing RCON client is getting connected to via Telegraf
```
[22:40:40 INFO]: Thread RCON Client /172.27.0.7 started
[22:40:50 INFO]: Thread RCON Client /172.27.0.7 started
[22:41:00 INFO]: Thread RCON Client /172.27.0.7 started
[22:41:06 INFO]: Thread RCON Client /172.27.0.7 shutting down
[22:41:06 INFO]: Thread RCON Client /172.27.0.7 shutting down
[22:41:06 INFO]: Thread RCON Client /172.27.0.7 shutting down
```

Relevant codebase [here](https://github.com/influxdata/telegraf/blob/bf1eb291f250d944930832d059020ba8b2be4f95/plugins/inputs/minecraft/internal/rcon/rcon.go#L168).

Willing to provide more information if necessary, thanks 😄

**Comment by ssoroka** [comment] 2020-09-10 14:55
Looks like the client received a packet it didn't expect. Probably requires someone to do some debugging and figure out what packet was received and what to do with it. maybe @halfa or @jsoref ?

**Comment by halfa** [comment] 2020-09-10 16:24
I don't see why I was tagged either but I can take a look this week-end

**Comment by itzg** [comment] 2020-09-10 18:26
@ZachMyers3  at the risk of hijacking the issue, I found the gathering of scoreboard metrics didn't help me for monitoring, so I developed a portable service to integrate health, player counts, and ping into telegraf/InfluxDB:

https://github.com/itzg/mc-monitor

**Comment by ZachMyers3** [comment] 2020-09-10 23:12
Thanks @itzg, I got this up and running!

As for this existing issue, I'm happy to help see it through.

Let me know if any additional information is needed.

**Comment by ssoroka** [comment] 2020-10-14 20:17
I think it's going to take someone debugging what's going on with the minecraft server communication protocol.

Sorry if I pinged anyone who hasn't worked on this plugin before; I believe your name came up in a git blame and I thought you might have some context.

**Comment by ZachMyers3** [comment] 2020-10-15 00:52
Okay, if anything is needed from me I'm happy to provide whatever is necessary.

**Comment by Plinz** [comment] 2020-11-24 12:06
I have the same issue with similar configuration (minecraft server and telegraf on docker)

**Comment by sjwang90** [comment] 2021-03-10 17:47
If anyone in the community is interested in working on this issue please feel free to open a PR and we can get it review and merged. Thanks 😄

**Comment by TheWing** [comment] 2021-07-01 15:20
Hi.

I've ran into this same issue and after a bit of looking around I also found this:
https://community.influxdata.com/t/cant-get-the-minecraft-input-working-server-failed-to-mirror-request-challenge/15391

Seems to be a similar issue, and in there it seems weird to me that input.minecraft would try to ask for 'scoreboard players list #1' (the third send method); as far as I can see, that tries to check the scores for a player named #1.

Now looking at the client.go, it seems the logic there should work for first finding the list of players, and after that checking scores for each player. However, it seems for some reason the Scores() function ends up executing a scoreboard players list -command with the wrong player name?

I'm not exactly sure how elboletaire got the debug output from telegraf in their example, so can't provide as detailed logs from my setup, but for what I can tell my configuration is essentially similar to this issue. I'm not running things with docker though, but I don't see how that would make things different.

**Comment by elboletaire** [comment] 2021-08-16 08:51
Hey, that's me :D

And I ended up here because I'm facing this issue again. It's weird because I left a fresh install working perfectly yesterday, with stuff monitored in grafana, but today, after a server restart, the telegraf plugin started complaining.

I've just started debugging it again right now, so if I find anything I'll tell you in this thread.

One thing I noted compared to yesterday: if I run "scoreboards players list" on my server, instead of seeing a lot of names, what I'm seeing is their respective UUIDs instead, not sure if this could be part of the issue.

On how I did debug this: just cloned the project and used `go run .`, after adding some pretty prints in the `telegraf.go` file.

**Comment by elboletaire** [comment] 2021-08-16 09:43
> One thing I noted compared to yesterday: if I run `scoreboards players list` on my server, instead of seeing a lot of names, what I'm seeing is their respective UUIDs instead, not sure if this could be part of the issue.

And it maaaay be related... not sure how yet, but after some more testing:

- Removing the `scoreboard.dat` file and letting the game re-create it "fixed the issue".
- The UUID which appeared in that (broken) file aren't really replacements, but new entities in the "Players" table. No idea why they appear as UUIDs, but could be related to the fact that I'm running an offline/insecure server (need to test this a bit more). From the fresh file to the broken one, there are more than 1k players added via UUIDs.
- Despite those all new entities, running commands like `scoreboards players list #1` work as expected in rcon-cli; I'd need to debug a bit more how those header challenge work to understand them, because there's obviously some difference, even though both responses (from the working and non-working files) look the same.
- All other objectives and stats look good.

For now I cannot reproduce breaking the file, so I'll stop testing until it breaks again and/or I can find a way to reproduce it.

I leave here the broken scoreboard.dat file, in case someone wants to try (renamed to .dat.txt to be able to upload it here, remember to change its extension again): [scoreboard.dat.txt](https://github.com/influxdata/telegraf/files/6991266/scoreboard.dat.txt)

**Comment by sspaink** [comment] 2022-08-08 18:38
From the latest comment it seems recreating the scoreboard.dat file resolved this issue? Because there hasn't been any activity in this issue for a year I am closing this, if you are still having this problem feel free to re-open or comment.

**Closed by sspaink** 2022-08-08 18:38 UTC
Labels: bug, help wanted
