### ISSUE TITLE
MQTT + JSON input, how to use "name" to create measurements?

### ISSUE THREAD

**Issue by diranbarana** [influxdata/telegraf#8228] opened 2020-10-06 12:33 UTC
Hi! 

I am newby in InfluxDB and Telegraf and I am honestly slightly stuck with this task. Here I expose my problem

Considering the following configuration: 

```
[[inputs.mqtt_consumer]]
servers = ["ssl://localhost:8883"]
topics = [
"+/data"
]
qos = 1
connection_timeout = "60s"
persistent_session = false
insecure_skip_verify = true
data_format = "json"
json_time_key = "timestamp"
json_time_format = "unix_ms"

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "Battery"
  skip_database_creation = false
  insecure_skip_verify = true

```
And sending the following message to the MQTT:

```
 [
{
    "name": "HE3161233018D41910281430146",
    "timestamp": 1601911947000,
    "voltage": {
        "c5": 3.789
    }
}
, 
{
    "name": "HE3161233018D41910281430146",
    "timestamp": 1601911949000,
    "voltage": {
        "c18": 3.918,
        "c4": 3.814
    }
}
, 
{
    "name": "HE3161233018D41910281430146",
    "timestamp": 1601911955000,
    "voltage": {
        "c4": 3.788
    }
}
, 
{
    "name": "HE3161233018D41910281430146",
    "timestamp": 1601911956000,
    "voltage": {
        "c18": 3.851
    }
}
....
```

I would like to write the input data in a measurement called with the value of "name" property . In the example above it would be the measurement HE3161233018D41910281430146.

I thought giving the "name" property Telegraf would write the incoming data in that measurement, but all the data is going to "mqtt_consumer" measurement. 

Is there some way to do what I would like?

Thank you!

**Comment by sjwang90** [comment] 2020-10-06 17:09
I believe it'd be easiest to add a `processors.converter` to the end of your config to convert your `name` tag/field to a measurement value. See the last [example here](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter#example).

Going to close this as we try to reserve Telegraf issues for bug or reproducible problems.  Feel free to drop into our [Community Slack](infludata.com/slack) or [Community Page](https://community.influxdata.com/) if you run into more problems.

**Closed by sjwang90** 2020-10-06 17:09 UTC
Labels: support

**Comment by diranbarana** [comment] 2020-10-07 07:53
Thanks sjwang90! I did not know yet what the processors.converter are used for. Anyway, I have a problem reloading Telegraf with the following code of config:

```
[[processors.converter]]
  [processors.converter.tags]
    measurement = ["name"]
```

The error:

```
2020-10-07T07:25:53Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 230: field corresponding to measurement is not defined in converter.Conversion
```

Is this some kind of version related issue?

**Comment by sjwang90** [comment] 2020-10-08 15:46
Shouldn't be a version issue. 

Can you provide a sample of what the output of your data looks like without the converter?

**Comment by diranbarana** [comment] 2020-10-09 07:06
I had Telegraf version 1.13 and I think version 1.14 added the possibility
of setting tag value to measurement. Telegraf was failing with version
1.13, but after updating to 1.15 I didn't realize I had to define "name" in
the input [inputs.mqtt_consumer]

tag_keys = [
"name"
]

So, honestly, I don't know whether I would work with version 1.13 an the
correct configuration.

I am very grateful for your help

Best Wishes
